### ISSUE TITLE
E-Mail text of notifications is a bit confusing/unspecific

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#1037]
I was confused, when I got an email saying, that a new "Beitrag" was added, when someone commented an idea, and even more confused why I got an email because someone commented a comment and I was still linked to the project. Could we be more specific with the actions?

**Comment by hmkay** [comment]
Maybe we could change "Neuer Beitrag" and/or "Neue Reaktion" to "Neue Aktivitäten im Projekt XXX" and/or "Neue Aktivität in Ihrem Beitrag".

As a moderator, though, it would be nice to receive exact information, thus also a direct link to the current activity/happening. What do you think?

**Comment by phillimorland** [comment]
email wording has been updated, was this issue sorted with that? @CarolingerSeilchenspringer

**Comment by CarolingerSeilchenspringer** [comment]
yes, we have new wording for all mails.
