### ISSUE TITLE
Allow icons in (dropdown) buttons (split select-item functionality) 

### ISSUE THREAD

**Issue by kleingeist** [liqd/a4-meinberlin#1069]
Currently there is no other way to add icons to dropdown buttons then to use the select-item class.
Unfortunately it also sets a larger font, as it was intended to use with the follow button that contains a heading and a description.
We should split the select-item functionality in a 
- `btn--icon` variant and a
- `select-item` equivalent for the follow button

**Comment by phillimorland** [comment]
class name no longer in use

**Comment by fuzzylogic2000** [comment]
Are both classnames no longer in use? Then the refactoring should be also removing the corresponding css here! (maybe a new issue) @phillimorland

**Comment by phillimorland** [comment]
I know, i'm making a list of apparently obsolete css files for a+, will do same for mB and create issue, mB is a little more scary to remove stuff from though
