### ISSUE TITLE
Varying height in component library

### ISSUE THREAD

**Issue by xi** [liqd/a4-meinberlin#1087]
Since #1068 we use autogenerated content for the component library. This has many benefits, but it also means that the height and position of the elements may change on reload, which is annoying.

**Comment by kleingeist** [comment]
good point, i missed that wenn using the lorem tag
but we could just remove the `random` param to have generated text with a fixed length

**Comment by xi** [comment]
Fixed length in characters is not the same as fixed size in pixels, especially when not using a monospaced font.

**Comment by kleingeist** [comment]
lorem ipsum without `random` generates the same characters on every call. as far as i can see this is the best we can achieve in case of html sizes. well apart from my favorite `height: 10px ! important;` :D
