### ISSUE TITLE
de translation: wrong salutation in register flow

### ISSUE THREAD

**Issue by xi** [liqd/a4-meinberlin#1091]
After registering I get the following message:

> Bestätige deine E-Mail-Adresse
>
> Wir haben dir eine E-Mail geschickt, um deine Adresse zu verifizieren. Bitte folge dem Link in der E-Mail um den Anmeldeprozess abzuschließen. Bitte kontaktiere uns, falls die E-Mail nicht in ein paar Minuten angekommen ist.

It should use formal salutation.

**Comment by kleingeist** [comment]
Note: should be adapted in product, too

**Comment by fuzzylogic2000** [comment]
Whoop whoop! @MagdaN fixed it! I will add an issue to product.
