### ISSUE TITLE
Dropdown issues on small screens

### ISSUE THREAD

**Issue by xi** [liqd/a4-meinberlin#1094]
- Dropdowns may be wider than the screen (caused by `white-space: nowrap`)
- Dropdowns may be higher than the screen
- Dropdowns may partly be offscreen, even if the screen would be big enough (e.g. missing `dropdown--right`)

Note that select elements (which we modelled the dropdowns after) get a special UI in mobile browsers to avoid these very issues.

**Comment by fuzzylogic2000** [comment]
Also a problem in project-follows.
![screen shot 2018-02-05 at 11 26 11](https://user-images.githubusercontent.com/8178179/35805105-d8e3a926-0a7a-11e8-94d3-b30c02a4f77b.png)

**Comment by CarolingerSeilchenspringer** [comment]
we will think about this with the new story regarding the follow function.
