### ISSUE TITLE
The address finder completion errors are yellow and very hard to read

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#1116]
https://meinberlin-dev.liqd.net/components/#cl-complete

**Comment by phillimorland** [comment]
@szukowski shall we change the overall warning colour? I tried adding it as a background but looks crap

**Comment by szukowski** [comment]
yes, we should ;)
Confirmation = green   #63AB86 Background alpha 10% 
Infomation, Notes = orange  #F49E00 Background alpha 10%
Errors = red  #DB3918 Background alpha 10%

![grafik](https://user-images.githubusercontent.com/36926290/48774574-ed162300-ecca-11e8-9f51-ebdf8f6ec0ba.png)

@fuzzylogic2000

**Comment by rmader** [comment]
Reopening as the related MR makes things better but not as requested in https://github.com/liqd/a4-meinberlin/issues/1116#issuecomment-440262354

**Comment by phillimorland** [comment]
contrast lower on design then currently used, won't lower contrast due to a11y so closing again

**Comment by fuzzylogic2000** [comment]
This was about the yellow for the address search. It's still there and impossible to read https://meinberlin-dev.liqd.net/components/#cl-complete Can we use the bootstrap colours here? https://getbootstrap.com/docs/4.3/components/alerts/

**Comment by fuzzylogic2000** [comment]
@phillimorland You're right. Sorry!
