### ISSUE TITLE
Wagtail bird only visible on homepage

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-meinberlin#1136]
even if I can edit a wagtail page, the wagtail bird (link to wagtail admin) is not shown on that page.

@kleingeist is there a reason for that?

**Comment by kleingeist** [comment]
hm i don't know. maybe because the subpages feature was introduced later when the leitlinien prozess became bigger and it was just forgot. can't remember anyone ever told me a reason

**Comment by phillimorland** [comment]
wagtail currently visible on all footer pages, if still missing on other required pages, please re-open @CarolingerSeilchenspringer @MagdaN
