### ISSUE TITLE
Leaflet draw controls overlap the map

### ISSUE THREAD

**Issue by kleingeist** [liqd/a4-meinberlin#1149]
The leaflet draw controls are overlapping a large area in the middle of the map

![leaflet-map-overlapping](https://user-images.githubusercontent.com/167407/35035244-041e02d0-fb71-11e7-920e-94e1dd9b0300.png)

**Comment by phillimorland** [comment]
we could display block to make it appear more like a dropdown although that uses up alot of space also. @szukowski from ux point of view, what do you think?
![edit areasettings spacial brainstorm map meinberlin](https://user-images.githubusercontent.com/5871230/46087564-e081bc80-c1aa-11e8-93a2-c3ef5a942364.png)

**Comment by szukowski** [comment]
at first, nothing speaks against it. However, you would have to click through the whole function once to say it final
