### ISSUE TITLE
Should we make sure, that old Vorhaben without district do not cause server errors?

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#1156]
Or do we just add districts to the three Vorhaben on stage?

@kleingeist

**Comment by kleingeist** [comment]
i think adding them on stage, dev and the 4 local dev machines is fine. and we could make the database model more correct by not allowing null for the district. as far as i can tell there has to be a district given, so the model should reflect that

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 this is outdated, right? it not, reopen.
