### ISSUE TITLE
wrong geo-koordinates in excel export

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1178]
longitude and lattitude need to be switched to work with berlins open data portal
 (Mail from Daniel: ich prüfe gerade, wie wir die Ergebnisdaten der Beteiligungsverfahren (XLS) ins Open-Data-Portal bekommen. Dabei ist mir aufgefallen, dass die Koordinaten-Spalte des Excel-Exports verdreht ist: z.B. 13.415766, 52.499713 – richtig wäre Breitengrad (52) vor Längengrad (13), sonst kommt man im Golf von Aden raus: https://www.google.de/maps/place/13%C2%B024'56.8%22N+52%C2%B029'59.0%22E/@12.240192,49.36975,6.96z/data=!4m5!3m4!1s0x0:0x0!8m2!3d13.415766!4d52.499713)

**Comment by MagdaN** [comment]
As there is no rule for the order of lat and lon (see [here](https://macwright.org/lonlat/)) I would be in favour of adding each value in a separate column

**Comment by kleingeist** [comment]
unfortuantely it is not clear what the correct order of lat and lon should be, as it is handled differently on most of the gis applications. see [1] for an overview

we are following the geojson standard which defines the  lon, lat order [2]

[1] https://macwright.org/lonlat/
[2] https://tools.ietf.org/html/rfc7946#section-3.1.1

**Comment by kleingeist** [comment]
@MagdaN yes that would be a good idea. or at least define the order in the title column of the export

**Comment by kleingeist** [comment]
will be fixed with liqd/adhocracy4#236

**Comment by fuzzylogic2000** [comment]
Fixed! coordinates are now split into two fields in the export.
