### ISSUE TITLE
delete scheduled dates on Wagtail

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1184]
to schedule a date on Wagtail (THF) does not work (and is probably neither used nor necessary), therefore can be deleted, so users may not use it not realizing it doesn't work.

**Comment by phillimorland** [comment]
We can maybe make this work with below link but i cannot seem to delete it as included in Wagtail release? thoughts? @fuzzylogic2000 @MagdaN 
http://docs.wagtail.io/en/latest/reference/management_commands.html#publish-scheduled-pages

**Comment by CarolingerSeilchenspringer** [comment]
I close this due to very low priority.
