### ISSUE TITLE
Firefox issue: The dropdownn toggle-button is on top of the search button of the freetext-filter

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-meinberlin#1191]
![35799923-a06c4eda-0a67-11e8-813f-e30b7f4afc07](https://user-images.githubusercontent.com/2905743/35805715-3a5c95e4-0a7d-11e8-8868-1bc72512b71a.png)

This issue only appears on Firefox when using the small screen debugging mode

**Comment by rmader** [comment]
That's odd. The search button is part of the search form, but for some reason it's rendered outside of it. So basically the button has end where currently the search block ends.

**Comment by CarolingerSeilchenspringer** [comment]
I just checked this again and it still does that when screen size is smaller than 450px. @phillimorland said we should test down to 375px so I guess we should have a look at it again.
