### ISSUE TITLE
Notification links to project instead of idea for ideas

### ISSUE THREAD

**Issue by kleingeist** [liqd/a4-meinberlin#1250]
https://github.com/liqd/a4-meinberlin/blob/master/meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_moderator.de.email#L11 tries to get the correct link, but somehow fails.
not sure if this is true for new ideas or only new comments for ideas

**Comment by fuzzylogic2000** [comment]
Don't we have the same problem for comments in ideas, when a comment is added? We should further investigate!
