### ISSUE TITLE
categories in idea forms shouldn't be preselected

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#1280]
![screenshot from 2018-04-10 09-49-17](https://user-images.githubusercontent.com/8178179/38543333-a035ca80-3ca4-11e8-8ddd-d24e8c0fd238.png)

**Comment by fuzzylogic2000** [comment]
This seems like a bigger thing. @CarolingerSeilchenspringer @szukowski How important it it/how fast should this be fixed?

**Comment by szukowski** [comment]
@CarolingerSeilchenspringer has to decied

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 @szukowski  I think this would be nice to have in terms of UX, but since it is too big for an issue I think we should close it.
