### ISSUE TITLE
form with errors should either jump to the (first) error or show an extra alert at the top

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#1282]
![screenshot from 2018-04-10 10-17-06](https://user-images.githubusercontent.com/8178179/38544718-8841cc2c-3ca8-11e8-9194-1631d3dd2fb5.png)

**Comment by CarolingerSeilchenspringer** [comment]
as this would be a story I put it in taiga backlog and will close issue.
