### ISSUE TITLE
category-dropdown in modules without map do not have right styling

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#1283]
![screenshot from 2018-04-10 12-05-34](https://user-images.githubusercontent.com/8178179/38551394-54f0ec7a-3cb9-11e8-98ab-b2f1f6d22bd3.png)

**Comment by phillimorland** [comment]
@phillimorland to check other dropdowns and investigate fix

**Comment by phillimorland** [comment]
@fuzzylogic2000 cannot quite reproduce, Chrome shows dopdown as a slightly darker grey than other browsers but rest of styling is fine, do you remember what browser you saw this on?

**Comment by CarolingerSeilchenspringer** [comment]
as I can also not reproduce I will close this issue. @fuzzylogic2000 if you can reproduce feel free to reopen.
