### ISSUE TITLE
Dropdown item description looks selectable

### ISSUE THREAD

**Issue by ihucos** [liqd/a4-meinberlin#1299]
![screenshot from 2018-04-19 11-05-11](https://user-images.githubusercontent.com/2066372/38982273-b65ff62c-43c1-11e8-8677-78abd085193e.png)

On this dropdown the user has two choices, for me it looks like its four and only a mouseover clarifies this. We could differentiate the dropdown item title from the dropdown item description with different front attributes (e.g cursive description)

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer @szukowski do we need such long descriptions? to "recieve email notifications" or something? not sure how that works in german though.

**Comment by fuzzylogic2000** [comment]
Looks fine on my screen:
![screenshot from 2018-09-20 16-32-47](https://user-images.githubusercontent.com/8178179/45825579-db2bfa00-bcf2-11e8-9312-0c8f5689cee3.png)

I propose we close this issue!

**Comment by fuzzylogic2000** [comment]
@phillimorland We kind of stole this from github. And I quite like it!
![screenshot from 2018-09-20 16-34-19](https://user-images.githubusercontent.com/8178179/45825689-1c240e80-bcf3-11e8-9e57-c29a8d7b7f5b.png)

**Comment by phillimorland** [comment]
closing is cool with me
