### ISSUE TITLE
/components page should not be included in production

### ISSUE THREAD

**Issue by ihucos** [liqd/a4-meinberlin#1322]
It may look funny, but I don't know if it really is a problem: https://mein.berlin.de/components/

**Comment by fuzzylogic2000** [comment]
As we don't have a link anywhere, I don't think it's a problem. If you think, we should change it, add it to the unassigned task on taiga about deploying mB next time, so that we add it to the commit  we need to cherry-pick for releases.

**Comment by ihucos** [comment]
> I don't think it's a problem
not really
