### ISSUE TITLE
Users with only one charachter

### ISSUE THREAD

**Issue by ihucos** [liqd/a4-meinberlin#1339]
I am privately using mein.berlin.de but actually created an user named 'a'. I think we want to validate that to a minimum character length.

**Comment by phillimorland** [comment]
what min char length, 3?

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer is this a priority do you think? 
I'm just not sure how we would deal with users in the database who have already registered usernames with less than 3 charecters? @MagdaN
