### ISSUE TITLE
JS error in page with embedded project

### ISSUE THREAD

**Issue by vellip** [liqd/a4-meinberlin#134]
Uncaught SyntaxError: Unexpected token o in JSON at position 1 &lt;embed.js:108&gt;

------

For some reason, when loading the page containing the iframe, it seems the `message` handler gets triggered and has an object `{request: 'geturi'}` in `event.data`.

Maybe its from a browser extension?

**Comment by xi** [comment]
we could simply wrap it in a `try` block
