### ISSUE TITLE
Text in image

### ISSUE THREAD

**Issue by ihucos** [liqd/a4-meinberlin#1346]
Organisations put text in their images before uploading them. Possibly they are trying to archive something that our software does not allow, or we should put a note on the text upload with shortly why text in images is considered bad practice

On the one hand I don't think it's a priority, on the other hand text in images on the web is very very suboptimal.

![screenshot from 2018-05-15 09-53-35](https://user-images.githubusercontent.com/2066372/40043881-14726f4c-5826-11e8-96d1-17811dd57546.png)

Some disadvantages of text in images:
https://ux.stackexchange.com/questions/41593/is-the-usage-of-text-embedded-in-an-image-a-bad-practice-for-very-controlled-us

EDIT:
Ha, I have the killer argument: text in images is not accessible because screen readers can not read it.

**Comment by phillimorland** [comment]
@fuzzylogic2000 do we think this is a problem for a11y? if so what shall we do? just add a little warning message about not adding text as suggested?

**Comment by fuzzylogic2000** [comment]
@phillimorland Sure, we always tell them that they absolutely shouldn't put text into images, but they just won't listen. I don't know how to fix that.
@CarolingerSeilchenspringer @szukowski I think the idea of adding something to the helptext about text in images would be worth a try. On the other hand, I don't think people read the helptexts very thoroughly. 
Maybe the possibility to add an alt-text for the images is worth a try? I mean that the initiators can add an alt text which will be put into the alt-text of the image if it's there and if not it just says what it does now?! 
What do you think?
