### ISSUE TITLE
"Aenderungsprotokoll" is in the wizard (dashboard)

### ISSUE THREAD

**Issue by ihucos** [liqd/a4-meinberlin#1350]
It's information to be show, not text input related to the project, so it should be somewhere else. I have to click "edit" on the project to see it.

**Comment by phillimorland** [comment]
It is a log of edits which can be viewed in the edit menu which seems fine, we could maybe distinguish  it from the main side menu if necessary, what do you think UX wise @szukowski?

**Comment by fuzzylogic2000** [comment]
I think, we should close this! There was a lot of discussion with Daniel and the Betriebsrat about this. Let's not start that again, but keep it as it is. 

Please reopen if necessary.
