### ISSUE TITLE
Red input fields on first page load

### ISSUE THREAD

**Issue by ihucos** [liqd/a4-meinberlin#1351]
When loading some pages, input fields are redish, suggesting there where validation errors, but there was not input submit yet.
![screenshot from 2018-05-16 15-40-43](https://user-images.githubusercontent.com/2066372/40120463-8dadcf06-591f-11e8-966b-0ab68e153da8.png)

**Comment by phillimorland** [comment]
this can be solved by removing the invalid styling but if this is required then do we really want to? @CarolingerSeilchenspringer 
code for fix 
.input-group__input {
  input:required:invalid {border-color: #ccc; color: #ccc;}
}

**Comment by phillimorland** [comment]
firefox issue @phillimorland to check other browsers
Also comment box also has red surrounding too, also to check

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland removed required (as initiator is automatically moderator now) and removed third email address
