### ISSUE TITLE
Wizard (dashboard) menu items header is project name

### ISSUE THREAD

**Issue by ihucos** [liqd/a4-meinberlin#1360]
But I think it should be something like "Project settings" or so. On modules, the menu item header should could be pefixed with "module: the module name"

**Comment by phillimorland** [comment]
maybe also can look at this at same times, all would help first time users [#1354]

**Comment by phillimorland** [comment]
@szukowski do you have any idea for a quick solution on this?

**Comment by szukowski** [comment]
@phillimorland this is a complexer story. we've to optimit some emelements at the dashboard navigation

here some layout:
![dashboard projektinformationen](https://user-images.githubusercontent.com/36926290/48774988-010e5480-eccc-11e8-847f-19aada6c1bdd.png)

**Comment by CarolingerSeilchenspringer** [comment]
implemented in new dashboard.
