### ISSUE TITLE
"unpublish" could easily be hit by mistake

### ISSUE THREAD

**Issue by ihucos** [liqd/a4-meinberlin#1368]
If I want to hit the preview, I could easily miss and unpublish the project.
There could be an javascript alert with a are you sure question.

And the german translation "unpublizieren" seems awkward to me.

![Uploading Screenshot from 2018-05-16 15-59-53.png…]()

**Comment by phillimorland** [comment]
Maybe we can fade the color in the large tic when it is not published so it is very clear?
