### ISSUE TITLE
Initiators rights should not be a superset of user rights

### ISSUE THREAD

**Issue by ihucos** [liqd/a4-meinberlin#1371]
Not too sure, but maybe initiators should not be allowed to involve themselves in the platform and for example vote, since they should have an neutral mindset about the project

**Comment by fuzzylogic2000** [comment]
But don't they need the superset to actually moderate and do the stuff they are usually doing? What do you think @CarolingerSeilchenspringer ?
Also, where do you want to cut off? Only in the projects the certain initiators started? On the whole platform or in the organisation where the user is initiator?
