### ISSUE TITLE
Moderator/Initiators should not be able to flag their own comment

### ISSUE THREAD

**Issue by ihucos** [liqd/a4-meinberlin#1373]
Only comments of other users (this issue should not have the highest priority)

**Comment by phillimorland** [comment]
@phillimorland to check if users can flag their own commet

**Comment by phillimorland** [comment]
User's can report/flag their own comments, @fuzzylogic2000 is this an easy fix or should it be a user story?

**Comment by CarolingerSeilchenspringer** [comment]
will close the issue due to very low priority.
