### ISSUE TITLE
Unsubscribe link in newsletter

### ISSUE THREAD

**Issue by ihucos** [liqd/a4-meinberlin#1376]
We ask the user to login and change something at some settings to unsubscribe, since we are a nice company, we could provide a link that automatically unsubscribes.
...but of course we are only changing the database with POST request, so there is still a final button.

**Comment by phillimorland** [comment]
@phillimorland to check if there is unsubscribe text in newsletter and maybe add link to unsubscribe location
Possibly part of bigger story

**Comment by phillimorland** [comment]
text in newsletter footer
" Diese E-Mail wurde an k.albers@liqd.net gesendet. Die E-Mail wurde an Sie gesendet, da Sie auf meinBerlin-dev registriert sind. Wenn Sie keine Newsletter mehr erhalten wollen, können Sie diese in Ihrem Benutzerkonto deaktivieren. "

I think adding a link to account settings is a good idea.
@CarolingerSeilchenspringer do you want to make a larger story for newsletter or shall i add link as issue?

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland I added this to a story
