### ISSUE TITLE
Tabs not consistently implemented

### ISSUE THREAD

**Issue by ihucos** [liqd/a4-meinberlin#1378]
When I click here:
![asdf](https://user-images.githubusercontent.com/2066372/40126273-3a011454-592d-11e8-8a70-2236bf560936.png)
Then I get here:
![screenshot from 2018-05-16 17-19-29](https://user-images.githubusercontent.com/2066372/40126306-4f782976-592d-11e8-9bb8-fbc7a6a9b0ae.png)

The tabbar disapears, and as an user I get disoriented.

**Comment by phillimorland** [comment]
Seems to be only a firefox issue, tested in chrome and safari and focus styling holds up

**Comment by ihucos** [comment]
ahhh, i did not know it was an actual bug

**Comment by phillimorland** [comment]
does not seem to be an issue any more, checked on ff, chr, saf
