### ISSUE TITLE
monitor email sending

### ISSUE THREAD

**Issue by ihucos** [liqd/a4-meinberlin#1396]
After this is implemented: https://github.com/liqd/a4-meinberlin/issues/1397
We should be able to get an idea about the status of mail sending by looking at tasks, where has_error is True. We also have the traceback in the logs at the server, but looking for has_error could be done in the django admin. I don't know, this issue is about figuring out a process to monitor the email sending, not every email has to arrive but general problems should be detected. How do we currently handle errors that happen at mein.berlin.de ? we should integrate how to handle email sending errors or even better background tasks errors in general into how we handle site errors.

This is not really a programming task, but a process question.

@treba123 any thoughts?

**Comment by phillimorland** [comment]
@treba123 @MagdaN @fuzzylogic2000 is this still in progress?

**Comment by treba123** [comment]
Yeah the topic comes up again and again...what about making sure exceptions get thrown, so we see them in sentry?

**Comment by phillimorland** [comment]
@treba123 thats a good idea! could you maybe implement it? :)

**Comment by rmader** [comment]
Sentry is up and running for a while now
