### ISSUE TITLE
Use one task per mail

### ISSUE THREAD

**Issue by ihucos** [liqd/a4-meinberlin#1397]
Currently we iterate over all email addresses to send them sequentially.
https://github.com/liqd/adhocracy4/blob/31bd992a1813208c5aa44a0cebb2fe00bdea6f34/adhocracy4/emails/base.py#L97
We should instead start one task for each email that is send instead
So the current task becomes kind of a parent task, that spawns child tasks.

**Comment by phillimorland** [comment]
@MagdaN we decided to leave it in 1 task, right? otherwise reopen
