### ISSUE TITLE
Fix newsletter issue

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-meinberlin#1400]
- [ ] send platform emails only to verified primary email addresses
- [x] don't restart task after it failed
- [x] check if more exception handling for sending emails should/can be implemented
- [x] check if each email should be handled in one task
- [ ] check for external service
- [x] send result report to admin to see which email addresses errored
- [x] add cron job to check which tasks errored

**Comment by phillimorland** [comment]
@MagdaN are we any further with this?
