### ISSUE TITLE
LLBB: Show footer on Iphone (mobile)

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-meinberlin#1405]
When accessing https://leitlinien-beteiligung.berlin.de/ via Iphone, the footer is not shown.

**Comment by phillimorland** [comment]
Can't seem to reproduce the error, can you add screen shots? @hmkay

**Comment by hmkay** [comment]
@CarolingerSeilchenspringer which browser did you use? And which IPhone do you have? Is it still valid that you do not see the footer on your phone?

**Comment by CarolingerSeilchenspringer** [comment]
@hmkay: I used safari on ios 11.4.1. Datenschutz and Impressum are not found anywhere. 
![image-1](https://user-images.githubusercontent.com/35491681/44215030-c9928800-a171-11e8-81ce-2799e25e54cf.jpg)

**Comment by hmkay** [comment]
thanks @CarolingerSeilchenspringer , and there you go @phillimorland
