### ISSUE TITLE
do not use extract-text-webpack-plugin to minify css

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#1441]
like https://github.com/liqd/a4-opin/issues/1246

corresponding PR: #1438

**Comment by fuzzylogic2000** [comment]
Unluckily we had to #1446 (revert #1438), because it broke the plans list.

**Comment by phillimorland** [comment]
@fuzzylogic2000 check

**Comment by fuzzylogic2000** [comment]
done!
