### ISSUE TITLE
Follow feature not used so much

### ISSUE THREAD

**Issue by ihucos** [liqd/a4-meinberlin#1459]
I would say that the follow button is not used so much, I did some statistics.
In general I would say its not too bad, but also not so good :-) since the feature is non unobtrusive it may be ok.
@CarolingerSeilchenspringer @szukowski FYI

#### In total the follow button was clicked 275 times.

```
>>> Follow.objects.all().exclude(creator__email__endswith='@liqd.net').count()
275
```

#### In total 153 different users used the follow feature.
```
>>> Follow.objects.all().exclude(creator__email__endswith='@liqd.net').values('creator').distinct().count()
153
```

#### At the moment 131 people are following at least one project
```
>>> Follow.objects.all().exclude(creator__email__endswith='@liqd.net').filter(enabled=True).values('creator').distinct().count()
131
```

#### At the moment we have 6993 users registered in the platform (also counting not active users)
```
>>> User.objects.exclude(email__endswith='@liqd.net').count()
6993
```

#### We have 2809 users that did an action at some point in time [1]
```
>>> Action.objects.exclude(actor__email__endswith='@liqd.net').values('actor').distinct().count()
2809
```

## 5% percent of our users use the follow button
```
>>> round(153. / 2809 * 100)
5
```

[1] users that did one of the following actions: a comment, an idea on the idea list, an idea on the map, and proposal in budgeting or an proposal in the "kiezkase"

One assumption: the follow feature was there from the beginning

**Comment by CarolingerSeilchenspringer** [comment]
very interesting @ihucos ! This is a good basis to discuss a renewal of the follow function. We should have a better way to remind people to participate and to keep them in a discussion. According to Django-admin we have 7016 users, where does this difference come from? 40% have been active at some point and we have about the same number of people (2726) that have never registered. These should mostly be those who were transferred from a3 to a4. Then we have about 20% who registered and then were not active (like me ;-).

**Comment by phillimorland** [comment]
will be part of a bigger story
