### ISSUE TITLE
grey in marked plan list entry is too dark

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#1463]
It wasn't that dark befor the bootstrap-update. @phillimorland Could you check?

![screenshot from 2018-06-22 14-44-38](https://user-images.githubusercontent.com/8178179/41777388-6be8fca0-762b-11e8-8890-67eb1f44a5d1.png)

**Comment by phillimorland** [comment]
fixed with Pm 2018 06 list item fixes#1463
