### ISSUE TITLE
components mssing from the library

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#1501]
namely: 
simple_page - Cannot locate a use of it
select2 -Only referenced in js files
lr_bar - Only referenced in import doc
select_dropdown - Only referenced in import doc
map - javascript

as noted in #1439

**Comment by phillimorland** [comment]
@fuzzylogic2000 do we want to add them or is this just a reminder?

**Comment by fuzzylogic2000** [comment]
@phillimorland Yes, when we have time, but has not the highest prio. So, for now it's a reminder.

**Comment by phillimorland** [comment]
@fuzzylogic2000 ok but the map is javascript so i would say it doesn't belong in a css component library?

**Comment by fuzzylogic2000** [comment]
@phillimorland True! I just copied from your PR what you said was still missing to think about it later.
