### ISSUE TITLE
feedback button disappears

### ISSUE THREAD

**Issue by szukowski** [liqd/a4-meinberlin#1547]
When testing I noticed that the feedback button disappears at a screen resolution below about 1200 pixels. I do not see him on the laptop.

Desktop
![auflosung_desktop1](https://user-images.githubusercontent.com/36926290/45620746-2f7a7400-ba7e-11e8-9e1d-b4f85d57cd2b.png)

![auslosung_desktop2](https://user-images.githubusercontent.com/36926290/45620752-37d2af00-ba7e-11e8-90e1-b09b699b0336.png)

Laptop
![auflosung_laptop](https://user-images.githubusercontent.com/36926290/45620767-3e612680-ba7e-11e8-936c-b65c52d58a16.png)

**Comment by phillimorland** [comment]
This is set in adhocracy to not display under 1360, should it alway be displayed, even on mobile? @szukowski @CarolingerSeilchenspringer

**Comment by phillimorland** [comment]
@phillimorland to add link to code 
@szukowski is feedback link footer ok?

**Comment by phillimorland** [comment]
No set in adhocracy, set [here](https://github.com/liqd/a4-meinberlin/blob/d4c59a449cd6174d40031fb796a2ae31b47b718d/meinberlin/assets/scss/components/_fixed_side.scss) and [here](https://github.com/liqd/a4-meinberlin/blob/d4c59a449cd6174d40031fb796a2ae31b47b718d/meinberlin/assets/scss/_variables.scss)

**Comment by szukowski** [comment]
@phillimorland Basically, a fixed possition is important for the orientation of the user, but we can close the story for the time being, as we solve the problem with the new concept.
