### ISSUE TITLE
testing #593: E-Mail invitation to private projects

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1555]
* in header (Betreffzeile) please put project title in "..."!!
* please note: Link to Initiator changes to link to Organisation
* support-Address changed, we have a specific mein.berlin.de-Adress now!!
* is it possible to put the Call to Action "EInladung annehmen" before the support-hint?

Einladung zum Projekt „xy“ 

Guten Tag, 

Sie wurden zum Projekt „xy [Projekttitel]“ auf mein.berlin.de eingeladen. Mein.Berlin.de ist die Beteiligungsplattform des Landes Berlin. Hier werden Sie um Ihre Meinung zu Projekten der Berliner Verwaltung gebeten. Sie wurden eingeladen von „xy [Organisation]“.

Klicken sie jetzt auf "Einladung annehmen" um an dem Projekt teilzunehmen. Sollten Sie noch nicht auf mein.Berlin.de registriert sein, ist dies in wenigen Schritten möglich. Bitte beachten Sie: Diese Einladung ist nur für Sie persönlich bestimmt. 

Wir freuen uns auf Ihren Beitrag! 

Einladung annehmen

Sie haben Fragen? Schreiben Sie an support@mein.berlin.de.

**Comment by MagdaN** [comment]
@CarolingerSeilchenspringer sorry, no it is not possible to to put the Call to Action "EInladung annehmen" before the support-hint
