### ISSUE TITLE
Brainstorming and maps: votes are shown

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-meinberlin#1557]
For brainstorming with maps, the votes (which are not there) are shown. See picture:

![mb_brainstorming votes](https://user-images.githubusercontent.com/30862422/45761508-b2413180-bc2c-11e8-988e-c639e2cd7868.jpeg)

**Comment by phillimorland** [comment]
do we only want the label to be visible or do we want the votes to be visable when there are some and not when there aren't? @hmkay @CarolingerSeilchenspringer

**Comment by hmkay** [comment]
@CarolingerSeilchenspringer this issue will be discussed within the devs before they get back to us :) If I get that right, @phillimorland

**Comment by phillimorland** [comment]
check list view as well

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland list view is ok, on map view pop-up it should not show votes as brainstorming does not have voting. We should change that with next release.

**Comment by CarolingerSeilchenspringer** [comment]
closed in favor of #1932
