### ISSUE TITLE
should demo have master deployed?

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#1583]
What exactly is demo used for again?
@CarolingerSeilchenspringer @treba123 

And as we have to deploy demo by hand (?!), I find it easier to just do that whenever I deploy stage and use the same build. What do you think? @MagdaN @treba123

**Comment by CarolingerSeilchenspringer** [comment]
Daniel uses demo to show meinBerlin to people, so there should be the same release as on stage and productive (not like dev).

**Comment by treba123** [comment]
Alright, will set it back to 1.16
