### ISSUE TITLE
Vorhabenliste

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1586]
in Steckbrief on detail page please change "geplante Kosten" to "Kosten" in order to make the Steckbrief more clear in avoiding two lines on the left side.

**Comment by phillimorland** [comment]
@phillimorland to check table behaviour

**Comment by phillimorland** [comment]
we can set table behaviour to fixed so col doesn't resize anymore but this could cause overlapping wth some content, especially on smaller screens where geplante kosten is on 2 lines anyway, I think just changing it to kosten would be most robust fix.
