### ISSUE TITLE
in upload manager open link in new window seems not to work

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1591]
As project initiator if I upload a pdf/ link a page in the upload manager, the settings on "Zielseite" seem not to work, at least the setting for "open in new window". After saving the form in backend (e.g. Information or Ergebnis) the "Zielseite" jumps back to "nicht festgelegt" and the pdf/page opens on the same page.

![image](https://user-images.githubusercontent.com/35491681/46471688-fca0e180-c7da-11e8-890c-6e1542b0e49f.png)

**Comment by phillimorland** [comment]
check for all rich text fields

**Comment by phillimorland** [comment]
all rich text fields are do not save selected target option 
possibly solution is to set all links to _blank by default - possible solution [here](https://stackoverflow.com/questions/46558041/ckeditor-default-target-link-blank-not-work-properly) although cannot find file it should be added to?

**Comment by CarolingerSeilchenspringer** [comment]
after talking to @phillimorland: should be fixed but not high prio

**Comment by CarolingerSeilchenspringer** [comment]
please note that we have the same issue in a+: https://github.com/liqd/adhocracy-plus/issues/123
