### ISSUE TITLE
reactivation of B-Plan projects (erneute Auslegung)

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1592]
background:
1) Bplan 10-44: had been published in April 2018, again from 25.6.2018 on with changed content; imperia-templated was updated, meinBerlin project was updated as well but still archivated; since date had changed to active, the archivation-option was no longer visible in backend; project was eventually de-archivated via django; due to sorting of projects by date of creation it was not at top of list; I think there was no new notification send to initiator (?)

2) Bplan 10-81aG: had been published in 2016 (!) and was published again in Oktober 2018; imperia-template was updated, new meinBerlin project was created but unpublished, without picture and without b-plan-form on bezirks-website; after manually publishing, b-plan-form did not appear on bezirks-website, still no picture. Bezirks-Website: https://www.berlin.de/ba-marzahn-hellersdorf/politik-und-verwaltung/aemter/stadtentwicklungsamt/bebauungsplaene/bebauungsplan.736681.php

suggested changes (maybe you have other solutions!): 
* automatically de-archivate bplans that are updated in imperia with new date in future/running
* sort projects by date of modification and not by date of creation
* send notification-mail for reactivated/changed bplan-projects so that initiators can make sure their project is online without checking meinberlin

And somehow make sure that b-plan-form is transferred to Bezirks-Website in cases like the second one. If complicated I might have to check again with SenStadt how often this will occur.

**Comment by phillimorland** [comment]
@MagdaN @fuzzylogic2000 to discuss

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer I don't have a better solution, but think your's are good!
Points one and three could make a US.
Point two is already one in the participation overview map thingy, right?
