### ISSUE TITLE
Server error in poll on stage server

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1599]
I get the follwing error message on stage if I try to answer a poll.

![image](https://user-images.githubusercontent.com/35491681/46663547-b377d580-cbbe-11e8-8b94-c67b796834fa.png)

seen in the project: https://meinberlin-stage.liqd.net/projects/cfd-finde-ich-gut-finde-ich-scheisse/

**Comment by phillimorland** [comment]
duplicate
