### ISSUE TITLE
Private Projects: Spelling mistakes in invitation and registration email

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-meinberlin#1600]
The Senatskanzlei noticed some spelling mistakes in the invitation emails and register emails for private projects on meinBerlin.

**Invitation (remarks/corrections in red)**
![bildschirmfoto 2018-10-10 um 16 13 59](https://user-images.githubusercontent.com/15341015/46742794-0b3e3b80-cca8-11e8-807c-c62643974d4b.png)

**Registration mail**
![bildschirmfoto 2018-10-10 um 16 18 19](https://user-images.githubusercontent.com/15341015/46742846-2741dd00-cca8-11e8-837c-34bf3fe11eba.png)

**E-Mail confirmation** 

The blue button is missing a hyphen. It should be labelled “Bestätigen Sie Ihre E-Mail-Adresse“ instead of “Bestätigen Sie Ihre E-Mail Adresse”

**Comment by MagdaN** [comment]
@rittermo @CarolingerSeilchenspringer should all "" in all emails be exchanged, because its probably kind of strange just to replace it in one email.

**Comment by rittermo** [comment]
@MagdaN Yes, please! :)

**Comment by phillimorland** [comment]
registration email and quotation marks still to be updated

**Comment by CarolingerSeilchenspringer** [comment]
spelling mistakes are already changed, the german quotation marks will soon follow with redoing of all mailings.
