### ISSUE TITLE
fix polls

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-meinberlin#1601]

**Comment by fuzzylogic2000** [comment]
There was a problem with the polls on stage and prod: votes were not counted. So, for the release we put this hotfix in: https://github.com/liqd/a4-meinberlin/commit/282ba47a570b5fb8c3e9cc795e8a6e19b6680aa3 
But we need to investigate if this is/could be still a problem and what actually happened there. Unluckily, even though the hotfix is not in the master, I can't reproduce the problem locally or on dev. Any ideas how to proceed?

**Comment by phillimorland** [comment]
@MagdaN any ideas?

**Comment by MagdaN** [comment]
@phillimorland No, not yet

**Comment by fuzzylogic2000** [comment]
@MagdaN Yeah, but don't we need to check why this happened? The answer should belong to the question, that validation must have been the for a reason. Or might have been there for a reason. :)

**Comment by rmader** [comment]
Can we close this?

**Comment by MagdaN** [comment]
yes
