### ISSUE TITLE
reenable csp

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#1633]
find out, why it broke https://github.com/liqd/a4-meinberlin/pull/1624

**Comment by MagdaN** [comment]
There is some documentation here: https://www.mapbox.com/help/how-to-use-mapbox-securely/#csp-directives

**Comment by treba123** [comment]
Fixed via https://github.com/liqd/admin/commit/8993fcb3fa131d4bfff6e9ab87029a010460e06a and https://github.com/liqd/admin/commit/5929399243501602eb3605d8ac9a076ff81cae90

But I really wonder what happens on your machines locally, as CSP_REPORT_ONLY should be set to True, disabling any blocking. Please check that you don't override that variable in your local.py or so and ask me again if it doesn't work.
