### ISSUE TITLE
Newsletter is only send to some initiators

### ISSUE THREAD

**Issue by phillimorland** [liqd/a4-meinberlin#1635]
When trying to send a newsletter to initiators of liqd, can be seen in Completed Tasks on 29. Oktober 2018 11:37 in django admin. It only sent successfully to 11 of the 13 initiators, did not show the error, also in task params had organisation_pk": null

**Comment by fuzzylogic2000** [comment]
Can you still remember what it was about? Could it be that the remaining two initiators were filtered out because they didn't agree to getting newsletters?

**Comment by phillimorland** [comment]
very probably, looking at the admin it looks about right, will close
