### ISSUE TITLE
Remove followers of org option in newsletter 

### ISSUE THREAD

**Issue by phillimorland** [liqd/a4-meinberlin#1636]
We don't have an option to follow an organisation so this option should be removed when sending a newsletter 
"Nutzer*innen die Ihrer Organisation folgen"

**Comment by phillimorland** [comment]
Can be removed in meinberlin/apps/newsletters/models.py

@CarolingerSeilchenspringer is it ok to remove this option?

**Comment by phillimorland** [comment]
@phillimorland to check for diff between mods and admin then can remove

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland I made a userstory, we need to think about follow concept on more general terms
