### ISSUE TITLE
myBerlin logo in E-Mails

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1637]
After the client told me, the logo in e-mail-notifications/newsletters was at a normal size again, today he send an SOS saying that the logo "is growing again". Do we have any idea on how to fix this problem? it seems to be an outlook thing. @szukowski can you test it on your outlook at home?

![image](https://user-images.githubusercontent.com/35491681/47650381-5d280200-db80-11e8-8dc3-04661d950ba5.png)

**Comment by fuzzylogic2000** [comment]
@phillimorland Can we add a max-width to the logo? Or is it already there and not working?

**Comment by phillimorland** [comment]
it currently has a max height set but the img tag also has a width set so will try setting a max width instead. 
Testing is a problem, my usual testing sites don't check outlook without a paid account also local testing of emails?

**Comment by fuzzylogic2000** [comment]
we decided to investigate more! find a testing computer and so on!

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer It should be fixed now! We will close the issue! But could you keep an eye out for people, who read newsletters on windows-outlook and check it it's really fixed?
