### ISSUE TITLE
Fix filter bar overlap

### ISSUE THREAD

**Issue by xi** [liqd/a4-meinberlin#166]
The filter bar is supposed to overlap its box in some cases:

![screenshot from 2017-04-10 14 37 24](https://cloud.githubusercontent.com/assets/202576/24863366/d0ce4bc2-1e00-11e7-972c-dc597afb7d89.png)

As you can see, the current implementation displaces the stats of the first list item.

A lot of work and thought was already put into this in #144, but with limited success. A workaround which disables the overlap was pushed in #165.

**Comment by vellip** [comment]
Hint: This only occurs if there's not left aligned filter but only the ordering widget.
