### ISSUE TITLE
Header font changed from Liberation Sans to DejavuSans

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#1669]
On the servers with the releases the font in the header is Liberation Sans. In the current master (and by that on the dev-server) DejaVuSans is used. As the second is broader it breaks the design as the user bar is going over the blue line.
@phillimorland @MagdaN Is that intended? Do you know why it happened?

**Comment by fuzzylogic2000** [comment]
Oh my, it's used everywhere now. So I guess it was intended??

**Comment by phillimorland** [comment]
@fuzzylogic2000 as this is browser dependent do we want to close the issue? or we could choose to have a specific site font and install it?

**Comment by fuzzylogic2000** [comment]
Also, we don't have the blue line anymore! So, doesn't matter!
