### ISSUE TITLE
accordion landing page (testing #741)

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1673]
there is a funny dotted line, window 10, latest firefox
![image](https://user-images.githubusercontent.com/35491681/48623949-841d6b00-e9ab-11e8-86a0-28c3ff96dbd7.png)

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer I had a little look at this issue, all the accordions currently behave in this way on windows with firefox however it doesn't happen with other OS/browser combinations on browser stack. It doesnt seem to be a quick fix so just wanted to make sure it's a priority before I sink more time in?

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer Do we need to fix this issue for the accordeon story to be closed? Doesn't seem very related (happens on all accordeons).
And how much time should we spend on this/is this an important issue to fix?

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland @fuzzylogic2000 I don't think it is important, I just noticed during testing. Since it is neither easy to fix nor does it happen often, I will close the story.
