### ISSUE TITLE
switch broken (goes with #744)

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1721]
can't use switch
Seen on ipad 5/safari 

![bildschirmfoto 2018-12-10 um 14 44 30](https://user-images.githubusercontent.com/35491681/49737991-8adb8d00-fc8e-11e8-8885-acc3699de5a1.png)

**Comment by fuzzylogic2000** [comment]
Uh, and there are both switches. I guess, the breakpoints are mixed up?!
