### ISSUE TITLE
Listview broken on ipad

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1733]
List-map-footer-combination seen on ipad 5, safari

![bildschirmfoto 2018-12-11 um 14 50 02](https://user-images.githubusercontent.com/35491681/49804933-30a4ff80-fd54-11e8-9ae8-4741f8d86f3d.png)

**Comment by fuzzylogic2000** [comment]
check again when #1706 fixed!

**Comment by CarolingerSeilchenspringer** [comment]
looks fine now!
