### ISSUE TITLE
take out g+ and i of footer

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1758]
since g+ will no longer continue after 2019 we should take it out of the footer. Also the "i" with its link to some article from 2014.

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer Well, we still use shariff, so the link should maybe be replaced? With shariff you actaully need to click on the social icons before you're tracked by these sites.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 you are right, if this is not standard we should inform about it. How about this link: https://www.berlin.de/wir-ueber-uns/agb/datenschutz/3990064-4219234-socialmediabuttons-mit-datenschutz-shari.html? It is part of the datenschutz of berlin.de. It also links to heise but gives its own explanation. It just seems strange to link to this old article with a lot of advertisement around.

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer Yes! Good link! Thank you!

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer I put in the link, but thought afterwards that it might make sense to add a wagtail site explaining it of our own?! Then we're not dependend on the berlin.de-site existing forever. But we can also do and change that later.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 yes, let's do this later and close the issue. I will write it on my list to discuss it in our next JF, as there might me more issues coming up in the end. For DKF it is important to take out G+, he saw that right away.
