### ISSUE TITLE
info grafic landin page (story #747)

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1780]
berlin logo is not correctly displayed 

mac, safari & galaxy s8, chrome (when zooming in with trackpad)
![bildschirmfoto 2019-01-04 um 14 25 48](https://user-images.githubusercontent.com/35491681/50690360-43e27c80-102d-11e9-92cb-33ef3197abd2.png)

![bildschirmfoto 2019-01-04 um 14 31 06](https://user-images.githubusercontent.com/35491681/50690395-66749580-102d-11e9-88cf-63be6657dccb.png)

**Comment by fuzzylogic2000** [comment]
@szukowski Could you make another image with a bit of whitespace to the right and the bottom of the be berlin-logo? 
I think we can solve the problem in the lower image with that but can't probably get the problem in the upper image right.

**Comment by phillimorland** [comment]
Second image issue
As stated in Taiga, cannot find logo with additional whitespace. 
Note to self:
Investigated other possible fixes, including adding spacer div, negative margins , changeing flex values including, grow. shrink. justify content. align items, also adding max width.
