### ISSUE TITLE
small font-sizes are too big

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#1838]
after we did #1786 the labels are better to read, but the breadcrumbs look a bit strange, like someone is screaming at you. Should we change it back and only give the labels a bigger font-size? Or should we change the font-sizes to something inbetween? Or should we use a smaller font-size for the breadcrumbs?
What do you think, @CarolingerSeilchenspringer @szukowski ?

**Comment by CarolingerSeilchenspringer** [comment]
I agree, they do look a bit too big. I will leave this up to @szukowski

**Comment by fuzzylogic2000** [comment]
@szukowski Could you say what to do here? (You can find the big writing on the plans detail page, when you click on a vorhaben on the list)

**Comment by fuzzylogic2000** [comment]
@szukowski says to make breadcrumbs same size as labels

**Comment by fuzzylogic2000** [comment]
not necessarily in release2.0 milestone, but I would like that.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 i'm fine with taking the milestone out of this issue.
