### ISSUE TITLE
starts at date string is missing the date on project tiles (in storefront)

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-meinberlin#1846]
![bildschirmfoto 2019-01-24 um 16 50 58](https://user-images.githubusercontent.com/2905743/51690177-76621280-1ff8-11e9-9492-8b0b328a52a3.png)

**Comment by CarolingerSeilchenspringer** [comment]
as discussed with @szukowski and @phillimorland : wording in German should be "Beteiligung ab ..."

**Comment by CarolingerSeilchenspringer** [comment]
#2050

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland please try external projects without phase.
