### ISSUE TITLE
#714 Filterbar - font

### ISSUE THREAD

**Issue by szukowski** [liqd/a4-meinberlin#1852]
DESKTOP:

- Button "weiter Filter": Please reduce font size. class btn light, size 15px. in comparison:  the sentence has class text lead font-size 20px

TABLET:

- the entire text (question & form) "I am interested ...." please in a larger font size class text lead 40px

**Comment by phillimorland** [comment]
@szukowski for tablet display it looks very large at 40px, do we definitely want it that big? 
![screenshot 2019-01-30 at 09 55 51](https://user-images.githubusercontent.com/5871230/51969702-64a7c180-2475-11e9-8061-0109f3e14ce0.png)
