### ISSUE TITLE
#714 Filterbar open view - position & spacing

### ISSUE THREAD

**Issue by szukowski** [liqd/a4-meinberlin#1853]
DESKTOP:
- Spacing bottom should be the same as top.

TABLET:
- in the tablet view, the filterelement is not going to the edge but has a white space left and right, flush with the underlying content.
 - The two dropdowns are not lie among themselves to each other but side by side.
- All elements should have a baseline - right and left. Please do not indent the filter options

SMARTPHONE:
-please do not break the sentence. the spacing right and left flush with the underlying content

**Comment by phillimorland** [comment]
@szukowski I think everything is fixed on this issue? It should have been closed with my pull request

**Comment by szukowski** [comment]
@phillimorland the spacing unfortunately does not fit yet:
- padding bottom and pading top should be the same
- now there is a space between the bar and the expanded. please remove. 

the same on the landigpage element
