### ISSUE TITLE
#714 Filterbar open view - font

### ISSUE THREAD

**Issue by szukowski** [liqd/a4-meinberlin#1854]
Could we have a check on the mobile typeface again? At the moment it seems a bit restless because we have many different sizes. For example: the sentence has a different size than the dropdown-text, dropdown default is large, filteroptions are smaller, …

TABLET:
- the entire text (question & form) "I am interested ...." please in a larger font size class text lead 40px
- the font size of the filter options looks a bit small. The class navbar sublevel 32px should be approximately in order to allow a good interface (click area)

**Comment by phillimorland** [comment]
@szukowski  I need clarification on this last point, I have partially fixed this issue but will leave open, maybe we can have a quick issue meeting after fixes have been merged
