### ISSUE TITLE
the star * is partly missing for obligatory fields

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1884]
the Ergonomiegutachten pointed out that the * is missing for Anfangsdatum/Enddatum although it is obligatory. As I can tell there is a ! at first but once you set a date it is gone and there is no *. If you publish the project the * appears and is gone again if you depublish.  The same is true for "Beschreibung ihres Projekts" in "Information" which also has a ! at first.

Is it supposed to behave like this? Supposingly it confuses the user and I guess it would be nicer to go from the ! directly to the * after saving (and not after publishing). 

 I checked for brainstorming and idea collection with map.

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer which browser? I have had trouble replicating this

**Comment by CarolingerSeilchenspringer** [comment]
will be fixed with story "1904 make phases for external projects obligatory"
