### ISSUE TITLE
PopUp underneath infobox

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-meinberlin#1890]
@CarolingerSeilchenspringer @szukowski at the moment the popup of a marker is displayed underneath the infobox and the searchbar. Should this stay like this?
![bildschirmfoto 2019-02-01 um 11 20 17](https://user-images.githubusercontent.com/2905743/52117670-92773c80-2614-11e9-8ce7-2220144dd4bd.png)

**Comment by CarolingerSeilchenspringer** [comment]
@szukowski wants to have it below and since it is complicated otherwise I close the issue
