### ISSUE TITLE
Map on mobile

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-meinberlin#1891]
@szukowski @CarolingerSeilchenspringer 

at the moment it is hard or even impossible to scroll when the map is activated as the user would drag the map instead. There are a view options that could help:

1. decrease the height of the map so that the user can always touch above or underneath the map
2. add some space besides the map so that the user can scroll there
3. disable dragging (not really an option)
4. add a button on the map that scrolls up and/or down
5. disable dragging and add a button to disable/enable drangging

Option 1. and/or 2. would be the easiest to implement

**Comment by CarolingerSeilchenspringer** [comment]
option  1 sounds best for me.

**Comment by fuzzylogic2000** [comment]
@szukowski  proposes to only enable scrolling with two fingers. Could hopefully be set like this: https://stackoverflow.com/questions/41622980/how-to-customize-touch-interaction-on-leaflet-maps

**Comment by phillimorland** [comment]
@fuzzylogic2000 is this the preferred way then?

**Comment by fuzzylogic2000** [comment]
Weeel, works on mobile, but broke it on desktop...
