### ISSUE TITLE
Tiles within plans and container have old style

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1902]
is there an easy way to copy the new styles of the tiles into containers and detail view of plans?

![z](https://user-images.githubusercontent.com/35491681/52209928-b4c3c100-2885-11e9-8e73-b68f872bc4a3.jpg)

**Comment by fuzzylogic2000** [comment]
Well, we can copy the markup and design, but that is an US. About 3 points.
And it's only the vertical project tiles in two places, right?

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer Can you please close this issue and make a US out of it?

**Comment by CarolingerSeilchenspringer** [comment]
done
