### ISSUE TITLE
missing topic in Steckbrief of plans

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1903]
![missing topic](https://user-images.githubusercontent.com/35491681/52210099-4cc1aa80-2886-11e9-9e70-f27221036fb6.jpg)

**Comment by fuzzylogic2000** [comment]
We added that on Friday. Seems like I have to recheck.

**Comment by fuzzylogic2000** [comment]
Well ok, we added the labels. Will add it to the Steckbrief as well. @szukowski Should it stay in both places (as label and in the Steckbrief)?

**Comment by CarolingerSeilchenspringer** [comment]
as discussed with @szukowski: leave out the topic label and only have topic in Steckbrief.
