### ISSUE TITLE
change icon for external project

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1906]
I like version A better than B as it is now. I discussed with @szukowski to stick to the original design of version A

A: 
<img width="61" alt="bildschirmfoto 2019-02-04 um 14 28 01" src="https://user-images.githubusercontent.com/35491681/52211123-3537f100-2889-11e9-9f73-7859267b8620.png">

B: 
![bildschirmfoto 2019-02-04 um 14 27 48](https://user-images.githubusercontent.com/35491681/52211092-1cc7d680-2889-11e9-8ca0-b543805f55de.png)

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer How important is this? It seems to be more than just exchanging the font awesome.
@phillimorland Did you add it as bg-image because it isn't font awesome or because it's not possible differently? Well actually, I don't know how it would be.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 nice to have

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer Well, then let's not do it. Would take too long and still enough to do. :) If you disagree reopen.
