### ISSUE TITLE
organisation filter

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1909]
the letters that I type and the grey ones the filter suggests are not really on top of each other .

![bildschirmfoto 2019-02-04 um 14 35 57](https://user-images.githubusercontent.com/35491681/52211464-3d446080-288a-11e9-8f44-4a6cccad0f2c.png)

**Comment by fuzzylogic2000** [comment]
Oh, what browser? It doesn't look that bad in my firefox.

**Comment by CarolingerSeilchenspringer** [comment]
oh sorry, chrome on mac

**Comment by CarolingerSeilchenspringer** [comment]
same for chrome on windows
