### ISSUE TITLE
Landing Page teaser: not easy to read text on map

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1911]
i find it hard to read the text in the teaser with the map as background. 

@MagdaN @szukowski 
can we find/generate a map of berlin that does not have Ortsbezeichnungen like "Gesundbrunnen" and "Berlin" on it? 

![teaser](https://user-images.githubusercontent.com/35491681/52213521-9ebafe00-288f-11e9-9cea-2a7b4309def9.jpg)

**Comment by fuzzylogic2000** [comment]
Well, this is not a programming issue. You can exchange the image in wagtail as soon as you have another one. Will leave it open for you as a reminder?!

**Comment by CarolingerSeilchenspringer** [comment]
@szukowski put a white background behind the text into her design (important: no straight edges). If it does not work now, @szukowski will provide a different map.
