### ISSUE TITLE
change wording for projects being part of container

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1913]
the navigation "zurück zu container xy" does not make sense if I come to this project via the project overview. We decided that for now we show both projects and container. Then we need to change the wording to: "zur Projektsammlung xy"

![bildschirmfoto 2019-02-04 um 15 24 24](https://user-images.githubusercontent.com/35491681/52214045-0887d780-2891-11e9-9d6b-e47dc6ce7be9.png)

**Comment by fuzzylogic2000** [comment]
Well, we don't know if we came from the participation overview or the container overview. We have to put in a link and wording that works for both cases.
Maybe we could add "back to participation overview" (like in the plans detail view) for all projects?

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer What do you think? (Sorry, forgot to mention you last time!)
