### ISSUE TITLE
add label to selection of secondary filter

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1921]
add a label/explanation to user selection of secondary filter in order to make it easier to understand.

"weitere gesetzte Filter"

same styling as "Karte anzeigen"

<img width="337" alt="bildschirmfoto 2019-02-05 um 11 12 33" src="https://user-images.githubusercontent.com/35491681/52266611-1f810500-2937-11e9-8440-0b28ab1b05e6.png">

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer I think that's a good idea! But where exactly do you want to put it? Over it, or also to the left? What should happen on tablet and mobile (where "Karte anzeigen" is also not shown)?
@szukowski How should we do it?

**Comment by CarolingerSeilchenspringer** [comment]
@szukowski already put some wording in the design. Since we use a different number on the blue tile in storefrontwindow and the numbers should be the same and we don't have much time, we will write "gesetzte Filter" for now and change it later when we introduce the number of filter results.
