### ISSUE TITLE
secondary filter: lables for search and organisation filter

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1923]
I think we should make the very long search bars in the secondary filter shorter. If we consequently put lables above them, as we do for the "Beteiligung" and "Projektstatus", it would become clear that the two search functions are not the same. The whole secondary filter window would become smaller, more compact.

what about this wording and order:
Beteiligung (top left)
Projektstatus (top right)
zuständige Organisation (bottom left)
Projekttitel (bottom right)

don't use the word "Verwaltung" as long as we still have many other organisations in there. We might change this later to "Verwaltung" when we have solved the problem of the external agencies of the administration getting their own organisation.

**Comment by fuzzylogic2000** [comment]
Hmm, this is for @szukowski to decide. It kind of looks like the design now?!
@CarolingerSeilchenspringer The text with Verwaltung is from the designs. What should we put there instead?

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer For the label and placeholder we need a text from you?!
@szukowski I will assign you to this issue to think about/comment the other bits!

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer Could you make up a text that doesn't include "Verwaltung"?

**Comment by CarolingerSeilchenspringer** [comment]
go for "Organisation" and "Name der Organisation eingeben"

**Comment by szukowski** [comment]
@CarolingerSeilchenspringer I would leave the successors of the filter elements so please. for someone who just wants to search fast, the entry is properly positioned, then come filters that are relevant to the participation. the last position gets the administration, this is the least important in the priority.

**Comment by CarolingerSeilchenspringer** [comment]
@szukowski sorry, this was just an idea from the review but we decided to leave it this way. Only the headline for the organisation filter needs to be implemented and changed in wording as we cannot use "Verwaltung" for the Quartiersmanagements.
