### ISSUE TITLE
secondary filter on mobile

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1924]
not according to design and a little buggy:
* filter too close to one another
* text outside button

using iphone 7 safari

![image](https://user-images.githubusercontent.com/35491681/52270352-04b38e00-2941-11e9-8824-f215691d887e.png)

**Comment by fuzzylogic2000** [comment]
This is just not done yet. The mobile overlay for the secondary filters was not meant to be tested yet, sorry!
@phillimorland is also fixing this with the overlay, right?

**Comment by phillimorland** [comment]
I have a pull request outstanding for switch button and making filters overlay but the formatting problems are new, guess it's a safari thing, I can look into it in another pull request
