### ISSUE TITLE
Teaser filter on LP: district filter disappears

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1927]
In teaser filter I set a district, then went back to „all“ and the filter disappeared.

On iPad Air 2

![5e17170e-f4e5-4dac-a48b-1cf93139bb5f](https://user-images.githubusercontent.com/35491681/52271760-e8195500-2944-11e9-9b73-af3fba0dbb02.png)

**Comment by phillimorland** [comment]
I cannot work out why this doesn't reset back to -1?
