### ISSUE TITLE
plan: jump to error message

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1930]
can we jump to the error message that appears when I don't enter a topic for my plan? Or have a warning if I leave the form?

if I don't chose topics in plans and still save, the page jumps to the top and I probably don't see that my plan is incomplete and not published. If I navigate somewhere else, I don't get a warning and nothing is saved.

The same is true for projects, although not as dangerous, because I have the little red !. 

<img width="948" alt="bildschirmfoto 2019-02-05 um 13 38 20" src="https://user-images.githubusercontent.com/35491681/52273891-6b3da980-294b-11e9-872b-e745efe6ec91.png">

**Comment by fuzzylogic2000** [comment]
I see this as a problem as well, but as this behaves in this exact same way everywhere in the dashboard and on other forms, I think we shouldn't tackle it here. Maybe US? 
At least it doesn't seem easy to me. What do you think, @MagdaN ?

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 @MagdaN we'll make a story out of it then.

**Comment by MagdaN** [comment]
@CarolingerSeilchenspringer @fuzzylogic2000 I think whats missing, is a notification (error message) on top of the form that says that there are errors further down. I think thats would be best as there might be several errors in the form and you would not know where to jump to then.

This is an easy fix, but I would agrre with @fuzzylogic2000 we should address this in a separate US (maybe looking at other forms as well ?)

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer With the new budgeting with two phases this becomes more important again: If you try to add overlapping phases, the error message is shown at the very end of the form and not be seen. An easy fix would be to display some error message on top as well, like we do in a+. Could you check it out? - That one should be a small story and fix it for everything in the dashboard!

**Comment by CarolingerSeilchenspringer** [comment]
thanks for the hint @fuzzylogic2000! I had a look at a+ and moved up the story already existing in mB-backlog. Can you just tell me what you mean with "display some error message on top as well". Does that not affect ALL errors? Or just the ones that are not visible right away? What is the behaviour?

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer Yes, that should and will affect all errors in the dashboard forms. Maybe say explicitly in the story if you also want that in all the extra-stuff in mB (linkages, plans, ...)
