### ISSUE TITLE
tiles: teaser and progress bar on top of each other

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1931]
the tiles look like this on mac firefox and chrome

<img width="581" alt="bildschirmfoto 2019-02-05 um 14 55 56" src="https://user-images.githubusercontent.com/35491681/52278021-4c90e000-2956-11e9-99f7-5ea124afcb10.png">

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer this is because we increased the char count and we now have option for 2 labels, make the char count lower again will help but might still be a problem if we have 2 labels and long title, will have a think on this

**Comment by fuzzylogic2000** [comment]
We decided to not show the description on the horizontal tiles, and the full description on the vertical ones.

**Comment by CarolingerSeilchenspringer** [comment]
@szukowski or do you have a different solution for smaller screens?
