### ISSUE TITLE
district, topic and localisation for external projects and bplans

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1933]
external projects also need district, topic and localisation as the other projects do. 

same is true for b-plans as not all of them come via imperia

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer Obviously true for external projects!
But kind of only partly for bplans. We need to add the topics for the Bplans as well, but I think we shouldn't add the location and district to the dashboard as we get that automatically!?

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 the senatsverwaltung für Stadtentwicklung sometimes also have bplans but don't use imperia. They start them via meinberlin.

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer That should be fine as long as they fill in the bezeichner-field, which should be there. As soon as they save the bplan, we try to get district and localisation from the other bplan-API, just as we do for the stuff filled in with imperia. So, we should be fine!

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 I will think of a helptext for the Bezeichner (Identifier) that works for both, SenStadt and Imperia

**Comment by fuzzylogic2000** [comment]
We said we will:
- add both tabs (Ort and topics) to external projects
- add topics to Bplans
- add a helptext for the identifier-field of bplans
- fix #1929 at the same time (wording change tab name/title)

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 as just discussed: no need to add topics to Bplans, just always set them on Stadtentwicklung, no matter if they come from imperia or via meinBerlin

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer Do you already have a helptext for the identifier?

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer Can you please give me the helptext for the identifier?

**Comment by CarolingerSeilchenspringer** [comment]
"Der Bezeichner des Bebauungsgplans muss identisch mit dem Bezeichner im FIS-Broker sein. So werden Informationen zum Bezirk und zur Verortung automatisch hinzugefügt."
