### ISSUE TITLE
change wording in "Orte"

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1934]
to make the difference between "Ort" and "Karte" more clear, please change the wording:

"Projekte, die auf der Karte lokalisiert werden können, werden in der Projektübersicht sowohl auf der Karte als auch in der Liste dargestellt. Projekte ohne räumlichen Bezug erscheinen lediglich in der Liste."

<img width="384" alt="bildschirmfoto 2019-02-05 um 15 26 54" src="https://user-images.githubusercontent.com/35491681/52279713-8368f500-295a-11e9-8b9f-fd0c393d3df1.png">

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer Where exactly is that? Dashboard? Location-Tab (do we have that)? Plans or projects or both?

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000: yes, Dashboard, the new tab to localize your project or container so that it appears on the new map. Plans work differently.

**Comment by CarolingerSeilchenspringer** [comment]
just realized that the whole explanation text on how to set a point is missing. So new wording:
Kann Ihr Projekt auf der Karte verortet werden?
Wenn Sie Ihr Projekt verorten, wird es in der allgemeinen Projektübersicht zusätzlich zur Liste auch in der Karte angezeigt. Um einen Pin zu setzen, klicken Sie innerhalb des markierten Bereichs oder geben Sie eine Adresse ein. Ein gesetzter Pin kann verschoben werden, wenn Sie ihn festhalten.

**Comment by fuzzylogic2000** [comment]
So, we put this title and help text into the project location and the second part of the helptext also in the map-thing for mapideas and plans.

**Comment by CarolingerSeilchenspringer** [comment]
even better: ...wenn Sie ihn gedrückt halten!
