### ISSUE TITLE
change wording on tiles and pop-up

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1935]
change the wording on tiles and pop up from
"Gesamtstädtische Projekte" zu "Gesamtstädtisch"

I guess this comes from the district filter? then please change it there, too, if they are dependent.

**Comment by fuzzylogic2000** [comment]
revert: https://github.com/liqd/a4-meinberlin/commit/d434fd0533fb9819022c52ca46ffe19c7d72bc4b
