### ISSUE TITLE
add URL for selection of secondary filter

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1937]
if possible, also add an URL for the secondary filter so that i can go back via browser and get to my filter selection.

**Comment by fuzzylogic2000** [comment]
If we do so, we should also adapt the district-link in the storefront tile, so that the number of projects on the button and in the list are the same.

**Comment by CarolingerSeilchenspringer** [comment]
moved into taiga backlog.
