### ISSUE TITLE
error message needs translation

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1938]
please translate "Sie können max. 2 Themen auswählen."

"![bildschirmfoto 2019-02-05 um 17 02 37](https://user-images.githubusercontent.com/35491681/52286122-e7de8100-2967-11e9-98e0-ade8f6d16d23.png)

**Comment by fuzzylogic2000** [comment]
This is in one of the packages: venv/lib/python3.6/site-packages/multiselectfield/validators.py
We found a way to translate package-strings/add them. Do you remember right away where that was, @MagdaN ?

**Comment by MagdaN** [comment]
https://github.com/liqd/a4-meinberlin/blob/master/meinberlin/apps/contrib/django_standard_messages.py

**Comment by MagdaN** [comment]
you might have to add the multiselect thing to installes apps in the settings. https://github.com/goinnn/django-multiselectfield#in-your-settingspy

**Comment by fuzzylogic2000** [comment]
done!
