### ISSUE TITLE
a11y secondary filters 

### ISSUE THREAD

**Issue by phillimorland** [liqd/a4-meinberlin#1943]
Tested with Chrome Vox in browser:
"nach projeckttitel suchen" is read twice, don't think we need placeholder and sr span?

**Comment by fuzzylogic2000** [comment]
This side says, that you shouldn't replace labels with placeholders: https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Placeholder_Research
I say. better to live with having it read twice than having read none?!
