### ISSUE TITLE
secondary filter: seach function and organisation filter doen't work on IE

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1950]
on Windows 10, Internet ExpIorer 11

I can fill seach function and organisation filter  but submitting does not change the result nor are they displayed underneath the blue bar together with the other selected filter.

**Comment by fuzzylogic2000** [comment]
Are we still doing IE11? Yeah, I know, argh. But all the other filters work?

**Comment by phillimorland** [comment]
@fuzzylogic2000 @CarolingerSeilchenspringer I checked analytics and we still get a big chunk of our traffic through IE (16%)

**Comment by phillimorland** [comment]
@fuzzylogic2000 @CarolingerSeilchenspringer I checked again on dev as we thought one of filters might be fixed but currently the filters that don't work; Themen, Search, Organisation, all can be selected/written in but they do not change the results or get added as search tags. When trying to update Themen option, the filter, list and map elements fail to load on the page.  
Also map search is translucent until clicked in with incorrect button padding

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland @fuzzylogic2000 : client put this on his issue list with priority 1. I know, it is IE11, but that's what the administration uses and the filters are elementary. Can we find a solution?
