### ISSUE TITLE
switch button to change list/map view

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1954]
on Galaxy S8 chrome the switch button is it a little too long on the bottom so the icon is not centered.

![bildschirmfoto 2019-02-07 um 12 13 36](https://user-images.githubusercontent.com/35491681/52407993-124c4d80-2ad2-11e9-9c28-a3472bebf422.png)

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer ahh this along with issue #1955 should have been fixed, hence can't reproduce
