### ISSUE TITLE
jumping switch button

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1955]
i find it a bit confusing that the switch button on mobile is on the left and jumps to the right if I deselect one of the two default secondary filter. Can't it always be left and just go down if there are filters selected? @szukowski ?

here: Galaxy S8

![bildschirmfoto 2019-02-07 um 12 19 42](https://user-images.githubusercontent.com/35491681/52408401-23498e80-2ad3-11e9-8539-87ecb3a6c4cb.png)
![bildschirmfoto 2019-02-07 um 12 19 29](https://user-images.githubusercontent.com/35491681/52408534-51c76980-2ad3-11e9-9809-9daacfb62267.png)

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer cannot reproduce either issue, what browser and device was this on?

**Comment by szukowski** [comment]
@CarolingerSeilchenspringer Filter elements belong together (filterable and filter tags) as well as map elements, the switch and the map. so first position is filters, then come the map elements. switch always right.

**Comment by CarolingerSeilchenspringer** [comment]
@szukowski I think @phillimorland already changed it. Now the switch is always right and does no longer jump around.
