### ISSUE TITLE
plans: take out wording if no project is connected

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1957]
if there is no project connected to a plan this is what it shows. please delete this connection to the filter. The info as already found on the top of the page.

<img width="696" alt="bildschirmfoto 2019-02-07 um 14 35 38" src="https://user-images.githubusercontent.com/35491681/52414970-0ec2c180-2ae6-11e9-855c-2e1cd1de82ab.png">

**Comment by fuzzylogic2000** [comment]
Can we do it later? And not for the release? This is neither connected to a story in the sprint, nor needed right away.

**Comment by CarolingerSeilchenspringer** [comment]
I wonder how it got there in the first place and Can't remember that I've seen it before. But yes, we can wait. I'll take out the milestone.
