### ISSUE TITLE
storefront window on smarthphone

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#1962]
in both testing and review we got the feedback that the entry into landing page is not very clear on smartphone. Instead of a random tile, can we have only the image tile and the blue tile? One of the random tiles alone is not very explainatory. What do you think, @szukowski ?

**Comment by fuzzylogic2000** [comment]
Or the image tile, one of the random tiles and the blue tile?

**Comment by CarolingerSeilchenspringer** [comment]
as discussed with @szukowski : Image tile, two random tiles, blue tile
