### ISSUE TITLE
Primary & Secondary Filter - close expanded Filter outside

### ISSUE THREAD

**Issue by szukowski** [liqd/a4-meinberlin#1997]
Desktop: Is it possible to close the expanded filters (primary and secondary) by clicking outside the filter element. For users this would be a learned behavior and also an expectation. At the moment he has to execute an action in the filter to close the element.

**Comment by fuzzylogic2000** [comment]
@szukowski I couldn't get that to work (in three hours). Is there another way?

**Comment by phillimorland** [comment]
I found this with a number of different options, I am having a play with the top one but i'll leave it here if I don't get it working
https://stackoverflow.com/questions/32553158/detect-click-outside-react-component
