### ISSUE TITLE
shopwindow - counter font style

### ISSUE THREAD

**Issue by szukowski** [liqd/a4-meinberlin#2007]
- please change the description style from bold to regular
- the description should be more like a block below the number. more indented on the left.
- the number should be closer to the description

on the pink field:
- the number is a little too small. in proportion it should be for example: 40px on pink and 60px on blue

**Comment by fuzzylogic2000** [comment]
@szukowski These are the blue and pink tiles, right?

**Comment by szukowski** [comment]
@fuzzylogic2000 Yes ;)
