### ISSUE TITLE
running container isn't shown as running (can't see when filter running is set)

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#2016]

**Comment by CarolingerSeilchenspringer** [comment]
saw that, too. e.g. for container of LLBB which is called "Leitlinien für Beteiligung von Bürgerinnen und Bürgern an der Stadtentwicklung" and which includes running projects

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland only do it if easy fix.

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer  Oh, this might not be easy. And also, it will not be counted on the district-tile. Should it also be counted there then? Then we will have to explicitly add that to the count as well.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 grrr, container! can we have a quick personal chat on this issue?

**Comment by CarolingerSeilchenspringer** [comment]
as discussed with @fuzzylogic2000 : leave container where they are, take out the whole Beteiligungsline and we will wait for the final decision whether or not to keep the container at all.
