### ISSUE TITLE
status of plans is shown as running, but not filetered in the same way

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#2039]
As noticed by @MagdaN in #2038.
When there are projects associated to the plan, we either print 'runnig', 'starts in the future' or 'ended'. When there are noc projects associated, we put in the value of the participation choice, filled in by the initiator, so iether 'yes', 'no', or 'undecided'. Is it intended like that, @CarolingerSeilchenspringer ?

**Comment by CarolingerSeilchenspringer** [comment]
@szukowski can we talk about this?

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 Where exactly do we display this info?

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer By now it behaves differently than described here. On the tile in the project list, we always display the Status that is set in the plan. The problem now is, that we still don't filter for it. So, when we display the plan as running, it is still not shown in the list filtered for riúnning projects, when no associated project is running.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 did you change something again? Or else I don't understand the problem, it all looks fine to me. eg this [plan](https://meinberlin-dev.liqd.net/vorhaben/2019-00051/) is shown and filtered as running and has no associated project.

**Comment by fuzzylogic2000** [comment]
Yes, you're right!
