### ISSUE TITLE
project storefront tile title goes over the status-timeline

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#2061]
For long titles, the text is going over the status. The time nearly over clock makes it a bit worse (and will also be there and make it worse if we remove the padding again. Any ideas, @phillimorland ?
![screenshot from 2019-02-27 14-20-33](https://user-images.githubusercontent.com/8178179/53493215-1d741700-3a9b-11e9-897d-7fb67666be51.png)
![screenshot from 2019-02-27 14-19-43](https://user-images.githubusercontent.com/8178179/53493216-1d741700-3a9b-11e9-8d20-803701d15ee4.png)

**Comment by phillimorland** [comment]
damm, i thought this was fixed in my last update, obviously wasn't testing with right title, i'll check the char limit on titles and test with the max and fix it once and for all (hopefully!)
@fuzzylogic2000 this is mobile right?

**Comment by fuzzylogic2000** [comment]
@phillimorland Desktop. (My big screen.) Sorry!

**Comment by phillimorland** [comment]
@fuzzylogic2000 ok no worries, when is next release? monday?
