### ISSUE TITLE
project title overlap with progress bar in project overview

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2063]
on smaller screens (here: Mac 13,3-Zoll 2560 x 1600) a long title overlaps the progress bar in the horizontal tiles. 

<img width="600" alt="bildschirmfoto 2019-03-04 um 14 17 51" src="https://user-images.githubusercontent.com/35491681/53735838-568bfd00-3e88-11e9-81e5-59fb0c6724f0.png">

This is what it looks like with the longest title possible with only one topic. 

<img width="600" alt="bildschirmfoto 2019-03-04 um 14 23 25" src="https://user-images.githubusercontent.com/35491681/53736129-22fda280-3e89-11e9-9b28-af409b753fd5.png">

@szukowski What would be your idea to solve this?

**Comment by szukowski** [comment]
@CarolingerSeilchenspringer There are different scales. for example the teaser image is omitted if the resolution is too narrow. Layouts are all in zeplin

**Comment by szukowski** [comment]
@CarolingerSeilchenspringer the basic idea was actually to shorten the teaser text with "...". Also, the distance to between the tags is a bit large.

**Comment by CarolingerSeilchenspringer** [comment]
@szukowski @phillimorland I am fine with not showing the picture for narrow resolutions. We have a problem with cutting off the teaser as the teaser does not know how long the title or tags are. You would have to always cut it off, which looks wired if you have a short title.

**Comment by fuzzylogic2000** [comment]
@szukowski @CarolingerSeilchenspringer When are the images not meant to be shown? 
I thought, we would just switch to vertical tiles on smaller screens? Also remember, that we only have three breakpoints, we can use and are currently using. We can only not show images, when smaller than some breakpoint.
So, what should we do? Make narrower space between the topics themselves and also the district? And cut of the description? Or not show it on vertical tiles? Or only show it on vertical tiles when there is no image?

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer @szukowski @fuzzylogic2000 we can set it to only show images on horizontal tiles over 1440px, will that be ok?

**Comment by szukowski** [comment]
@phillimorland That's exactly how it was planned. either below 1440 or below 1200px. how it makes the most sense.
