### ISSUE TITLE
pictures cut off in project overview

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2065]
client hinted at the fact that pictures are cut off/not displayed completely. This of course depends on the tile, as we have square pictures on the horizontal tile and horizontal picture on the vertical tiles. 

![bildschirmfoto 2019-03-04 um 15 32 17](https://user-images.githubusercontent.com/35491681/53739723-c69f8080-3e92-11e9-839d-423b87bdec09.png)

![bildschirmfoto 2019-03-04 um 15 32 32](https://user-images.githubusercontent.com/35491681/53739724-c69f8080-3e92-11e9-848c-7ae931409932.png)

What can we do about it (as issue or story)?
* make all pictures square, also in vertical tiles?
* say in helptext to not use pictures with words?
Any other solution I could offer?

@szukowski this question is mainly a design question

**Comment by szukowski** [comment]
@CarolingerSeilchenspringer Here you have to choose another picture section. The tags have a fixed position and there will always be motifs that overlap. Here is the editor asked.

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer @szukowski we can set the images to be contained within the image space but this will look like this, would that work? or we make it so they can only upload square images? 
I think we already ask them not to add text to images but apparently it doesn't work
![screenshot 2019-03-07 at 13 46 27](https://user-images.githubusercontent.com/5871230/53957780-8d0f8500-40df-11e9-9531-656fb590a237.png)

**Comment by CarolingerSeilchenspringer** [comment]
ok, then we will leave it like it is and the editor has to chose a different picture. Thanks!
