### ISSUE TITLE
zoom button outside view on project map

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2066]
can we put the zoom button in the top right corner for desktop and tablet and low right for smartphones? client put this on his issue list, medium priority.

@szukowski could you live this this as a flexible zoom button seems to be way more difficult to be implemented?

**Comment by szukowski** [comment]
We can not just put the button up. In the mobile views, we get conflicts with the display of the search, e.g. goes across the entire width.

**Comment by MagdaN** [comment]
we can check if we are on desktop and move it to the topright corner then
