### ISSUE TITLE
upcoming start date for project

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2067]
is there a reason why we make upcoming projects look like this

![bildschirmfoto 2019-03-04 um 15 49 05](https://user-images.githubusercontent.com/35491681/53741377-86420180-3e96-11e9-84b4-a11dd0014735.png)

instead of this (according to design)?

<img width="568" alt="bildschirmfoto 2019-03-04 um 15 55 30" src="https://user-images.githubusercontent.com/35491681/53741460-be494480-3e96-11e9-85f8-db5092664d17.png">

sorry, I guess I missed this during testing.

**Comment by fuzzylogic2000** [comment]
This is a normal project with a phase? Then it shouldn't look like that. External projects without phases might look like that. And maybe containers? But the normal projects with phases shouldn't.

**Comment by fuzzylogic2000** [comment]
Ok, this needs to be fixed. It's also the normal projects on dev

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland check design with @szukowski as this should be the same as on storefront (see Zeplin, cross out "möglich")
