### ISSUE TITLE
store window: color of text in blue tile with mouse over

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2068]
mouseover in the blue tile in store window leads to pink words on blue background.

![bildschirmfoto 2019-03-04 um 16 20 04](https://user-images.githubusercontent.com/35491681/53743094-5bf24300-3e9a-11e9-8884-9e590d429544.png)

@szukowski is this still accessible? I know we don't have a design for this as it wasn't planned to make the blue tile clickable in the first place. However, seeing other people use this page I am glad we made it clickable.

**Comment by szukowski** [comment]
@CarolingerSeilchenspringer The counters do not have a mouseover because they are not a link. Pink on blue is also not barrier-free

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer @szukowski the blue tile is currently a link, it links to the active projects, should it no longer be a link?

**Comment by CarolingerSeilchenspringer** [comment]
I think it is important that the tile is clickable. Maybe we can leave it white and not make it turn pink?

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer @szukowski It's good (for a11y, meaning here for everyone to get it's a link) to make a link or a link-button change when hovered. The pink is our normal link-hover-behaviour, which doesn't make a lot of sense here. Nonetheless, I think we shouldn't just remove all hover-behaviour.

**Comment by CarolingerSeilchenspringer** [comment]
as discussed with @phillimorland and @szukowski we try to add a background image with arrow and make tile not clickable
