### ISSUE TITLE
#1825 number on filter tags 

### ISSUE THREAD

**Issue by phillimorland** [liqd/a4-meinberlin#2087]
When we add the number of results to the filter tags it will always show the same number on each tag as can be seen in screen shot, we can change the filter behavior to be an or filter but this doesn't really make sense in the context @CarolingerSeilchenspringer @szukowski what do you think? 
![Screenshot 2019-03-11 at 14 56 42](https://user-images.githubusercontent.com/5871230/54129470-9ade4680-440e-11e9-9323-811cf55a3221.png)

**Comment by CarolingerSeilchenspringer** [comment]
@szukowski I would leave this question to you. Or maybe we can have a quick talk-about-it next week?

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland as discussed, please leave out the numbers on the tags. And please change the wording to "x Suchergebnisse".
