### ISSUE TITLE
embedded projects: Does not show comments

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-meinberlin#2094]
![Issue-embedded projects](https://user-images.githubusercontent.com/30862422/54198403-b2790600-44c6-11e9-9622-f2a7ba401bb7.png)
Embedded projects do not show comments underneath topics in topic prio. The browsers are (so far ;) ) Opera and Firefox (61.0.1)

**Comment by CarolingerSeilchenspringer** [comment]
@MagdaN is this a knows issue? is there a way to fix it?
