### ISSUE TITLE
testing 1822 show responsible administration

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2101]
I tested story #1822 and here is what I've noticed:

* please add helptext to "Webseite der Organisation" (as we did last sprint for external projects): "Bitte geben Sie eine vollständige URL ein, die mit https:// or http:// beginnt."
* delete "Stelle und", it should only be Postadresse as the organisation is not mentioned again in this field and the Abteilung should be entered via Ansprechpartner
* @szukowski: do we have or need a design for the headline on mobile? it has the same size as the organisation name (this is also true for the contact person)

nothing bizzare on browserstack :-)

**Comment by CarolingerSeilchenspringer** [comment]
as discussed with @szukowski make the headline bold or bigger, whatever is easier.

**Comment by MagdaN** [comment]
@CarolingerSeilchenspringer could you please create a new issue for it as I already worked on the other stuff

**Comment by CarolingerSeilchenspringer** [comment]
sure!
