### ISSUE TITLE
links have to break

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2138]
![Image-2](https://user-images.githubusercontent.com/35491681/55156475-4e0ea580-515a-11e9-9d89-363c772a4dcc.jpg)

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer I am having trouble recreating this problem, Have tried on FF, Safari and Chrome and link always breaks, 
what browser/device were you using?

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland the project was depublished again so I faked it on dev. https://meinberlin-dev.liqd.net/projects/brainstorming/ have a look at the inforeiter using safari on iphone 7
