### ISSUE TITLE
When adding a plan to a project I can chose all plans from the organisation

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-meinberlin#2157]
@CarolingerSeilchenspringer: When creating an project I can add it to any plan that belongs to the organisation (not only the ones belonging to the group). Should that stay that way?

**Comment by CarolingerSeilchenspringer** [comment]
@MagdaN: yes, groups should be able to link their project to any plan that somebody else within the organisation (and outside the group) has created.
