### ISSUE TITLE
remove old projects list page (and tile template) and add redirect to new projekte-page

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#2165]

**Comment by fuzzylogic2000** [comment]
@rmader There is or was a PR for the first bit (#2230), but we need to set the redirect. Do you do that or do you show me how?

**Comment by rmader** [comment]
Yes we can do that together

**Comment by MagdaN** [comment]
can we do that in wagtail?

**Comment by MagdaN** [comment]
yes, we can: https://meinberlin-dev.liqd.net/projects

**Comment by phillimorland** [comment]
related: #2165

**Comment by rmader** [comment]
Will be done with the next release
