### ISSUE TITLE
Identity spoofing via secondary email

### ISSUE THREAD

**Issue by treba123** [liqd/a4-meinberlin#2168]
See https://github.com/pennersr/django-allauth/issues/2265

cc: @CarolingerSeilchenspringer @MagdaN @fuzzylogic2000

**Comment by treba123** [comment]
@CarolingerSeilchenspringer, @MagdaN: actually the content of the email address

```
diese E-Mail-Adresse soll dem Benutzerkonto "..." auf der Beteiligungsplattform meinBerlin-dev hinzugefügt werden
```

makes it quite clear that the original intention was to sent it to the newly added address. So probably this is simply a bug. Also see the reply to my issue above: https://github.com/pennersr/django-allauth/issues/2265#issuecomment-482440609

**Comment by CarolingerSeilchenspringer** [comment]
thanks, @treba123! If it is not a problem of django-allauth, can we find a solution then? We should fix this with the next release, so I set a milestone. Maybe you also want to check our other platforms?
