### ISSUE TITLE
Comments are not shown when not logged in

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-meinberlin#2201]
The comments are not shown when I am **not logged in** on meinBerlin productive:
See here for example: https://mein.berlin.de/text/paragraphs/1170/
Or here: https://mein.berlin.de/mapideas/2019-04342/

**Comment by fuzzylogic2000** [comment]
I found the commit that introduced the bug about two month ago: https://github.com/liqd/a4-meinberlin/commit/19ad98fa86d16738e5f51003a35255842b0d3999
But if I revert these (minor) changes in the current version, the bug is still there. :(
