### ISSUE TITLE
participation starting date wrongly displayed on tiles

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2228]
tiles show a different participation date than the actual one. Tile is one day ahead of date in dashboard:

![Bildschirmfoto 2019-05-17 um 15 21 13](https://user-images.githubusercontent.com/35491681/57930915-76dc2d00-78b7-11e9-900b-d2b060a1c3d0.png)

![Bildschirmfoto 2019-05-17 um 15 19 27](https://user-images.githubusercontent.com/35491681/57930847-48f6e880-78b7-11e9-8d5c-ea34505b01c8.png)

**Comment by rmader** [comment]
Fixed by https://github.com/liqd/a4-meinberlin/pull/2238
