### ISSUE TITLE
no notification after offizielle Rückmeldung?

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2240]
Did I test correctly that users do not get a notification in case there is an "offizielle Rückmeldung" with the moderation-tool? If so, is it broken or was it never planned? It seems unlogical to me.

**Comment by fuzzylogic2000** [comment]
Yes, you don't get a notification. I couldn't find a trace of sth. that could have made it work earlier. So. I guess it should become a story!

**Comment by CarolingerSeilchenspringer** [comment]
thanks, I just wrote a story to it.
