### ISSUE TITLE
test what Error bplan 549 triggered and catch

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#2249]
Error in Task [[549], {}], see: /django-admin/background_task/completedtask/45620/change/ 

Maybe the ö in the identifier?

**Comment by MagdaN** [comment]
yes it is the 'ö' : 'ascii' codec can't encode character '\xf6' in position 32: ordinal not in range(128)

**Comment by rmader** [comment]
Where was this one? on prod? Can't find it anymore :(

**Comment by fuzzylogic2000** [comment]
Yeah, I deleted the task and didn't copy the stack trace... Sorry!
