### ISSUE TITLE
sticky map broken

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-meinberlin#2303]

**Comment by rmader** [comment]
```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
6c0009d12886213cccf4a223bfd5cf5c65c5a1dc
7bd6efb96277c5b698361adf5f0e569a60e5e453
We cannot bisect more!
```

**Comment by MagdaN** [comment]
hmm any other ideas?

**Comment by rmader** [comment]
The problem is https://github.com/liqd/a4-meinberlin/blob/master/meinberlin/assets/scss/_base.scss#L7-L9

Removing that make the map sticky again. I'll create a PR. cc @phillimorland, as this could break stuff around the carousel

**Comment by rmader** [comment]
By the way, this one was probably easy to overlook in local testing as by default, if there are not enough projects, the sticky map isn't used

**Comment by phillimorland** [comment]
@rmader ahhh forgot about sticky map, it might create a scroll on some browsers but i only added it as a precaution
