### ISSUE TITLE
#2060 rounded corners for timeline 

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-meinberlin#2312]
On meinBerlin (and bet.in) all buttons and clickable elements apart from links have rounded corners. I think it would make it more consistent and clearer for users that they can click the timeline if the boxes had rounded corners
![IMG_33B232E75CE5-1](https://user-images.githubusercontent.com/15341015/60257464-ca3c9480-98d3-11e9-8c1c-94ff916fee11.jpeg)

**Comment by phillimorland** [comment]
@rittermo for consistency this is a valid pint, we do have square cornered list items and clickable tiles though and the timeline tiles are kind of half way between a tile and a btn, @szukowski what do you think?

**Comment by phillimorland** [comment]
@rittermo I have spoken to @szukowski, as these are not button then we thought on mB to keep them square, we have improved the focus and hover behavior though to make the tiles larger when in focus. But it would be simple to add rounded corners for ad+ if you think that it fits better?

**Comment by rittermo** [comment]
Thank you @phillimorland and @szukowski for looking into it. We can keep the square corners for a+ too, then.
