### ISSUE TITLE
Carousel not a11y compliant

### ISSUE THREAD

**Issue by phillimorland** [liqd/a4-meinberlin#2317]
cannot seem to tab onto event/project tiles, can only move carousel along. Also not outline of tab focus on arrows.

**Comment by phillimorland** [comment]
@szukowski what should the focus behavior, be for the timeline tiles as we need some indication if people are tabbing though, as they are links I have added the focus link colour for time being, is that acceptable?

**Comment by fuzzylogic2000** [comment]
This is closed, right?
