### ISSUE TITLE
testing timeline: jump to upcoming project

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2322]
timeline always jumps to first module/event, even if they are in the past and there are more upcoming.

If everything is in the past, we jump to the last module/event, right? We haven't defined that in the story.

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer i'm a little confused, are you saying the timeline focuses on modules that have ended? 
Current behavior should be that it focuses on running module, if its not doing that can you add a link?
 
And for everything being in the past, as modules are prioritised I assume it will focus on the last active module but i'm not sure, @MagdaN @fuzzylogic2000 any idea?

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland as just discussed, have a look at this project:  [https://meinberlin-dev.liqd.net/projects/ihre-vision-fur-berlin-welche-themen-sind-ihnen-wi/](url)

**Comment by phillimorland** [comment]
@MagdaN @fuzzylogic2000 so if there is a module beginning in the future for some reason the timeline goes back to the first entry, any idea on this?

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer checking the link again, it seems to be working as discussed?
