### ISSUE TITLE
module detail view 

### ISSUE THREAD

**Issue by phillimorland** [liqd/a4-meinberlin#2336]
As discussed in zeplin, this is how the module detail view looks when we don't change anything, other then adding details about the module to the top, I'm not sure on how the tiles look after the comments @CarolingerSeilchenspringer @szukowski what do you think?

![Spacial Brainstorm this is as long as it can get Spacial Brainstorm this is as long as it can get SpacialBrainstorm this — meinBerlin(1)](https://user-images.githubusercontent.com/5871230/60582748-b1c3f280-9d89-11e9-981a-d73b4704e27f.png)

**Comment by phillimorland** [comment]
NOTE: will increase width of comments so there is some consistency, should look better then now.

**Comment by szukowski** [comment]
@phillimorland the title of the other modules is missing in the module detail. the user does not know what that is in the end. even if then also the comments are displayed.

![grafik](https://user-images.githubusercontent.com/36926290/61205217-c42a1e80-a6ef-11e9-98bd-c82b894036a3.png)
