### ISSUE TITLE
Breadcrumb consistency

### ISSUE THREAD

**Issue by phillimorland** [liqd/a4-meinberlin#2339]
breadcrumb wording inconsistent across entire site, need to be reviewed 

@szukowski : this came to our attention because in the module detail design, the new back button looked out of place when clicking from views with breadcrumbs to go back. It makes breadcrumbs look even more inconsistent. Our answer for now is to use breadcrumb like we do on rest of site and create story for back button to be used everywhere.

**Comment by szukowski** [comment]
@phillimorland please let us work with the new button here. The so-called Breadcrumb is an old fragment, which we are lifting piece by piece and bringing it into a new structure. please let us work with the new button here. The so-called Breadcrumb is an old fragment, which we are lifting piece by piece and bringing it into a new structure. the style of the old variant fits is no longer consistent with the redesign. @CarolingerSeilchenspringer your decision

**Comment by CarolingerSeilchenspringer** [comment]
made a story out of it.
