### ISSUE TITLE
#2060 timeline still visible in Result tab

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-meinberlin#2344]
The timeline should not be visible in the Result tab.
https://meinberlin-dev.liqd.net/projects/ihre-vision-fur-berlin-welche-themen-sind-ihnen-wi/

Tested in Safari

![Bildschirmfoto 2019-07-04 um 17 01 31](https://user-images.githubusercontent.com/15341015/60675749-67bc3900-9e7d-11e9-815c-85e2fd3e83da.png)

**Comment by CarolingerSeilchenspringer** [comment]
if you click on "über das Projekt" first and then on "Ergebnis", content also stays the same (in this case "über das Projekt")

**Comment by CarolingerSeilchenspringer** [comment]
it still does not work for me :-(

**Comment by CarolingerSeilchenspringer** [comment]
please also note this little weirdo:

![Bildschirmfoto 2019-07-12 um 13 04 47](https://user-images.githubusercontent.com/35491681/61123886-cdc04600-a4a5-11e9-9589-079ae60dcec9.png)
