### ISSUE TITLE
#2061 headline or divider before tiles underneath content

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-meinberlin#2346]
I love that there are tiles now for other modules! So cool for users to be able to see the whole participation possibilities of one project! When the tiles follow underneath content like comments they are pretty unexpected and feel a bit distracting. I would propose we give them a headline („Weitere Beteiligungsmöglichkeiten“) and some whitespace.
https://meinberlin-dev.liqd.net/projects/module/text-kommentieren-8/

![Bildschirmfoto 2019-07-04 um 17 07 43](https://user-images.githubusercontent.com/15341015/60676349-f7161c00-9e7e-11e9-89aa-84bec1909fac.png)

**Comment by CarolingerSeilchenspringer** [comment]
according to design there should be the sentence:  "weitere Fragen aus dieser Online-Beteiligung". I struggle with the word "Beteiligungsmöglichkeiten" as it is very long though more correct than "Fragen". But as we also use the word "Fragen" on top and it is less complicated and therefore more understandable also for some of the "quiet voices" we want to reach, I think we should stick to it.

**Comment by CarolingerSeilchenspringer** [comment]
I have to reopen this again, as it should be implemented in the module view and not in the project view. Upsi :-)
