### ISSUE TITLE
deleting a featured project causes a 500 error on home

### ISSUE THREAD

**Issue by vellip** [liqd/a4-meinberlin#235]
^

**Comment by kleingeist** [comment]
as projects can only be deleted via django admin and not the dashboard this bug is not that relevant to "regular admins" of meinberlin. It should still be fixed but has not to be done in the Release 1.0 milestone

**Comment by xi** [comment]
I agree for deletion, but what about depublication? Is that affected?

**Comment by xi** [comment]
> I agree for deletion, but what about depublication? Is that affected?

I just saw that this is tracked in #422.
