### ISSUE TITLE
change helptext of module

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2351]
with the new design the helptext  for module Grundeinstellungen does no longer work. Please change to:

Der Modultitel erscheint auf der Modulkachel und auf der Modulseite, sobald das Projekt mehr als ein Modul oder eine Veranstaltung hat. Er darf maximal 512 Zeichen lang sein.

Die Kurzbeschreibung des Moduls erscheint auf der Modulseite, sobald das Projekt mehr als ein Modul oder eine Veranstaltung hat. Sie sollte in maximal 512 Zeichen das Ziel des Moduls beschreiben.

![Bildschirmfoto 2019-07-05 um 12 24 01](https://user-images.githubusercontent.com/35491681/60716508-e23d9500-9f1f-11e9-8a9b-ccb6fe223ab2.png)

**Comment by phillimorland** [comment]
change german in translation
