### ISSUE TITLE
upcoming modules don't have "nextination"

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2352]
if you are here: [click](https://meinberlin-dev.liqd.net/projects/module/umfrage-8/) and click on "next", the next module (which has not yet started) does not have the "previous" and "next" button

 ![Bildschirmfoto 2019-07-05 um 13 50 14](https://user-images.githubusercontent.com/35491681/60720914-83cae380-9f2c-11e9-9c52-b1125232f471.png)

**Comment by phillimorland** [comment]
Seems to only be issue for Ortspriorisierung

**Comment by phillimorland** [comment]
seems to be a problem with this project [#2381](url)

**Comment by MagdaN** [comment]
fixed with fixing Ortspriorisierung
