### ISSUE TITLE
change navigation for idea forms

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2353]
If I am in an idea form or idea detail view I should go back to module view and not to project.

for now add title of module, we will have to rethink the breadcrumbs in a later story (https://github.com/liqd/a4-meinberlin/issues/2339)

![Bildschirmfoto 2019-07-05 um 14 04 20](https://user-images.githubusercontent.com/35491681/60721321-d22cb200-9f2d-11e9-9e20-437350e1b3c2.png)

![Bildschirmfoto 2019-07-05 um 14 05 27](https://user-images.githubusercontent.com/35491681/60721363-fa1c1580-9f2d-11e9-876a-fd5ee43f1dec.png)

**Comment by phillimorland** [comment]
@magda looking into idea forms and detail pages knowing if they came from a multi module or single module

**Comment by MagdaN** [comment]
@phillimorland @CarolingerSeilchenspringer we could set the link to the page where the link was clicked. So if I click the cta button in a module page we would know that. Everything else is really complicated and I would rather fix it when we do the breadcrumbs

**Comment by phillimorland** [comment]
@MagdaN sounds perfect!

**Comment by MagdaN** [comment]
linked to #2339

**Comment by fuzzylogic2000** [comment]
Alright, as this does not belong to a story and is pretty complicated to do, we will leave the back-button linking to the projects for now. (It says it's going back to the project anyway. With the breadcrumb-story we will make the modules know, if they are part of a cluster and with that if they need to link back to the project or the module page. 
I will remove this from the milestone.

**Comment by CarolingerSeilchenspringer** [comment]
I made a breadcrumb-story in taiga. But since this WAS an acceptance criteria in the story ("navigate back to module view from both idea detail view and idea submit form, call it "go back"") and since I know it is important to administration and since I don't know if and when we will take care of the breadcrumbs, we need to find a solution here before release. @MagdaN let's talk about it when you are back. @phillimorland also found out that text commenting is not behaving as it should (if you go back from comments to a chapter in a multimodule via breadcrumb you are directed to a single project view with timeline).

**Comment by fuzzylogic2000** [comment]
The link is also in the update forms. Next to "back to idea". So these have "back to idea" and "go back" next to each other.
