### ISSUE TITLE
single module project without timeline is missing any discription

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2354]
my single module project [https://meinberlin-dev.liqd.net/projects/schillerkasse-ihre-kiezkasse-fur-den-schillerkiez/](url) which is module Kiezkasse should have a phase information. It is currently running.

![Bildschirmfoto 2019-07-05 um 14 17 04](https://user-images.githubusercontent.com/35491681/60721991-e1acfa80-9f2f-11e9-950f-cf28dd3e7645.png)

**Comment by CarolingerSeilchenspringer** [comment]
same is true for ideensammlung mit KArte [https://meinberlin-dev.liqd.net/projects/carolin-findet-ihrberlin-2/](url)

**Comment by MagdaN** [comment]
@CarolingerSeilchenspringer what exactly do you expect there? at the moment the active phase description is displayed

**Comment by CarolingerSeilchenspringer** [comment]
@MagdaN please leave it as it was before, this view should not change at all and still look like here: [https://mein.berlin.de/projects/stadtteilkasse-tiergarten-sud/](url) . 
Does this have to do with this issue as somehow the display of phase description was gone in multimodule? https://github.com/liqd/a4-meinberlin/issues/2350
