### ISSUE TITLE
contributions not counted

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2355]
in some module the contributions are not counted. 

For text commenting it should count the comments on paragraphs as well as the comments below the document.

For polls it guess we count the number the answers to (multiple) questions and the comments below the document? 

for topic/map prio it should only count comments and if possible not the topics/localisations.

![Bildschirmfoto 2019-07-05 um 14 38 45](https://user-images.githubusercontent.com/35491681/60722968-a2cc7400-9f32-11e9-854f-7c0a5ded2ba3.png)

**Comment by fuzzylogic2000** [comment]
> For polls it guess we count the number the answers to (multiple) questions and the comments below the document?

Ok!

> for topic/map prio it should only count comments and if possible not the topics/localisations.

Should we also count the votes then? Analogous to the poll?

**Comment by fuzzylogic2000** [comment]
counting the votes was moved to #2367
