### ISSUE TITLE
count comments on comments

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2356]
is it possible/complicated to count comments on comments? Do you consider it a good idea? This should be a new story, just wanted to ask!

Where: on module tiles, in text commenting on paragraph button, in idea list view, in idea detail view, in comments below polls and text commenting.

![Bildschirmfoto 2019-07-05 um 14 48 07](https://user-images.githubusercontent.com/35491681/60723449-f095ac00-9f33-11e9-99e6-9f1faa59215e.png)

**Comment by phillimorland** [comment]
@fuzzylogic2000 is this possible with the new comments?

**Comment by fuzzylogic2000** [comment]
It's possible, we just have to decide if we want that and go for an overall solution everywhere, I guess. Maybe we can even check for comments and answers and count both? That would be cool for the debating. But on the idea tiles and above the comments, it seems to make sense to count comments and answers and display that.
As the annotation with the comments is done in a4, we would need to find a solution that works for all projects there, though.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 thanks, I will close this and talk to @fredewe about it.
