### ISSUE TITLE
missing text and call to action in map prio

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2357]
I added a map prio to my multi module project [https://meinberlin-dev.liqd.net/projects/ihre-vision-fur-berlin-welche-themen-sind-ihnen-wi/](url) and there is only the map in the module view, no call to action or text.

[https://meinberlin-dev.liqd.net/projects/module/ortspriorisierung-4/](url)

**Comment by phillimorland** [comment]
Note: loads project header, not proper module view?!

**Comment by MagdaN** [comment]
@CarolingerSeilchenspringer I found the reason/bug why there is no text, but I guess there is no call to action because it is a topic prio and all users can do is to uprate or downrate topics?

**Comment by CarolingerSeilchenspringer** [comment]
@MagdaN you are right, I forgot about the call to action. Then I guess it is fine if the text is added so it looks again like e.g. this project: [https://mein.berlin.de/projects/diskutieren-sie-die-instrumente-der-leitlinien-bur/](url)
