### ISSUE TITLE
Word "Topic" is used to categoritze projects and in module Topicprio

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#2363]
I find it a bit confusing, that in the dashboard there are Topics in the projects and there is another tab to add the topics for the module topicprio.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 same is true for "Bezirk und ORT" and mapprio. How about we change wording in the project settings to "Themenfeld(er)" and "Projektverortung"?  The word "Themenfeld" is already used in the helptext so that makes sense. English would be "subject area" (or whatever we wrote into the helptext) and "project localisation".

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer As the project is in a4, we need to change it there and for the other plattforms this sounds a bit complicated and "hölzern"?! Yeah, but changing it in the Topicprio and Mapprio also is not really better. :(

**Comment by CarolingerSeilchenspringer** [comment]
@CarolingerSeilchenspringer finds another concept as project info is in a4 and module can be change on each platform (note: rather use project location, not project localisation)

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer This has prio medium, which means that it should be fixed and released with the next release. Is this the goal? Otherwise, please change the label.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 thanks, I set it on low prio.

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer Are we still thinking about this? Otherwise if it's fine, we could just close.

**Comment by CarolingerSeilchenspringer** [comment]
if A4 this is rather a story so i will close the issue and move it to taiga. PMs already discussed having an A4-talk soon. https://taiga.liqd.net/project/liqd-meinberlin/us/347?no-milestone=1
