### ISSUE TITLE
count the votes for module tile

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#2367]
@CarolingerSeilchenspringer 
So, if we have time to do it: what exactly are we counting? Everything (votes on polls, ideas, proposals, topics and all comments (not comments on comments)?

**Comment by CarolingerSeilchenspringer** [comment]
If we count the votes we have to do so in all modules with voting (idea collection, agenda setting, topic/map prio, Bürgerhaushalt, Kiezkasse). Then I like your idea of saying: x Beiträge (counting ideas and comments), x Bewertungen (counting votes). Then maybe @szukowski could find a little icon for it? But we will save this for later, so not needed to close the timeline-story.

**Comment by phillimorland** [comment]
this is for nice to have so will close for now
