### ISSUE TITLE
project map/list view not visible in IE 11

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2375]
there is no project view in IE 11, I can only see header/footer.

**Comment by fuzzylogic2000** [comment]
Was fixed by https://github.com/liqd/a4-meinberlin/pull/2376
So, @rmader could you make a new PR and make it work with IE? If that's possible.

**Comment by rmader** [comment]
Hm I tested it before/after merging and it worked well on browser stack. Must somehow collide with something that was merged later. Will create a new PR.

**Comment by fuzzylogic2000** [comment]
fixed by #2411 Yeah!
