### ISSUE TITLE
IE: project title not centered in header/ project picture

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2377]
on windows 10, IE 11 
e.g. [here](https://meinberlin-dev.liqd.net/projects/ihre-vision-fur-berlin-welche-themen-sind-ihnen-wi/)

![Bildschirmfoto 2019-07-12 um 12 03 27](https://user-images.githubusercontent.com/35491681/61120387-32c36e00-a49d-11e9-97e0-c1cbb4563002.png)

**Comment by phillimorland** [comment]
The fix I implemented made projects with no picture on other browsers look broken, it is a problem that IE doesn't center without height setting but that makes content squashed

**Comment by fuzzylogic2000** [comment]
I will remove it from the milestone. It's not a new issue and is not critical nor belonging to the stories. I would even advocate just leaving it like that and waiting for IE to go away!

**Comment by CarolingerSeilchenspringer** [comment]
Ok, thanks for checking. If there is no easy solution we will wait for IE to be no longer in use as @fuzzylogic2000 suggested. It does look very wired, but I guess IE-users are used to things looking wired. :-)
