### ISSUE TITLE
headline for timeline missing

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2379]
one of the acceptance criteria of story #2060 in taiga is: add header to timeline ("Projektverlauf"). @szukowski as this is no longer in the design but was in there before, did you kick it out on purpose? To me it seems that it would be better to have it and let the project page for multimodule speak a bit more to the user. Especially on mobile you don't know right away what the timeline is about.

**Comment by szukowski** [comment]
@CarolingerSeilchenspringer @phillimorland yes, actually I had kicked the headline, as the timeline should explain itself. We have the title in the tabs, then the timeline title, then the headlines in the timeline items ... a little bit of title. but if you find it clearer with tiel do that

**Comment by phillimorland** [comment]
@szukowski so not sure exactly where you want it, do you still have a sketch from before you removed it from designs that you could send me?

**Comment by szukowski** [comment]
@phillimorland 
![grafik](https://user-images.githubusercontent.com/36926290/61212375-63f0a800-a702-11e9-9007-9224f7bc5913.png)

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer I added it and it looks a bit odd and I think @szukowski, the timeline does seem self explanatory, what do you think?
![Brainstorm Leitlinien zur Bürgerbeteiligung im Bezirk Treptow Köpenick von Berlin — meinBerlin](https://user-images.githubusercontent.com/5871230/61275724-d6b75d00-a7ae-11e9-96bc-73a10e329b38.png)

**Comment by fuzzylogic2000** [comment]
I also like it much more without the timeline title and find the timeline self-explanatory enough. I propose we kick it out again and close this issue!
