### ISSUE TITLE
picture in event not correctly displayed

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2380]
If I add a picture to an event it looks a little squeezed. It's not the same on stage so I guess it has to do with the timeline changes?

have a look [here](https://meinberlin-dev.liqd.net/projects/ihre-vision-fur-berlin-welche-themen-sind-ihnen-wi/?initialSlide=3)

![Bildschirmfoto 2019-07-12 um 12 33 34](https://user-images.githubusercontent.com/35491681/61122155-5688b300-a4a1-11e9-925d-797e33425ad0.png)

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer this is an editor issue, ensure aspect ratio is unlocked and there is no minimum height

**Comment by CarolingerSeilchenspringer** [comment]
ok, thanks @phillimorland . I am pretty sure I had the same settings (not changing anything), but at least I know now how to change it.
