### ISSUE TITLE
#2060 no titel - Projekt overview

### ISSUE THREAD

**Issue by szukowski** [liqd/a4-meinberlin#2387]
the titel "more questions from this online participation" is not displayed on the project overview. But he will be shown on the detail page of the participation modul

overview:
![grafik](https://user-images.githubusercontent.com/36926290/61208646-2edf5800-a6f8-11e9-9387-957a453f6e88.png)

detail:
![grafik](https://user-images.githubusercontent.com/36926290/61209639-9696a280-a6fa-11e9-8aec-0639dfa15f45.png)

should
<img width="958" alt="grafik" src="https://user-images.githubusercontent.com/36926290/61209584-71a22f80-a6fa-11e9-8719-5952c49283a2.png">

**Comment by phillimorland** [comment]
duplicate issue
