### ISSUE TITLE
grey backround in container

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-meinberlin#2410]
![Bildschirmfoto 2019-07-17 um 09 56 53](https://user-images.githubusercontent.com/2905743/61357859-61648e80-a879-11e9-8a14-124004c7c9ed.png)

**Comment by fuzzylogic2000** [comment]
@phillimorland I think, I know, where I didn't notice that you broke it. :) I think it was with the getting the button always the same width. So I will assign you?
