### ISSUE TITLE
no next-previous navigation for future modules 

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2434]
there should be a next-previous navigation as there are more modules but this one is in the future.

<img width="904" alt="Bildschirmfoto 2019-07-30 um 13 53 03" src="https://user-images.githubusercontent.com/35491681/62127132-9ccb7800-b2d1-11e9-81f8-0f3bcce1ab22.png">

**Comment by fuzzylogic2000** [comment]
Well, somehow the future modules do not know, that they are in an cluster, they have 0 other modules. 
(it asks {% if other_modules|length > 1  %} and other_modules|length is 0 in the future modules.)
