### ISSUE TITLE
Wording for future projects

### ISSUE THREAD

**Issue by phillimorland** [liqd/a4-meinberlin#2437]
Update wording of info message for future projects - make it more inviting and not duplicate of timeline wording

**Comment by fuzzylogic2000** [comment]
Do you mean in the module tile?

**Comment by phillimorland** [comment]
in the info sentance, informing users about project starting in the future, it was something that came up during review. @CarolingerSeilchenspringer had an idea of what wording could be

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer did we want to update the wording before release?

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland puh, I don't remember what exactly I wrote. But what about: Sie möchten sich beteiligen? Kommen Sie am [date without time] wieder oder folgen Sie dem Projekt um eine Erinnerung zu erhalten. (you want to participate? Come back on the ... or follow the project to get a reminder.) But we can only do this after finishing story 2252!

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer Is this still there and important? Then we'd quickly fix it for the next release. Otherwise please close.

**Comment by CarolingerSeilchenspringer** [comment]
I think it is important but I also think it should be a story. So I will close.
