### ISSUE TITLE
Prevent removal of phase dates from published projects

### ISSUE THREAD

**Issue by kleingeist** [liqd/a4-meinberlin#244]
This is a counterpart to #226 
If a project is already published it should not be possible to remove dates from its phases. 
Maybe users should also be prevented from modifying dates?

**Comment by Janaba** [comment]
We need to give initiators the freedom to modifye dates lateron as sometimes they change while a longer process has already started.

**Comment by kleingeist** [comment]
closed with the introduction of the datepicker in #241
it is no longer possible to remove dates or leave them empty, but the dates can still be changed.
