### ISSUE TITLE
sender of newsletter

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2465]
if I put my address in the "Absender" field in newsletter (standard: support@mein.berlin.de) the mail still has the sender "no-reply@mein.berlin.de". However the address I put it is show behind: Antwort an. Is that what it should be? It is not what I would expect as an initiator.

**Comment by fuzzylogic2000** [comment]
Hmm, we can't change how it behaves, because we can't send it from the initiator's address.
But we can change the wording?!

**Comment by CarolingerSeilchenspringer** [comment]
moved it to taiga.
