### ISSUE TITLE
The project is not referred on idea detail page

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-meinberlin#247]
If you are on an idea detail page, the project the idea is linked to is not referenced. It would be important to show at least the project’s title to make the connection between project and idea clear to the user.

<img width="1191" alt="bildschirmfoto 2017-04-24 um 15 42 05" src="https://cloud.githubusercontent.com/assets/15341015/25340072/e30d058a-2904-11e7-9fb4-58540a4fc40e.png">

**Comment by damusp** [comment]
That's an interesting idea. I suggest we think a bit on this one because it might be useful also to opin. 

This is what came to my mind immediately: 
![breadcrumb](https://cloud.githubusercontent.com/assets/22769111/25384870/2ce41672-29c2-11e7-8e5c-f0d0d025e14c.png)

**Comment by rittermo** [comment]
I never realized we had the same problem in OPIN when viewing ideas. Thanks for pointing that out, @damusp ! I like your idea, however it might be good to make that information even bigger and more prominent, similarly to what we do in OPIN currently when you add new ideas (see screenshot). 

![bildschirmfoto 2017-04-25 um 15 00 26](https://cloud.githubusercontent.com/assets/15341015/25386555/0aeb7f5a-29c8-11e7-8ba5-a4c8f72d3f0a.png)

**Comment by damusp** [comment]
I disagree on this one. In my opinion, here it should be easy for the user to focus on the proposed idea, which is contains a wide range of different informations. They should be most prominent. 

The name of the project should be definetely there, but in my opinion it can go a bit into the background. 

![breadcrumb](https://cloud.githubusercontent.com/assets/22769111/25859466/eaf73e4c-34de-11e7-8396-c668cf27dea2.png)

**Comment by phillimorland** [comment]
this issue seems to have been resolved by adding project as a link as suggested
