### ISSUE TITLE
Servicekonto todo

### ISSUE THREAD

**Issue by rmader** [liqd/a4-meinberlin#2498]
- we need a unique id from the API. Currently all we get is an email
- we can't directly redirect to the ServiceKonto mB page, as there's no automatic login. So we do have to force a relogin every time, even if the user is still logged in
- if the user gave consent once, relogin should be possible directly
- we should have a "remember me" checkbox for this login, too

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 is this something that will/should be a story eventually? Is this a good place as reminder?

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer Yes, I think for things, we will need once we get back into doing that and that are not a feature request, we could also simply not do and not loose a lot, an issue is an okish enough place to remind us of it. :)

**Comment by goapunk** [comment]
closing as we removed the servicekonto app
