### ISSUE TITLE
Project timeline looks broken on small screen

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-meinberlin#250]
On very narrow screens (tested on 320px width), the project timline breaks into multiple lines and looks broken. More vertical spacing and some styling changes should help.

<img width="272" alt="bildschirmfoto 2017-04-24 um 16 00 40" src="https://cloud.githubusercontent.com/assets/15341015/25340909/745057fc-2907-11e7-81e3-68d1873e8f82.png">

**Comment by damusp** [comment]
@tobi I'd like to suggest a solution for this, but maybe there are simpler ways to get the timeline fit for mobile devices. What do you think?


![mobile_timeline](https://cloud.githubusercontent.com/assets/22769111/25380811/dc64f67c-29b1-11e7-9ca5-0a66cdb93582.png)

**Comment by xi** [comment]
@damusp this layout looks very hard to do for me. Let's stick to centering but fix the vertical spacing.

**Comment by damusp** [comment]
@xi I see. Can we do anything about the horizontal lines? 
Maybe we can get them centered as well, something like this:

![mobile_timeline2](https://cloud.githubusercontent.com/assets/22769111/25423939/c1c83b02-2a66-11e7-8e8c-a14ec5d7ea1b.png)

or alternatively we might just don't display the lines on mobile at all.

**Comment by xi** [comment]
> Can we do anything about the horizontal lines?

Not really. But I think the lines are actually helpful to understand that this is an ongoing timeline, not three distinct ones.

**Comment by damusp** [comment]
i agree. so ideally it would more like this:

![mobile_timeline3](https://cloud.githubusercontent.com/assets/22769111/25426840/ca62bcd8-2a70-11e7-8893-ff14ccd1d803.png)

**Comment by damusp** [comment]
But it would it already look decent if we just add a little vertical spacing. This would be totally fine, at least for now.
