### ISSUE TITLE
testing #2249 notification

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2502]
nice improvement for that functionality! 
I have some minor changes and 1 question.

dropdown: change "rückmeldung" to "beantworten" (I just checked duden again an "rückmelden" is not in it while "Rückmeldung" doesn't match the logic of the other words in the dropdown).

form: change header "Idee moderieren" to "Rückmeldung zu dieser Idee".

mail: 
- change "Status:" to "Ihr Beitrag [status].". Just came to me that we can make a nice sentence out of it. :-)
- the ":" behind the first sentence looks wired. Replace it by a dot =  "...reagiert."

question: 
The mail styling isn't that cool yet, eg. distances and quotation marks for the official feedback. Also the footer hasn't changed. Will that change with the mailing-story?

**Comment by fuzzylogic2000** [comment]
Alright!
Are you sure, you want the wording in the dropdown changed again? "beantworten" doesn't say that it's for moderation and might be hard to find? You are right about the "Rückmeldung not fitting in with the other words. I like "rückmelden" more, even though it's not in the duden.
And yes, it is easier to change it together with all emails. Also it would be a bit strange if we had only one email with another footer. I think it was in the story, so it changes with that story.

**Comment by fuzzylogic2000** [comment]
Right, I will put in the quotation marks though!
