### ISSUE TITLE
Proposal forms are missing the currency symbol 

### ISSUE THREAD

**Issue by kleingeist** [liqd/a4-meinberlin#251]
the input field for the budget is missing a currency symbol when a new proposal is entered or updated

![screenshot from 2017-05-02 13-54-40](https://cloud.githubusercontent.com/assets/167407/25616787/05d64a14-2f3f-11e7-9e88-a7e2851c455a.png)

**Comment by xi** [comment]
Can you please explain a bit more, maybe with a screenshot?
