### ISSUE TITLE
wrong helptext for modules

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2540]
URL: https://meinberlin-dev.liqd.net/dashboard/modules/brainstorming-19/module_basic/

user: initiator/moderator/groupmember

expected behaviour: correct helptext
Bei parallel laufenden Modulen erscheint der Modultitel auf der Modulkachel, der Modulseite und im Ideenformular. Er darf maximal 512 Zeichen lang sein.
AND
Bei parallel laufenden Modulen erscheint die Kurzbeschreibung des Moduls auf der Modulseite und im Ideenformular. Sie sollte in maximal 512 Zeichen das Ziel des Moduls beschreiben.

behaviour: incorrect helptext

device & browser: all

Importance: relevant for release

**Comment by fuzzylogic2000** [comment]
Ok, so this is the text that should be there? Could you also add the English version, please?

**Comment by CarolingerSeilchenspringer** [comment]
yes. English would be "For parallel running modules the titel is shown on the module tile, the module page and the idea form. ...[rest stays the same]." and "For parallel running modules the description is shown on the module page and the idea form. ...[rest stays the same]."

**Comment by CarolingerSeilchenspringer** [comment]
I have to close this issue again. Before we change the text we should think about showing module title and description for all modules with timeline again as it was before.
