### ISSUE TITLE
project header on IE

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2544]
URL: every project page
user: all
expected behaviour: title, description and follow button are central within picture
behaviour: title, description and follow button are at the top end of picture
device & browser: Windows 10, IE 11
Importance: change if easy

<img width="550" alt="Bildschirmfoto 2019-09-23 um 14 04 03" src="https://user-images.githubusercontent.com/35491681/65424642-5182a100-de0c-11e9-8f8a-2c0f07526b04.png">

**Comment by fuzzylogic2000** [comment]
Didn't we try to fix that before and failed? Somehow it rings a bell. @phillimorland or @CarolingerSeilchenspringer can you remember?

**Comment by fuzzylogic2000** [comment]
* or didn't fail, but decided not to pour too much time in.

**Comment by CarolingerSeilchenspringer** [comment]
yeah, I check old issues again, it wasn't an easy fix so I will close it. Too bad...
