### ISSUE TITLE
testing #2251 follow button: show follow button if not signed in

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2545]
for consistancy reasons and to make follow more public/inviting: I think we should show the button even if user is not signed in. Clicking on it will lead you to sign-in-form. We have the same behavior for submitting ideas and voting. What do you think?

**Comment by fuzzylogic2000** [comment]
Yes, I think it's a good idea! But as it's something that would have been good to know before we finish the story, I would prioritize it at the end of the other issues.

**Comment by fuzzylogic2000** [comment]
This needs a few changes in a4 and wasn't talked about in the other projects. It should go into a story!
