### ISSUE TITLE
testing #2252 follow mailing: change wording and link in mail event invitation

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2546]
URL: mail for event invitation

changes:
* change mail Betreff to „Einladung zu einer Veranstaltung im Projekt…" (...startet jetzt! is not correct)
* Change header to „Veranstaltung" (spelling mistake)
* Add „Uhr“ behind time
* Button "Veranstaltung anzeigen" has to go to project directly
* does it look better to add a paragraph before and after event title? It might give some more "air" to the mail.

**Comment by fuzzylogic2000** [comment]
Alright! Will do! But the link should go to the project currently. Doesn't it?

**Comment by CarolingerSeilchenspringer** [comment]
right now the link of the button goes to landing page. What do you mean with project tile open? If possible it should go directly to the event information. If not, it should go to the standard view you have if you open the project.
