### ISSUE TITLE
testing #2252 follow mail: change mail project/modul starts

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2547]
where: Mail "modul/project starts"

* Change mail betreff to: "Los geht’s: [project] startet jetzt!"
* Button „Join now“ needs translation „Jetzt mitmachen" (wouldn’t the English rather be „participate now“?)
* Add paragraph between the two sentences to give some „air“ to the mail
* Can we send the mail only once if two or more modules start at one time?

**Comment by fuzzylogic2000** [comment]
To your last question: no, unluckily not. But the emails should link to the modules, so the links are different in every email.

**Comment by CarolingerSeilchenspringer** [comment]
hm, the mails all look the same, though. And if we add the module title into the mail? e.g. 
"...hat begonnen: 
[modul title]
Sie können..."
Then we have a problem with single module projects, right?

**Comment by fuzzylogic2000** [comment]
Oh, and the link is not yet different. I will change that!
Is it bad, when we have the extra module title in single module projects?

**Comment by CarolingerSeilchenspringer** [comment]
in single module project the module title is not shown so people don't fill it is. As standard the template is written so that would look wired in the mail.
