### ISSUE TITLE
testing #2251 follow button: large font size

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2551]
where: project page
user: everyone signed in
expected behaviour: follow-alert font size is same as/ smaller than other wording
behaviour: follow-altert (and other texts, e.g. phase description) is very large if phone is held horizontally
device & browser: iphone 7, safari, horizontal
Importance: relevant for release

**Comment by fuzzylogic2000** [comment]
This is pretty strange. The alert-thng didn't have a font-size, which we can fix. 
But the phase description has 1rem (normally equalling 16px) everywhere. It must be some strange setting for this device if you can't reproduce it elsewhere.
