### ISSUE TITLE
testing #2252 follow mails: react mail

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2553]
where: mail reaction to my content

* Betreff: Reaktion auf Ihren Beitrag im Projekt [project title]
* add "..." to the comment and make it italic to make clear that this is a quote
* I think we should cut the comment, the mail gets very long otherwise. I wrote 200 before but maybe 500 is better.

**Comment by fuzzylogic2000** [comment]
There is also a way to cut off after a certain number of words, which might be the better choice here?! We decided to go for 75 words.
