### ISSUE TITLE
don't show user profile pages

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2575]
URL: https://mein.berlin.de/profile/caroka/
user: participants
expected behaviour: click on any username should either show valuable input or not be possible. 
behaviour: click on username shows a page with the username.
important screensize: -
device & browser: all
Comment/Question: Since we don't have user profiles on meinberlin, these pages should not be visible. A) Is that possible? B) should I make a story out of it?

**Comment by CarolingerSeilchenspringer** [comment]
nevermind, we already had this in issue  #1885 and you said it's A4 and not possible. So I will close this again.

**Comment by rmader** [comment]
This could be done as part of moving to the new comment system. If we move them to A4, we could simply make it optionally via settings.

For @CarolingerSeilchenspringer, the advantages include:
 - linkable comments
 - links to comments in notifications / for moderators
 - comments get loaded on demand, dramatically improves page loading on sites with many comments

**Comment by CarolingerSeilchenspringer** [comment]
moved into taiga.
