### ISSUE TITLE
preview in text commenting does not work

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2595]
URL: https://meinberlin-dev.liqd.net/dashboard/projects/textkommentierung/basic/
user: initiator
expected behaviour: should be able to see preview
behaviour: get 405 error
Comment/Question: I checked brainstorming and it works. After I enter content for the document it also works, so I guess it has to do with the module text commenting. We also have the problem on prod, so I guess we need a hot fix.

**Comment by fuzzylogic2000** [comment]
So, it works, when there is a document, but not if there's none?

**Comment by MagdaN** [comment]
hmm, did this ever work? What would you expect to see there? The project header with nothing underneath?

**Comment by CarolingerSeilchenspringer** [comment]
@MagdaN: for brainstorming and ideacollection with or without map and topicprio it does show the header and/or phase description and some grey area for the map. 

<img width="704" alt="Bildschirmfoto 2019-10-28 um 09 24 53" src="https://user-images.githubusercontent.com/35491681/67663067-f7be4b00-f964-11e9-90c7-d19c4d1d6543.png">

for poll there is also a 405 but with more info.
<img width="602" alt="Bildschirmfoto 2019-10-28 um 09 23 06" src="https://user-images.githubusercontent.com/35491681/67663108-0c024800-f965-11e9-969f-4d5b17399c44.png">

the first is nicer, the second is ok. Good point that it might be related to dashboard. Maybe you want to put this issue as a task within the story so we don't forget?

**Comment by MagdaN** [comment]
@CarolingerSeilchenspringer I added a task
