### ISSUE TITLE
make sure project created success message only when project create successful

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#2607]
like https://github.com/liqd/adhocracy4/issues/413
here: https://github.com/liqd/a4-meinberlin/blob/c9b1dd308b7d8a5703400f0b2e22a8b2dade3da6/meinberlin/apps/dashboard/views.py#L204

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 this is also related to dashboard so I set a milestone, correct?

**Comment by fuzzylogic2000** [comment]
This actually needs to go in there. It's a bit weird, but the model is actually saved in this method!
https://github.com/django/django/blob/d36413a2eb5678dda35559a48769703acd784898/django/views/generic/edit.py#L123
