### ISSUE TITLE
dashboard project list: pagination doesn't know if list filtered for group members

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#2616]
![Screenshot from 2019-10-31 12-07-24](https://user-images.githubusercontent.com/8178179/67941963-06ac3400-fbd7-11e9-8491-217e84eb9a77.png)

**Comment by phillimorland** [comment]
@fuzzylogic2000 @CarolingerSeilchenspringer I miss read this and thought it was just the didn't take into account filtering. When you say for group members you mean for mods and initiators right? when I was testing it seems when I am in moderator group I can see all the projects anyway, what should I not see as a member of moderator group?

**Comment by fuzzylogic2000** [comment]
@phillimorland It's not the initiators or moderators, but the group. You can edit a project if you are in a group and the group is assigned to the project or organisation. That's only doable in the django-admin, though.
But then, when you are assigned the filtering happens after the pagination. :woman_shrugging:

**Comment by fuzzylogic2000** [comment]
This is turning out to be a bit more complicated. It's from a4: https://github.com/liqd/adhocracy4/blob/master/adhocracy4/dashboard/views.py
The filtering for viewable projects in a+ is done like this: https://github.com/liqd/adhocracy-plus/blob/master/apps/projects/query.py
Maybe we can do it like that, but in a4.

**Comment by fuzzylogic2000** [comment]
@rmader As you're currently in fixing mood as well, maybe you can have a look?

**Comment by rmader** [comment]
Jup, fixing mood!!

**Comment by rmader** [comment]
Hm, looks like `django-rules` and `django-filter` do not play well together by default :(
See https://github.com/dfunckt/django-rules/issues/116, https://github.com/dfunckt/django-rules/issues/40 and https://bridgekeeper.readthedocs.io/en/latest/tutorial/views.html#filtering-querysets

This looks like a bigger thing to investigate though :/

**Comment by rmader** [comment]
As an alternative approach we could list all projects but make them inactive - what do you think?

**Comment by rmader** [comment]
FTR., this is something to keep in mind when we think again about permission refactoring. IMO this is a pretty big drawback of `django-rules`.

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer The same problem is there for bplans, linkages and containers by the way...
If this issue will be fixed, it's worth some testing on dev! :)

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 good to know, I will have a closer look.
