### ISSUE TITLE
dashboard navigation not fully responsive

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2620]
URL: https://meinberlin-dev.liqd.net/dashboard/organisations/caros-testorga/projects/
behavior: tabs are in two lines
expected behavior: tabs are in one line
device: iphone 6/7/8
comment: since this is the dashboard we can ignore smartphones smaller than that. As far as I see it, it would be possible to have the tabs in one line.

**Comment by phillimorland** [comment]
linked #2401
