### ISSUE TITLE
button "new project" should be left aligned on smartphone

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2621]
url: https://meinberlin-dev.liqd.net/dashboard/organisations/caros-testorga/projects/
behavior: button "new project" stays right aligned even if not in same line with title
expected behavior: button "new project" is left aligned
device: iphone 6/7/8
comment: since this is the dashboard we can ignore smartphones smaller than that.

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer can you link to liqd org or just add an image? I can't see anything on your org :)

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland sorry! Take this link: 
[project overview dashboard](https://meinberlin-dev.liqd.net/dashboard/organisations/liqd/projects/)

actually this is true for all overviews of projects and containers in dashboard. And now I just saw this is also for the changes in the current dashboard story since we now have overviews of Bebauungspläne as well. Verlinkungen work (since wording is shorter) and for the plans it has been programmed to be left aligned. We should be consistent here. 

![Bildschirmfoto 2019-11-25 um 12 00 32](https://user-images.githubusercontent.com/35491681/69535008-37d01800-0f7b-11ea-8d4e-fb6635b8bc4f.png)
