### ISSUE TITLE
 Unnecessary to put in time of event - not displayed in user view

### ISSUE THREAD

**Issue by Amelie-liqd** [liqd/a4-meinberlin#2657]
user: moderator / initiator
expected behavior: since initiator is asked to insert time of offline event, the time will also be shown to regular users in the timeline
behavior: initiator can set a time but that in the timeline view of the project, only the day is shown.
screensize: any
device & browser: macbook air, firefox

**Comment by CarolingerSeilchenspringer** [comment]
see issue 109 in adhocracy.plus

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland put info of date and time on detail page of event

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland is it possible to write time and date like this: 30. März 2020, 8:57 Uhr (instead of 13. Juni 2019 00:00)?
