### ISSUE TITLE
testing 2394: create project: change button wording

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2670]
**URL:** https://meinberlin-dev.liqd.net/dashboard/organisations/liqd/projects/create
**user:** initiator/group member
**expected behaviour:** wording of buttons creating projects, plans, containers and external projects should all be the same, that is "Speichern"
**behaviour:** button is "Projektentwurf anlegen" or "Senden"
**important screensize:**
**device & browser:** 
**Comment/Question:**

**Comment by MagdaN** [comment]
@CarolingerSeilchenspringer which one do you prefer?

**Comment by CarolingerSeilchenspringer** [comment]
@MagdaN I checked the design again and we have "Projekt anlegen" in header and "Speichern" and "Abbrechen" for the buttons. And as there will be the new status guide on the right side we won't need these longe instructions above the buttons because the status guide will tell me what is coming next. Would you delete this ? (that was my first intention of this issue as you can tell from the unmatching title ;-).
