### ISSUE TITLE
testing 2394: missing translation in modal to choose module

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2672]
**URL:** https://meinberlin-dev.liqd.net/dashboard/projects/testing-dashbaord/basic/ + modal "new module"
**user:** all
**expected behaviour:** German title
**behaviour:** english title
**important screensize:**
**device & browser:** 
**Comment/Question:** missing translation. translate as "Beteiligungsmodul wählen"

<img width="537" alt="Bildschirmfoto 2019-11-27 um 13 02 52" src="https://user-images.githubusercontent.com/35491681/69721993-574f7800-1116-11ea-9fe2-f51358a37972.png">

**Comment by fuzzylogic2000** [comment]
Should be fixed with the merged PR.
