### ISSUE TITLE
testing 2394: Navigation minimization part 1

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2673]
**URL:** https://meinberlin-dev.liqd.net/dashboard/projects/testing-dashbaord/basic/
**user:** initiator
**expected behaviour:** If I add a module I can still see in the navigation which form is actually shown.
**behaviour:** as navigation is not minimized automatically the navigation and form are far apart.
**important screensize:**
**device & browser:** 
**Comment/Question:** I suggest we always close all navigation elements once user creates a new module. I would also close a module after adding it to the project since user is finished then. Also by automatically closing them, user gets aware of the possibility of closing/opening. Maybe we can have a quick usertesting?

**Comment by MagdaN** [comment]
The thing is, that we implemented that the browser remembers which form navigation is open an which one is closed when the page changes or is refreshed. Would it not feel weird if this would not work anymore on some pages?

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer I think closing the navigation when you add a module makes sense. 
Closing all navigation on page change might be more problematic because the user hasn't interacted with the navigation directly so might be confused? 
@MagdaN is there a quick way to set up the closing on page change to we can do a proper testing?

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland @MagdaN Can't we automatically close navigation whenever it makes sense and still save this setting when leaving the page? Testing would be great!

**Comment by fuzzylogic2000** [comment]
I think this would be confusing and propose we leave it like it is! It's not the biggest prio, to me it seems fine like it is now and we don't know how many people will use it and so on.

**Comment by phillimorland** [comment]
Closing this issue as we have defined some other solutions in following issues:
#2721
#2723
#2722
#2720
