### ISSUE TITLE
testing 2394: preview of multimodule

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2674]
**URL:** https://meinberlin-dev.liqd.net/projects/testing-dashbaord/
**user:** initiator
**expected behaviour:** See the preview of my current settings.
**behaviour:** preview says: Die Beteiligung ist aktuell nicht möglich. Sie startet am None.
**important screensize:**
**device & browser:** 
**Comment/Question:** This behaviour is valid even if both modules are completely filled out, as long as they are not added to the project. Single module projects however have a more informative preview even if module has not been added to project and is incomplete. I guess we need the phase info for a correct preview of multimodules? Can we show correct preview once multimodules are complete but not added to project?

**Comment by MagdaN** [comment]
@CarolingerSeilchenspringer I don't quite understand what you mean.

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer looking at the preview of single module projects, I actually don't think we should give that much detail, it doesn't make sense when no module has been added, we should think of removing it. We could have a notification box or something that says, 'To preview module, please add to project' to help with confusion.
what do you think?

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland what if I have a published project and add a new module for a new participation phase? Then I can't see how the changes will effect my running project.

**Comment by fuzzylogic2000** [comment]
Well, as the preview and the normal view are the same and the difference is just done with the rules, I can't think of way to do this. Currently we just show modules that are added to the project everywhere and I think it should stay like that.
Also, if we wanted to have it differently, we should have thought of this a bit earlier.

**Comment by CarolingerSeilchenspringer** [comment]
as discussed with @fuzzylogic2000 we will have the rule: Preview is what my project would look like if I would publish now (or have already published = change to "Ansicht"). So to be consistent we need to change the view for projects with only one module that has NOT beed added to the project: We then only show the project header. Making a preview for published projects with new (not added) modules would be another story.
