### ISSUE TITLE
testing 2394: deleting published/running modules should not be easily possible

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2675]
**URL:** https://meinberlin-dev.liqd.net/dashboard/projects/testing-dashbaord/basic/
**user:** initiator
**expected behaviour:** cannot delete a published/running module easily 
**behaviour:** Initiator can delete a module from a published project without getting a notification. 
**important screensize:**
**device & browser:** 
**Comment/Question:** I suggest only to allow deleting a module not attached to the project.

**Comment by fuzzylogic2000** [comment]
connected to #2679 . Lacking a concept. 
Currently only modules that are not published (added to the project) can be deleted. Is that not the right precaution?

**Comment by fuzzylogic2000** [comment]
Ups, you said it should be like that. I thought it was! Alright, then we will fix it.

**Comment by CarolingerSeilchenspringer** [comment]
I reopen because now I cannot delete any module at all, even those not added to a project.
