### ISSUE TITLE
testing 2394: moderation cannot add module

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2676]
**URL:** https://meinberlin-dev.liqd.net/dashboard/projects/testing-dashbaord/basic/
**user:** moderator
**expected behaviour:** can create module
**behaviour:** cannot create module
**important screensize:**
**device & browser:** 
**Comment/Question:** We should allow this. In the long run we should reconsider general project changing rights to moderators. Now that we have groups we might no longer need it.

**Comment by fuzzylogic2000** [comment]
These are two questions:
1. Who should be allowed to add a module? Currently only users who are allowed to add a project are also allowed to add a module. You said, that everyone allowed to change a project should be able to add a module, right?
2. Should moderators be allowed to change a project they are moderating? We should tackle that later as this is quite a big change for the (dashboard) users.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 ok, now I get the logic and it makes sense that moderators can only change an existing project but not add one or add a module to a project. But I just checked again: they can delete modules and add/disconnect them with the project. I would restrict all that because we have groups. But maybe we should discuss this again with other PMs/PO and have the same solution there that works for all platforms?

**Comment by fuzzylogic2000** [comment]
Yeah, here and for now moderartors should be allowed to add modules as they are allowed to remove them and change the project. About everything else we can think later!
