### ISSUE TITLE
testing 2395: wording changes in navigation

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2678]
**URL:** https://meinberlin-dev.liqd.net/dashboard/projects/testing-dashbaord/basic/
**user:** initiator
**expected behaviour:** left navigation says "Modul" in the header of a module navigation.
**behaviour:** left navigation says "Module"
**important screensize:**
**device & browser:** 
**Comment/Question:** missing translation or german plural? :-)

<img width="264" alt="Bildschirmfoto 2019-11-27 um 13 43 10" src="https://user-images.githubusercontent.com/35491681/69724287-e14e0f80-111b-11ea-90eb-1dd646f3aff3.png">

**Comment by fuzzylogic2000** [comment]
Should be fixed with merged PR?!
