### ISSUE TITLE
testing 2395: deleting only module

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2679]
**URL:** https://meinberlin-dev.liqd.net/dashboard/modules/brainstorming-46/module_basic/
**user:** initiator/moderator/group member
**expected behaviour:** I add the first module to my project, made a mistake, can delete it and add a new one.
**behaviour:** I add the first module to my project, made a mistake but cannot delete it. this is strange as there was no module before. To add a second module and then delete the first is not intuitive.
**important screensize:**
**device & browser:** 
**Comment/Question:** is it possible to set the rule that a project can be without module just it cannot be published? As this is the starting point after creating a project it seems unlogic that it cannot be the same afterwards.

**Comment by fuzzylogic2000** [comment]
Yes, we can do that. But then we need another logic, so that there are no (published) projects without any modules. Maybe we don't let initiators remove the last module from the project?

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 yes, I just added another issue #2688 and your suggestion would solve both problems.

**Comment by fuzzylogic2000** [comment]
This is currently like this and thus fixed.
Modules can only be added to project when they are filled in.
Modules can only be deleted when they are removed from the project first.
When a project is published, the last module can't be removed from the project,
