### ISSUE TITLE
testin 2394: starting external project broken

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2680]
**URL:** https://meinberlin-dev.liqd.net/dashboard/projects/testing-project-links/topics/
**user:** initiator/ group member
**expected behaviour:** after creating an external project and filling in all info I can publish.
**behaviour:** after creating an external project and filling in all info navigation fields/forms from regular projects show up including event/information etc. Module information (eg. phase) is displayed below project navigation.
**important screensize:**
**device & browser:** 
**Comment/Question:** 

<img width="260" alt="Bildschirmfoto 2019-11-27 um 14 11 58" src="https://user-images.githubusercontent.com/35491681/69726043-ead97680-111f-11ea-993c-43834991bfbb.png">

**Comment by fuzzylogic2000** [comment]
Fixed!
