### ISSUE TITLE
testing 2394: spelling mistake

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2682]
**URL:** https://meinberlin-dev.liqd.net/dashboard/organisations/liqd/bplans/
**user:** initiator/group member
**expected behaviour:** button says "Neuer Bebauungsplan"
**behaviour:** button says "Neuer Benauungsplan"
**important screensize:**
**device & browser:** 
**Comment/Question:**

**Comment by fuzzylogic2000** [comment]
:rofl:
