### ISSUE TITLE
testing 2394: cannot publish with one module incomplete

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2683]
**URL:** https://meinberlin-dev.liqd.net/dashboard/modules/brainstorming-52/phases/
**user:** initiator/group member
**expected behaviour:** should be able to publish my project with one added module even if other modules aren't complete
**behaviour:** project ready to publish can no longer be published once I crate new module 
**important screensize:**
**device & browser:** 
**Comment/Question:**

**Comment by fuzzylogic2000** [comment]
This is the next story. What do we do with this now?

**Comment by CarolingerSeilchenspringer** [comment]
close it :-)
