### ISSUE TITLE
testing 2394: trashcan too small on smartphone

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2684]
**URL:** https://meinberlin-dev.liqd.net/dashboard/modules/brainstorming-52/phases/
**user:** initiator/group member
**expected behaviour:** trashcan icon should be as larges as button next to it
**behaviour:** trashcan is smaller
**important screensize:**
**device & browser:** iphone 7, safari, device held horizontal
**Comment/Question:** 

<img width="176" alt="Bildschirmfoto 2019-11-27 um 15 30 01" src="https://user-images.githubusercontent.com/35491681/69732668-57f30900-112c-11ea-81af-0693b5616ddc.png">

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer cannot re-produce, is this with browserstack or a browser emulator?

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland yes, browserstack and my iphone. as just checked: not on android and only if phone is held horizontally.

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland unfortunately this didn't fix it. Do you have another idea? Could we otherwise live with it? it seems to be only on iphone 6/7/8 (both safari and chrome).

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer there is something else I can try, I just can't test locally right now, local testing on browser stack sometimes works and sometimes not so it's a case of merging stuff that might fix and then testing on dev so will give other thing a go

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland the trashcan is still too small. But you thought about a different display of deleting modules yesterday in any case. Would that solve the problem?

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer yes, it will :D

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland nice, thank you!!
