### ISSUE TITLE
Bezirkauswahl currently doesn't select the Bezirk on map (at least for containers)

### ISSUE THREAD

**Issue by rmader** [liqd/a4-meinberlin#2701]
See https://mein.berlin.de/dashboard/projects/radverkehrsversuch-tempelhofer-damm/point/

**Comment by CarolingerSeilchenspringer** [comment]
@rmader we will probably get rid of containers but i will leave this issue open in case we decide otherwise.

**Comment by fuzzylogic2000** [comment]
The bezirk is in no way connected to the polygon. It's just a string you can add in the django-admin and then it's settable in the projects https://github.com/liqd/adhocracy4/blob/master/adhocracy4/administrative_districts/models.py
It would be cool if we could change that, but seems like a lot of work for a small change. It would make sense, though

**Comment by fuzzylogic2000** [comment]
As we don't at all use the polygons in the containers, I will close this.
(I mean, the first dropdown is to select the Bezirk, but the map to select a point, so I don't think we need to select the Bezirk on the map when one is chosen. Both fields are not connected.)
