### ISSUE TITLE
testing 2394: activate dropdown in overview of external projects and bplans

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2705]
**URL:** https://meinberlin-dev.liqd.net/dashboard/organisations/liqd/external-projects/
**user:** initiator
**expected behaviour:** I can use the dropdown next to the buttons vorschau/ansicht and bearbeiten 
**behaviour:** dropdown is always inactive
**important screensize:**
**device & browser:** 
**Comment/Question:** 

![Bildschirmfoto 2019-12-04 um 11 59 35](https://user-images.githubusercontent.com/35491681/70137421-27602180-168e-11ea-888c-3e5edb35697e.png)

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer what should the dropdown contain? we don't duplicate external or bplans currently so there is nothing to put in it

**Comment by phillimorland** [comment]
have removed dropdown

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland if we don't duplicate removing it is good.
