### ISSUE TITLE
embed: fixed button for navigating back

### ISSUE THREAD

**Issue by damusp** [liqd/a4-meinberlin#272]
Navigating inside the embed should be easier. A fixed "Back"-button would help a lot. It would also bring out the application-based concept more.

Here's an old wireframe that features such a button. 

<img width="331" alt="bildschirmfoto 2017-04-27 um 17 28 35" src="https://cloud.githubusercontent.com/assets/22769111/25491478/6118d220-2b70-11e7-80ff-507a06534686.png">

**Comment by xi** [comment]
Here is an idea on how to implement this:

- On small screens, hide any but the last breadcrumb
- Change the breadcrumb styling to look more like buttons
- Use `position: sticky` on breadcrumbs within the embed shell.

A downside of this is that it would attach implicit semantics to breadcrumbs.

An alternative approach would be to simply have something like a "home" button in the shell header that takes me back to the project detail.
