### ISSUE TITLE
change wording in Änderungsprotocoll according to Dashboard navigation

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2744]
**URL:** https://meinberlin-dev.liqd.net/dashboard/projects/project/log/
**user:** initiator
**expected behaviour:** wording in Änderungsprotokoll (what's that in English?) is the same as in dashboard navigation
**behaviour:** "im Projekt anzeigen" is "dem Projekt hinzufügen", "nicht mehr anzeigen" is "aus dem Projekt entfernt"
**important screensize:**
**device & browser:** 
**Comment/Question:** I would wait with these changes until final user testing is done in case we change the wording of the button again. New wording is a bit tricky here but could be: "[user] lässt das Modul [xy] im Projekt anzeigen", "[user] lässt das Modul [xy] nicht mehr im Projekt anzeigen". 

Screenshot?

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer do we have final working for this, also which wording do you want changed? you write about different things in the **expected behaviour** and **behaviour**, im a little confused?

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland sorry for the confusion, I meant to say that the wording should be all the same in the status guide, the alerts and the Änderungsprotokoll. I have suggestions for changes but would ask @fuzzylogic2000 to check if they makes sense in German. It is a bit tricky with "im Projekt anzeigen" and steps out of the structure of the other protocol entries.

is = "user" hat das Projekt "project" erstellt.
should be = "user" hat das Projekt "project" angelegt. (English: use word you also use in status guide)

is = "user" hat das Modul "modul" zum Projekt hinzu gefügt.
should be = das Modul "modul" wurde durch "user" im Projekt angezeigt. (modul "modul" has been shown in project by "user")

is = "user" hat das Modul "modul" aus dem Projekt entfernt.
should be = das Modul "modul" wurde durch "user" nicht mehr im Projekt angezeigt. (modul "modul" has no longer been shown in project by "user)

**Comment by fuzzylogic2000** [comment]
Somehow this feels like a weird mix of tenses, but I don't know how to fix that. :(
If it helps: we can also add the title of the project to the module stuff, though.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 thanks, thats how I feel. I will get back to you about this.
