### ISSUE TITLE
external projects are not marked as external in the project list

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#2757]
**URL:** /projekte
**user:** all
**expected behaviour:** there should be small icon marking the project as external in the upper right corner
**behaviour:** it's not there
**important screensize:** all
**device & browser:** all
**Comment/Question:** It still works for developments plans. It must have been introduced with the changes because of the project_type

Screenshot?

**Comment by MagdaN** [comment]
I can't reproduce this. Can you give some further information on how you found this?

**Comment by fuzzylogic2000** [comment]
@MagdaN Ohhhh, sorry! My external projects with that thing have the project_type project...
