### ISSUE TITLE
I can't log out on embedded page

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-meinberlin#2779]
**URL:** e.g. (need to be logged in) https://meinberlin-dev.liqd.net/embed/projects/brainstorming-7/ 
**user:** user that is logged in
**expected behaviour:** when I click on 'Abmelden' I will be logged out
**behaviour:** when I click on 'Abmelden' nothing happens
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by MagdaN** [comment]
I think it is a CSRF cookie problem

**Comment by rmader** [comment]
Yep, from the log:
`[2020-01-15 12:15:29 +0100] [WARNING] log -- Forbidden (CSRF token missing or incorrect.): /accounts/logout/`

**Comment by MagdaN** [comment]
I am not sure if this ever worked ...

**Comment by rmader** [comment]
I'm gonna take a look
