### ISSUE TITLE
Map only loads only once on embedded page

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-meinberlin#2781]
**URL:** https://mein.berlin.de/embed/projects/burgerhaushalt-treptow-kopenick/
**user:** any user
**expected behaviour:** when I click a link in a popup of a marker, I can see more detail of the idea. If I click on 'zurück' in the top left corner, I can see the map again with all ideas
**behaviour:** when I click a link in a popup of a marker, I can see more detail of the idea. If I click on 'zurück' in the top left corner, the map does not load again
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
![Bildschirmfoto 2020-01-14 um 17 43 09](https://user-images.githubusercontent.com/2905743/72363572-5f2ea000-36f5-11ea-8f0d-876ce9d10ea7.png)

**Comment by phillimorland** [comment]
when testing also can't seem to add ideas via embed https://meinberlin-dev.liqd.net/embed/projects/test-proj/

**Comment by phillimorland** [comment]
@rmader any ideas on this?

**Comment by rmader** [comment]
A rough one - it's about how we initialize our js, which I *think* is on the page load signal. We'd need sure to emit some signal when we change the site in the embed code and listen to it in the initializer.

**Comment by rmader** [comment]
Note to myself: the `a4.embed.ready` is properly emitted (`$(document).trigger('a4.embed.ready')`) and `a4map_display_points.js` does listen to it (`$(document).on('a4.embed.ready', init)`) but for some reason does not fire. To fix the issue here we need to figure out why that is.

**Comment by rmader** [comment]
Note to myself: https://github.com/liqd/a4-meinberlin/pull/2169 was also already an incomplete fix for the same issue
