### ISSUE TITLE
background task to get bplan point errors when there are no bplans(?!)

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#2794]
**URL:** 
**user:** 
**expected behaviour:** It should notify us via email, but not throw an error and trigger chronjob-emails
**behaviour:** The task get_location_information was completed, but has an error.
**important screensize:**
**device & browser:** 
**Comment/Question:** This might be because there was no connection?! Should we get notified if that's the case? Or should the task be tried again? When, how and so on.

Screenshot?

**Comment by rmader** [comment]
If there are connection problems, IMO we should throw sentry errors. That's what we do with the IGBCE and SPD logins - we should only get an email once for the same error then. See https://github.com/liqd/adhocracy-plus/blob/master/apps/users/forms.py#L124

**Comment by rmader** [comment]
The problems got fixed on the other side - as throwing errors is a kind loudly complaining, I'd leave as it is for now - better error notifications are probably low-prio.
