### ISSUE TITLE
Export of polygon broken

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2823]
**URL:** https://mein.berlin.de/dashboard/modules/kiezkasse-11/area_settings/
**user:** initiator
**expected behaviour:** I can export my polygon
**behaviour:** if I hit the export button nothing happens.
**important screensize:**
**device & browser:** testet chrome and firefox on mac
**Comment/Question:**

**Comment by rmader** [comment]
Should be similar to https://github.com/liqd/adhocracy-plus/pull/228, will need to port that over.

See https://github.com/liqd/adhocracy-plus/pull/228/files#diff-41cc48c025952a18eef09ca0430ab179L5
