### ISSUE TITLE
Poll "Jahn-Sportpark" problems

### ISSUE THREAD

**Issue by lthueer** [liqd/a4-meinberlin#2824]
**URL:** https://mein.berlin.de/projects/jahnsportpark/
**user:** all
**expected behaviour:** the project side on meinBerlin opens
**behaviour:** page opens very slowly, participation takes a lot of time as well.
**important screensize:** /
**device & browser:** /
**Comment/Question:** I already talked with Katharina and she said it depends on the poll module which would have to be changed then.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 that would change if implementing the new comment system because they don't all load at the same time, right? Then it would make a nice story :-)

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer Yes, I hope it will!
