### ISSUE TITLE
forwarding feedback-Mail turnes my mail grey

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2844]
**URL:** 
**user:** support
**expected behaviour:** if I forward a feedback-mail (in order to reply to the user) my mail has a white background color 
**behaviour:** if I forward a feedback-mail my mail turns the same grey as the background of the feedback-e-mail and I can't change it.
**important screensize:**
**device & browser:** PC, Outlook (Berlin administration)
**Comment/Question:** a+ mails have a white background. So I guess the background does not have to be grey?

Screenshot
![Bildschirmfoto 2020-03-23 um 15 52 38](https://user-images.githubusercontent.com/35491681/77330086-21667d00-6d1f-11ea-9b19-e06925da7a8d.png)
![Bildschirmfoto 2020-03-23 um 15 52 55](https://user-images.githubusercontent.com/35491681/77330094-23304080-6d1f-11ea-96e6-be14c569b07c.png)

**Comment by phillimorland** [comment]
remove the gray background and leave the shadow
