### ISSUE TITLE
API validation of documents and polls should not set module

### ISSUE THREAD

**Issue by kleingeist** [liqd/a4-meinberlin#285]
Currently the `.validate()` methods of the Documents and Poll Serializers are setting the related module. Consider using a HiddenField  for the module which could be set from the kwargs. Compare the creator fields which is set with:

`
    creator = serializers.HiddenField(
        default=serializers.CurrentUserDefault()
    )
`

**Comment by rukala** [comment]
Is this related to the internal server error I get when trying to fill in content for polls after creating a poll process?

**Comment by kleingeist** [comment]
@rukala no this is a different issue. although i am pretty sure the internal error is a database problem. the models had been renamed and i had some problems on my development machine, too

**Comment by kleingeist** [comment]
No longer valid, as the module is now set in the create methods of the serializer
