### ISSUE TITLE
missing alert for creating module

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2856]
**URL:** dashboard
**user:** unitiator
**expected behaviour:** I get an alert for successfully creating a module
**behaviour:** I don't get an alert
**important screensize:**
**device & browser:** 
**Comment/Question:** Alert should be "Das Modul wurde angelegt." (module was created)

Screenshot?

**Comment by fuzzylogic2000** [comment]
fixed by #2866
