### ISSUE TITLE
remove "hack to ensure german mails are sent'

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#2860]
**URL:** emails (meinberlin/templates/email_base.html and meinberlin/templates/a4reports/emails/report_moderators.en.email)
**user:** 
**expected behaviour:** no hack needed
**behaviour:**
**important screensize:**
**device & browser:** 
**Comment/Question:** @rmader  We do know why that happens by now. I think we should overwrite the method for getting the language in the email or do the nginx-magic.

Screenshot?

**Comment by rmader** [comment]
I added the nginx header to all berlin pillars. Together with the `LANGUAGE_CODE` and `DEFAULT_LANGUAGE` I *think* that should do to allow us to remove the hack, no?

**Comment by fuzzylogic2000** [comment]
Yes, if there's no way the email default language from a4 is used, we can finally remove it!

**Comment by rmader** [comment]
AFAIK `LANGUAGE_CODE` should prevent the a4 implementation to ever return `en` - lets try :)
