### ISSUE TITLE
testing 2770 redesign mails

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2865]
**URL:** mail
**user:** moderator/ user
**expected behaviour:** date and time in the mail I get are displayed e.g. "30. März 2020, 07:34 Uhr"
**behaviour:** they are displayed "30. März 2020 07:34"
**important screensize:**
**device & browser:** 
**Comment/Question:** If the comma is not possible, please add at least "Uhr". This is what we also did in the follow-mails we re-did before. The report mail is also missing a "." behind the "Uhr".

Screenshot?

**Comment by Rineee** [comment]
@CarolingerSeilchenspringer So this is only in the report e-mail, right?
