### ISSUE TITLE
rounded corners of feedback button 

### ISSUE THREAD

**Issue by damusp** [liqd/a4-meinberlin#288]
The feedback button is not supposed to have all corners rounded, just the two on the left hand side. 

<img width="170" alt="bildschirmfoto 2017-05-05 um 16 24 59" src="https://cloud.githubusercontent.com/assets/22769111/25749633/7e0ba0ac-31af-11e7-9d7c-b80b8ab42040.png">

**Comment by xi** [comment]
So what is the idea here? Our buttons have rounded corners, so is this not a button? Or yet another button variant?

**Comment by damusp** [comment]
i guess that would be another variant. it's about averting those little holes on the very right. 

this is of course just a minor aesthetic detail, but I wanted to point it out because i wasnt sure if it was styled this way intentionally.
