### ISSUE TITLE
Application port

### ISSUE THREAD

**Issue by raulsperoni** [liqd/a4-meinberlin#2881]
**Comment/Question:** 

Hello, I'm trying to run meinberlin in order to test adhocracy. It might be a dumb question but once I run make watch, in which port will i find the application?

Thank you.

**Comment by Rineee** [comment]
Hey Raul, it runs on 8003. You can also see that in the console output once you run make watch.. all the best!

**Comment by raulsperoni** [comment]
Thank you! Saw the console but was running inside docker and for some reason it wasn't working. Can you tell me the default admin user and password? Thank you (i couldn'd find any guide, if there is please tell me)

**Comment by Rineee** [comment]
Actually all there is, is in the README, so I think we should work on our documentation :) But default login is admin@liqd.net | password. 
Hope you can get started now!

**Comment by raulsperoni** [comment]
Thank you so much! Now I just need to go through all the german...😂

**Comment by Rineee** [comment]
Oh true, everything is in German there... but I think setting the language code to English, so  
LANGUAGE_CODE = 'en-EN'
in meinberlin/config/settings/base.py should help?

**Comment by fuzzylogic2000** [comment]
If you want to try something that also has everything also in English and less very specific modules, try a+: https://github.com/liqd/adhocracy-plus
Setup should be the same, so if you came this far here, you should be quick also setting up this.

**Comment by raulsperoni** [comment]
Perfect thank you! I will look at it. So far I'm finding adhocracy great.
No sure I understand the structure or how everything works yet but I'm
testing the features just fine. I'm working with this as part of a survey
of a number of e-participation tools for an academic project. Thank you.

**Comment by Rineee** [comment]
Cool! Any feedback will be appreciated :)
