### ISSUE TITLE
only module can be removed from published project

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#2898]
**URL:** https://meinberlin-dev.liqd.net/dashboard/projects/lorem-ipsum/basic/
**user:** initiator
**expected behaviour:** when a project is published, at least one modle should always be added to the project, the initiator shouldn't be able to remove the last one 
**behaviour:** last added module can be removed, resulting ind strange project detail view ("Die Beteiligung ist aktuell nicht möglich. Sie startet am None. ") with an empty project without any participation.
**important screensize:**
**device & browser:** 
**Comment/Question:** @CarolingerSeilchenspringer I am not sure we decided it should be like that (or can you just not delete the last module and only delete it after it has been removed?), but I think this needs to be fixed. Do you agree?

Screenshot?

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 this is strange because I am almost certain it wasn't like this when I tested. The remove button needs to be inactive for the last module of a published project. Totally agree!
