### ISSUE TITLE
warning in project overview after setting filter

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2910]
**URL:** https://mein.berlin.de/projekte/
**user:** any
**expected behaviour:** if I set a filter via search function and click on a project tile, I am going straight to the project page
**behaviour:** I get a warning first, that my changes will not be saved
**important screensize:**
**device & browser:** I tested chrome, firefox, safari on mac
**Comment/Question:** 

Screenshot?
![image](https://user-images.githubusercontent.com/35491681/80224787-7d882e00-864a-11ea-8dfa-2ec165c9d8da.png)

**Comment by fuzzylogic2000** [comment]
So, we should move it back to just be used in the dashboard and maybe add a base_form to also include it in and use in all forms?!
https://github.com/liqd/a4-meinberlin/commit/80fe4e69d996f360025751535af06b40dfbf6d6f

**Comment by rmader** [comment]
Judging from the discussion when we landed this I think this was not really intended: https://github.com/liqd/a4-meinberlin/pull/2777/files#r366878224

So I'd just move that back.
