### ISSUE TITLE
pictures on project tiles do not change with filter but project tiles do

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2911]
**URL:** https://mein.berlin.de/projekte/
**user:** any
**expected behaviour:** tile pictures change if - after I set filters - the tiles change
**behaviour:** after filtering the tiles change but the pictures don't leading to projects with pictures of other projects 
**important screensize:** 
**device & browser:** at least windows with Expoler and Firefox, also mac with chrome and safari
**Comment/Question:** 

example:
first project right now:

![image](https://user-images.githubusercontent.com/35491681/80378944-afdd9980-889d-11ea-9d55-dc2376119b2e.png)

after setting filter to "lichtenberg"
![image](https://user-images.githubusercontent.com/35491681/80378973-be2bb580-889d-11ea-9f30-0d8fab745b13.png)

**Comment by fuzzylogic2000** [comment]
I don't get it? It's two different projects, or a project and an external project, right?
Is it the wrong picture displayed for the second one?

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 The picture belongs to the Kiezkasse, which in the unfiltered list is the top project. If I set a filter the picture stays the same but the project list changes according to the filter, so that the now top external project "runder Tisch..." has the picture of the Kiezkasse. Without setting the filter the project is found further down the list and  (correctly) looks like in this screenshot:
![image](https://user-images.githubusercontent.com/35491681/80498309-db2eba00-896b-11ea-8c8e-881ec2206734.png)
This is true for all pictures, they seem to not react to the filter.

**Comment by fuzzylogic2000** [comment]
Ah! Thanks!

**Comment by rmader** [comment]
Ok, this was introduced by 68c4d97e8 which the nice lazy loading of images - will try to debug it, otherwise we might have to disable it again for the moment.
