### ISSUE TITLE
newsletter picture wider than newsletter

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2933]
**URL:** newsletter
**user:** initiator/ follower of a project
**expected behaviour:** If as initiator I add a picture to my newsletter it looks nicely in any mail programme
**behaviour:** larger pictures are wider than the newsletter frame and the text also jumps out of the frame.
**important screensize:**
**device & browser:** mac and both mail and thunderbird
**Comment/Question:** 

![newsletter](https://user-images.githubusercontent.com/35491681/81184930-43574e80-8fb1-11ea-8f4d-e94468daca70.png)

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer @Rineee this is kind of a user error as the user chooses the size of the image at upload (height and width), we have a width set for emails and most clients adhere to that but we will have to overwrite a hard coded image width added by the user in and email. Just wondering how much time should we spend on something like that?

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer see above

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland how about adding a helptext into the newsletter form saying what the maximum width should be in case a picture is entered? Problem is that the initiators don't get a preview. But they can test on stage.

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer I think a preview wouldn't be accurate anyway as a webpage would use the email template styling and the email clients some use the template styling, some use the uploaded image styling, ok i have an idea, will try that, if it doesn't work i'll add helptext

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland just tested again: with ios 10.15, 13zoll-laptop, mail program, 650px is the maximum width in which the mail is correctly displayed. Window size also affects it, if I make it smaller the text is larger than the mail-background but that can be helped by enlarging the window. But if the picture is more than 700px and I enlarge the window, it does not help.

![image](https://user-images.githubusercontent.com/35491681/86735304-ff290e80-c032-11ea-8083-4f269a05d37f.png)

**Comment by CarolingerSeilchenspringer** [comment]
and the logo is not centered as you can see on the screenshot.
