### ISSUE TITLE
Static/Assets directories in apps

### ISSUE THREAD

**Issue by vellip** [liqd/a4-meinberlin#295]
Django says to include app specific static files in a `/static` directory in the root of the particular app (https://docs.djangoproject.com/en/1.11/howto/static-files/). On `runserver` Django collects static files from the project wide static directory (mentioned in base.py) and the `/static` directories within all apps, grouping them into one global `/static` directory.
Now, we don't need `.jsx` files in that global `/static` directory since they are required and put together into one file by webpack. Still, those files need a directory to be put into on app level – therefore sometimes there might be an asset directory instead of a static directory or the other way around.
It'd be great to have one directory and in the best case that would include not having `.jsx` files in that django-generated, global `/static` directory.

**Comment by kleingeist** [comment]
maybe we could use a solution like http://stackoverflow.com/questions/12082902/how-do-i-ignore-static-files-of-a-particular-app-only-with-collectstatic  but i'd suggest to move everything to /asset/ and copy them to the static directory.  i would really like to add static/ to .gitignore
