### ISSUE TITLE
Should the initial slide number used for the slider of multi module projects have some error handling

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#2960]
**URL:** https://meinberlin-stage.liqd.net/projects/neugestaltung-park-test/?initialSlide=blabla
**user:** 
**expected behaviour:** 
**behaviour:** If it's not a number, there's a 500. Also: https://sentry.liqd.net/sentry/meinberlin-stage/issues/1061/?query=is%3Aunresolved
**important screensize:**
**device & browser:** 
**Comment/Question:** How does the paginator do it?

Screenshot?

**Comment by phillimorland** [comment]
@fuzzylogic2000 just to check how does the initial slide become not a number, I can't seem to make that happen unless i edit url? Also do you think expected behavior should be a 404?

**Comment by fuzzylogic2000** [comment]
@phillimorland  Yes, it should only happen when someone edits the url, but sentry reported that on stage, so maybe somehow it can also happen differently?!
What happens for the pagination when the number is too high or a string is given? 404? But yes, I think that would be a good solution!

**Comment by fuzzylogic2000** [comment]
added to a4
