### ISSUE TITLE
testing 2956: add platform mail

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2966]
* footer needs to be changed (see comments of story in taiga)
* change wording in dropdown to "Plattform-Mail" in German
* pre-entered name "meinberlin" should be changed to "meinBerlin"
* missing translation

Please note: two related issues (concerning newsletter in general) are still open:
#2933  
#2932

**Comment by fuzzylogic2000** [comment]
"meinberlin" still missing.
