### ISSUE TITLE
#2959 [mB] redesign mail of new Stellungnahme in b-plan module

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#2975]
**URL:** e.g. https://meinberlin-dev.liqd.net/dashboard/projects/lorem-2/bplan/

**Comment/Question:** *Everything worked perfectly but I was just able to do it following Rine`s instructions. How can the admins know that they have to copy the embedded link? Also, how can they copy on Mobile? I think this would need more concept, right?* 

<img width="607" alt="Screenshot 2020-05-26 at 16 16 28" src="https://user-images.githubusercontent.com/59610786/82912428-6603d400-9f6d-11ea-95b6-8b81e29c8a18.png">

*Regarding the email itself, I would just increase the margins a bit if possible.* 
![Screenshot-2020-05-26-at-16 21 20](https://user-images.githubusercontent.com/59610786/82912517-803db200-9f6d-11ea-8a6e-18e2903ea3fc.jpg)

Thanks! :)

**Comment by fuzzylogic2000** [comment]
Hey @mcastro-lqd ! Yes, that would be a bit cumbersome if the Sachbearbeiter and users would need to use it like that! But that was only for us to test. The usual way would be: The bplan is added in a different form that is not on our side by the Sachbearbeiter. That different form is using our API to create the bplan. The Sachbearbeiter then gets the whole embed code also on the other side, not on ours. And the whole embed code is then also put into the other site and displaying the form for the user there. So, neither Sachbearbeiter nor user ever get to our site to add a bplan or a statement.
For the margins: @Rineee or @phillimorland could you do that?

**Comment by phillimorland** [comment]
@mcastro-lqd can't replicate the no margins, which email program are you viewing from?

**Comment by phillimorland** [comment]
@mcastro-lqd is there no margin on you view of the email? or should it just be increased a little!

**Comment by mcastro-lqd** [comment]
@phillimorland The current spacing is marked in red, I would just increase a little a bit. :)
