### ISSUE TITLE
testing 2961: captcha-number shown in feedback-mail

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2991]
**URL:* feedback-mail 
**user:** person receiving feedback-mail
**expected behaviour:** 
**behaviour:** some number of the captcha is presently shown in the feedback mail. Can we take it out?
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
https://meinberlin-dev.liqd.net/feedback/
![image](https://user-images.githubusercontent.com/35491681/85280199-f4de1080-b487-11ea-9149-218dec3522dd.png)

**Comment by rmader** [comment]
Fixed by https://github.com/liqd/a4-meinberlin/pull/3003
