### ISSUE TITLE
testing 2961: captcha

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#2992]
**URL:** https://meinberlin-dev.liqd.net/feedback/
**user:** non-registered user
**expected behaviour:** my answer using the text mode is not correct
**behaviour:** I still get an alert
**important screensize:**
**device & browser:** 
**Comment/Question:** I sometimes find the text mode a bit complicated and didn't always get it right, but I guess that's how it is?

Screenshot?
![image](https://user-images.githubusercontent.com/35491681/85280399-5d2cf200-b488-11ea-9411-c55400aa0014.png)

![image](https://user-images.githubusercontent.com/35491681/85280548-9feeca00-b488-11ea-8da7-1a907b80dbdb.png)

**Comment by CarolingerSeilchenspringer** [comment]
<img width="979" alt="Bildschirmfoto 2020-06-22 um 12 53 08" src="https://user-images.githubusercontent.com/35491681/85285531-5bb3f780-b491-11ea-9f32-29345e821fc3.png">

also this answer was seemingly wrong. I don't know if I would have to write it as a figure? maybe @rmader we can talk about it?

**Comment by rmader** [comment]
> <img alt="Bildschirmfoto 2020-06-22 um 12 53 08" width="979" src="https://user-images.githubusercontent.com/35491681/85285531-5bb3f780-b491-11ea-9f32-29345e821fc3.png">
> 
> also this answer was seemingly wrong. I don't know if I would have to write it as a figure? maybe @rmader we can talk about it?

Yes, some translated solutions are a big buggy, but that's something we need to fix on the captcha database :/ Number always work when you write it as number, like `11`

**Comment by CarolingerSeilchenspringer** [comment]
@rmader can we fix the captcha database if we want to? I will close this issue, I just wanted to hint at it so that I know what to say in case of feedback. Most questions worked and I guess most people will use the graphics anyways.

**Comment by rmader** [comment]
> can we fix the captcha database if we want to?

Yup, can fix it whenever there's time.

**Comment by CarolingerSeilchenspringer** [comment]
nice. We will leave it for now but now I know it is possible in case of complaints.
