### ISSUE TITLE
mB demo: missing district outlines on project overview

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3008]
**URL:** https://meinberlin-demo.liqd.net/projekte/
**user:** all
**expected behaviour:** there are outlines for the districts on the map
**behaviour:** there are no outlines
**important screensize:**seems to effect all sizes
**device & browser:** chrome on Mac
**Comment/Question:** Isn't demo always the same as stage and prod?

![image](https://user-images.githubusercontent.com/35491681/85681577-b769c500-b6cb-11ea-9f90-0a9f91956e68.png)

**Comment by phillimorland** [comment]
not present on dev, stage or prod. @fuzzylogic2000 @rmader what is the relationship of demo to the others? i've not come across demo before?!

**Comment by fuzzylogic2000** [comment]
As suspected, the outlines are data, not code. They are taken from the map presets, whcih need to have the map preset category "Bezirke - Berlin": https://github.com/liqd/a4-meinberlin/blob/2233ea5f2268938eac49d87a3f00ea658a7bc1a9/meinberlin/apps/plans/views.py#L49
That category was missing on demo and thus also not assigned to the districts. The districts were also not properly added to the administrative districts and the filters were broken.
Adding everything fixed it.
