### ISSUE TITLE
bplans tile status of participation incorrect

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3022]
**URL:** https://mein.berlin.de/projekte/
**user:** all
**expected behaviour:** bplan should be displayed as running as it has started 6.7. at 00 Uhr.
**behaviour:** bplan displayed as upcoming
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

![image](https://user-images.githubusercontent.com/35491681/86571518-d68d1000-bf71-11ea-8c95-a7aa3814d3a2.png)

**Comment by CarolingerSeilchenspringer** [comment]
ok, tile is shown correctly now, but should have changed to running project and midnight. These are the settings in Dashboard:

![image](https://user-images.githubusercontent.com/35491681/86581638-a6993900-bf80-11ea-884b-a42b43f5338e.png)

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer I've been trying to reproduce this and i haven't been able to, were these created by the api or in the dashboard? i'm not sure if that would make a difference but without being able to replicate it's hard to fix, might also be a 00:00 and 12:00 problem?! @fuzzylogic2000 is it possible it's reading 00:00 at 12:00?

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland the 00/12 could be the problem. I checked at 12:02. I started a new testproject on dev starting at midnight and will check in the morning what it displays.

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer And this is only like that for bplans? Not for external or normal projects?

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland @fuzzylogic2000 : my testproject on dev is shown correctly even before noon and so are external and other projects. So I will close the issue and have an eye on bplans and if it happens again.
