### ISSUE TITLE
testing bplan verification mail

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3032]
**URL:** mail
**user:** Sachbearbeiter of bplan
**expected behaviour:** should get a verification mail when adding a new bplan and when publishing it via Dashboard
**behaviour:** only get a verification mail if I change a bplan
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by fuzzylogic2000** [comment]
When you add bplan via the dashboard, the email of the office worker is not yet filled in. So, it tries to send (makes a task), but has nowhere to send it to. And as the email is exactly to test if the office worker email is filled in correctly, I would say, this is not a problem?! If it's a requirement, you should add another story to add the office worker email to the first form (where only title and description are currently displayed). @CarolingerSeilchenspringer 
And now I will check out the publish! :)

**Comment by fuzzylogic2000** [comment]
Alright! When the project is published, that is saved to the project, not the corresponding bplan. :facepalm: 
We can also send the email, when the bplan is published, but that would mean, that for creating a published bplan via the API, the office worker would get two emails, which might be annoying.
On the other hand, when publishing the bplan via the dashboard, the office worker wouldn't get an email for that. :thinking: 
We can also distinguish what happened with the bplan, though and send two different emails, one for creating and changing and one for publish.
So, the decision is: do we want two emails, which might be sent to the office worker publishing via the API at the same time or do we only want an email for creating and updating? @CarolingerSeilchenspringer

**Comment by fuzzylogic2000** [comment]
Alright, no! I got that wrong! For the API, the publish results in an email, because that is a normal update (just like any of the other fields). So, there is only one email no matter if the bplan is created as a published or draft one.
So, there is only no email, when the bplan is published via the dashboard. Do we need to fix that @CarolingerSeilchenspringer ?

**Comment by fuzzylogic2000** [comment]
Aright! As all is working and fine in the API, it's fine!
We might add another US for emails about published projects (in the dashboard) at some point.
