### ISSUE TITLE
Some users have the same lower/uppercase names and can't log in or participate

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#3037]
**URL:** 
**user:** 
**expected behaviour:** Everyone with an user account is able to log in.
**behaviour:** When two users have the same name with different cases (e.g. user and User), they both can't log in.
**important screensize:** 
**device & browser:** 
**Comment/Question:** We already fixed that it's not possible to get the same lower/uppercase name anymore, but there are still some in the database on prod. Maybe we can find them, Change one of the names and let them know via Email?

@CarolingerSeilchenspringer Do you have an idea how to fix this? We can find out who exactly failed logging in and maybe change their names and write an email to them?

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 I wouldn't know how to finde the doubles, so waiting for failed log-ins sounds good. Do we get Sentry-Notifications? Would we get one for each failed log-in, like if people get their password wrong?

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer Yeah, we have the sentry errors and can see there who tried to login. It's a bit more than 20 by now, but I guess quite a few duplicate names (but don't know).

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer Sentry says it happened 41 times now. I think, we should find a solution.
Oh, and it's not the same as a wrong password. We don't know about these users, but the login attempts trigger the error from #2813

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 can you give me the usernames who recently tried to log-in? I will write them.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 as discussed: I have the list (thanks!) and will only write to users when we get a sentry. Please send the sentry to support@-Address. I will close the issue.
