### ISSUE TITLE
[stage] no captcha on stage

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3040]
**URL:** both feedback and registration form
**user:** everyone
**expected behaviour:** there is a captcha
**behaviour:** cannot be displayed
**important screensize:**
**device & browser:** mac, both chrome and firefox
**Comment/Question:** 

Screenshot?

![image](https://user-images.githubusercontent.com/35491681/87136522-ea9b7f00-c29b-11ea-9b13-db9d074e74ab.png)

**Comment by fuzzylogic2000** [comment]
It's there now!
