### ISSUE TITLE
[dev/stage] auto-fill-in overwrites my bplan-name

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3041]
**URL:** https://meinberlin-stage.liqd.net/dashboard/projects/caro-testing-new-bplan-mail-2/bplan/
**user:** initiator addin bplan
**expected behaviour:** I can use autofill to add my mail-address
**behaviour:** if I do so, the title of bplan is overwritten by my name but as it is far up the form I don't notice it.
**important screensize:**
**device & browser:** mac, chrome
**Comment/Question:** is that even something we can influence?

Screenshot?
<img width="673" alt="Bildschirmfoto 2020-07-10 um 11 02 30" src="https://user-images.githubusercontent.com/35491681/87137579-6b0eaf80-c29d-11ea-928f-c888dc8eb430.png">
<img width="673" alt="Bildschirmfoto 2020-07-10 um 11 06 10" src="https://user-images.githubusercontent.com/35491681/87137586-6cd87300-c29d-11ea-965d-74b4ecba8bc8.png">

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland I still have that issue on stage. Any other idea? If not please close again as not may people use this form.

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer then we can't do anything about it then, I added the no autofill/autocomplete attributes to the form field but Chrome is over riding them so it's a Chrome issue
