### ISSUE TITLE
Button style missing for password reset form

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-meinberlin#305]
In the form to reset your password the button is not recognizable as a button. 
https://meinberlin-dev.liqd.net/accounts/password/reset/

<img width="643" alt="bildschirmfoto 2017-05-09 um 12 01 34" src="https://cloud.githubusercontent.com/assets/15341015/25845849/d0971d76-34af-11e7-8314-de070b03e56c.png">

**Comment by vellip** [comment]
Thanks for that! We already got it covered in #124 though. ;)
