### ISSUE TITLE
Button to confirm email address invisible

### ISSUE THREAD

**Issue by rukala** [liqd/a4-meinberlin#306]
After adding a new email address in the account settings and clicking on the link in the verification email, user have to click another button in the confirm-email dialogue (is this necessary?) - in Firefox this button is not visible - only writing black on white
<img width="1437" alt="bildschirmfoto 2017-05-09 um 13 36 05" src="https://cloud.githubusercontent.com/assets/11075214/25848987/f74b7770-34bc-11e7-87ff-a3d5610a468f.png">
 (see screenshot).

**Comment by vellip** [comment]
Hey! Thanks for that, but we already got it covered in #124.
