### ISSUE TITLE
when bplan is archived, office worker update email is sent

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#3061]
**URL:** 
**user:** 
**expected behaviour:** Office workers only get an update email when bplan is "published, changed or created as draft"
**behaviour:** The automatic archiving also changes the bplan and by that triggers the email. Thinking about it, it should also trigger the get-point thing (and might result in failure errors being thrown).
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer I think we should investigate and fix this rather quickly, right?! Not sure if prio should be high or medium, though. When is the next scheduled release?

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 what is the "get-point thing"? but you are right, this may be quite confusing for office worker. It should have time till next scheduled release end of september.

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer That is the script that checks for point and district in the bplan map.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 ah thanks. So can we make the archiving not trigger mail and get-point thing? Alternatively we could also write in the mail that the mail is send when the project finishes and automatically is being archived.

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer No, we can make it not sent the email and trigger the get-point thing. :)

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 just saw that this is also in the milestone. If you manage to fix before monday, it's good, if not, we'll do it with next release. I'll leave it in the milestone for now.
