### ISSUE TITLE
Projects are not filtered

### ISSUE THREAD

**Issue by lthueer** [liqd/a4-meinberlin#3081]
**URL:** https://mein.berlin.de/projekte/?district=Steglitz-Zehlendorf&topic=-1
**user:** initiator
**expected behaviour:** projects are filtered and displayed correctly
**behaviour:** the initiator is redirected to a new page which seems to have no layout
**important screensize:** /
**device & browser:** Microsoft & Firefox Quantum 68.9.0esr
**Comment/Question:** /

![GW_00001](https://user-images.githubusercontent.com/36957474/90531693-a93d9f80-e176-11ea-92d8-52c1b26a076f.png)

**Comment by phillimorland** [comment]
Original message: 
"vielen Dank für die schnelle Reaktion. Ich verwende Firefox Quantum 68.9.0esr auf einem Microsoft-Rechner. Gegebenenfalls könnten auch Sicherheitseinstellungen unserer IT-Stelle beim Bezirksamt Steglitz-Zehlendorf für Einschränkungen verantwortlich sein, wenn für die Anzeige der Projekte ein Plug-In, Add-On o.ä. benötigt wird. Wir haben gerade erst auf den direkten Internetzugang umgestellt und bestimmte Webseiten-Kategorien sind gesperrt, können aber freigeschaltet werden, wenn ich die Notwendigkeit melde."

@rmader are you on this?

**Comment by rmader** [comment]
Yep, answered them somewhere. Their settings were way to strict :)
