### ISSUE TITLE
#3289 Interactive Event 

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#3131]
**URL:** https://meinberlin-dev.liqd.net/projekte/module/interaktive-veranstaltung/
**device & browser:** *e.g. Firefox 80.0 (64-bit)*

**Comment/Question:**
![Screenshot_2020-09-17-Lorem-Ipsum-—-meinBerlin(2)](https://user-images.githubusercontent.com/59610786/93490308-9d293700-f908-11ea-827f-a0988917bf37.jpg)
01 – The questions were supposed to be 20px, but its also fine for me like that. 
02 – The Icons are different and fine, but this one seems a bit off, I have save the ones I did here in case you need them: Nextcloud/Projekte/meinBerlin/Material/CI/Bilder & Grafiken/icons/svg
03 – Shall we put a max number of characters here since the questions should be short? @CarolingerSeilchenspringer 
04 – I did the spacing between the questions using 8px but if that was already the meinBerlin spacing guidelines, we leave like that. 
05 – The category labels seem a bit far from the question, if possible, could we shorten the spacing here a bit so it gets closer from the question and "far" from the Like button? 
06 – Are the moderators supposed to like the question? If yes, its not working for me. :/

![Screenshot 2020-09-17 at 17 05 20](https://user-images.githubusercontent.com/59610786/93491015-7d464300-f909-11ea-9f17-fc4d7195597a.png)
07 – If possible can we use here the text style from the notes (14px)? 

![Screenshot 2020-09-17 at 17 08 19](https://user-images.githubusercontent.com/59610786/93491078-90f1a980-f909-11ea-9b5a-22d06351d485.png)
08 – The statistics seem a bit off compared to the sketch on Zeplin. Same on Mobile.

![Screenshot 2020-09-17 at 17 03 12](https://user-images.githubusercontent.com/59610786/93491135-a1a21f80-f909-11ea-929d-e8bdb2140015.png)
09 – Selected categories seem a bit off after selecting them, they kind of stay there instead of just being selected. (Do you know what I mean? I can also explain to you better sharing the screen or something).

![Screenshot 2020-09-17 at 17 27 12](https://user-images.githubusercontent.com/59610786/93492752-715b8080-f90b-11ea-8a1f-b7d87e13416f.png)
10 – The Menu on Mobile is different than on Zeplin. 

![Screenshot 2020-09-17 at 17 24 33](https://user-images.githubusercontent.com/59610786/93492800-86381400-f90b-11ea-993c-2616dc4993ab.png)
11 – Same here, the infobox is difficult to understand. Also the buttons are off, spacing inbetween them are different.

![Screenshot 2020-09-17 at 17 26 58](https://user-images.githubusercontent.com/59610786/93492878-994ae400-f90b-11ea-84a1-db9b760ba010.png)
12 – Small thing here but if possible, the success infobox should be aligned properly to the left. 

![Screenshot 2020-09-17 at 17 25 59](https://user-images.githubusercontent.com/59610786/93492962-b2539500-f90b-11ea-9b06-bad2fa5eab15.png)
13 – Can we increase the spacing here a bit between the link and icon? 

![Screenshot 2020-09-17 at 16 50 18](https://user-images.githubusercontent.com/59610786/93492603-4709c300-f90b-11ea-973a-8e99376faa24.png)
14 – The Blueprint is not updated, I left the .svg file on Taiga
 
I just didn't manage to test the Initiator's view cause there is no project open to testing, could you edit the phase from one of yours and send me the link? Cause all the ones I created I'm the moderator as well. 

Thanks a lot! Let me know if you need anything :)

**Comment by CarolingerSeilchenspringer** [comment]
my remarks:
3) there is a limit of 1000 characters. We can leave it like this for now and should think about it in the next iteration. It seems too high to me. At least we have to mark the limit.
6) moderations don't need to like questions
9) this is on all browsers if there is no questions in this category. And I found it on all mobiles if the filter is too far down the screen.
10) I didn't check the moderator
12) can you make a separate issue out of it as it is not part of the story @mcastro-lqd ?

**Comment by phillimorland** [comment]
Thanks guys! in answer to questions:
2 - we will stick with font awesome until all the icons are chosen as it is much smoother and easier to add a full set so once the like is decided upon then we will add a new custom set of icons for mB
3 - answered by @CarolingerSeilchenspringer 
6 - Mods can like but they need to see how many likes but should we try to style this differently in the next iteration to make it clearer, what do you think @mcastro-lqd? 
10 - as mentioned in zeplin, this will be a different story as it should be changed in all projects
12 - see Caro's comment

Cheers! :)

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland thanks for your answers!!
