### ISSUE TITLE
testing interactive event: screen

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3144]
**URL:** https://meinberlin-dev.liqd.net/questions/present/module/interaktive-veranstaltung-2/
**user:** user in event/ moderator
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** 
1) veranstaltung -> Veranstaltung
2) Mitmachen -> Mitmachen unter:
3) question-icon: it is slightly cut off on both edges

Screenshot?
<img width="1277" alt="Bildschirmfoto 2020-09-22 um 16 36 25" src="https://user-images.githubusercontent.com/35491681/93906540-9893c280-fcfc-11ea-85ab-a3303f5016de.png">

**Comment by phillimorland** [comment]
@mcastro-lqd the question-icon file seems to be slightly cut off in the original file, can you add a new one to nextcloud please? danke! :)

**Comment by mcastro-lqd** [comment]
@fuzzylogic2000 @phillimorland Can you try using this one? Ive also updated the nextcloud folder. 


[icons-iv_fragen-64px.svg.zip](https://github.com/liqd/a4-meinberlin/files/5297715/icons-iv_fragen-64px.svg.zip)

**Comment by phillimorland** [comment]
@mcastro-lqd danke!
