### ISSUE TITLE
testing stage: moderator request mail is send in english

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3164]
**URL:** 
**user:** moderator
**expected behaviour:** the mail I get is in german
**behaviour:** it is in english (but with a * that does not belong there)
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
<img width="598" alt="Bildschirmfoto 2020-09-29 um 10 49 45" src="https://user-images.githubusercontent.com/35491681/94535293-b5bb1a80-0241-11eb-9619-7bc760bf2298.png">

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer I don't think, we will manage to fix this until the release. Maybe @Rineee can have a look?
