### ISSUE TITLE
video cookie info: layout broken 

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3178]
**URL:** https://meinberlin-dev.liqd.net/projekte/ihre-vision-fur-berlin-welche-themen-sind-ihnen-wi/?initialSlide=4 (click: über das Projekt)
**user:** unregistered user
**expected behaviour:** should look like this: https://meinberlin-dev.liqd.net/projekte/ihre-vision-fur-berlin-welche-themen-sind-ihnen-wi/?initialSlide=2 (click: über das Projekt)
**behaviour:** layout is broken if 1) there is a module with map that is not part of a cluster 2) URL has ending of the slide of that module (if you have a timeline)
**important screensize:**
**device & browser:** 
**Comment/Question:** the only difference of the two above URL is the initialSlide. if it leads to a map, the view is broken in both information and result tab. if it leads to an event or module without map, view of video is fine. It does not have to do with state of publication nor with active/non-active phase. it happens on both chrome and firefox and an dev/stage/prod.

Screenshot?
<img width="692" alt="Bildschirmfoto 2020-10-07 um 16 25 18" src="https://user-images.githubusercontent.com/35491681/95344228-b6932280-08b9-11eb-8958-3d79fca3a7f5.png">

**Comment by phillimorland** [comment]
fix broke other things
