### ISSUE TITLE
accordeon broken

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3180]
**URL:** https://meinberlin-stage.liqd.net/projekte/initiator-5-neugestaltung-des-mauerparks-neu/
**user:** unregistered user
**expected behaviour:** accordeon is shown
**behaviour:** text is shown without accordeon
**important screensize:**
**device & browser:** mac both chrome and firefox
**Comment/Question:** within the same project it is correctly shown in infotab but not in result tab. In other projects it also isn't shown correctly in info tab. No clue what else to test.

<img width="467" alt="Bildschirmfoto 2020-10-07 um 18 03 05" src="https://user-images.githubusercontent.com/35491681/95357158-d03b6680-08c7-11eb-8af6-7e0aacfa6891.png">

<img width="467" alt="Bildschirmfoto 2020-10-07 um 18 02 57" src="https://user-images.githubusercontent.com/35491681/95357157-cf0a3980-08c7-11eb-96f6-bb9913c7cad4.png">

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer I found the reason it isn't showing in the results tab but cannot replicate error of not showing correctly in the info tab as you mention in your comment, can you add a link?

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland this is an example of not showing correctly in infotab: https://meinberlin-stage.liqd.net/projekte/initiator-5-neugestaltung-des-mauerparks/.

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer this is very weird, so are there other projects that do this? sorry to keep asking but I can't replicate it, even when I duplicate that project so it's difficult to fix. If i can find a similarity between other projects that show the behavior then I should be able to find the issue.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 @phillimorland totally agree to leave the issue open and see, if it occurs again. If it does not within 6 month we will close the issue.

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland @fuzzylogic2000 this issue occured again on stage. I manage to break/repair my accordeon by moving it but don't know why that is. Check https://meinberlin-stage.liqd.net/projekte/test-release-v27/, go to infotab, move accordeon no 2 (broken) to the top (e.g. below accordeon no 1), then it will look good. Does that bring us closer to the solution?

**Comment by lthueer** [comment]
This issue also occurs on a+:https://github.com/liqd/adhocracy-plus/issues/1077

However, the accordeon doesnot work at all in the result tab -despite of moving or removing/readding it. For the infotab it works fine.

**Comment by CarolingerSeilchenspringer** [comment]
as this didn't happen again and we still cannot replicate I will close the issue
