### ISSUE TITLE
map in spatial brainstorming: cannot click individual pins in some browsers

### ISSUE THREAD

**Issue by Amelie-liqd** [liqd/a4-meinberlin#3201]
**URL:** https://mein.berlin.de/projekte/module/brainstorming-mit-kartenfunktion-21/
**user:** unregistered user 
**expected behaviour:** When I see the pins on the map I can select them individually, click on them and then look at the idea. 
**behaviour:** In Safari and Explorer the pins are visible, however cannot be selected. 
**device & browser:** Safari, Explorer

**Comment by phillimorland** [comment]
@rmader @Rineee I thought this might be a zindex issue but i've checked and it doesn't seem to be and there isn't an error that points in any direction, any ideas? or shall we not worry about it for this release
