### ISSUE TITLE
testing 3491 (livestream interactive event): add livestream before publishing

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3247]
**URL:** 
**user:** initiator
**expected behaviour:** I can add a livestream before I publish the project
**behaviour:** as the navigation is not there I don't even see that I have the possibility to add a livestream before I publish. 
**important screensize:**
**device & browser:** 
**Comment/Question:** Is there a particular reason why you did it that way? 

Screenshot?

**Comment by fuzzylogic2000** [comment]
@phillimorland Just fixed it and it should be on dev for 20 minutes now. When did you find it @CarolingerSeilchenspringer ? Is it still there? :thinking:

**Comment by CarolingerSeilchenspringer** [comment]
äh, tested before 2 pm and just continued. I will check again tomorrow!

**Comment by phillimorland** [comment]
The builds are super slow right now, this is already fixed on dev
