### ISSUE TITLE
testing 3491 (livestream interactive event): can write into livestream ck-editor

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3248]
**URL:** 
**user:** initiator
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** It is not by any chance possible to not be able to write into the CK-editor?  Initiators can write long texts in there and what can be done probably will be. The questions is, if we want to allow it or not? At least I think we should add a helptext saying that they SHOULD NOT write here. this could be also the place to explain that the video is only visible during active phase. Let's discuss this in comments and depending on what we decide I can think about a helptext.

Screenshot?

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer I don't know how to stop them from being able to write in there other then making our own embed component so help text would be preferred method from my side.

**Comment by CarolingerSeilchenspringer** [comment]
ok then, let's change wording to:
English: You can enter a livestream from YouTube or Vimeo. The livestream will be shown when the module phase is active. For description text please use module or phase description.

German: Sie können einen Livestream von YouTube oder Vimeo einfügen. Der Livestream wird während der aktiven Modulphase angezeigt. Für Beschreibungstexte nutzen Sie bitte die Modul- oder Phasenbeschreibung. 

Please also rename the Navigation from "Live Stream" to "Livestream" according to Duden.
