### ISSUE TITLE
testing 3491 (livestream interactive event): cookie warning

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3249]
**URL:** 
**user:** user (all)
**expected behaviour:** I get a cookie warning just like for the other videos on meinBerlin
**behaviour:** there is no cookie warning
**important screensize:**
**device & browser:** 
**Comment/Question:** the customized cookie warning was optional but we do need at least the regular one we also have for the other videos. Otherwise we have trouble with data protection.

Screenshot?

**Comment by phillimorland** [comment]
this is already fixed, but build is taking a while so not showing yet
