### ISSUE TITLE
add tests for group member to all rule-tests

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#3269]
- [x] documents
- [x] offlineevents?
- [x] plans?
- [x] projects

**Comment by fuzzylogic2000** [comment]
Are there tests for offlinevents and plans?

**Comment by sabinammm** [comment]
Group member rules tests for projects were added to in [PR 477](https://github.com/liqd/a4-meinberlin/pull/4077/files)
