### ISSUE TITLE
testing 3546 semi-public projects: missing tile icon

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3277]
**URL:** https://meinberlin-dev.liqd.net/projekte/
**user:** any
**expected behaviour:** tile should indicate that project is semi-public
**behaviour:** symbol on tile (eye) is missing
**important screensize:**
**device & browser:** 
**Comment/Question:** as on a+, do we still icon adapted to mb? 

Screenshot?

**Comment by fuzzylogic2000** [comment]
@mcastro-lqd Did you already get the chance to make a badge for the semi-public projects? The current ones (private and linkage) are here: https://github.com/liqd/a4-meinberlin/tree/master/meinberlin/assets/images (called badge_...)

**Comment by mcastro-lqd** [comment]
@fuzzylogic2000 Opsie, I just saw this email, sorry!

I didn't manage to find these files, but I created one based on the badge_priva_projekt.png, is that ok?

Here you go: 
https://github.com/liqd/a4-meinberlin/blob/master/meinberlin/assets/images/badge_semi-public_projekt.png

Or if you prefer saved as .svg:
[201201-semi-public.svg.zip](https://github.com/liqd/a4-meinberlin/files/5624265/201201-semi-public.svg.zip)

Best

**Comment by fuzzylogic2000** [comment]
@mcastro-lqd Very nice! Thank you!
