### ISSUE TITLE
testing 3546 semi-public projects: change wording for comment sections

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3280]
**URL:** https://meinberlin-dev.liqd.net/ideas/2020-00489/, any comment section
**user:** uninvited user
**expected behaviour:** reasonable explanation
**behaviour:** can't comment because phase supposingly does not allowed but in fact it's because I am not invited
**important screensize:**
**device & browser:** 
**Comment/Question:** instead of "Die aktuell laufende Phase erlaubt keine Kommentare." Should say "Nur eingeladene Nutzer*innen können sich aktiv beteiligen./ Only invited users can actively participate.“

Screenshot?
<img width="640" alt="Bildschirmfoto 2020-12-01 um 13 24 56" src="https://user-images.githubusercontent.com/35491681/100740223-a5a5ef80-33d8-11eb-87d7-e1379d1109f7.png">

**Comment by fuzzylogic2000** [comment]
@Rineee Didn't you fix that already? Rings a bell...

**Comment by Rineee** [comment]
I did, but for the new comments, but these are the old ones, right? So will have to also fix it there!
