### ISSUE TITLE
testing 3546 semi-public projects: explanation in (interactive) event

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3281]
**URL:** in event (https://meinberlin-dev.liqd.net/projekte/testing-semi-public-project/?initialSlide=0) and interactive event (https://meinberlin-dev.liqd.net/projekte/module/interaktive-veranstaltung-12/)
**user:** all
**expected behaviour:** 
**behaviour:** saying only invited people can participate does not make sense in events, as you can't participate there online and in interactive events, as you can still participate online.
**important screensize:**
**device & browser:** 
**Comment/Question:** I guess we decided this is for later and till then we will have an eye on semi-public projects. So this issue is a reminder for later when we make event into module?

Screenshot?

**Comment by CarolingerSeilchenspringer** [comment]
can we talk about this again? Actually this will effect a major running private project after release. Maybe it is better then to take the wording out for now if there is no easy way to solve it?

**Comment by CarolingerSeilchenspringer** [comment]
as it is not on module but on project level, maybe it should even be part of the header instead of the module

**Comment by fuzzylogic2000** [comment]
What exactly do you want to take out? The explanation for private and semi-private from the module?
We can't change the explanation for the project in the dashboard as we don't know which modules will be added.

**Comment by fuzzylogic2000** [comment]
Hmmja, there is no easy solution now. We could remove it from the module info and add it to the project part. But then @mcastro-lqd needs to say how and where.

**Comment by CarolingerSeilchenspringer** [comment]
as discussed with @fuzzylogic2000 we will take this out of events which should be possible. for interactive event it will be part of another story.
