### ISSUE TITLE
testing 3492: change UX of entering questions: different filter than rest of platform

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3282]
**URL:** https://meinberlin-dev.liqd.net/projekte/module/interaktive-veranstaltung-11/
**user:** all
**expected behaviour:** easy to use filter, same filter everywhere
**behaviour:** the filter is not the one we usually use. In firefox also there is a strange behaviour: if I click once on the filter, it does not stay open. Sometimes is does, depending on where on the button I click and what I had chosen before. 
**important screensize:**
**device & browser:** 
**Comment/Question:** the filter used here is with the arrows up/down (right side) and is not the same we usually use with one arrow pointing down only. We should be consistent here and use the one we use to filter categories in projects. 

Screenshot?
<img width="355" alt="Bildschirmfoto 2020-12-01 um 14 44 22" src="https://user-images.githubusercontent.com/35491681/100748537-ba3bb500-33e3-11eb-86f8-5bbcf9e8288e.png">

**Comment by CarolingerSeilchenspringer** [comment]
actually I found another filter. Maybe we can quickly talk about which filter to use everywhere in the near and far future and therefore here, also with @mcastro-lqd ?

**Comment by mcastro-lqd** [comment]
@CarolingerSeilchenspringer I thought they are supposed to be like the ones that I already have in the file, but if its not updated I can change the symbols in the file as well.

**Comment by CarolingerSeilchenspringer** [comment]
@mcastro-lqd the filter here (the one used to filter the questions, not to select the category) https://meinberlin-dev.liqd.net/projekte/module/interaktive-veranstaltung-11/ does not behave the same as the filter here: https://meinberlin-dev.liqd.net/projekte/module/brainstorming-80/. They look alike, but if you use them, one turns blue. Also one says per default "Merkmal auswählen" and the other one "Kategorie: alle". We PMs thought it was nicer to have "Kategorie: alle" but wanted you to say.

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer @mcastro-lqd Unfortunately we couldn't use our normal dropdown filter as this is purely a react component we have to use a select filter (like we use in map idea collection). I will check the width and the firefox problem but the filter type will have to stay the same, sorry!

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland where in map idea collection do we use it? The category filter above the map is a dropdown. THe one in the idea form is a dropdown with search option.

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland ah, you mean the one in dashboard choosing pin icons. ok then. But can we change the arrow icons? The one for the pins also only has one arrow pointing down. And is there in general the possibility to have one kind of filter all over if we make a story out of it?

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer i'll polish it as much as possible. The reason we use a select element (sorry not filter) is because it needs to send data to a database, this isn't normally done with a dropdown as they are used for either filtering or navigation not for adding stuff to a form. I'll double check how we do it in user side map select and see if I can reproduce that but it being a react component makes it a little more tricky, you have to adhere to more rules in react then we do when adding stuff to templates, its kind of annoying!

**Comment by CarolingerSeilchenspringer** [comment]
ok I got that now, thanks! let's just make them look as much alike as possible. :-)
