### ISSUE TITLE
testing 3492: change UX of entering questions: wording change

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3283]
**URL:** https://meinberlin-dev.liqd.net/projekte/module/interaktive-veranstaltung-11/
**user:** all
**expected behaviour:** same button as in other modules I am used to
**behaviour:** button says "Frage stellen"
**important screensize:**
**device & browser:** 
**Comment/Question:** I think we should stick to „senden“ as we do for comments and also do on a+. For ideas it says „speichern“ which I don’t like and which has confused users and think we should also change at some (other!) point to have „senden“ all over the platform.

there is another wording change that I think is best to add to this issue? (if now I will make another one)
the pre-text already showed in the form should be "Ihre Frage/ your questions" instead of "frage stellen/??". for comments it is "Ihr Kommentar hier", which we should (at another time) also change to "ihr Kommentar" to make it the same. Or should we rather not have pre-texts on the platform at all as we work with help texts? @mcastro-lqd do you have an opinion on that? 

Screenshot?

**Comment by mcastro-lqd** [comment]
@CarolingerSeilchenspringer I agree, I think Senden makes more sense than Speichern here. Regarding the other issue, I think its understandable without it but again I thought it was supposed to be like that because of how it was before. I would leave it it as simple as possible.
