### ISSUE TITLE
testing 3492: change UX of entering questions: edge filter looks wired

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3287]
**URL:** https://meinberlin-dev.liqd.net/projekte/module/interaktive-veranstaltung-11/
**user:** all
**expected behaviour:** shiny looking filter
**behaviour:** the filter does not look right
**important screensize:**
**device & browser:** edge on windows
**Comment/Question:** is that what it is supposed to look like? If so and we can't change it, you can close the issue.

Screenshot?
<img width="350" alt="Bildschirmfoto 2020-12-01 um 14 19 36" src="https://user-images.githubusercontent.com/35491681/100750675-aba2cd00-33e6-11eb-8f1d-dd3c33c119a0.png">

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer This is to do with it being a select not dropdown element, does the map icon select look weird on edge too?

**Comment by CarolingerSeilchenspringer** [comment]
that's what the select element looks like for choosing the icons. 

 <img width="449" alt="Bildschirmfoto 2020-12-02 um 11 20 04" src="https://user-images.githubusercontent.com/35491681/100865656-e6b10900-3497-11eb-9ca9-db3368520753.png">

<img width="449" alt="Bildschirmfoto 2020-12-02 um 12 15 44" src="https://user-images.githubusercontent.com/35491681/100865816-1fe97900-3498-11eb-828b-7e5e6b068912.png">
