### ISSUE TITLE
testing 3492: change UX of entering questions: wording to agree to terms of use

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3289]
**URL:** https://meinberlin-dev.liqd.net/projekte/module/interaktive-veranstaltung-11/
**user:** all
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** please cut the first sentence and the "also" in the second sentence. "I confirm that I have read and accept the terms of use and the privacy policy."

Screenshot?

**Comment by Rineee** [comment]
In the story it explicitly says 'like registration', so please next time think about it before to avoid unnecessary work. Even though its just a wording change, it takes time, especially when translations have already been done.. Thank you!

**Comment by CarolingerSeilchenspringer** [comment]
@Rineee as discussed please wait for client to confirm.

**Comment by Rineee** [comment]
> @Rineee as discussed please wait for client to confirm.

:+1:

**Comment by CarolingerSeilchenspringer** [comment]
@Rineee good that I asked again, this is what we'll write: 
Hiermit willige ich ausdrücklich in die Speicherung und Veröffentlichung meiner Fragen, wie in der Datenschutzerklärung beschrieben, ein. Zudem bestätige ich, dass ich die Nutzungsbedingungen und die Datenschutzerklärung gelesen habe und akzeptiere.

I hereby expressly consent to the storage and publication of my questions, as described in the [privacy policy | link]. I also confirm that I have read and accept the [terms of use | link] and the [privacy policy | link].
