### ISSUE TITLE
testing 3492 change UX of entering questions: wording change from category to affiliation

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3290]
**URL:** https://meinberlin-dev.liqd.net/projekte/module/interaktive-veranstaltung-11/
**user:** all
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** @fredewe @lthueer and I agreed to call the categories here "Zugehörigkeit" which translates to "affiliation" (@phillimorland does that sound good to you?). This need to be changed for filter when entering the questions and in dashboard.

new wording  would be:
navigation:
Zugehörigkeit /affiliation

form:
Zugehörigkeiten bearbeiten / edit affiliations

helptext:
Hier können Sie Zugehörigkeiten vorgeben. Nutzer*innen müssen Fragen entsprechend einordnen. Die Fragen können nach Zugehörigkeiten gefiltert und in der Statistik ausgewertet werden. 
Here you can specify affiliations. Users must classify questions accordingly. The questions can be filtered by affiliation and evaluated in the statistics.

**Comment by Rineee** [comment]
@CarolingerSeilchenspringer Ok, lets take that, sounds good to me! 
So the above wording is for the dashboard, what would you like in the user form? Just 'Zugehörigkeit' above the affiliaton dropdown select or maybe some helptext to explain? And on the filter below it now says 'Merkmal auswählen', so now it would be 'Zugehörigkeit auswählen'?

**Comment by CarolingerSeilchenspringer** [comment]
@Rineee as I was writing to client about the policy confirmation issue I also mentioned the new wording so in this issue as well: let's wait for confirmation before we change.

**Comment by Rineee** [comment]
> @Rineee as I was writing to client about the policy confirmation issue I also mentioned the new wording so in this issue as well: let's wait for confirmation before we change.

:+1:

**Comment by CarolingerSeilchenspringer** [comment]
@Rineee thanks for asking! Here is the whole wording for user form
Zugehörigkeit / affiliation
Beantwortete Fragen werden entsprechend der ausgewählten Zugehörigkeit in der Statistik dargestellt. / Answered questions will be displayed in the statistics according to the chosen affiliation.
filter: "Zugehörigkeit auswählen" "chose affiliation (? whatever you have there in english in other filters)

Frage/questions
[form]

**Comment by CarolingerSeilchenspringer** [comment]
@Rineee I realized we have to also change the wording in statistic tab. Please change "Ausgewählte Merkmale" to "Zugehörigkeit der beantworteten Fragen/ affiliation of answered questions"
