### ISSUE TITLE
multimodule: not all modules properly shown

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3319]
**URL:** https://mein.berlin.de/projekte/fachdialog-hauptstadtregion/
**user:** participant of private project
**expected behaviour:** show all modules in multimodule
**behaviour:** shows one module twice
**important screensize:**
**device & browser:** 
**Comment/Question:** all modules (text commenting) start at the same time, one module (brainstorming) started 1 minute late. The first module was then shown twice. Trying to delete one module, another one was deleted. @fuzzylogic2000 already tried to fix it and knows more about it. 

Screenshot?

**Comment by fuzzylogic2000** [comment]
fixed with https://github.com/liqd/adhocracy4/pull/645
