### ISSUE TITLE
unneeded alert in modul short descriptions

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3321]
**URL:** modul short description in poll module
**user:** initiator
**expected behaviour:** If I enter more than the 512 allowed characters they will be cut off at 512.
**behaviour:** text is cut off after 514 characters and gives me a warning. 
**important screensize:**
**device & browser:** 
**Comment/Question:** is there a reason for this behaviour? can't we just cut off at 512? maybe say "your text was to long, has been cut off" or something? or say nothing? That's what we do in phase description and it seems more ux friendly to me.

Screenshot?
<img width="677" alt="Bildschirmfoto 2020-12-14 um 13 52 23" src="https://user-images.githubusercontent.com/35491681/102083554-0b03d280-3e14-11eb-8dad-14843b5cf0d1.png">

**Comment by fuzzylogic2000** [comment]
We use different fields (TextField for the phase description, CharField for the module description) here. I think it should also behave the like this for the module name, which is also a CharField.
As you put prio: low on it, should we even do it or just close? To me cutting it off silently seems worse, but the not-centered error message bugs me more. :p
And if we start here, we should test all project, module and phase text/char fields and try to make them behave the same, which would mean changes in a4 and by that also a+ and opin.

**Comment by CarolingerSeilchenspringer** [comment]
what is a CharField?
Yes, I will close this issue then. And yes, we should generally talk about the error messages and yes, I already mentioned to other PMs that I would like to have an A4 talk about changes we want in all project. :-)

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 in PM we had the idea to collect general questions to the devs on a+ so you don't have to answer them again and again. I just started a project with my first question "what is a char field" so you can answer there. I will introduce the project in next MMM. :-)
