### ISSUE TITLE
poll: results are being shown before phase as started

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3322]
**URL:** https://meinberlin-dev.liqd.net/projekte/pre-release-testing/?initialSlide=0
**user:** any
**expected behaviour:** I can't see the poll before the phase has started. I may see the questions but not the results.
**behaviour:** results are being shown
**important screensize:**
**device & browser:** 
**Comment/Question:** was this before? is that easy to fix? If not we should integrate into poll re-do story.

Screenshot?

**Comment by fuzzylogic2000** [comment]
Yes, this is for a while and not so easy, because we need a concept and then need to add that to the react code.

**Comment by CarolingerSeilchenspringer** [comment]
as discussed with @fuzzylogic2000 I will include this into another poll story as this has been there before.
