### ISSUE TITLE
position anchor for my question in interactive event

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3323]
**URL:** https://meinberlin-dev.liqd.net/projekte/module/interaktive-veranstaltung-15/
**user:** any user
**expected behaviour:** can easily see my question after I added it
**behaviour:** I can see part of the question "tile" at the very bottom of the page
**important screensize:**
**device & browser:** 
**Comment/Question:** This is great that you added this anchor! However at first I didn't get it. It may be even easier if not only the questions but the whole question "tile" was visible after entering the question. Including affiliation and likes.

Screenshot?

**Comment by Rineee** [comment]
Hm not sure what you mean here.. for me it looks like this (both firefox and chrome):
![grafik](https://user-images.githubusercontent.com/9589411/102198968-53c69480-3ec3-11eb-933f-b5e19a80a968.png)
 
So the whole question tile is actually visible (Philli improved that again last week..).

**Comment by Rineee** [comment]
Does it look different for you?

**Comment by CarolingerSeilchenspringer** [comment]
I guess it is a safari issue, screenshot from macOS, same on ios

<img width="371" alt="Bildschirmfoto 2020-12-15 um 14 03 54" src="https://user-images.githubusercontent.com/35491681/102218690-a5304d00-3ede-11eb-9acd-85415ac545d4.png">

**Comment by CarolingerSeilchenspringer** [comment]
@Rineee : also, in chrome question takes about 6 seconds to appear, also leading to confusion.

**Comment by CarolingerSeilchenspringer** [comment]
as discussed with @fuzzylogic2000 we will fix this with next release when @phillimorland had a chance to have a look.
