### ISSUE TITLE
frontend: category filter broken 

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3365]
**URL:** https://meinberlin-dev.liqd.net/projekte/burgerhaushalt-spandau/
**user:** all
**expected behaviour:** 
**behaviour:** filter broken having more than 11 categories.
**important screensize:**
**device & browser:** chrome, firefox and safari
**Comment/Question:** 

Screenshot?
<img width="491" alt="Bildschirmfoto 2021-02-05 um 10 24 16" src="https://user-images.githubusercontent.com/35491681/107014740-4f6c7880-679c-11eb-8cd0-83cc71352576.png">

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer whats wrong with it exactly? It seems to be showing all categories.

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland no, there is one more category (in this case "grün") that is hidden behind "Kategorie: alle"
