### ISSUE TITLE
#3824 UX/UI testing  [mB] add fields to form and export for plans

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#3384]
**URL:** https://meinberlin-dev.liqd.net/dashboard/organisations/liqd/plans/
**important screensize:** *Both*
**device & browser:** *Safari Version 14.0.2 (16610.3.7.1.9)*
**Comment/Question:** *Comments are in the pdf*

Desktop:
[200211-d-add-fields-to-form-and-export-for-plans.pdf](https://github.com/liqd/a4-meinberlin/files/5966340/200211-d-add-fields-to-form-and-export-for-plans.pdf)

Export:
[200211-export-add-fields-to-form-and-export-for-plans.pdf](https://github.com/liqd/a4-meinberlin/files/5966341/200211-export-add-fields-to-form-and-export-for-plans.pdf)

**Comment by fuzzylogic2000** [comment]
- [ ] translation "duration" to "Zeitspanne"
- [ ] check if select-replacement broken for "Bezirk" and also last two fields?

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer @mcastro-lqd suggests to have placeholder texts showing what would be a good way to fill in the fields duration and cost, like "4 Monate" and "24.000 €". Do you agree?

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 @mcastro-lqd I think this is something we need to discuss generally. If we do it once, shouldn't we do it everywhere? As we don't have it somewhere else in this form I would not show a placeholder text here.

**Comment by fuzzylogic2000** [comment]
Yes, I think so too! So, for now we'll close (as other issues are done) and keep it in mind!
