### ISSUE TITLE
testing 3773: copyright credits for maps

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3393]
**URL:** all maps
**user:** all
**expected behaviour:** should say: ©MapTiler ©OpenStreetMap contributors with links accordingly
**behaviour:** says:  ©OpenStreetMap contributors"
**important screensize:**
**device & browser:** 
**Comment/Question:** as discussed in taiga please write "©MapTiler ©OpenStreetMap contributors". Or is there a reason you didn't add MapTiler?

Screenshot?

**Comment by fuzzylogic2000** [comment]
@rmader Where is it actually set? Does it come from the settings or the map provider?

**Comment by rmader** [comment]
This is done via salt, however I'm having troubles to get the string properly piped from the salt pillar to the config - just a configuration issue, no changes in mB needed.

**Comment by rmader** [comment]
Err, was easier than I thought :) Done now
