### ISSUE TITLE
test 3780: form for plans

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3394]
**URL:** https://meinberlin-dev.liqd.net/vorhaben/2021-00065/
**user:** all
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** should we cut long words into pieces for both laufzeit and costs? I actually don't know what the best UX is.

<img width="877" alt="Bildschirmfoto 2021-02-15 um 13 39 16" src="https://user-images.githubusercontent.com/35491681/107947789-354c4a80-6f93-11eb-922e-3fc91d79d758.png">

<img width="405" alt="Bildschirmfoto 2021-02-15 um 13 55 37" src="https://user-images.githubusercontent.com/35491681/107949504-a42aa300-6f95-11eb-9ebc-1dc59bb75edd.png">

**Comment by phillimorland** [comment]
@fuzzylogic2000 I think we should probably remove the table if it's not too far out the scope of the story but I want to check it properly for a11y but the software I use won't run on linux so will have to check it tomorrow

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 will try again with longest german word she can find :-)

**Comment by fuzzylogic2000** [comment]
same link: https://meinberlin-dev.liqd.net/vorhaben/2021-00065/
And I fear, we have to do sth. about the table for mobile:
![Screenshot from 2021-02-16 16-10-35](https://user-images.githubusercontent.com/8178179/108082051-f3460600-7071-11eb-88f0-9f0686c15cbd.png)
![Screenshot from 2021-02-16 16-11-50](https://user-images.githubusercontent.com/8178179/108082054-f3de9c80-7071-11eb-98bb-0b51db59b721.png)
![Screenshot from 2021-02-16 16-12-23](https://user-images.githubusercontent.com/8178179/108082059-f4773300-7071-11eb-9ed3-c3295c0afe50.png)

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 wow, were did you come up with such long words? I love them!!  I still wonder if we should close this issue as it seems to be complex and so far the case didn't occur... Just now as I am writing @phillimorland self-assigned herself. Maybe you can have a look but if it is too complex let's talk about it first.

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer I think we should fix it for mobile definitely! if we want it done quickly I can do a hacky fix i think

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland then go for it, thanks!
