### ISSUE TITLE
testing 3781: participatory budgeting 2 phases - category filter

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3397]
**URL:** https://meinberlin-dev.liqd.net/budgeting/create/module/burgerinnenhaushalt-2-phase-2/
**user:** registered user
**expected behaviour:** 
**behaviour:** the filter has no frame
**important screensize:**
**device & browser:** windows 10, edge
**Comment/Question:** as this is not really part of the story and also effects other modules we can - if not easy to fix - move it into the march-release.

Screenshot?
<img width="685" alt="Bildschirmfoto 2021-02-15 um 17 45 27" src="https://user-images.githubusercontent.com/35491681/107973590-abfa3f80-6fb5-11eb-9a12-094bd471098c.png">

**Comment by fuzzylogic2000** [comment]
Is this a new (old) thing or does it also belong the select-weirdness @phillimorland ?

**Comment by phillimorland** [comment]
@fuzzylogic2000 @CarolingerSeilchenspringer I would assume this is an old issue as we haven't touched this but will take a look, maybe edge has updated how they render selects or something

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer cannot reproduce on browserstack, I would now close this unless you think otherwise?

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer this is a different issue, I would open a new one so that the fix pull requests don't get muddled

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland ok thanks, I will do that.
