### ISSUE TITLE
filter above map

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3398]
**URL:** https://meinberlin-dev.liqd.net/projekte/testing-burgerhaushalt-2-phases/
**user:** any
**expected behaviour:** 
**behaviour:** filter is on top of map zoom buttons
**important screensize:**
**device & browser:** iphone 8, safari
**Comment/Question:** is this a bug or bad responsive design from previous times? Easy fix or need of concept? @mcastro-lqd any idea to it?

Screenshot?
<img width="444" alt="Bildschirmfoto 2021-02-15 um 18 02 26" src="https://user-images.githubusercontent.com/35491681/107975233-1ca25b80-6fb8-11eb-8950-a2cdd6fd7ddb.png">

**Comment by fuzzylogic2000** [comment]
Can you zoom with two fingers here? Should we show the zoom button as well? Or should it be moved somewhere else? Or we can put the buttons above the list here and make them full width? It looks a bit weird currently.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 yes, map can be zoomed. @mcastro-lqd what do you think we should do? We have the same problem when there is no archived filter, then the "ansicht"button is in the way. Means we have that problem for all projects with maps. In project overview the +/- is in the lower right corner. Maybe we should move it there?

**Comment by mcastro-lqd** [comment]
@CarolingerSeilchenspringer Sorry for letting this issue go unnoticed but It looks like a bug, I don't think someone would  design it like that. I've just made 2 possible solutions for it: 

![Screenshot 2021-02-25 at 18 44 51](https://user-images.githubusercontent.com/59610786/109194283-8d582d80-7799-11eb-88bd-65f487d9868a.png)

Would that work for you?

**Comment by CarolingerSeilchenspringer** [comment]
@mcastro-lqd thanks! Adapting the Ansicht-Filter to the design we have in project overview has been on our wishlist for a while. Could you make a design with the button below? Would that button also work for larger screens UX-wise? I guess this would become a story but we would not be able to do that before April. But I wouldn't like to touch the filter twice.
<img width="121" alt="Bildschirmfoto 2021-02-26 um 09 07 59" src="https://user-images.githubusercontent.com/35491681/109273702-d4363980-7812-11eb-952a-eb90a91040b8.png">

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer should this issue still be in the milestone as it's going to become a story?

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland took this issue out of the milestone. I will leave it open until we decide for sure that it will be a story. Want to wait first for @mcastro-lqd to see what he thinks, then we can move this to taiga.

**Comment by mcastro-lqd** [comment]
@CarolingerSeilchenspringer Ah, I didn't know about this button. Thanks! Maybe the problem with the current one is also the text, it says "Ansicht" only in both situations which can be confusing. I thought about 3 options, changing the copy to something like "Show as list", use the buttons you just mentioned or these buttons + a very short description. 

I personally think that the icons itself can be pretty much understandable and accessible.

![Screenshot 2021-03-02 at 10 22 58](https://user-images.githubusercontent.com/59610786/109626835-45daf400-7b41-11eb-86e4-069f9992d164.png)

**Comment by CarolingerSeilchenspringer** [comment]
moving this to story: https://taiga.liqd.net/project/liqd-meinberlin/us/345?no-milestone=1 and closing issue.
