### ISSUE TITLE
long phase title for active phase

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3399]
**URL:** https://meinberlin-dev.liqd.net/projekte/testing-burgerhaushalt-2-phases/
**user:** any
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** when phase title is long, should the "active" not rather be in the second line instead of a new extra and otherwise empty line? @mcastro-lqd what do you think?

Screenshot?
<img width="568" alt="Bildschirmfoto 2021-02-15 um 18 12 36" src="https://user-images.githubusercontent.com/35491681/107976350-b1f21f80-6fb9-11eb-8979-963268e0f0db.png">
<img width="568" alt="Bildschirmfoto 2021-02-15 um 18 13 06" src="https://user-images.githubusercontent.com/35491681/107976351-b3234c80-6fb9-11eb-8163-411dd2aa5d2d.png">

**Comment by fuzzylogic2000** [comment]
But that's not new? It's a styling issue, but not connected to the story. :woman_shrugging: 
I think it's easier to make it stay in the upper right corner and make the title break before it. Is that right, @phillimorland ?

**Comment by phillimorland** [comment]
yeah we can either use columns (need to check they work properly as mB is a bit funny with bootstrap) or we just position it and add margin to the title.

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer to confirm, when title is on 2 lines we want active to be on same line as end of title, is that correct?

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland I thought it would always stay in the first line also as @fuzzylogic2000 mentioned?
