### ISSUE TITLE
Delete Follows

### ISSUE THREAD

**Issue by 2e2a** [liqd/a4-meinberlin#341]
We need to delete follows at some point, e.g. when the project is archived or deleted.

**Comment by kleingeist** [comment]
if we'd set `on_delete=models.CASCADE` on the  `a4.follows.model.Follows.project` field they would be at least deleted with projects.
for archived projects we'd have to manually delete the follows while handling archiving

**Comment by kleingeist** [comment]
this is a general issue. at some point we have to decide how to cleanup the database. but this is not specific for follows (compare with Actions etc)
