### ISSUE TITLE
participatory budgeting 2 phases: reply form shown in second phase but submit button doesn't work

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3421]
**URL:** https://meinberlin-dev.liqd.net/budgeting/2021-00520/
**user:** any
**expected behaviour:** if I cannot reply to a comment the form and submit button should not show or be inactive
**behaviour:** I can enter the reply form, but the button doesn't work (firefox, chrome, edge). In Safari the whole comment section disappears clicking on "show answer"
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

firefox
<img width="488" alt="Bildschirmfoto 2021-02-19 um 15 38 55" src="https://user-images.githubusercontent.com/35491681/108518731-2df5ab80-72c9-11eb-98bd-3c3fb42e9c61.png">

chrome
<img width="603" alt="Bildschirmfoto 2021-02-19 um 15 47 15" src="https://user-images.githubusercontent.com/35491681/108519243-bffdb400-72c9-11eb-8230-5c6013d6e94c.png">

**Comment by Rineee** [comment]
Note: this is not participatory budgeting specific, its the same behaviour for other modules that are over.
