### ISSUE TITLE
Timeline squeezes smartphone project view

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3426]
**URL:** https://meinberlin-stage.liqd.net/projekte/marienhofe-verkehrsplanung/
**user:** any
**expected behaviour:** project view on whole width
**behaviour:** timeline goes all the way, rest is smaller than it could
**important screensize:**smartphone only, several ones
**device & browser:** e.g. galaxy 10, iphone 11
**Comment/Question:** 

Screenshot?
<img width="297" alt="Bildschirmfoto 2021-02-22 um 17 52 13" src="https://user-images.githubusercontent.com/35491681/108741435-073cac80-7537-11eb-88a0-8edb318c3ec5.png">

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland @fuzzylogic2000 the initiator of https://mein.berlin.de/projekte/blankenburger-sueden-snk/ pointed out to me that projects with timeline still have a long timeline and white space on the right and can be scrolled to the side. I didn't notice as page is no longer squeezed and you actively have to scroll, otherwise the page is shown as should be. Do we want that behaviour? Seems to be on all browsers, also mobile.

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer I couldn't reproduce that. Neither on my android phone, nor on both desktop browsers (Firefox and chromium), sized down to 329 px. Which browsers did you try? Could you add a screenshot?

**Comment by CarolingerSeilchenspringer** [comment]
I also didn't get it as first. But the timeline is longer than the rest of the page, but you only see it if you scroll to the side. 

Here is the users screenshot, in this case microsoft edge. I can reproduce that on chrome, firefox and safari, but actually not on my iphone. Seems to only start with breaking point 800, so only on larger screens. 

![image002](https://user-images.githubusercontent.com/35491681/115722043-e3eb7d80-a37e-11eb-8c11-5a708d45b504.jpg)

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 should I reopen this issue?

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer It shouldn't be like that, but could you open a new issue? It's not the same as this one and the title confused me last time.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 thanks, will do that!
