### ISSUE TITLE
bplan statement form blank on IE 11

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3441]
**URL:** https://www.stadtentwicklung.berlin.de/planen/b-planverfahren/de/fruehbb/6-47/index.shtml
**user:** any
**expected behaviour:** statement form can be used
**behaviour:** statement form is empty
**important screensize:** 
**device & browser:** Windows, IE 11
**Comment/Question:** can you look into it soon and then we decide how to handle/prioritize it?

Screenshot?
<img width="534" alt="Bildschirmfoto 2021-02-24 um 14 17 48" src="https://user-images.githubusercontent.com/35491681/109009263-a0da9a00-76ae-11eb-8f98-b57ca8b8274b.png">

**Comment by rmader** [comment]
Weirdly the issue appears to be the same that triggered https://github.com/liqd/a4-meinberlin/issues/3422 - I'm just confused that it doesn't happen on other browsers :confused: 

The error message is: `Unable to set property 'getCurrentPath' of undefined or null reference`, so https://github.com/liqd/a4-meinberlin/pull/3445/commits/99da934476a0dbe05dbac91bf88346fc1be93d2f should fix it

**Comment by fuzzylogic2000** [comment]
@carolin It should be fixed on dev now, could you check? But I wouldn't put that onto prod today and also next week I am hesitant, as we did lots of refactoring and that might break other stuff.

**Comment by CarolingerSeilchenspringer** [comment]
@rmader @fuzzylogic2000 I just tested this for IE 11 via browserstack and the form is still empty. Tested this URL: https://meinberlin-dev.liqd.net/embed/projects/mein-neuer-bplan-testing-mail/

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 @phillimorland As I understood we can close this issue now as it is only IE 11. Please reopen if wrong.
