### ISSUE TITLE
testing 3804 _ templates: wording change

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3442]
wording change in template interactive event, german and english, second sentence: plural for question/Frage.

Should be "Andere Teilnehmende können die Fragen unterstützen." "Other participants can support the question."

<img width="171" alt="Bildschirmfoto 2021-02-24 um 15 32 59" src="https://user-images.githubusercontent.com/35491681/109015672-aedfe900-76b5-11eb-9806-4a8d6e27fcf1.png">

**Comment by Rineee** [comment]
@CarolingerSeilchenspringer In the doc you attached, it says Frage :neutral_face: But will change it..

**Comment by CarolingerSeilchenspringer** [comment]
@Rineee I know it was wrong in the doc, sorry!
