### ISSUE TITLE
testing 3803_templates: phase title in dashboard

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3443]
**URL:** https://meinberlin-dev.liqd.net/dashboard/modules/burgerinnenhaushalt-2-phasen-2/phases/
**user:** initiator
**expected behaviour:** form title doesn't equal form content
**behaviour:** it's the same
**important screensize:**
**device & browser:** 
**Comment/Question:** Does the phase title automatically set the form title? The new titles are good for the users but not as form titles in dashboard. Is there an easy solution? Should we make a little story out of it that can still be done in this (or next) sprint? Should I change the wording again?

<img width="534" alt="Bildschirmfoto 2021-02-24 um 15 37 13" src="https://user-images.githubusercontent.com/35491681/109016175-2d3c8b00-76b6-11eb-9f4f-6bd56b1e2794.png">

**Comment by Rineee** [comment]
Yes, it takes the (initial) phase name as form title, which worked with the old phase names, but with the new ones it is really very confusing, yes .. easy solution would be to just not show the form title (only show 'Phaseneinstellungen bearbeiten'), but that would look odd for 2 phases I guess? Hm, tricky..

**Comment by fuzzylogic2000** [comment]
Maybe we can introduce another variable only into the phases on meinBerlin? (There's also module_name, which doesn't exist in a4). I am not sure it works, and it would be another small story.
Or yes, we don't show the headline. That's only an easy solution when we don't need to overwrite the phase form template from a4, because we already do that. If we don't do that yet, that seems like another story to me as well.

**Comment by Rineee** [comment]
Yes, we have our own phase form template in mB, so hiding it would be possible. @CarolingerSeilchenspringer I think we have 2 options:

1. not show the headline in phase form (so only show 'Phaseneinstellungen' bearbeiten and then the form(s))
2. have a new variable for the headline. That would be a small story and we would need the wording for all phases.

What do you think?

**Comment by CarolingerSeilchenspringer** [comment]
@Rineee how about option 3 ;-)
We take option 2 and call the phases "Phase 1" and "Phase 2". To explain what that means we add a helptext just below the main header (just as we do e.g. in categories). That helptext could be "Je nach ausgewähltem Modul hat der Beteiligungsprozess eine oder zwei Phasen. Name und Beschreibung der Phase(n) sollten die Nutzer*innen zur Teilnahme anregen und sie wissen lassen, wie sie sich beteiligen können." Then we have a nice and understandable form. We would make a story out of it!

**Comment by CarolingerSeilchenspringer** [comment]
@Rineee @fuzzylogic2000 I wrote a story for this, can you check it out? would that be a small story solution?

**Comment by fuzzylogic2000** [comment]
Yes, it is, nice!
