### ISSUE TITLE
[mB] change template overview 

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#3444]
**important screensize:** *Both*
**device & browser:** *Safari*
**Comment/Question:** *If possible, the only thing I would do is reduce a bit the spacing between Module Title and Description marked in green. Thanks!*

![IMG_7955](https://user-images.githubusercontent.com/59610786/109128372-b81d9400-774f-11eb-902e-49c80b7cd938.PNG)
* 
<img width="915" alt="Screenshot 2021-02-25 at 09 47 56" src="https://user-images.githubusercontent.com/59610786/109128386-bbb11b00-774f-11eb-98ee-47861e705483.png">

**Comment by phillimorland** [comment]
note: have removed from taiga as not an issue caused by story

**Comment by mcastro-lqd** [comment]
Sorry, I thought we had started putting all the issues there as well

**Comment by phillimorland** [comment]
@mcastro-lqd, yep ypou are so please put any issue you think are realted to stories you are testing into taiga and we'll check them. If we find it's not directly related to changes we made for the story then we'll remove it from Taiga and the PM can decide if it goes into the milestone, does that make sense?
