### ISSUE TITLE
pictures via ck editor squeezed

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3446]
**URL:** squeezed: https://meinberlin-stage.liqd.net/maptopicprio/2020-01523/ 
**user:** all
**expected behaviour:** 
**behaviour:** the pictures are squeezed
**important screensize:**
**device & browser:** 
**Comment/Question:** seems to be only true for pictures larger than our frame, eg. looks good here, where they set the width to 800 (https://mein.berlin.de/projekte/jonny-k-aktivpark-online-beteiligung/)

Screenshot?

**Comment by fuzzylogic2000** [comment]
If it's too big it gets unsqueezed, when you take width and height out. 
Was it looking differently before the last release?

**Comment by CarolingerSeilchenspringer** [comment]
as discussed with @fuzzylogic2000 I will close this issue. I will mark in Handreichung that width and height need to be taken out and will brief support to do so for already existing projects in case they contact us.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 I reopen the issue with the question if there is anything we can do about it. The solution via Handreichung and support seems to not be enough. I found several running projects with squeezed images yesterday and I suppose initiators don't check their project on mobile.

**Comment by fuzzylogic2000** [comment]
Oh right. We decided, that we would check out if there is a (not totally hard) fix for this. @phillimorland Could you have another go, now, that we have time for this (and it's not some kind of hotfix for something we can't change superquick)?

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland I reopen as now, if you add a picture via CK editor and don't take out the width, it seems to look good (https://meinberlin-dev.liqd.net/projekte/text-kommentieren-3/). But if you - in text commenting - klick on comments and get to the detail page of the paragraph, the pictures is squeezed (https://meinberlin-dev.liqd.net/text/paragraphs/43/)

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland also in events the image is squeezed. Check out this project: https://meinberlin-dev.liqd.net/projekte/text-kommentieren-3/. I added the same large image to all places of ck editor (info and result tab, event, chapters). Mapprio seems to look fine (https://meinberlin-dev.liqd.net/maptopicprio/2018-00190/) and topicprio (https://meinberlin-dev.liqd.net/topicprio/2021-00535/) as well. Can't think of other places with CK editor.

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer awesome testing thankyou! really helped :) will be fixed soon, sorry it's been a on off one.
