### ISSUE TITLE
Empty frame for ck editor image on prod

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#3447]
URL: https://mein.berlin.de/text/chapters/5072/?initialSlide=9
user: all
expected behaviour:
behaviour: empty frame is shown
important screensize:
device & browser:
Comment/Question: not true for all pictures added via ck editor, fine here: https://mein.berlin.de/projekte/jonny-k-aktivpark-online-beteiligung/

Screenshot?

**Comment by fuzzylogic2000** [comment]
It tries to load the image from the stage-media-server and is then blocked by our content security policy, which it should be.
@CarolingerSeilchenspringer Could you upload the picture to the prod server and try to add it from there? (It's here: https://meinberlin-media-stage.liqd.net/uploads/raumscript/2019/09/06/perspektive_grunraum-statt-autoverkehr_web.jpg)

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 ok, user error, will close this issue as the project ran up quite a while ago.
