### ISSUE TITLE
question: Can name of menu "feedback geben" be changed via wagtail?

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3448]
**URL:** https://meinberlin-dev.liqd.net/
**user:** any
**expected behaviour:** people use feedback form to give feedback
**behaviour:** people quite often write their comment on projects into this form, more work for support
**important screensize:**
**device & browser:** 
**Comment/Question:** I played a little bit around on dev with the wording and also managed to change the URL from /feedback to /kontakt. Can I via wagtail change the menu wording from "Feedback geben" to "Kontakt" or would that be a story? And what if we take it out at all and only link to feedback form from the help-page?

Screenshot?
<img width="208" alt="Bildschirmfoto 2021-02-26 um 16 18 23" src="https://user-images.githubusercontent.com/35491681/109318592-41b38b80-784e-11eb-97f9-733e1cc8eaa5.png">

**Comment by Rineee** [comment]
No, the wording for the link is not settable in wagtail, its in the code.

You could remove the link yourself by removing the page in wagtail Einstellungen -> Header pages -> Feedback Form Page. And then you could edit the help page and make a new entry that links to the feedback page.

**Comment by CarolingerSeilchenspringer** [comment]
@Rineee thanks, I will propose this to Senatskanzlei!
