### ISSUE TITLE
bplan map embed not correctly shown, map view missing

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3465]
**URL:** https://www.stadtentwicklung.berlin.de/planen/b-planverfahren/berlin/index.shtml
**user:** any
**expected behaviour:** I can see a map, switch from list to map view
**behaviour:** map and switch (Ansicht) are not displayed
**important screensize:**
**device & browser:** seems to only appear on big sur/apple, chrome only
**Comment/Question:** 

Screenshot?
<img width="928" alt="Bildschirmfoto 2021-03-05 um 10 49 29" src="https://user-images.githubusercontent.com/35491681/110099030-23dfac80-7da1-11eb-806a-68e74c2484f8.png">

**Comment by fuzzylogic2000** [comment]
Can you see the map itself without embed on that browser?

**Comment by CarolingerSeilchenspringer** [comment]
moved here: https://github.com/liqd/django_zbp/issues/324

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 will answer in other repo :-)
