### ISSUE TITLE
Animation for polls

### ISSUE THREAD

**Issue by damusp** [liqd/a4-meinberlin#347]
It would be really cool to have a build-up animation for the graph in our polls. 

A transition that builds up the bars from left to right would not just be pretty, it would also create a better sense for what's happening.

**Comment by xi** [comment]
In which cases should this be triggered? I imagine it would look nice the first and second time, but would become incredibly annoying after that.

**Comment by damusp** [comment]
I think it should be triggered every time the user votes or gets to see the preliminary results. 

Of course, it should not be distracting, much less annoying. I believe it can add a lot to the user experience without being consciously noticed.
