### ISSUE TITLE
stage: interactive event, livestream generated from Zoom does not show

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3478]
**URL:** https://meinberlin-stage.liqd.net/projekte/module/interaktive-veranstaltung-19/
**user:** any
**expected behaviour:** can see livestream in interactive event after setting up zoom livestream on youtube and entering sharelink into meinBerlin
**behaviour:** instead of livestream it shows the name of the livestream only
**important screensize:**
**device & browser:** bigsur, Chrome
**Comment/Question:** it did work with different livestreams (e.g. the one from deutsche welle) but not with the one we generated out of zoom

already talked about it with @phillimorland 

Screenshot?

**Comment by CarolingerSeilchenspringer** [comment]
I added this to the milestone but we actually need this to work on Friday (test event), latest Tuesday (real event). If too complicated we have to find a different solution for the event.

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer after too many checks on our CSP and different link variations I found it's actually a youtube issue, there are a few work around suggestions on there that can be tried: https://support.google.com/youtube/thread/44312561?hl=en
