### ISSUE TITLE
external projects: character limit for URL length?

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3491]
**URL:** any external project / Dashboard (e.g. https://meinberlin-dev.liqd.net/dashboard/projects/test-verlinkung/external/)
**user:** initiator of external project
**expected behaviour:** I can enter any URL
**behaviour:** my URL is been cut off
**important screensize:**
**device & browser:** 
**Comment/Question:** do we have a character limit in the URL field? following URL is cut off: https://www.berlin.de/ba-mitte/politik-und-verwaltung/aemter/strassen-und-gruenflaechenamt/planung-entwurf-neubau/staedtebauliche-ausgleichsmassnahme-fischerinsel-aufwertung-der-noerdlichen-freianlagen-940440.php

Screenshot?

**Comment by Rineee** [comment]
Oh yes, it seems like Django URLFields have a default max_length of 200 characters.. so we should change that! What length do you think would be sufficient? @CarolingerSeilchenspringer @fuzzylogic2000

**Comment by CarolingerSeilchenspringer** [comment]
@Rineee do we need to give a max length? Can't we just make it really long? I mean if it is not a URL it won't work, right? So we might as well say 1000. no? I will add to the milestone for next release.

**Comment by Rineee** [comment]
Yes, we need to give a max length, because it is a URLField is a CharField (you know that one now :wink:) and they need to have a max length specified. A workaround would be to make it a textfield, but I guess just limiting it to 1000 or maybe even 500 should do?

**Comment by CarolingerSeilchenspringer** [comment]
@Rineee yeah, let's take 500 and we should be fine. This was the first time that someone complained. Thanks!
