### ISSUE TITLE
testing 3784: translation for error message needs to be "Sie"

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3496]
**URL:** https://meinberlin-dev.liqd.net/budgeting/2021-00529/update/
**user:** logged in
**expected behaviour:** the error message when entering a wrong mail-address "siezt mich"
**behaviour:** it is not as friendly as it should be :-)
**important screensize:**
**device & browser:** 
**Comment/Question:** please change to "Bitte geben Sie eine gültige E-Mail-Adresse an."

Screenshot?

**Comment by Rineee** [comment]
@CarolingerSeilchenspringer Just a note, because I guess this is fine: this will then change for all e-mails fields.

**Comment by CarolingerSeilchenspringer** [comment]
@Rineee yes, should be "sie" all over platform. Thanks!
