### ISSUE TITLE
Explain what follow means

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-meinberlin#351]
It would be great if we could explain what following means with a short notice (maybe after clicking on the button?), something like this: ”You will be notified via email when new proposals are posted or when the project’s phase changes“.

![bildschirmfoto 2017-05-11 um 17 26 58](https://cloud.githubusercontent.com/assets/15341015/25991661/4fcd4dee-3704-11e7-8f99-eabab28091bd.png)

**Comment by rittermo** [comment]
Maybe you have an idea, @damusp ?

**Comment by vellip** [comment]
This could easily be done with a popover, like we have for the hover on timeline or on erroneous category fields in the dashboard.

**Comment by xi** [comment]
> hover on timeline or on erroneous category fields in the dashboard.

We have neither of these things. The popover in the timeline is shown on click, the error alert in input field is always shown. The reason for this is that hover only really works with a mouse, not with touch or keyboard.

**Comment by damusp** [comment]
Are we really sure an explenatory note is needed? 
If so, it should be visible **before** a user clicks on the button. 

Using popovers or tooltips would be an easy solution, but, as @xi said, not fit for people without cursors. 

How about putting a note in the user profile? It's the place where users find all projects they're following. ("Follow projects to get updates via mail. All projects you're following will appear in this list")

**Comment by damusp** [comment]
idea: follow can be explained like github's watch feature!

**Comment by damusp** [comment]
this is now a user story

**Comment by xi** [comment]
Fxied in https://github.com/liqd/adhocracy4/pull/164
