### ISSUE TITLE
question modul text commenting wording change

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3514]
**URL:** https://meinberlin-stage.liqd.net/text/chapters/1742/
**user:** any
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** this modul is often used to display spatial plannings (plans, maps, grafics etc.) If you work with chapters you have an "Inhaltsverzeichis" and the buttons "nächstes Kapitel" und "vorheriges Kapitel". Can those three fields be changed without touching A4 to make the wording more general (e.g. "Übersicht" and "vor", "zurück"?). How difficult (=quickly to implement) would it be?

<img width="941" alt="Bildschirmfoto 2021-03-25 um 11 10 40" src="https://user-images.githubusercontent.com/35491681/112456139-bea52880-8d5a-11eb-8448-e6f60fe00e72.png">

**Comment by Rineee** [comment]
@CarolingerSeilchenspringer The module doesnt come from A4 and thus the wording without touching A4. But we should keep it synchronized with the wording in the dashboard, where it says 'Inhaltsverzeichnis' and 'Kapitel bearbeiten' and I am not sure if 'Übersicht' would make sense there?

**Comment by CarolingerSeilchenspringer** [comment]
Thanks, @rine you are probably right. I think we have to find a different solution here. I was thinking about projects that mainly want to show Planungsentwürfe. But maybe a new module (e.g. plan commenting) would be better.
