### ISSUE TITLE
Login: Login button should be first

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-meinberlin#352]
Currently in the login form, the password reset button comes before the login button. This should be changed, so that the login button comes first. I also think, we should maybe de-emphasize the password reset somehow (maybe make it a link in a small text underneath?).

![bildschirmfoto 2017-05-12 um 11 14 26](https://cloud.githubusercontent.com/assets/15341015/25991794/dd8d098a-3704-11e7-804d-154e958a328d.png)

**Comment by xi** [comment]
duplicate of #124
