### ISSUE TITLE
title not centered on landing page

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3547]
**URL:** https://mein.berlin.de/
**user:** any
**expected behaviour:** title and wording centered
**behaviour:** they are left alighned
**important screensize:** 
**device & browser:** testet on chrome and firefox
**Comment/Question:** is that something I can change via wagtail (couldn't find it) or an issue?

Screenshot?
<img width="1208" alt="Bildschirmfoto 2021-04-16 um 10 33 25" src="https://user-images.githubusercontent.com/35491681/114996948-a7f87a00-9e9f-11eb-9a6c-9a88a7898091.png">

**Comment by phillimorland** [comment]
oooo weird, this shouldn't happen and no you can't align text in wagtail, although that would be cool, so yes it is an issue

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland ok I will then put it into the milestone and prioritize rather high within milestone.
