### ISSUE TITLE
Newly created project lost after saving

### ISSUE THREAD

**Issue by rukala** [liqd/a4-meinberlin#358]
After creating a new priotisation of topics process and saving the "information" tab the project is lost when I navigate back to the dashboard

**Comment by vellip** [comment]
You cannot just save one part of the form, you have to actually fill out all required fields for a project to be generated.

**Comment by rukala** [comment]
How is this issue closed? If it's technically not possible we need to solve this through the design - e.g. excluding navigation items that lead back to overview, or including warning messages (cf. Advocate Europe)

**Comment by vellip** [comment]
@rukala do you think this is necessary to solve **before** the planned redesign of the dashboard? Because the redesign would make this issue obsolete.

**Comment by rukala** [comment]
okay :)
