### ISSUE TITLE
dev: project overview: search function, topic/district filter broken

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3583]
**URL:** https://meinberlin-dev.liqd.net/projekte/
**user:** any
**expected behaviour:** if I use the filter, the list reacts according to my search results.
**behaviour:** the search (project titles) and the topic/district filter do not react properly. Eg if I have 0 search results, all projects are being shown. Only filters that are respected are status and with/out participation. BUT: if I turn off the map, the list is correct, also when turning map on again.
**important screensize:**
**device & browser:** 
**Comment/Question:** dev only, prod is ok, so maybe it has to do with the changed map toggle?

Screenshot?
<img width="811" alt="Bildschirmfoto 2021-04-30 um 14 53 52" src="https://user-images.githubusercontent.com/35491681/116697780-e3c53080-a9c3-11eb-86d9-13cddcacb3d6.png">

**Comment by phillimorland** [comment]
I don't think this is from the filter, I think it's the updating we did, will investigate
