### ISSUE TITLE
newsletter form in disorder

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3584]
**URL:** https://meinberlin-dev.liqd.net/dashboard/newsletters/caros-testorga/create/
**user:** initiator
**expected behaviour:** 
**behaviour:** the newsletter form is in disorder, chosing option for receivers is above content field (should be below)
**important screensize:**
**device & browser:** 
**Comment/Question:** firefox (tested on big sur and windows), edge (tested on windows), chrome (windows only, fine on mac), safari (catalina only, big sur is fine); newsletter can still be sent

Screenshot?

<img width="955" alt="Bildschirmfoto 2021-04-30 um 15 25 27" src="https://user-images.githubusercontent.com/35491681/116702451-64d2f680-a9c9-11eb-8e5c-bf9ea4387b20.png">

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer when you say 'content field' do you mean subject field (Betreff)?

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer i've been having trouble tracking this down, just to check, the effected browsers should be: 
firefox (big sur and windows), 
edge (windows), 
chrome (windows), 
safari (catalina only)

I have tested the following and cannot replicate:
firefox (big sur)
safari (catalina)

can you possible retest and let me know?

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland I can no longer reproduce either so will close.
