### ISSUE TITLE
Selecting "today" in date-picker not working

### ISSUE THREAD

**Issue by rukala** [liqd/a4-meinberlin#359]
When I select "today" in date-picker, 01.01.2017 is chosen. I know this might be due to the fact that the date-picker is not ready yet, though still wanted to mention the issues. :)

**Comment by vellip** [comment]
This is working as intended, clicking `today` makes you jump to the current date, but it does not select it. If this is confusing we can only remove the `today` button completely.

**Comment by xi** [comment]
@rukala which of the options outlines by @vellip would you prefer?

**Comment by rukala** [comment]
@xi let's keep it as it is
