### ISSUE TITLE
Text commenting Issue

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#3599]
**URL:** https://meinberlin-dev.liqd.net/projekte/textkommentierung-2/
**user:** *initiator*
**important screensize:** *Mobile*
**device & browser:** *Safari Version 14.0.3 (16610.4.3.1.7)*
**Comment/Question:** *I just found some stuff that could be improved on Mobile, I think it's already like that for a while, but something to keep in mind for the next sprint.*

![IMG_1492](https://user-images.githubusercontent.com/59610786/117309544-cc35ee00-ae82-11eb-9e5a-5154ea10bd08.PNG)

1 – The menu seems a bit off, the Bearbeiten button could be on top of everything to have a clearer division between both fields. 

2 – These two buttons are to close to each other, I would either increase the distance or try to leave them in the same line, It can be hard due to the text length, but maybe next time we can even find a different solution for that next time. 

Here is my proposal: 
[m - text-commenting.pdf](https://github.com/liqd/a4-meinberlin/files/6435033/m.-.text-commenting.pdf)

**Comment by CarolingerSeilchenspringer** [comment]
@mcastro-lqd thanks for pointing that out again. This really has been there for a while but we shouldn't forget about it. The solutions you have are rather a story, no? @fuzzylogic2000 ?

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer Yes, this could be a small story. Or we do it when we touch it anyway. 
1) should be fixed for all projects, though.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 @mcastro-lqd I will make a story out of #1 . For #2 we may want to touch these buttons anyways as I thought the module would be more flexible to be used e.g. to make people comment on plans and planning variants with little wording changes. e.g. if we call the buttons "vor/zurück" and call the Inhaltsverzeichnis "Übersicht" the module would work much better for Projects like this one: https://mein.berlin.de/projekte/mauerpark/?initialSlide=3. What do you think? Or should we rather develop a new module for these kinds of projects? text commenting is rarely used on mB for text commenting but rather for presenting of plans/ideas of administration to be commented upon.

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer Yes, I guess, rewording would fix that! A new module that does the same does not make a lot of sense to me and with "Übersicht" and "vor/zurück" it could still be used as text commenting. I think if it's only these three wording changes, we can do it in this issue. If it's a bigger documenting-rework thing, we should add a story.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 thanks for giving your perception on this. A new module could have more, could have a different completely different ux/design. I think this needs to be discussed with client. I will close this issue and make a story out of it.

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer Thank you! But then also include adapting the mobile styling for this module in that story, so we don't forget. :)

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 done :-)
