### ISSUE TITLE
Moderators not invited after adding them to project

### ISSUE THREAD

**Issue by rukala** [liqd/a4-meinberlin#360]
When I want to add moderators to my project I can add their email address in the dashboard. Though if the moderator is not registered yet on the platform I get an error message:
![bildschirmfoto 2017-05-12 um 13 50 24](https://cloud.githubusercontent.com/assets/11075214/25996936/149156d8-371a-11e7-978c-83aca09e6071.png)

**Comment by vellip** [comment]
We talked about this internally and said this was not needed yet.

**Comment by vellip** [comment]
replaced by https://tree.taiga.io/project/ggr-meinberlinteam/us/1009?no-milestone=1
