### ISSUE TITLE
should form fields with errors be marked?

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#3601]
**URL:** 
**user:** 
**expected behaviour:** I can see right away where the error is
**behaviour:** I might have to scroll down quite a bit
**important screensize:**
**device & browser:** 
**Comment/Question:** Maybe this can go into a story also adding an error-alert to the top? Or is it ok, the way it currently is?
Analogous to https://github.com/liqd/adhocracy-plus/issues/38

Screenshot?
![Screenshot from 2021-05-07 12-01-35](https://user-images.githubusercontent.com/8178179/117434053-79b10c00-af2c-11eb-8b0d-60966b6a2a24.png)

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer  I have seen a story handling this. So, we can close this issue?

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 yes, I closed it, thanks!
