### ISSUE TITLE
interactive event: association should either be required or filter should be hidden

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#3603]
**URL:** 
**user:** 
**expected behaviour:**  If no association is added in the dashboard, the list to filter for is empty.
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** We could either make the association required in the dashboard or hide the filter when it's not given. 

Like https://github.com/liqd/adhocracy-plus/issues/1022, where we solved it with making the affiliation required in the dashboard. Can we also do that here @CarolingerSeilchenspringer ?

Screenshot?

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 Daniel was in favour of NOT making association required. I will write a story for hiding the filter.
