### ISSUE TITLE
do duplicated projects keep the group?

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#3613]
**URL:** 
**user:** 
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** I am currently working on https://github.com/liqd/adhocracy-plus/issues/1063. This is in a4, so it will also be fixed here. :) But while doing so, I wondered if a copied project keeps the group, meaning if the same group is allowed to work on it. Did you already check that @CarolingerSeilchenspringer ?

Screenshot?

**Comment by fuzzylogic2000** [comment]
Yes, they do! All fine!

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 now I was also checking this parallel to you :-) Found the same: they are copied as they should.
