### ISSUE TITLE
add handling for published modules in ModuleDeleteView

### ISSUE THREAD

**Issue by Rineee** [liqd/a4-meinberlin#3614]
**URL:** 
**user:** 
**expected behaviour:** check if module is draft before deletion, like its done in Aplus [here](https://github.com/liqd/adhocracy-plus/blob/3d521b9307dd415c76cbc6fcd0ee8fdb7a7e3de3/apps/dashboard/views.py#L192-L197)
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by sabinammm** [comment]
Yes, this has been done here https://github.com/liqd/a4-meinberlin/commit/592fc010878856d069b8aed5a7d47840eae141e3#diff-869829b87ac18983112d8989747a5d7c3134dbd1ee22a2596c3f3f824395f41c
