### ISSUE TITLE
Commenting fails

### ISSUE THREAD

**Issue by rukala** [liqd/a4-meinberlin#362]
I can't leave comments under my priotisation of topics process although the participation phase already started: https://meinberlin-dev.liqd.net/topicprio/demokratie/

**Comment by rukala** [comment]
This might be due to the fact that the text I pasted was too big - if so there should be an error message issued.

**Comment by kleingeist** [comment]
the a4 core component is missing error handling for comments. i did open an issue there. 
@rukala have you been able to submit smaller comments? or has it been a general problem with topicprio

**Comment by xi** [comment]
creating short comments works fine, so this is really a duplicated of liqd/adhocracy4#95.
