### ISSUE TITLE
project overview: pins inactive

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3633]
**URL:** mein.berlin.de/projekte
**user:** any
**expected behaviour:** I can click the project pins on the map
**behaviour:** I can only click the pin cluster, the (white) project pin does not react.
**important screensize:**
**device & browser:** Mac Big Sur/ Safari 14.1, Catalina/ Safari 13.1 (ios works)
**Comment/Question:** 

Screenshot?

**Comment by phillimorland** [comment]
NOTE: Big sur issue

**Comment by phillimorland** [comment]
@khamui I am having replicating this issue in order to fix it, maybe you can take a look?

**Comment by khamui** [comment]
Issue should be fixed in a4 (maps are used from there):
https://github.com/liqd/adhocracy4/pull/781
