### ISSUE TITLE
Remove start/end times from project detail view

### ISSUE THREAD

**Issue by rukala** [liqd/a4-meinberlin#364]
I think it might be better to not include the exact start and end times in the project detail views - it's enough when this info is shown in the time-line, when clicking on the participation phases.

**Comment by vellip** [comment]
There are cases where there is no timeline (projects with one phase only), so this information would then be missing.

**Comment by rukala** [comment]
Okay, would it be possible to make time optional? ;) sorry I know PM/PO nightmare questions

**Comment by vellip** [comment]
As discussed, we can leave the time in for now since it's possibly the only place where it's shown (depending on the number of phases), but keep it in mind.
