### ISSUE TITLE
deeplinks info-tab/result-tab don't work

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3645]
**URL:** https://mein.berlin.de/projekte/umgestaltung-der-dorpfeldstrasse-vorplanung/#tabpanel-project-929-result
**user:** any
**expected behaviour:** show result-tab
**behaviour:** shows participation-tab
**important screensize:**
**device & browser:** 
**Comment/Question:** that hint came from a user. I never worked with those deeplinks. Is it supposed to be this way? Do we want to change it? I mean there is a reason that we always show the participation tab first. Any thoughts on that?

**Comment by fuzzylogic2000** [comment]
It also annoys me that we do not show the tab that is requested. But I think there was no easy fix. 
So, this should be a story? Or at least please define how important it is and if we should spent time on fixing it.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 what do we need these tab links for? What would change if we'd fix it? So what would be the "why" in the story?

**Comment by fuzzylogic2000** [comment]
You could link to or bookmark the info and result tabs directly instead of always having the participation tab open when accessing the project site. But yeah, I guess that is not really needed.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 thanks! I will talk with Skzl about it. Some initiators wish to lead users to info-tab first, this could be an option.

**Comment by fuzzylogic2000** [comment]
But only if they use links to get the users there. To do that on mB, we could lead people to the info tab prior to project start and the result tab afterwards. But that would be for all projects, then.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 yes, this is also something we have been talking about, especially for the result. Could this be in one story?

**Comment by fuzzylogic2000** [comment]
yes, we can put it into one and if need be just split it.
