### ISSUE TITLE
Feedback button glitch in Chrome

### ISSUE THREAD

**Issue by rukala** [liqd/a4-meinberlin#365]
In Chrome the feedback button seems to create small glitches:
![bildschirmfoto 2017-05-12 um 14 04 54](https://cloud.githubusercontent.com/assets/11075214/25997381/0e11a446-371c-11e7-9500-7501e847e73b.png)

**Comment by xi** [comment]
Looks like a chrome/OS bug. I don't think we can do anything about it. @vellip

**Comment by vellip** [comment]
I don't think this ever occurred for me.

**Comment by kleingeist** [comment]
i can reproduce the error with Chrome 58.0.3029.110
the error does not occur if the `font-weight: bold` attribute of the button is removed or explicitely set to "regular" on the element. this is definitely a chrome bug
