### ISSUE TITLE
dev/ dashboard: entering district for project overview broken

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3655]
**URL:** https://meinberlin-dev.liqd.net/dashboard/projects/beteiligungshaushalt/point/
**user:** initiator
**expected behaviour:** 
**behaviour:** filter works but doesn't look as it shold
**important screensize:**
**device & browser:** tested on bigsur both chrome and firefox
**Comment/Question:** 

Screenshot?
![Bildschirmfoto 2021-06-22 um 13 16 19](https://user-images.githubusercontent.com/35491681/122915465-0fc5b800-d35c-11eb-997e-1c2b245ea08a.png)

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer can you add a link to a stage project where it does look like it should? it really helps to quickly fix issues when we don't have to create a project or try to find one for comparison, cheers!

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland sure, this is what it should look like (stage):https://meinberlin-stage.liqd.net/dashboard/projects/big-multimodule-test-project/point/

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer danke!
