### ISSUE TITLE
dev/dashboard: category icon dropdown doesn't work

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3656]
**URL:** https://meinberlin-dev.liqd.net/dashboard/modules/burgerinnenhaushalt-2-phase-2-2/categories/
**user:** initiator
**expected behaviour:** can chose different icons for my categories
**behaviour:** dropdown doesn't open
**important screensize:**
**device & browser:** tested on big sur chrome and firefox
**Comment/Question:** 

Screenshot?

**Comment by phillimorland** [comment]
fixed with a4 update seemingly
