### ISSUE TITLE
account settings styling broken

### ISSUE THREAD

**Issue by Swetlana1** [liqd/a4-meinberlin#366]
Under account settings: navigation styling is broken, it's in red instead of white fields. please correct it.

**Comment by xi** [comment]
Can you please add a screenshot?

**Comment by kleingeist** [comment]
![screenshot-account-links](https://cloud.githubusercontent.com/assets/167407/26047608/2764f7f6-3954-11e7-9073-0e439ac66f80.png)
![screenshot-dashboard-links](https://cloud.githubusercontent.com/assets/167407/26047609/2768f64e-3954-11e7-8b38-ce77fa713794.png)

**Comment by vellip** [comment]
Related to #321
