### ISSUE TITLE
dev: account dropdown (upper right corner) does not work when inside a project in dashboard

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3661]
**URL:** https://meinberlin-dev.liqd.net/dashboard/projects/test-poll-merge-running-poll-with-user-content/basic/
**user:** initiator
**expected behaviour:** I can use the dropdown anywhere
**behaviour:** it doesn't work if I am in dashboard inside a project. It does work for plans, b-plans, external projects etc.
**important screensize:**
**device & browser:** mac big sur, chrome and firefox; also tested windows 10 firefox/chrome with same result
**Comment/Question:** 

Screenshot?

**Comment by Rineee** [comment]
also fixed by https://github.com/liqd/a4-meinberlin/pull/3660
