### ISSUE TITLE
Initiator dashboard: too many notification

### ISSUE THREAD

**Issue by Swetlana1** [liqd/a4-meinberlin#367]
I get notifications of any projects of my organization, even it's not my project. I'm not sure if I want to see all changes in all projects of my organization. I think it will be too much.

**Comment by Janaba** [comment]
@Swetlana1 I agree. 

@2e2a can we generally change the settings, so initiators only get notifications from their own projects?

**Comment by xi** [comment]
Proposal on how to improve the situation:

- Only autosubscribe the *creator* of a project to that project.
- Subscribe *initiators* only to "project created" events.

**Comment by kleingeist** [comment]
Currently there is no "project created" action/event and the notifications app assumes every action is related to content inside a project. Thus it is not simple to introduce the new functionality. 
The "project created" notification should be handled when we start to rework the actions/notifications for the activity stream.

Still i would remove the autofollow function for organisation initiators. The creator of a project is not directly saved to the database, but she is added as a moderator and thus follows the project automatically

**Comment by kleingeist** [comment]
i also created a user story for the "project created" issue https://tree.taiga.io/project/ggr-meinberlinteam/us/1011?no-milestone=1
