### ISSUE TITLE
testing 4293: phases in new poll module not translated

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3678]
**URL:** https://meinberlin-dev.liqd.net/dashboard/modules/umfrage-39/phases/
**user:** initiator
**expected behaviour:** german
**behaviour:** english
**important screensize:**
**device & browser:** 
**Comment/Question:** the pre-filled text in phases form is still in english

Screenshot?
<img width="363" alt="Bildschirmfoto 2021-06-30 um 15 36 54" src="https://user-images.githubusercontent.com/35491681/123969958-00c4b280-d9b9-11eb-9911-76f59049d006.png">

**Comment by phillimorland** [comment]
translations is still a 'todo' task and so have not been added will close for now
