### ISSUE TITLE
testing 4293: change wording for template

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3680]
**URL:** module template in dashboard
**user:** initiator
**expected behaviour:** correct template description
**behaviour:** needs to be adapted
**important screensize:**
**device & browser:** 
**Comment/Question:** 

change wording from:
Die Teilnehmenden können auf eine oder mehrere Fragen mit vordefinierten Antwortmöglichkeiten antworten und die Umfrage kommentieren.

to 
Die Teilnehmenden können auf offene und Multiple-Choice-Fragen antworten und die Umfrage kommentieren.

Participants can answer to open and multiple choice questions and comment on the poll.

**Comment by phillimorland** [comment]
better english i think would be:
'Participants can answer open and multiple choice questions and can comment on the poll'

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland great, thanks!
