### ISSUE TITLE
testing 4293: wording changes/ translations in poll form

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3681]
**URL:** https://meinberlin-dev.liqd.net/dashboard/modules/umfrage-39/poll/
**user:** initiator

so here is the wording for the poll form in dashboard (sorry for being late on that!)

Nutzer*innen können für mehrere Antworten abstimmen. -> change to: Participants can vote for more than one option / Teilnehmer*innen können mehrere Antworten auswählen

Users can answer openly. -> change to: Participants can add an additional text answer (other) / Teilnehmer*innen können eine zusätzliche Textantwort geben (sonstiges)

Other -> change to: "other" and translate to "sonstiges" 

add helptext -> change to: explanation / Erläuterung (without "add", the + makes this quite clear I would say)

helptext -> change to: Erläuterung

predifined answers -> change to: Multiple-Choice-Frage/ multiple choice question

open answers -> change to: offene Frage / open question

**Comment by Rineee** [comment]
@CarolingerSeilchenspringer 
Sure about predifined answers -> change to: Multiple-Choice-Frage/ multiple choice question? Because it also includes single choice questions...

**Comment by CarolingerSeilchenspringer** [comment]
@Rineee thanks for asking! I was unsure about it but already discussed this with @phillimorland on Zeplin and also with PMs. Seems that in German we associate Multiple-Choice with "you can choose more than 1 option" while in English it originally means that you have several answers you can choose from (the term single choice is not even used in English). Looking at a big survey tool that also in German uses the English term Multiple-Choice for both we decided to also use the English term in German, so yes, please go for it. If we get negative feedback from users we can still change it again.

**Comment by Rineee** [comment]
@CarolingerSeilchenspringer Thanks for the explanation, that makes sense! So it was my very German understanding of it :)

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer @hello-kathi Sorry, I only saw this issue after I went through all of zeplin. Could you please check if the strings on zeplin are the same strings as here and then close this issue? So, that we have only one place to look. Or you say on zeplin that it's here for the respective comment and resolve the comment on zeplin. Or I doooon't know how to do it best. Maybe first option. Check that strings are up to date on zeplin and then close?!
