### ISSUE TITLE
delete poll app (two deployments after release v2107)

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#3687]
**URL:** 
**user:** 
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** We have deleted the poll, models and moved lots of code to a4. We also dropped the poll tables. If we do not use it anymore, we should delete the poll app. We might still either want to keep the export (and by that keep the app) or move it to another app.

Connected to #3686 (needs to be done after)

Screenshot?

**Comment by phillimorland** [comment]
@fuzzylogic2000 has this been completed?

**Comment by fuzzylogic2000** [comment]
No, it's still there. I guess, we can look into deleting the migrations and maybe moving the other stuff? Or do we want to keep the overwrites in it's own app, where we can easily find it? @Rineee What do you think?

**Comment by Rineee** [comment]
@fuzzylogic2000 I would also prefer to delete it and move to the other stuff.. next question would be where to :sweat_smile:
