### ISSUE TITLE
testing 4293: missing alert for helptext too long

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3688]
**URL:** https://meinberlin-dev.liqd.net/dashboard/modules/umfrage-39/poll/
**user:** initiator
**expected behaviour:** I get a warning if my helptext is too long
**behaviour:** I get a notification at the end of the page that poll couln't be saved
**important screensize:**
**device & browser:** 
**Comment/Question:** may be related to #3689 

Screenshot?

**Comment by mcastro-lqd** [comment]
@CarolingerSeilchenspringer That's because of the countdown missing, right?

**Comment by CarolingerSeilchenspringer** [comment]
@mcastro-lqd we don't have countdowns for characters in meinBerlin, so that shouldn't be the reason. Also other fields (e.g. question) have it.

**Comment by Rineee** [comment]
fixed in https://github.com/liqd/adhocracy4/pull/771
