### ISSUE TITLE
testing 4293: wrong error alert when question too long

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3689]
**URL:** https://meinberlin-dev.liqd.net/dashboard/modules/umfrage-39/poll/
**user:** initiator
**expected behaviour:** if my question is too long I only get an alert for my too long question
**behaviour:** in addition I get an alert for my helptext, even if it is not too long
**important screensize:**
**device & browser:** 
**Comment/Question:** may be related to issue #3688 

![Bildschirmfoto 2021-07-05 um 09 33 50](https://user-images.githubusercontent.com/35491681/124437165-14846600-dd77-11eb-8f9a-2dab5635728a.png)

**Comment by Rineee** [comment]
fixed in https://github.com/liqd/adhocracy4/pull/771
