### ISSUE TITLE
testing 4293: can't edit polls somebody else created even if I have the rights

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3690]
**URL:** https://meinberlin-dev.liqd.net/dashboard/modules/umfrage-24-4/poll/
**user:** group member
**expected behaviour:** I can edit polls somebody else created if I have the right to do so
**behaviour:** cannot save, getting an red altert
**important screensize:**
**device & browser:** 
 **Comment/Question:** also true for new polls whose rights have been given to me. for polls I started myself it is fine.

![Bildschirmfoto 2021-07-05 um 10 32 14](https://user-images.githubusercontent.com/35491681/124444710-2bc75180-dd7f-11eb-946b-78cc99c9c975.png)

Screenshot?

**Comment by CarolingerSeilchenspringer** [comment]
I think this is also true for initiators that cannot edit polls that have been created by other, only admin can change all polls, no matter who created them

**Comment by fuzzylogic2000** [comment]
> I think this is also true for initiators and moderators that cannot edit polls that have been created by others, only admin can change all polls, no matter who created them

This does work for moderators and initiators (at least when I tested it, could you check again?)
That is also why a group member that added the poll can edit it: she becomes a moderator automatically. But for group members, you are right! Good catch! But it should never have worked and probably was there from when we added the groups. I will also check the documents!

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 I will check again. But what should never have worked? So far we didn't have problems with groups, so you can easily give a group the right for a project they haven't created via django. Has been working fine so far.

**Comment by fuzzylogic2000** [comment]
I think a group member was never able to change the poll. (Only if they also were moderators, which was likely to happen, they could.)

**Comment by CarolingerSeilchenspringer** [comment]
was that only for polls? nobody ever noticed :-)

**Comment by CarolingerSeilchenspringer** [comment]
but you are right, I checked again as moderator and in one project I can change one poll but not the other, so there is another problem I cannot find. Can you check https://meinberlin-dev.liqd.net/dashboard/modules/umfrage-43/poll/, e.g. as moderator I cannot save the (second) poll.

**Comment by fuzzylogic2000** [comment]
I can! But you coudln't because of the other problem we currently have: you cannot update any polls that have open choices. :grimacing: @Rineee is currently fixing that.
