### ISSUE TITLE
in multi module project, link of comment on poll links to project page instead of detail page

### ISSUE THREAD

**Issue by Rineee** [liqd/a4-meinberlin#3692]
**URL:** https://meinberlin-stage.liqd.net/projekte/testprojekt-4/?comment=1979 
**user:** 
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** It seems to work for other modules, eg https://meinberlin-stage.liqd.net/ideas/2020-01272/?comment=1982

Screenshot?

**Comment by CarolingerSeilchenspringer** [comment]
@Rineee this is an important bug, or not? Should I put it into this milestone or can it wait?

**Comment by Rineee** [comment]
@CarolingerSeilchenspringer I think it can wait and doesnt have to be in this milestone.

**Comment by CarolingerSeilchenspringer** [comment]
@Rineee ok, will move it then.

**Comment by CarolingerSeilchenspringer** [comment]
@Rineee I don't really understand this issue but it has to do with polls. Should we fix it in this milestone?

**Comment by Rineee** [comment]
@CarolingerSeilchenspringer The issue is that the link above should link to a comment (you can also see that in the url at the end), but links to the project overview instead. I just did 2 reports on comments in the poll (you should have gotten an email since you are moderator :)), and the links inside the e-mails link to project overview. Does that make it clearer?

**Comment by CarolingerSeilchenspringer** [comment]
@Rineee sorry for my late answers. Now I get it and yes, that should be fixed soon as it makes moderation a lot easier.
