### ISSUE TITLE
testing 4295: order of question not according to their number

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3699]
**URL:** export of project https://meinberlin-dev.liqd.net/dashboard/modules/umfrage-11/poll/
**user:** admin
**expected behaviour:** the order of my question is according to their number
**behaviour:** Q39, Q41, Q40
**important screensize:**
**device & browser:** 
**Comment/Question:** can we change the order?

Screenshot?

**Comment by CarolingerSeilchenspringer** [comment]
are the numbers given according to creation, so first question on platform is q1, then q2 and so on? They seem to be rather random now.

**Comment by Rineee** [comment]
@CarolingerSeilchenspringer They are ordered by single choice questions first, multiple choice second and open questions last as it was in the example.. is that wrong? Within that they are ordered by their id.

**Comment by CarolingerSeilchenspringer** [comment]
@Rineee yeah, that was just the example. Best would be ordered as they are in dashboard. But that can easily be changed. So if that is not possible I would order them according to their number, because this probably in many cases is the order in dashboard. Does that make sense?

**Comment by Rineee** [comment]
@CarolingerSeilchenspringer Ok, I see. Would have been good to point that out, that its only in the example and not meant to be like that for the real export. Since we didnt have any acceptance criteria for the ordering, I was following the example.. but well, it is changed now!
