### ISSUE TITLE
#4293 Mobile editing isn't working

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#3702]
**URL:** https://meinberlin-dev.liqd.net/projekte/poll/
**user:** *initiators*
**expected behaviour:** *I expect that initiatiors can edit their polls on Mobile*
**behaviour:** *Every-time I try to edit, it says it can't be saved*
**important screensize:** *Mobile*
**device & browser:** *Safari*

![IMG_3767](https://user-images.githubusercontent.com/59610786/124585967-2557d900-de56-11eb-9933-0c8661d67032.jpg)

**Comment by fuzzylogic2000** [comment]
This might be the problem with saving the questions with other options again, we had yesterday. So, if you had a poll with a question that had an other option, that poll couldn't be saved anymore. Could you please try again today and see if it's fixed? :crossed_fingers:

**Comment by fuzzylogic2000** [comment]
@mcastro-lqd Sorry, didn't tag you! Is it already fixed with the other bug?

**Comment by mcastro-lqd** [comment]
@fuzzylogic2000 Its working now! Thanks :)
