### ISSUE TITLE
#4293 Character Count

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#3704]
**URL:** https://meinberlin-dev.liqd.net/dashboard/modules/umfrage-4/poll/
**user:** *initiator*
**behaviour:** *Im adding a 232 characters question but it doesn't save cause it should be maximum 255*
**important screensize:** *both*
**device & browser:** *Safari*
**Comment/Question:** 

![Screenshot 2021-07-06 at 12 41 33](https://user-images.githubusercontent.com/59610786/124587255-b54a5280-de57-11eb-9cda-4dfecc268e23.png)

![Screenshot 2021-07-06 at 12 41 23](https://user-images.githubusercontent.com/59610786/124587261-b7acac80-de57-11eb-8d98-dd895d2704b7.png)

**Comment by fuzzylogic2000** [comment]
@mcastro-lqd I think, it also counts the spaces, which should be alright?

**Comment by goapunk** [comment]
@fuzzylogic2000 unless there are trailing whitespaces or something the lorem ipsum part is only 231 chars including whitespaces :) I was able to enter a 253 long string, so maybe it's a safari issue?

**Comment by fuzzylogic2000** [comment]
Ahh, that's a pity, that the explaining it away didn't work. :p

**Comment by khamui** [comment]
@mcastro-lqd i could not replicate this issue (chrome and safari). Up to 255 chars (including whitespaces) is savable in both browsers. 256 (including whitespaces) will raise that validation error.

Any chance in your test case you have 231 chars plus 35 spaces which leads to a total num of chars of 266 (including whitespaces)?

**Comment by mcastro-lqd** [comment]
@fuzzylogic2000 @khamui Ahh, true my bad. Sorry for the inconvenience

**Comment by fuzzylogic2000** [comment]
Haha, cool, I am just very relieved!
