### ISSUE TITLE
test 4294: show result page when phase is over

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3735]
**URL:** https://meinberlin-dev.liqd.net/projekte/umfrage-2/
**user:** any
**expected behaviour:** when phase is over I see result page
**behaviour:** I can change still participate but not save
**important screensize:**
**device & browser:** 
**Comment/Question:** 

![Bildschirmfoto 2021-07-14 um 09 31 03](https://user-images.githubusercontent.com/35491681/125584552-70446ee2-13de-4996-804f-f7c76df5b9d0.png)

**Comment by fuzzylogic2000** [comment]
will be fixed with a4 update
