### ISSUE TITLE
test 4294: what to show before phase starts?

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3736]
**URL:** https://meinberlin-dev.liqd.net/projekte/test-poll-merge-future-poll-without-content/
**user:** any
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** what do we show before a phase starts? On stage we currently show result page (https://meinberlin-stage.liqd.net/projekte/poll-test/). On dev we currently show questions that are editable but I cannot save the form. As we haven't considered this during in the concept, what could be a good and simple solution? Should we go back to result page as we did before? Or not show form at all? Or make form inactive? Or write a short info sentence "poll will be shown as soon as phase starts", something like that? for other modules we usually show the map or the filters, for text commenting also the document. So showing the inactive form would be the most consistent.

Screenshot?
![Bildschirmfoto 2021-07-14 um 11 08 26](https://user-images.githubusercontent.com/35491681/125595724-058d2f2c-ef6a-4274-a02d-933bee42844e.png)

**Comment by CarolingerSeilchenspringer** [comment]
just realising that we show inactive form for unregistered users. So that may be the best option to also show before phase?

**Comment by fuzzylogic2000** [comment]
The problem here is, that currently in the poll, we do not know if we are before or after a phase, we only know if the phase is running or not. So, treating it different before the phase starts would be another (small) story, I think. 
The easiest option here would be to show the results-page like after the phase, I would say?
(We also had it for a while, that you could only look at the poll after the phase started, but as that means a 403 when it hasn't yet, we removed that. Didn't work like in the other projects and especially not with the multi modules.)
So, we will show the (still empty) results before phase start?

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 yes, I prefere showing result page then, that's how it currently is with the old poll. I will mark a small story for it.

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer For this and issue #3735: When the results page is shown, should there be the link "Zur Umfrage", when the poll is over or before the poll? Would be easier without showing the link.

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer No, actually, that is not true! It's the same level of easy. Just need to know.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 would the link "zur Umfrage" lead me to the active form without a save-button? this is the form I don't like but on the other hand the helptexts of the questions are not shown on result page (which is good) but maybe - if you want to understand better - you may want to check them again. So i thought at least for after the phase it would be good to have the option to go back. But a clickable form is not what we need outside the phase. So if this leads me to a clickable form I would do it without the link.
