### ISSUE TITLE
testing 4294: wrong error

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3737]
**URL:** https://meinberlin-dev.liqd.net/projekte/test-poll-merge-running-poll-with-user-content/
**user:** registered
**expected behaviour:** I can change my mind if answering a question
**behaviour:** if I put wording into "sonstiges", save, change to another answer, save the other answer or not (no difference), go back to "sonstige" my text is still there, but if I hit save I get the error below. I can get around by changing the text.
**important screensize:**
**device & browser:** 
**Comment/Question:** rather an edge case but still not correct. Can we ignore it?

Screenshot?
![Bildschirmfoto 2021-07-14 um 11 30 40](https://user-images.githubusercontent.com/35491681/125599076-b3d1fa8c-98a8-419a-bc88-6a0e189d9dab.png)

**Comment by khamui** [comment]
@CarolingerSeilchenspringer i was working on that part. IMO we should fix it, i don't think its an edge case. Will have a look and fix it.

**Comment by CarolingerSeilchenspringer** [comment]
@khamui thanks :-)
