### ISSUE TITLE
make captcha non sexist

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3743]
**URL:** captcha registration
**user:** any
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** someone on twitter pointed at our captcha. How difficult is it to take out the gender-related questions?

![Bildschirmfoto 2021-07-14 um 15 32 05](https://user-images.githubusercontent.com/35491681/125630783-4f04faac-7c56-4cf9-9f5c-2871dcda0702.png)

Screenshot?

**Comment by fuzzylogic2000** [comment]
@goapunk This is really easy, right? Can you do it? :)

**Comment by goapunk** [comment]
I can have a look, yes

**Comment by phillimorland** [comment]
@goapunk this is now fixed right?

**Comment by goapunk** [comment]
@phillimorland yup, this is fixed and deployed
