### ISSUE TITLE
dashboard: button order and missing preview button

### ISSUE THREAD

**Issue by Swetlana1** [liqd/a4-meinberlin#375]
Please change the order ob buttons in project overview, because is more logical.

1. bearbeiten
2. management
3. Vorschau
4. publish
5. moderators

**Comment by 2e2a** [comment]
`moderators` and `management` should be the end, as they are optional.

We do not have a "preview" button, do we need one?

**Comment by xi** [comment]
> We do not have a "preview" button, do we need one?

According to @damusp, "preview" is simply meant  to be a link to the project detail. This link is currently on the title. If we add the preview button, the title should not be a link anymore (so not interactive at all).

However, @damusp also wants there to be 3 buttons at max. It is not clear in the current situation which one is more important: Having the preview button or minimizing the number of buttons.

**Comment by damusp** [comment]
In my opinion currently it would be better having the preview button (that indeed simply links to the project detail). 

minimizing the number of buttons will be part of the dashboard redesign (we'll get rid of _moderators_ and _management_)

**Comment by xi** [comment]
The order in the designs is "view", "edit", "publish". The currently implemented order is "edit", "publish", "moderators", "management". So which one do we want now?

**Comment by Janaba** [comment]
we definitely need a preview option as well.

In my opinion moderators and management would also make sense somewhere else. however we need a short term version before the redesign and management is an integral part of the participation process that needs to be obvious for initiators.

**Comment by Janaba** [comment]
To make it more logical and also consider that some buttons are not always necessary, we should use the following order:
1. Vorschau
2. Veröffentlichen
3. Bearbeiten
4. Management/Inhalte
5. Moderatoren
