### ISSUE TITLE
New Poll: user confusion through login button shown while loading poll questions

### ISSUE THREAD

**Issue by khamui** [liqd/a4-meinberlin#3753]
**URL:** /projekte/module/umfrage/
**user:** any
**expected behaviour:** Given user is logged in and new poll pages are being loaded, then a loading indicator should be shown.
**behaviour:** However, a button is shown, asking the already logged in user to log in.
**important screensize:**any
**device & browser:** any
**Comment/Question:** 
With loading questions asynchronously, the page is loaded before all data are fetched. This gap causes the wrong buttons to be shown and can confuse users. Instead we should hide or indicate that it is loading/fetching all questions.
Screenshot?

<img width="1680" alt="Bildschirmfoto 2021-07-21 um 09 09 07" src="https://user-images.githubusercontent.com/52801593/126447336-fdb214fd-05eb-48c5-971a-23c60a6df891.png">

**Comment by sabinammm** [comment]
This issue must be adressed in a4, correct? I've added the label just in case. Does this go into the direction you mean: https://stackoverflow.com/questions/40987309/react-display-loading-screen-while-dom-is-rendering ?
