### ISSUE TITLE
"Further participation processes" missing underneath poll process

### ISSUE THREAD

**Issue by rukala** [liqd/a4-meinberlin#376]
"Further participation processes" missing underneath poll process (as planned in design).

**Comment by 2e2a** [comment]
This is a new feature request.

**Comment by vellip** [comment]
And additionally unrelated to polls but to all projects.

**Comment by xi** [comment]
We do not usually track internal feature request in github issues. @rukala can you please add a user story to the backlog?

**Comment by rukala** [comment]
I will add a user story. Though we might have to discuss the design process then - since in my opinion the designs become part of the user story and acceptance criteria -  @damusp what do you think?

**Comment by damusp** [comment]
@rukala depends – is a new design really needed for this?

**Comment by rukala** [comment]
@damusp I think no new design is needed - we just overlooked including this element in the participation projects - new user story is in the backlog
