### ISSUE TITLE
Timeline for polls

### ISSUE THREAD

**Issue by damusp** [liqd/a4-meinberlin#378]
So, polls only have one single participation phase, therefore we do not show the timeline here. 

@rukala just made me aware that, for multiple reasons, this is a bit odd. Should we have a phase / an event that marks the end of participation, something that we can also show in the timeline?

**Comment by xi** [comment]
related to #364

**Comment by xi** [comment]
The phase timeline is in the process of being completely redesigned (see for example https://github.com/liqd/a4-meinberlin/pull/620)
