### ISSUE TITLE
poll user front-end, missing translation

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3787]
**URL:** https://meinberlin-stage.liqd.net/projekte/module/umfrage-76/
**user:** any
**expected behaviour:** german
**behaviour:** english
**important screensize:**
**device & browser:** 
**Comment/Question:** should be: Sonstige

Screenshot?
<img width="426" alt="Bildschirmfoto 2021-08-18 um 11 17 58" src="https://user-images.githubusercontent.com/35491681/129872995-75be1fd2-7234-4ccc-9ffb-c1569702ad5f.png">

**Comment by fuzzylogic2000** [comment]
@sabinammm I will assign you to this and the other translation issue, so that you can (if it's already in the translation and not missing in the code, meaning not marked as translatable) also add them when you do the translations for the sprint.

**Comment by fuzzylogic2000** [comment]
Hmm, maybe, I need to check this first or @Rineee We might display what's in the DB here? I will assign all of us. :)

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 are translations still coming? on resultpage "other" still has no translation on dev.

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer No, all translations should be there now. We seem to only have fixed it for the users then, please make issues for missing translations you find!
