### ISSUE TITLE
poll user front-end inconsistent behavior

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3788]
**URL:** https://meinberlin-stage.liqd.net/projekte/future-poll-semi-public/
**user:** any
**expected behaviour:** have the same behavior for both types of open question
**behaviour:** if only 1 person has answered and shows results, there are click-through-arrows for the sonstige but none for the open question. 
**important screensize:**
**device & browser:** 
**Comment/Question:** I would suggest we add arrows for the open question as well even if only 1 person has answered to have same behavior.

Screenshot?

<img width="641" alt="Bildschirmfoto 2021-08-18 um 11 30 52" src="https://user-images.githubusercontent.com/35491681/129874972-c11d549e-bd7a-4a6f-a727-ce52eb6546d9.png">

**Comment by fuzzylogic2000** [comment]
We did actively remove them for the open answers, so we could also remove them for the other answers?!

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 you can also remove them for the other-questions. It just should be the same :-)

**Comment by fuzzylogic2000** [comment]
@sabinammm This is a4 and react, but as we do the same for the open answers, maybe you can find where to fix it?

**Comment by sabinammm** [comment]
> @sabinammm This is a4 and react, but as we do the same for the open answers, maybe you can find where to fix it?

Looking at this now
