### ISSUE TITLE
poll user front-end: which behavior/alert if I save my form twice?

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3789]
**URL:** https://meinberlin-stage.liqd.net/projekte/running-poll-with-content/
**user:** registered user
**expected behaviour:** If I save my poll answers and then hit save again (e.g. I come back and don't know if I have saved or not) I would like to be informed that I have already participated and saved my answers. 
**behaviour:** I get alert "Ihre Antwort ist ungültig oder leer. Bitte versuchen sie es erneut".
**important screensize:**
**device & browser:** 
**Comment/Question:** Do we know if user has already participated? Can we specify the altert to something like "You have already saved your answers. You can change them if you want to."?

Screenshot?

<img width="641" alt="Bildschirmfoto 2021-08-18 um 11 42 04" src="https://user-images.githubusercontent.com/35491681/129876238-5a1b2c2c-2f36-48fc-976c-9adc1fd1ff58.png">

**Comment by fuzzylogic2000** [comment]
@Rineee I guess there is no difference in the response when posting the poll? So, we cannot easily display different alerts for empty answers or if someone hit the button twice? 
If that is true, this is an improvement. It would be better to change the text. Can you think of a wording @CarolingerSeilchenspringer ?

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 you mean changing the existing text for both alerts? So think of an alert text that works for both cases?

**Comment by fuzzylogic2000** [comment]
Yes, that's what I meant. But looking into the code, there might be other things that could go wrong?

@Rineee @khamui Can you think of other errors why this fails and should also be in the alert?
https://github.com/liqd/adhocracy4/blob/8da785317f437f6c67a59ca6e9b2e21a67a552cc/adhocracy4/polls/assets/PollQuestions.jsx#L253

**Comment by khamui** [comment]
@CarolingerSeilchenspringer i think a more intuitive solution is to disable the button if no changes have been made, so far? this way we do not need to explain it in an alert.

@fuzzylogic2000  regarding errors that can happen, i can only think of validation errors (required, max/min chars etc.). So if we disable the button, the alert message can stay as is?
