### ISSUE TITLE
project list dashboard: buttons not aligned 

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3790]
**URL:** https://meinberlin-dev.liqd.net/dashboard/organisations/caros-testorga/projects/
**user:** initiator
**expected behaviour:** 
**behaviour:** the buttons "view" and "edit" are not aligned
**important screensize:**
**device & browser:** big sur, safari, 14.1.1. (chrome and firefox are ok)
**Comment/Question:** 

Screenshot?
<img width="337" alt="Bildschirmfoto 2021-08-18 um 11 46 10" src="https://user-images.githubusercontent.com/35491681/129877131-e05f1934-1d56-43cc-bf2f-0e5bb76c1df6.png">

**Comment by phillimorland** [comment]
@khamui can you replicate this behaviour? I tried on linux and my mac but it's not there

**Comment by khamui** [comment]
@CarolingerSeilchenspringer @phillimorland also showing fine for me.

tested in Safari (15.0) and Chrome (96.0), with different screensizes.
macOS Big Sur.

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland @khamui I also can no longer replicate so will close the issue.
