### ISSUE TITLE
B-Plan-map: missing links to b-plan-maps

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3792]
**URL:** https://www.stadtentwicklung.berlin.de/planen/b-planverfahren/berlin/index.shtml
**user:** any
**expected behaviour:** for some bplans in the detail overview there is a direkt link that leads to the webpage of the district. The link should be at the bottom.
**behaviour:** missing link
**important screensize:**
**device & browser:** tested on big sur chrome and ff, hint came from administration, so probably not related to browser. 
**Comment/Question:** I am not sure which info exactly should be shown for which plan, but I remember that there was at least a link to the final bplans (status: festgesetzt) and the button said "zum B-Plan".

Screenshot?
![Bildschirmfoto 2021-08-18 um 15 47 53](https://user-images.githubusercontent.com/35491681/129909678-d4610429-0994-444b-909b-f089d9026884.png)

**Comment by fuzzylogic2000** [comment]
This is an issue in https://github.com/liqd/django_zbp and also needs to be fixed there and then that platform needs to be deployed. Should we add a story for that?

Are the buttons missing for all bplans? Is there a way to find out, what's meant to be there or how it behaved before?

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 I did some research for old stories but cannot find anything except for the field "zum B-Plan". I checked quite a few bplans with different status and districts and none had a button.

**Comment by fuzzylogic2000** [comment]
Alright! I hope that can be found in the code or in the data we get from the FIS broker.

**Comment by fuzzylogic2000** [comment]
Issue moved to other repo.
