### ISSUE TITLE
Pins on map show rating option although no rating allowed

### ISSUE THREAD

**Issue by rukala** [liqd/a4-meinberlin#381]
e.g. in spatial brainstorming Pins on the map show rating option although no rating is allowed - i.e. there is no rating phase:
![bildschirmfoto 2017-05-12 um 18 48 15](https://cloud.githubusercontent.com/assets/11075214/26008106/b25d90c4-3743-11e7-8cf7-af3d131db1ac.png)

**Comment by xi** [comment]
This is tracked in https://github.com/liqd/adhocracy4/issues/64
