### ISSUE TITLE
#4540 - [mB] plan: search function for plan - Design

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#3810]
**URL:**https://meinberlin-dev.liqd.net/dashboard/organisations/liqd/plans/
**user:** *initiator*
**important screensize:** *Mobile*
**device & browser:** *Safari Version 14.1.2 (16611.3.10.1.6)*
**Comment/Question:** *On Mobile I would leave the "Liste herunterladen" on top of the "Neues Vorhaben" one like on the design. Would that be possible? 

**Current:** 
<img width="369" alt="Screenshot 2021-08-24 at 09 54 49" src="https://user-images.githubusercontent.com/59610786/130579350-ba3748e5-b65b-4b7a-ba1f-10b5257ec034.png">

**Design:**
<img width="377" alt="Screenshot 2021-08-24 at 09 57 38" src="https://user-images.githubusercontent.com/59610786/130579383-d833f3bd-edc4-4f9d-85ef-ad413cf46b2b.png">

**Comment by mcastro-lqd** [comment]
@fuzzylogic2000 Ah true, so probably the button I took from the file is old and we don't use it anymore. If that's secondary, we can use this one instead. :)

**Comment by fuzzylogic2000** [comment]
Note for person fixing it: also check projects, linkages and so on and if the create button is full width there.
