### ISSUE TITLE
#4545 [mB] plans: adapt contact field(s) to project - Design

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#3816]
**URL:** https://meinberlin-dev.liqd.net/dashboard/organisations/liqd/plans/69/
**user:** *initiator*
**important screensize:** *Desktop*
**device & browser:** *Safari*
**Comment/Question:** *I just checked the contact fields and everything looks fine, I just wanted to mention that it would be good to have the field container using the same width/columns as the editing page ones on Beteiligungsprojekte, Bebauungspläne, Projektsammlungen, usw. Also because currently we have up to 138 in one line and readability-wise speaking, it's better to have between 65~75 characters per line. Let me know if you have any question.*

<img width="890" alt="Screenshot 2021-08-26 at 12 16 24" src="https://user-images.githubusercontent.com/59610786/130946090-d6e0e0f9-2b1b-4105-89b2-8f171e33f4c6.png">

**Comment by fuzzylogic2000** [comment]
Done!
