### ISSUE TITLE
testing 4544: picture of old plans on header AND tile

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3823]
**URL:** https://meinberlin-dev.liqd.net/vorhaben/2021-00064/
**user:** initiator
**expected behaviour:** after the release my old picture should become a headerpicture but not show anywhere else
**behaviour:** same picture shown as tile picture but only in project overview (not dashboard list), in dashboard form the tile upload is empty
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
old picture show correctly as headerpicture
<img width="623" alt="Bildschirmfoto 2021-08-27 um 15 11 42" src="https://user-images.githubusercontent.com/35491681/131132543-3f57a08a-860e-49ff-9263-7f79ecdc2814.png">

user-dashboard tile picture upload is empty as should be
<img width="778" alt="Bildschirmfoto 2021-08-27 um 15 07 11" src="https://user-images.githubusercontent.com/35491681/131131978-d80b677d-a9f7-4e88-8320-86d651340054.png">

tile picture in dashboard list view empty as should be
<img width="894" alt="Bildschirmfoto 2021-08-27 um 15 06 26" src="https://user-images.githubusercontent.com/35491681/131131881-4e5353c3-af32-4f80-8158-0f4d2db72bd8.png">

old picture (now headerpicture) shown on tile in project overview!!
<img width="894" alt="Bildschirmfoto 2021-08-27 um 15 06 52" src="https://user-images.githubusercontent.com/35491681/131131931-0603b366-ef92-4ccf-9d49-127d3ff0bbde.png">

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer It is the same we do for the projects. When the tile image is there we show that in the project overview. When it isn't, but there is a header image we show the header image instead. Should we really change that? And if we do, should we change it only for plans or also for projects?

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 interesting, I didn't know that. I actually found 3 running projects where the headerpicture is shown on the tile because no tile picture was uploaded so it may occur more often than we think. So we'll leave it this way.
