### ISSUE TITLE
dashboard: in list view search filter and "new" button are not aligned

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3844]
**URL:** https://meinberlin-dev.liqd.net/dashboard/organisations/caros-testorga/projects/
**user:** initiator
**expected behaviour:** in list view the search filter and the button to add new project/plan/bplan/external project are aligned
**behaviour:** they are not
**important screensize:**
**device & browser:** big sur, chrome, FF and safari
**Comment/Question:** 

Screenshot?
<img width="919" alt="Bildschirmfoto 2021-09-06 um 11 35 51" src="https://user-images.githubusercontent.com/35491681/132196182-db5d8a73-4ed2-4f39-bc7c-aa9d4139faab.png">

**Comment by fuzzylogic2000** [comment]
This happened when we fixed https://github.com/liqd/a4-meinberlin/issues/3810
Before it was next to the headline, not the filters (https://meinberlin-stage.liqd.net/dashboard/organisations/liqd/projects/). Should we try to get it back there before the release or just change it back to the way it was before?

**Comment by CarolingerSeilchenspringer** [comment]
I'll leave this for @mcastro-lqd to decide

**Comment by fuzzylogic2000** [comment]
Yes, I will try to get it back there first!
