### ISSUE TITLE
feature request: open graphics at full resolution

### ISSUE THREAD

**Issue by digitalesIch** [liqd/a4-meinberlin#3848]
It should be possible to click on a graphic to open it at full resolution.
For example here https://mein.berlin.de/projekte/neugestaltung-der-muhlendammbrucke-in-berlin-mitte/ text on the cross section graphic is not readable.
Ideal would be to open graphics in a light box, this way there could be additional controls like zoom in and out.

**Comment by goapunk** [comment]
Thanks for reporting this @digitalesIch. I'm not sure this will be fixed anytime soon but for now you can easily workaround this by right-clicking/long-pressing the image and cklicking on `Open Image in New Tab`.  I can zoom-in and read it without problems this way.

@CarolingerSeilchenspringer any opinion on this?

**Comment by CarolingerSeilchenspringer** [comment]
@digitalesIch @goapunk thanks for you ideas! I will discuss this with the responsible senate department. This would become an improvement story so I will close this issue here and bring it into taiga.
