### ISSUE TITLE
mailings in outlook: logo messed up

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3869]
**URL:** 
**user:** 
**expected behaviour:** 
**behaviour:** the logo of an organisation is huge and squeezed in newsletter
**important screensize:**
**device & browser:** microsoft / outlook
**Comment/Question:** similar problem as discussed here: https://github.com/liqd/a4-meinberlin/issues/1637

Screenshot?
<img width="732" alt="Bildschirmfoto 2021-09-15 um 16 26 59" src="https://user-images.githubusercontent.com/35491681/133459279-64d24529-fd2f-45e4-9a77-dfb413a2b9de.png">

**Comment by hklarner** [comment]
@CarolingerSeilchenspringer is this fixed?

**Comment by pascalkienast** [comment]
@CarolingerSeilchenspringer as a short update: The solution is quite simple: Almost all logo image-files are just too big. if we resize the logo-images to the recommended sizes (max. 650px width), everything should work, without changing any lines of codes.
