### ISSUE TITLE
plans form dashboard: spelling mistake

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3877]
**URL:** https://meinberlin-dev.liqd.net/dashboard/organisations/caros-testorga/plans/78/
**user:** initiator
**expected behaviour:** 
**behaviour:** spelling mistake german translation
**important screensize:**
**device & browser:** 
**Comment/Question:** 

wrong: Die folgenden Angaben haben Einfluss auf die Darstellung des Vorhabens in der allgemeine Projektübersicht.
correct: Die folgenden Angaben haben Einfluss auf die Darstellung des Vorhabens in der **_allgemeinen_** Projektübersicht.

**Comment by fuzzylogic2000** [comment]
@sabinammm Could you fix this?

**Comment by sabinammm** [comment]
Yes, am on it
