### ISSUE TITLE
dashboard: cannot upload any picture with crome

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3933]
**URL:** https://meinberlin-dev.liqd.net/budgeting/create/module/burgerinnenhaushalt-2-phasen-3/
**user:** any
**expected behaviour:** I can upload pictures with the picture upload (not CK editor)
**behaviour:** my finder doesn't open so that I cannot choose the files. True for user frontend and dashboard (all kinds of projects, bplans, plans, external links)
**important screensize:**
**device & browser:** mac (big sur) + chrome (works on big sur with firefox and safari, also on catalina + chrome as well as on microsoft with edge, firefox and chrome)
**Comment/Question:** 

Screenshot?

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer tested on my mac with big sur, cannot replicate, can you clear your cache and check again? if that fails please give me a list of what extesions you have running and which version of chrome, cheers!

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland It does work now for me. I did just do a chrome update the other day so I guess that helped. Will close the issue.
