### ISSUE TITLE
map area can be moved (also by user) 

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3938]
see issue on a+

https://github.com/liqd/adhocracy-plus/issues/1548

**Comment by lthueer** [comment]
only on mB dev, for stage and prod it seems to work fine

**Comment by fuzzylogic2000** [comment]
@sabinammm Can you fix that like on a+?
https://github.com/liqd/adhocracy-plus/issues/1548
https://github.com/liqd/adhocracy-plus/pull/1563/files
The maps on mB can be locally tested like this: https://github.com/liqd/a4-meinberlin/blob/main/docs/local_map_testing.md (hopefully)

**Comment by sabinammm** [comment]
> @sabinammm Can you fix that like on a+? [liqd/adhocracy-plus#1548](https://github.com/liqd/adhocracy-plus/issues/1548) https://github.com/liqd/adhocracy-plus/pull/1563/files The maps on mB can be locally tested like this: https://github.com/liqd/a4-meinberlin/blob/main/docs/local_map_testing.md (hopefully)

On it! Thanks for the references

**Comment by sabinammm** [comment]
@CarolingerSeilchenspringer @fuzzylogic2000 It's working fine on dev and locally for me. I also checked the package.json, and the version is the same as in the fix: https://github.com/liqd/a4-meinberlin/blob/bffdc451e8dc9df2219158349b60f082ab087a27/package.json#L37
Can we close this?

**Comment by fuzzylogic2000** [comment]
Oh, sorry, I didn't check if it was already fixed.
Fixed by #3944
