### ISSUE TITLE
Cannot upload shapefile to map in Dashboard

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#3970]
same issue as in a+ only that geojson works on mB.

https://github.com/liqd/adhocracy-plus/issues/1542

**Comment by sabinammm** [comment]
@CarolingerSeilchenspringer This functionality was added 2018. Do you know when it was last usable?

**Comment by CarolingerSeilchenspringer** [comment]
@sabinammm unfortunately I don't know when I tested it last. It was found on a+ and then checked for mB. So maybe it was even broken starting a+? Not sure how often this is used, we didn't get any user feedback.

**Comment by phillimorland** [comment]
fixed with https://github.com/liqd/a4-meinberlin/pull/4021
