### ISSUE TITLE
Missing/wrong error messages for missing title in create & edit idea forms

### ISSUE THREAD

**Issue by sabinammm** [liqd/a4-meinberlin#3989]
**URL:** https://meinberlin-dev.liqd.net/mapideas/create/module/ideensammlung-mit-karte/
**user:** any user who wants to create or edit an **idea** or a **map-idea**
**expected behaviour:** If I forget to add a title, I get an error message that is consistent with the other error messages in a language that I can understand
**behaviour:** There is an error message here, but it's not in a red box with a translated/translatable text as all the other missing field error messages are.
**important screensize:** any
**device & browser:** ubuntu chrome/firefox
**Comment/Question:** 
@CarolingerSeilchenspringer Do you want fields that show these error message to also have the dark red box with translated text as with other missing or erroneous field values?

Screenshot?
![image](https://user-images.githubusercontent.com/17978375/143562255-1d8bcf23-b6cf-4356-86fa-f5dad2dedb9f.png)

**Comment by CarolingerSeilchenspringer** [comment]
@sabinammm I haven't understood so far when we have the browser error message and when the adhocracy error message. We have this behavior at several places on the platform. Consistency would of course be great, but is it possible? Haven't we talked about it before @fuzzylogic2000 ? for now it is important that the user can see that there is an error on the page. What you suggest would be nice as well, but is it quick to implement or rather a story to have it the same everywhere?

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer Yes, we did talk about it, but concerning different forms, I think? In the same form, I also think it should be the same for all errors.
The difference is, that this error is from the html, so a browser error and the other one is by Django or done by us. So, the first is depending on the validation by the browser, the latter on the validation by our code/the database.
I know, there is a way to disable the browser errors, but am unsure if our error notifications will be shown instead or if we have to do sth. more to enable these. (And reading https://github.com/liqd/adhocracy-plus/issues/1596, my wild guess is, that just disabling the html ones is not enough...)

**Comment by fuzzylogic2000** [comment]
Also in bplan forms #3990 
Note: check linkages and other project create!

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 @sabinammm So it may be possible to show an Django error instead of the browser error? This would be nicer for the user, especially in frontend! So would you need to investigate on how to do this?

**Comment by fuzzylogic2000** [comment]
Yes, we would need to do investigate.

**Comment by CarolingerSeilchenspringer** [comment]
then I'd say we close it for now and maybe integrate into a story whenever we touch the user idea form where it seems to me most important.
