### ISSUE TITLE
Sortierung "meist kommentiert" leads to error message

### ISSUE THREAD

**Issue by maxliqd** [liqd/a4-meinberlin#3992]
**URL:** 
https://meinberlin-dev.liqd.net/projekte/module/brainstorming-22/?ordering=-created
and
https://meinberlin-dev.liqd.net/projekte/module/brainstorming-22/?ordering=-comment_count
**user:** participants
**expected behaviour:** Comments ranked according to most comments when you click on "meist kommentiert"
**behaviour:** Links to error message
**important screensize:** *desktop*
**device & browser:** *e.g. Mac, Desktop, firefox 94.0.2 (64-Bit))*

![Bildschirmfoto 2021-11-29 um 15 43 41](https://user-images.githubusercontent.com/94360651/143888396-bd345538-c7c3-41f6-8a6f-a2dd51a5934d.png)
![Bildschirmfoto 2021-11-29 um 15 47 12](https://user-images.githubusercontent.com/94360651/143888869-ab5b7200-dc81-4410-aa23-00702ca6c026.png)

**Comment by fuzzylogic2000** [comment]
That is actually this issue #3976 (same problem for comment count and the rating count ordering there) and we are on it!
