### ISSUE TITLE
Inconsistent error messages: Moderator:innen-form and Teilnehmer:innen-form has no message on top for faulty mail-address

### ISSUE THREAD

**Issue by sabinammm** [liqd/a4-meinberlin#4023]
**URL:** https://meinberlin-dev.liqd.net/dashboard/projects/sabinasprojekt/moderators/
**user:** Project initiator
**expected behaviour:** same error messages on same form, in this case the default is a red box on the top of the form indicating that there are other error messages marked by an additional red box on the affected fields within the form.
**behaviour:** Only one light-red box at the top of the form for all errors occurring within the form
**important screensize:** any
**device & browser:** ubuntu chrome
**Comment/Question:** 
The default has been set to this https://github.com/liqd/a4-meinberlin/pull/3985 and should be used here as well.

Screenshot?
![image](https://user-images.githubusercontent.com/17978375/144564755-aea56305-43e5-4721-86df-8bb6fcd048d9.png)

![image](https://user-images.githubusercontent.com/17978375/144569066-cb70eb2e-fd2d-4a5f-aa1a-e2a512daeaf0.png)

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer We decided to do two things:
- change the shown error to the "normal" one used in the other forms
- add the new "check below" from story
Hope that is fine!
