### ISSUE TITLE
dev dashboard: module template overview empty

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4025]
**URL:** https://meinberlin-dev.liqd.net/dashboard/projects/closed-poll-with-content/basic/
**user:** initiator
**expected behaviour:** I can chose a module out of all template
**behaviour:** If I add module the modal (?) opens but only the header is visible, not the templates
**important screensize:**
**device & browser:** tested on big sur/ monterey firefox, chrome, firefox
**Comment/Question:** 

Screenshot?
<img width="666" alt="Bildschirmfoto 2021-12-02 um 14 20 19" src="https://user-images.githubusercontent.com/35491681/144598415-a9839aff-38f7-486a-8e41-a0e8a97bb344.png">

**Comment by fuzzylogic2000** [comment]
duplicate of #4022
