### ISSUE TITLE
No Validation or Error when Phases in Dashboard are set in Illogical Order

### ISSUE THREAD

**Issue by sabinammm** [liqd/a4-meinberlin#4029]
**URL:** https://meinberlin-dev.liqd.net/projekte/module/burgerinnenhaushalt-2-phasen/?mode=list
**user:** Project initiator
**expected behaviour:** If I have more than one phase in a module, I would expect them to only be able to be set to occur in 1st proposal, 2nd rating, and 3rd voting time slots. If I make a mistake, I hope I am alerted and cannot publish this.
**behaviour:** Both 3-phase and 2-phase modules can be published with phases that make no sense in their time line. Users can set up and publish modules with voting phases that occur before rating and proposal phases. There is no validation or error.
**important screensize:** any
**device & browser:** any
**Comment/Question:** 
Since it hasn't come up, how urgent do you think this is @CarolingerSeilchenspringer ?
It would make sense to implement this, but the how should this be implemented best?

Screenshot?
**2-Phase module published with reverse phases:**
![image](https://user-images.githubusercontent.com/17978375/144612794-5b6aced9-3ed2-45c1-bbc6-a6712f191671.png)

**Comment by fuzzylogic2000** [comment]
I think, that is what @CarolingerSeilchenspringer meant in the discussion in the alert story:
> 2. There is no error message if the 1st phase is set to be AFTER the 2nd phase (only if they overlap). There should be one though.

My answer was:
> 2. is an a+ issue and quite complicated. But just add it to a4 and maybe also assign a prio. And we should probably think again about what to do with the a4 issues and if we can find time in a sprint to clean them up and work on them.

So, let's move this issue to a4!

**Comment by CarolingerSeilchenspringer** [comment]
moved to a4
