### ISSUE TITLE
frontend idea list in pb with 1+2 phases: Code field is shown

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4044]
**URL:** https://meinberlin-dev.liqd.net/projekte/burgerhaushalt-spandau/
**user:** any
**expected behaviour:** I cannot enter voting code in projects without voting
**behaviour:** in modules participatory budgeting with 1 and 2 phases the code field is shown
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
<img width="605" alt="Bildschirmfoto 2021-12-08 um 12 23 40" src="https://user-images.githubusercontent.com/35491681/145200341-f56709d7-9fd0-4c63-a392-9699ac4e65ae.png">

**Comment by sabinammm** [comment]
Just an addition: this is only the case for admin-users
