### ISSUE TITLE
[#5050] Edited idea information looks a little off on Mobile

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#4047]
**URL:** https://meinberlin-dev.liqd.net/budgeting/2021-00643/
**user:** *all*
**behaviour:** *The "Username created on 2. Dezember 2021" info seems off on Mobile, I would rather stick to the design or if it's not possible, we could hide the Referenznr. on Mobile. Me and Caro already spoke about it.*
**important screensize:** *Mobile*
**device & browser:** *Safari*

How it is now:
<img width="316" alt="Screenshot 2021-12-08 at 14 47 51" src="https://user-images.githubusercontent.com/59610786/145219689-900402ce-770f-4ebf-b987-14c655efb623.png">

Design proposal: 
<img width="344" alt="Screenshot 2021-12-08 at 14 52 34" src="https://user-images.githubusercontent.com/59610786/145219836-8baa5d69-fcbe-475c-8326-ed6453666d7c.png">
https://zpl.io/bW3DmXj

**Comment by phillimorland** [comment]
https://github.com/liqd/a4-meinberlin/issues/4069
