### ISSUE TITLE
list-item refactor needed 

### ISSUE THREAD

**Issue by phillimorland** [liqd/a4-meinberlin#4065]
currently we have the following files that are very similar and could be refactored into 1 file, would also make maintaining easier we could also make them clickable at the same time?
`maptopic_list_item`
`topic_list_item`
`mapidea_list_item`
`idea_list_item`
`proposal_list_item`

@CarolingerSeilchenspringer can we add the 'last edited' information to topic list items as well?

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland as discussed: let's not show the date of creation/last edited.

**Comment by phillimorland** [comment]
files now merged
