### ISSUE TITLE
user front end: make username in idea list bold

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4069]
**URL:** https://meinberlin-dev.liqd.net/projekte/brainstorming-2/
**user:** any
**expected behaviour:** 
**behaviour:** better distinguish username and date of creation/editing. e.g. by making the username bolt as we do in idea detail view
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
<img width="639" alt="Bildschirmfoto 2021-12-16 um 12 14 35" src="https://user-images.githubusercontent.com/35491681/146361740-cf6915cf-bef4-497d-83f5-6e8cf1154ddb.png">

**Comment by fuzzylogic2000** [comment]
Is this a question to discuss and for @mcastro-lqd to decide or should we just do it?

**Comment by mcastro-lqd** [comment]
@CarolingerSeilchenspringer I just kept the current version. But here you go: https://zpl.io/25mrrOn

**Comment by CarolingerSeilchenspringer** [comment]
thanks @mcastro-lqd and after reading @fuzzylogic2000 s question on issue #4098 I guess this would also be true for the other idea/proposal list.
