### ISSUE TITLE
Indicate error message

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#4070]
**URL:** https://meinberlin-dev.liqd.net/dashboard/modules/burgerinnenhaushalt-1-phase-3/phases/
**important screensize:** *Mobile*
**device & browser:** *Safari*
**Comment/Question:** *Would it be possible to add an anchor link to the error message when the page gets reload so that users understand that it hasn't been saved and something needs to be changed? Another option would be adding the error message on the same spot as the Success message. Whatever is easier for you.* 

Success message when reloaded:
<img width="359" alt="Screenshot 2021-12-16 at 12 18 51" src="https://user-images.githubusercontent.com/59610786/146362583-86ef2c61-0e53-4e0a-841b-d4d40a6a389f.png">

Error message when reloaded, you have to scroll down to see what happened: 
<img width="361" alt="Screenshot 2021-12-16 at 12 15 48" src="https://user-images.githubusercontent.com/59610786/146362671-4283730e-a33b-4aaa-b3f2-6f0af314dee8.png">

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer The story was to add this error message to make the user see that there was an error and it wasn't saved. The anchor is a new thing and I think, then we wouldn't need this message on top. The message on top was the easier solution here. Do we want to add the anchor as well or instead?

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer Ah, reading it again, the other option is adding it as an alert like the success message. That would mean, we redo the whole thing. Should we?

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 @mcastro-lqd As I understand it this problem is only on mobile version (smart phone) where the form is below the navigation, right? On desktop or even on tablets the message is on top. I would say to leave it that way because probably not many users edit projects on their smartphone and it seems to be too much work for this rather edge-case.
