### ISSUE TITLE
dashboard: cannot enter livestream

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4071]
**URL:** https://meinberlin-dev.liqd.net/dashboard/modules/interactive-event/livestream/
**user:** initiator
**expected behaviour:** I can enter a livestream in information or result tab or in an event or in interactive event module 
**behaviour:** get an error (see screenshot)
**important screensize:**
**device & browser:** mac big sur and monterry on all major browser, also edge
**Comment/Question:** 

Screenshot?
<img width="639" alt="Bildschirmfoto 2021-12-16 um 12 05 48" src="https://user-images.githubusercontent.com/35491681/146363784-ea795c03-6812-4cb1-82f0-60132cd88a72.png">

**Comment by phillimorland** [comment]
same as here https://github.com/liqd/adhocracy-plus/issues/1546

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer can you enter video embed for any of the tabs? we also have it in info tab

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland I tried in infotab, result tab, event and interactive event. None of them worked.

**Comment by phillimorland** [comment]
ok yeah found the error in ckeditor but theres no info or fix for it, will discuss with others 
https://ckeditor.com/docs/ckeditor4/latest/guide/dev_errors.html#exportpdf-no-token-url

**Comment by phillimorland** [comment]
ckeditor changed default with recent update and now we must set url in cofig however tried setting it in video-editor config in base but same error, maybe it needs to be set as part of dafault? alternativly we must create a iframe.ly account and pay per view  
https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-embed_provider

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer can you test using the embed url instead of the share link? it seems to be working but I want confirmation on that because I thought that it wasn't when I tried yesterday

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland It doesn't work for me, neither embed URL nor share link. Tried with two different videos.

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer @lthueer thanks for checking again, I think this is maybe a restriction from the third party service that creates an iframe from the url, they have a public api that we currently use but they seem to be fading this out. Yesterday I managed to add videos in the info tab of a project which means it's more likely a third party issue but it was end of the day so will repeat steps today and maybe contact the company to check the situation but we may need to consider paying for the iframe service, not sure how viable that is?

**Comment by phillimorland** [comment]
NOTE: working on dev again: https://meinberlin-dev.liqd.net/dashboard/modules/interaktive-veranstaltung-11/livestream/

**Comment by lthueer** [comment]
@phillimorland I still can't run it on a+ dev., also tried it on mB dev. Not sure if I am doing anything wrong but still get the same error message (also in a private tab) and in Firefox and Chrome.

**Comment by phillimorland** [comment]
@lthueer no you aren't doing anything wrong, sorry, forgot I added the fix to the testing branch. Basically it seems their api blocks/limits us most of the time but sometimes not and only on dev, this is why it has worked once or twice. It seems that stage and prod are not limited but they might start doing so at any point so what we should change our set up. our 2 options are:
1. Set up a paid for account with [iframely](https://iframely.com/plans) (we would need the editorial one)
2. Host our own version of iframely (it's opensource) which I discussed briefly with @goapunk and it apparently shouldn't be too problematic but it will need a bit of work.

What do you guys think? 

Also relevant for @CarolingerSeilchenspringer @fredewe

**Comment by phillimorland** [comment]
Note for @goapunk I have it working with api key now however did not getting working with local install of iframely but I think thats an issue with my embed_provider config

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer This is in the release milestone, so we need to find a solution very quickly. I think the options were:
- keeping it like it is and hoping that we do not exceed the max number on prod
- paying for an account and setting that up (would require a story and the money to come from somewhere)
- setting it up on our servers (would require a story (and also money for maintenance and updates, I guess)

Did I get that right @phillimorland ?
So, for this release, I think we need to go with option 1!?

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 @phillimorland I suggest to take it out of milestone but have a concept meeting about it quickly. Then implement a solution story soon and either release with next regular release or have an extra release if the problem happens on prod.

**Comment by phillimorland** [comment]
@fuzzylogic2000 @CarolingerSeilchenspringer tested on stage and it is not working so we need to come up with solution before release

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland this has been fixed, no? I know that we discussed it but cannot find a story. I will move into milestone but please close if/when done.

**Comment by phillimorland** [comment]
this is fixed, sorry got bad with issue referencing recently
