### ISSUE TITLE
infotab in container broken

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4078]
**URL:** https://meinberlin-dev.liqd.net/projekte/bibliothek-findet-stadt-stadt-findet-bibliothek-de/#tabpanel-project-194-information
**user:** any
**expected behaviour:** I can click the infotab
**behaviour:** nothing happens
**important screensize:**
**device & browser:** big sur, chrome, firefox and safari
**Comment/Question:** this problem is already on prod, user told us in November

Screenshot?

**Comment by phillimorland** [comment]
NOTE: check data-toggle for all interactove elements
