### ISSUE TITLE
Refactor ideas/mapideas/budgeting/kiezkasse to share more functionality

### ISSUE THREAD

**Issue by kleingeist** [liqd/a4-meinberlin#408]
For example the List FilterSets are copied between all projects types with minor differences (mainly the concrete Item Model). It should be possible, but challenging, to implement a common generic default FilterSet that could be used by all projects.

**Comment by xi** [comment]
related to #276

**Comment by kleingeist** [comment]
as it is expected that the project types diverge it does not make sense to unify filtersets now
