### ISSUE TITLE
rules/participate in project

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#4089]
As you can see in the test, the paricipate_project rule behaves a bit weird for project group members. I think, they should also be allowed to participate. The question is what it is used for.

Cool! The participate_project rule is a bit unexpected, so we should check that out. Like where it is used and what for. But anyway, will merge for now and add an issue.

_Originally posted by @fuzzylogic2000 in https://github.com/liqd/a4-meinberlin/pull/4077#pullrequestreview-837466549_

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 can you prioritize this? Don't know if it should go into the milestone.

**Comment by fuzzylogic2000** [comment]
@sabinammm  Haha, this is exactly the issue we just saw in the list. :)

@CarolingerSeilchenspringer This is actually for you to decide. There are a few things that project group members are not yet allowed to do, but that are allowed for initiators and sometimes also moderators. Like taking part in a private project, they are group member, but not participant in.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 a thanks, I didn't know what it was about. Yes, let's talk about it in person.

**Comment by phillimorland** [comment]
@fuzzylogic2000 is this still outstanding?

**Comment by fuzzylogic2000** [comment]
> @fuzzylogic2000 is this still outstanding?

Yes, but good point, I will assign myself, make a list and then @CarolingerSeilchenspringer has to decide

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer I stumbled over this again when I wanted to write tests for group members. So, the problem is:
Sometimes group members have the same rights as initiators, but in other cases they don't.
For example for add or change projects the group members have the same rights as the initiators and they should as this was what it is all about.
But for participating in a project, the group member is only allowed to do that in a public project, like the normal user. For draft or private projects, the group member is not allowed to participate while the initiator and even the moderator is allowed to participate. I don't find that logic and would like to change that.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 yes, please change that, I don't think that was intendet. Group members should be able to do the same thing as initiators only restricted to their project(s).
