### ISSUE TITLE
archived ideas and proposals should have a badge/label

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#4090]
**URL:** 
**user:** 
**expected behaviour:** I can see all the stuff that I can filter for.
**behaviour:** If I look at the proposal list (budgeting) with all ideas (archived and unarchived), I cannot distinguish between these two. This will get more confusing, once we have the voting and that is only allowed on unarchived proposals, so the button will only be shown on unarchived ones, but the archived ones do look the same in the list.
**important screensize:**
**device & browser:** 
**Comment/Question:** @CarolingerSeilchenspringer I think that is a question for @mcastro-lqd and should be a story once we decide to add that label.

Screenshot?

**Comment by fuzzylogic2000** [comment]
Oh, same on the detail page. Not shown that it is archived, but users will not be able to vote on it.

**Comment by mcastro-lqd** [comment]
@fuzzylogic2000 I thought we would leave the filtering options once we know more about them, that's why my designs have no specific filters. 

But I have one question, why would people have access to archived ideas if they are on the voting phase? Wouldn't it make more sense to leave that to the 2nd Phase only? 3rd Phase should be focused on voting only.

**Comment by fuzzylogic2000** [comment]
@mcastro-lqd Yeahhhhhh, we did rebuild the whole list in React. Including the archived filter. And testing that, I noticed this issue. Hmm. Yours would also be a solution, but as the "only vote on unarchived ideas" was an acceptance criterium, I thought, we would leave the filter. Maybe talk to @CarolingerSeilchenspringer what exactly this should look like?

**Comment by CarolingerSeilchenspringer** [comment]
Thanks for pointing that out @fuzzylogic2000! I will write a story about the label and include @mcastro-lqd question of if/how to show archived proposals.
