### ISSUE TITLE
testing 5024: missing location label

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4095]
**URL:** https://meinberlin-dev.liqd.net/projekte/burgerhaushalt-spandau/?mode=list
**user:** any
**expected behaviour:** 
**behaviour:** location label (Bezeichnung des markierten Ortes) is missing
**important screensize:**
**device & browser:** 
**Comment/Question:** maybe we need a smaller char restriction here? it's at 255 now, I wonder if something like 50 should be enough for something displayed as a tag? or continue with ... for longer words?

old list
<img width="446" alt="Bildschirmfoto 2021-12-21 um 16 35 27" src="https://user-images.githubusercontent.com/35491681/146956690-789f6d02-372c-4877-a4c9-c539b5fc90c3.png">

new list
<img width="446" alt="Bildschirmfoto 2021-12-21 um 16 34 09" src="https://user-images.githubusercontent.com/35491681/146956491-2472f9f2-e90d-4975-88a8-fbe1a7012657.png">

old list with long label
<img width="656" alt="Bildschirmfoto 2021-12-21 um 16 36 09" src="https://user-images.githubusercontent.com/35491681/146956804-ced5b4b8-0da8-42fc-a17c-901fc86efe9b.png">

**Comment by fuzzylogic2000** [comment]
While it does not really belong in here @CarolingerSeilchenspringer Just tell us, what you want changed for the label. So, if you want
1. a shorter char count in the field - existing long place names will be cut off
or
2. want the label cut off after come chars and if yes, where exactly (list and detail?)
and then we will just do it together with displaying in the react list

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 I will write a story about shortening the label as this is also true for non react list such as the one in brainstorming/idea collection. So to close this issue: just show the label in the new react list.
