### ISSUE TITLE
testing 5024: wording changed date

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4096]
**URL:** https://meinberlin-dev.liqd.net/projekte/burgerhaushalt-spandau/?mode=list
**user:** any
**expected behaviour:** translation changed date should be "bearbeitet am"
**behaviour:** is "geändert am"
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by fuzzylogic2000** [comment]
I put the wording issue in the other milestone, so that we do it together with other wording issues and translations if we have more
