### ISSUE TITLE
idea and so on lists: username + date

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4098]
**URL:** https://meinberlin-dev.liqd.net/projekte/burgerhaushalt-spandau/?mode=list
**user:** any
**expected behaviour:** 
**behaviour:** 
**important screensize:** smaller than around 450, depening on length of username + date
**device & browser:** 
**Comment/Question:** can the date switch so a second row for smaller screens? connect to issue #4069 ?

Screenshot?
<img width="379" alt="Bildschirmfoto 2021-12-21 um 16 41 43" src="https://user-images.githubusercontent.com/35491681/146958102-af66ae30-e420-418a-96fa-1c367d7824a5.png">

**Comment by fuzzylogic2000** [comment]
On which list is that? Maybe this issue should be changed in both lists if we decide to do so? And then it shouldn't prevent us from closing the React list story, I think.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 you are right, this is in both idea/proposal lists. And no, it should not prevent us from closing the story. I set the prio on low and took it out of the milestone again.
