### ISSUE TITLE
budgeting: use api instead of props through template tag in react_proposals_vote

### ISSUE THREAD

**Issue by Rineee** [liqd/a4-meinberlin#4107]
**URL:** 
**user:** 
**expected behaviour:** consistent passing of information
**behaviour:** For now, we are using the proposal api to get all info on the proposal list, but on detail view put all information in the template tag* 
**important screensize:**
**device & browser:** 
**Comment/Question:** With the proposal pk, we could also just pass the the proposal detail api url in the [template tag](https://github.com/liqd/a4-meinberlin/blob/d69a4dd624705c7f28a053e123e0dcdf847fbe3d/meinberlin/apps/budgeting/templatetags/react_proposals_vote.py) and then fetch the proposal information from there. @khamui @phillimorland I dont know how much refactoring this would mean? We would still need to pass token info though or write another mixin that adds that info to proposal detail. 

 

Screenshot?

**Comment by khamui** [comment]
yes, it gets messy quickly if we have to maintain two "bridges".
I will think about how we can unify that better in frontend, so we only go one way and keep the template tag attribute as small as possible.

btw: @Rineee you mentioned the other Kha again, sorry Kha...

**Comment by khamui** [comment]
just assigning, so i do not forget about it

**Comment by phillimorland** [comment]
@khamui maybe doing the refactor you can also add disabled behaviour for when user has used their 5 votes: https://taiga.liqd.net/project/liqd-liquid-software/task/5130

**Comment by phillimorland** [comment]
NOTE: hover styling still present even when disabled, maybe due to it being a styled checkbox, maybe need to consider additional styl rules?

**Comment by phillimorland** [comment]
@fuzzylogic2000 I just re-read the issue and i'm a little confused, do we still want to consider doing this?

**Comment by fuzzylogic2000** [comment]
@phillimorland Yes, we have 
this for the list: https://github.com/liqd/a4-meinberlin/blob/main/meinberlin/apps/budgeting/templatetags/react_proposals.py
and this for the detail view: https://github.com/liqd/a4-meinberlin/blob/main/meinberlin/apps/budgeting/templatetags/react_proposals_vote.py
That is quite confusing. 

On the other hand, it's probaly not that important right now as we hope to get the detail view into React as well at some point and would need to redo the template tag for that anyway. Sooo, let's close this issue and do it when we work on it anyway?! Reopen if you diagree. @Rineee or @phillimorland
