### ISSUE TITLE
budgeting: think about moving phase information to api

### ISSUE THREAD

**Issue by Rineee** [liqd/a4-meinberlin#4109]
**URL:** 
**user:** 
**expected behaviour:** phase information is coming from api like all other data
**behaviour:** is_voting_phase is passed in the template tag
**important screensize:**
**device & browser:** 
**Comment/Question:** We need to know if voting phase is active to decide whether to show the ratings or not: https://github.com/liqd/a4-meinberlin/blob/d69a4dd624705c7f28a053e123e0dcdf847fbe3d/meinberlin/apps/budgeting/assets/BudgetingProposalListItem.jsx#L23

Screenshot?

**Comment by fuzzylogic2000** [comment]
also check out #4597
