### ISSUE TITLE
Process to archive ideas 

### ISSUE THREAD

**Issue by phillimorland** [liqd/a4-meinberlin#4121]
The process to archive ideas is convoluted and confusing, we should maybe consider redoing it, maybe the simplest way would be to use different wording on the menu?

currently: 'zurück melden' > 'Vorschlag moderieren' > archive checkbox 

Instead of 'zurück melden' maybe we could have 'moderate' or something? 

Also we are unsure of how archive is used for ideas, or at what point during the process ideas would be archived and as such we went with the simple option of not showing the vote button on archived ideas even if they have been voted on but we don't know if it makes sense. 

@CarolingerSeilchenspringer @mcastro-lqd what do you think?

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland the archive is only in participatory budgeting modules. Idea behind is, that if you have an ongoing project, you can archive ideas that e.g. have been implemented or that cannot be implemented after having been checked. So it does make sense but maybe not behind the wording "zurück melden" and I like the idea to call it "moderieren".

As of the voting butting: It is not possible to vote on an archived idea, right? However it is possible to rate on them. So to make this more clear I will add a story to discuss archived ideas. My first thoughts: 
* it should be easily found how to do it (wording change, maybe also design change in the form)
* you should not be able to rate/ vote on archived ideas
* if rating/voting happened before being archived, results should be visible
* Idea should somehow be tagged as archived.
