### ISSUE TITLE
testing 5049: group member cannot moderate

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4124]
**URL:** https://meinberlin-dev.liqd.net/projekte/moderiertes-projekt-testprojekt/
**user:** group member
**expected behaviour:** I should at least have all rights the moderation has
**behaviour:** I cannot: zurück melden, moderation notice, edit/delete comments (although I can edit/delete ideas)
**important screensize:**
**device & browser:** 
**Comment/Question:** was it like this before? I think the roles should built upon each other, so group has more rights than moderation, initiator more than group. So one level should always have the rights of the level below plus more. Therefore the group member should also be able to moderate.

Screenshot?

**Comment by CarolingerSeilchenspringer** [comment]
also true for moderating interactive event which I cannot do as group member. Just having another though: initiators automatically have moderation rights when starting a project. so probably this behavior has been like it before and should stay like it. Also because moderation is connected to getting a lot of mails that I as group member starting the project may not want to have. Unsure here, @fuzzylogic2000 what do you think?

**Comment by fuzzylogic2000** [comment]
Hmm, right. I think, we don't really have a concept here. While the e-mails are only for the moderators, the rights to do sth. are normally assigned like you describe it. But yeah, I guess when we tested it so far, the group member cretaed the project and was thus also the moderator of that project. 
What about testing if it is the same on stage? And depending on the outcome, we can either fix it (when it is different on stage) or keep it like that for now and this release (if it is the same on stage). 
And then (in the second case) we do another concepting/story/discuss it in an issue before we change it. And we have a look into the list of permissions @sabinammm is compiling.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 it is the same behavior on stage. So no need to change now and for me - as it works out - no need to change in the future. But maybe we can have a look together on the list once @sabinammm has finished it?

**Comment by fuzzylogic2000** [comment]
Yes! Let's look at the list once it's done, but as this does not need changing, also close this issue. :)

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 I though to leave this issue open as a reminder to talk about it again, but I took it out of the milestone and set on low prio. Do we have another way to not forget?

**Comment by fuzzylogic2000** [comment]
@sabinammm Is currently working on it and we will talk about it or show it to you right away! And moderation permissions will come up again with KOSMO, I guess.
