### ISSUE TITLE
Translation strings in JSX-files overlooked and deleted

### ISSUE THREAD

**Issue by sabinammm** [liqd/a4-meinberlin#4152]
**URL:** 
**user:** 
**expected behaviour:** All django translation texts in jsx-files are picked up by makemessages
**behaviour:** Sometimes, these translations are not picked up and instead, existing translations are deleted in another round of makemessages.
**important screensize:**
**device & browser:** 
**Comment/Question:** 
This has been successfully corrected by creating variables with the strings at the top of jsx-files, as it is done [here](https://github.com/liqd/a4-meinberlin/pull/4140/commits/cdd4792113284b79cfe8a253a592de34aa53dc86) and in PR #4151 .
Should we do this proactively or in a case by case situation?

Screenshot?

**Comment by fuzzylogic2000** [comment]
Do you know how many are left to do proactively? Here as well as in a4.
I would say, it it's a loooooot, we do it case by casee and also whenenver we work on the jsx-files anyway. If there's only a few left, it might be easier to just do it before we forget about it again.

**Comment by sabinammm** [comment]
@fuzzylogic2000 I found 11 files with translations without variables:
BudgetingProposalList.jsx
ListItemStats.jsx
Pagination.jsx
ChapterForm.jsx
ChapterNav.jsx
ChapterNavItem.jsx
DocumentManagement.jsx
ParagraphForm.jsx
FilterNav.jsx
FilterOptions.jsx
FilterRadio.jsx

**Comment by fuzzylogic2000** [comment]
Then I would say: if you have time to do it, go for it!

**Comment by sabinammm** [comment]
> @fuzzylogic2000 I found 11 files with translations without variables: BudgetingProposalList.jsx ListItemStats.jsx Pagination.jsx ChapterForm.jsx ChapterNav.jsx ChapterNavItem.jsx DocumentManagement.jsx ParagraphForm.jsx FilterNav.jsx FilterOptions.jsx FilterRadio.jsx

Missed two additional ones:
BudgetingProposalListItem.jsx
Alert.jsx
