### ISSUE TITLE
module tile shows running project although in between phases

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4153]
**URL:** https://meinberlin-dev.liqd.net/projekte/ihre-vision-fur-berlin-welche-themen-sind-ihnen-wi/
**user:** any
**expected behaviour:** module tile should show the project as upcoming if participation is in between two phases
**behaviour:** user is invited to participate but cannot
**important screensize:**
**device & browser:** 
**Comment/Question:** does this have to do with the module not knowing what type it is?

Screenshot?
Module tile
<img width="361" alt="Bildschirmfoto 2022-01-13 um 10 35 23" src="https://user-images.githubusercontent.com/35491681/149304201-8d058669-1c08-4ba0-9e24-13982b380a68.png">

Module page
<img width="538" alt="Bildschirmfoto 2022-01-13 um 10 35 45" src="https://user-images.githubusercontent.com/35491681/149304263-a15b9772-f59d-45e2-a516-cc2c57a3135a.png">

**Comment by Rineee** [comment]
@CarolingerSeilchenspringer No, that doesnt have to do with the module type. Here we only consider phases and a module is active if the last phase is not over yet (and the first phase has started already). So we do not consider the case that it is in between phases (it is still active then). See also this issue here: https://github.com/liqd/adhocracy-plus/issues/1074 where the behaviour is explained for projects. 
Would you like to change that?

**Comment by Rineee** [comment]
> @CarolingerSeilchenspringer No, that doesnt have to do with the module type. Here we only consider phases and a module is active if the last phase is not over yet (and the first phase has started already). So we do not consider the case that it is in between phases (it is still active then). See also this issue here: [liqd/adhocracy-plus#1074](https://github.com/liqd/adhocracy-plus/issues/1074) where the behaviour is explained for projects. Would you like to change that?

But thinking about it, the module type might help to detect if a module is in between phases, because then we know which phases and in which order belong to it..

**Comment by CarolingerSeilchenspringer** [comment]
@Rineee thanks, that helps. Yes, I think we should change that at some point because the invitation on map tile to participate now is misleading if you cannot participate. I will write a story about it.
