### ISSUE TITLE
403 csrf error page should have same styling as other error pages

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#4170]
**URL:** 
**user:** 
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** https://docs.djangoproject.com/en/3.2/ref/settings/#std:setting-CSRF_FAILURE_VIEW

https://docs.djangoproject.com/en/3.2/ref/csrf/

Screenshot?
![Screenshot from 2022-01-25 16-36-16](https://user-images.githubusercontent.com/8178179/151017958-b886693d-b00b-4035-9648-105cc550f836.png)

**Comment by fuzzylogic2000** [comment]
@Rineee I forgot that there is an issue that is kind of important! We should do this before release, I think.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 @Rineee please move it into the milestone if you think this is important.
