### ISSUE TITLE
testing 5377: funny dots on apple mobile devices

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4200]
**URL:** /projekte
**user:** any
**expected behaviour:** 
**behaviour:** there are white dots in the filter and list/map switch
**important screensize:**
**device & browser:** all mobile apple devices 
**Comment/Question:** 

Screenshot?
<img width="281" alt="Bildschirmfoto 2022-02-24 um 17 38 18" src="https://user-images.githubusercontent.com/35491681/155569983-eee89d04-1409-434c-960d-1acabdcbf1e2.png">

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer is it only when iphones are using Safari or also for ff and Chrome?

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland also for chrome, ff for safari is not available (at least in browserstack).
