### ISSUE TITLE
Timeline icons broken

### ISSUE THREAD

**Issue by phillimorland** [liqd/a4-meinberlin#4207]
icons in timeline broken
Check other icons too

**Comment by fuzzylogic2000** [comment]
Oh no, I updated font awesome... And it said, that the only breaking changes were dropping two random icons, we do not use. Probably not true.

**Comment by sabinammm** [comment]
I think this is the same issue as with the calender, which now looks like this in Firefox:
![calender](https://user-images.githubusercontent.com/17978375/156132680-6050042f-ba0e-4b11-b507-167680c4f5d9.png)

And like this in Chrome:
![image](https://user-images.githubusercontent.com/17978375/156132835-4a5e87e9-4ba2-4e1f-b510-c3bbdc8a5784.png)

**Comment by phillimorland** [comment]
@fuzzylogic2000 did you do the upgrade steps? https://fontawesome.com/v6/docs/web/setup/upgrade/ I think as we don't use a kit we would need to follow all the steps I assume?!

**Comment by fuzzylogic2000** [comment]
No, I only merged this https://github.com/liqd/a4-meinberlin/pull/4181 after checking the changelog https://fontawesome.com/docs/changelog/ That was too early obviously. Should I revert? Or can we live with the broken thing until someone has time to look into it?

**Comment by phillimorland** [comment]
@fuzzylogic2000 I would maybe revert as we want to release mB soon right? maybe we can trial the update on Opin and if easy we can try get it done here before release but don't want to have to put that back just for early adoption of update

**Comment by fuzzylogic2000** [comment]
The release is not that urgent. Let's just add this issue to the release milestone to not forget and then see, when we are closer to the release which one it will be. :)
