### ISSUE TITLE
missing translation e-mail verification process

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4221]
**URL:** dev-server
**user:** about to finalize registration
**expected behaviour:** german
**behaviour:** english
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

<img width="609" alt="Bildschirmfoto 2022-03-01 um 09 57 41" src="https://user-images.githubusercontent.com/35491681/156168314-777b7cf8-484a-4170-a0a6-411baba07fbc.png">

**Comment by fuzzylogic2000** [comment]
We have this original string and this translation. Is the translation alright?

"We have sent an e-mail to you for verification. Follow the link provided to "
"finalize the signup process. If you do not see the verification e-mail in "
"your main inbox, check your spam folder. Please contact us if you do not "
"receive the verification e-mail within a few minutes."
msgstr ""
"Wir haben Ihnen eine Bestätigungs-E-Mail geschickt. "
"Folgen Sie dem Link, um den Anmeldevorgang abzuschließen. "
"Wenn Sie die Bestätigungs-E-Mail nicht in Ihrem "
"Posteingang sehen, überprüfen Sie Ihren Spam-Ordner. Bitte "
"kontaktieren Sie uns, wenn Sie die Bestätigungs-E-Mail "
"nicht innerhalb weniger Minuten erhalten."
