### ISSUE TITLE
remove default text from plan - participation explanation?

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#4222]
**URL:** 
**user:** 
**expected behaviour:** I get an empty field for participation explanation when I add a plan.
**behaviour:** I have to remove the default text when I add a new plan. This invites to leaving the default text, which will then not be shown. Something we also did not want to encourage.
**important screensize:**
**device & browser:** 
**Comment/Question:** We can fix that by just removing the default from the field again. Then it will behave like the other required fields: initially empty and complaining if nothing is filled in. This is for @CarolingerSeilchenspringer to decide!

Screenshot?

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 as just discussed: yes, let's take default for the new plans out again.
