### ISSUE TITLE
UX/UI testing on [#5388] font formatting 

### ISSUE THREAD

**Issue by sabinammm** [liqd/a4-meinberlin#4226]
**URL:** https://meinberlin-dev.liqd.net/vorhaben/2019-00045/
**user:** all
**behaviour:** _Participation Explanation Box: According to the design, the texts "Art der Beteiligung" has the same formatting as the UL at the top with "Ort", "Thema", etc. (Arial-BoldMT, Size: 16px, Line Heigth: 24px)._ 

_(The same is true for "Kontakt für Rückfragen" and "Verantwortliche Stelle", but wasn't part of this story.)_
**important screensize:** all
**device & browser:** all: chrome, firefox, edge, safari, mobile and desktop

How it is now
![plan_participation](https://user-images.githubusercontent.com/17978375/156361574-c6199579-bf5f-4c88-b126-01ab89f9a0aa.png)

Design:

https://zpl.io/llJjN8D

**Comment by fuzzylogic2000** [comment]
@phillimorland Right, this was also in the plan detail! Could have put the missing grey line in here...
