### ISSUE TITLE
Testing 5209: Filter incorporates deleted comments

### ISSUE THREAD

**Issue by sabinammm** [liqd/a4-meinberlin#4229]
**URL:** https://meinberlin-dev.liqd.net/text/paragraphs/91/?comment=547
**user:** any
**expected behaviour:** If I filter for most popular comment, I'd expect to only see one that I can read. Thus, probably deleted comments shouldn't be incorporated.
**behaviour:** Filtering for "Meiste Zustimmung" takes deleted comments with this attribute into account
**important screensize:** any
**device & browser:** desktop and mobile
**Comment/Question:** 

Screenshot?
![image](https://user-images.githubusercontent.com/17978375/156525954-b146f02f-1464-490d-a139-9c94462efda8.png)

**Comment by fuzzylogic2000** [comment]
douplicate of https://github.com/liqd/adhocracy4/issues/978
