### ISSUE TITLE
UX/UI testing on [#5209] line that separates comments missing

### ISSUE THREAD

**Issue by sabinammm** [liqd/a4-meinberlin#4230]
**URL:** https://meinberlin-dev.liqd.net/text/paragraphs/91/?comment=546
**user:** any
**behaviour:** _In the design, there are lines between the comments that separate them. These only actually appear <512px, so they are there in mobile, not in desktop._
**important screensize:** >512px
**device & browser:** desktop
![image](https://user-images.githubusercontent.com/17978375/156527842-4702386e-acb4-461e-82c3-f2cb2bf040a1.png)

Desgin: https://zpl.io/JEk7xpW

**Comment by khamui** [comment]
<img width="842" alt="Bildschirmfoto 2022-03-03 um 09 14 46" src="https://user-images.githubusercontent.com/52801593/156533921-9d330149-7c29-4530-ae66-477e1af396d0.png">

@sabinammm i relied on this design (which is probably deprecated?)

**Comment by phillimorland** [comment]
@khamui you were working off the correct design, however mobile and desktop will often have small differences in design to ensure both are as user friendly as possible on their respective screen sizes, something to note specifically for UX/UI testing @sabinammm
