### ISSUE TITLE
consistent design of Modals over whole site

### ISSUE THREAD

**Issue by sabinammm** [liqd/a4-meinberlin#4232]
~~**URL:** https://meinberlin-dev.liqd.net/text/paragraphs/88/~~
~~**user:** any~~
~~**behaviour:**  _The share link box styling looks similar to a+, but different from the mB design with regard to:_~~

~~_- button styling_~~
~~_- close button should be in top right corner_~~
~~_- "Teilen"-text in top left corner is missing_~~
~~_- there should be no line in the box_~~

Small fix was implemented for the button styling however as other styling means it will be inconsistent from the other modals have left issue open so @mcastro-lqd can take a look and decide on a consistent style

![image](https://user-images.githubusercontent.com/17978375/156547993-a96d4171-abc1-400c-bed4-cb962c92fcf5.png)

In the design with "Teilen"-text:
![image](https://user-images.githubusercontent.com/17978375/156548073-9bde730b-b1a1-4b65-818e-fb7052c1e742.png)

Design: https://zpl.io/aB36MQq

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer @mcastro-lqd I think we should look at consistency for our modal alerts, see below for screen shots of all, what style should we follow everywhere?
![screenshot(17)](https://user-images.githubusercontent.com/5871230/156601338-b96ede0a-1ce0-4691-ab4b-09ca2f86cb38.png)
![screenshot(18)](https://user-images.githubusercontent.com/5871230/156601347-2fea4f3b-8f76-4b14-b488-a01a71a969c4.png)
![screenshot(19)](https://user-images.githubusercontent.com/5871230/156601363-a756c68b-50de-4086-b880-767357d0ca78.png)
![screenshot(20)](https://user-images.githubusercontent.com/5871230/156601372-76b77eec-747e-49cd-a10f-c74ab0d53346.png)
![screenshot(21)](https://user-images.githubusercontent.com/5871230/156601377-65e7e5c4-14cf-4a3a-8b6d-dd2e8ad012db.png)

**Comment by hello-kathi** [comment]
@phillimorland it is ok for me! Thank you!

**Comment by fredewe** [comment]
Fine for me!

**Comment by CarolingerSeilchenspringer** [comment]
thanks for pointing this out @phillimorland! Would be great if @mcastro-lqd could have a look also at a+ and suggest a consistent design for all platforms.

**Comment by mcastro-lqd** [comment]
I know that most of the stuff on mainBerlin was created using primary and secondary buttons aligned to the left, but I actually prefer them aligned to the right. Most of the Google Materials DOs are done this way: https://material.io/components/buttons  But I'd be up to leave them below as most of the rest of the platform. 

meinBerlin: https://zpl.io/Dlv4B6g
aplus+: https://zpl.io/p1ml4K8
