### ISSUE TITLE
testing 5388: design of box, distance box and text

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4251]
**URL:** https://meinberlin-dev.liqd.net/vorhaben/2021-00082/
**user:** any
**expected behaviour:** 
**behaviour:** design of box is not as in zeplin; distance between text inside box and frame of box is larger than should be. The distance to the contact below the box is smaller than supposed to be.
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
on dev:
<img width="507" alt="Bildschirmfoto 2022-03-10 um 09 21 05" src="https://user-images.githubusercontent.com/35491681/157618620-27965375-2b03-44e4-86fe-21bf267d4da4.png">

on zeplin:
<img width="372" alt="Bildschirmfoto 2022-03-10 um 09 21 54" src="https://user-images.githubusercontent.com/35491681/157618747-47f2ff64-553a-44f3-9ebb-ab4c73e44229.png">

**Comment by fuzzylogic2000** [comment]
Last issue! I will assign you both @khamui and @phillimorland . So, who gets here first. :)
