### ISSUE TITLE
testing 5209: wording/ translation change

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4253]
**URL:** https://meinberlin-dev.liqd.net/mapideas/2021-00629/
**user:** any
**expected behaviour:** correct wording: "Antworten ausblenden"
**behaviour:** current wording: "Antworten verbergen"
**important screensize:**
**device & browser:** 
**Comment/Question:** this can be changed in a4/+ as has been discussed with respective PMs. English should be "hide answers" I guess (but for mB not relevant)

Screenshot?

**Comment by sabinammm** [comment]
@CarolingerSeilchenspringer @fuzzylogic2000 this has been closed in https://github.com/liqd/a4-meinberlin/pull/4258. Translation changes for a+ have to done there, I think?
