### ISSUE TITLE
testing 5209: search result

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4254]
**URL:** https://meinberlin-dev.liqd.net/mapideas/2021-00629/
**user:** any
**expected behaviour:** when searching comments should display: "x Beiträge gefunden zu: [search word]" or respective "1 Beitrag gefunden zu: [search word]"
**behaviour:** see screenshot
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
<img width="372" alt="Bildschirmfoto 2022-03-10 um 10 51 05" src="https://user-images.githubusercontent.com/35491681/157637200-e20c1ca9-e9e0-4f4e-8388-bab1856e7e03.png">

**Comment by sabinammm** [comment]
Wrong issue mentioned in PR, this issue remains open until a4 update is merged.

**Comment by CarolingerSeilchenspringer** [comment]
I will reopen because I just realized that the plural form of "x Beiträge" only appears after reloading the page. When entering a 2 nd comment, it will say "2 Beitrag". Is there anything we can do about that?
screenshot: right after submitting comment
<img width="973" alt="Bildschirmfoto 2022-03-16 um 11 30 38" src="https://user-images.githubusercontent.com/35491681/158573464-d75779fa-061a-4f91-b5f0-31c0013a2ec7.png">
?
screenshot: after reloading page
<img width="973" alt="Bildschirmfoto 2022-03-16 um 11 30 55" src="https://user-images.githubusercontent.com/35491681/158573584-2f4c8275-7f73-4355-b95f-271d6c7c623f.png">

**Comment by fuzzylogic2000** [comment]
Hmm, yeah, there is no quick solution for this. We could when we add the comment to the state also update that number there, but that's kind of a lot of work for an edge case.
We probably rather want our comments to automatically update anyway? That would be an even bigger story, but worth the effort, I think. Currently it is also very weird that when many people comment at the same time, I have to reload to see the other comments.
Also, this is an a4 issue.

**Comment by fuzzylogic2000** [comment]
Wait, and where does it do that? Not in the filter anymore, right? So, this is also a different issue. Will copy it over to a4
