### ISSUE TITLE
testing 5209: clear search comment filter

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4255]
**URL:** https://meinberlin-dev.liqd.net/mapideas/2021-00629/
**user:** any
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** can we have the same clearing of comments search as for search in dashboard project list? it is different in design and behaviour. At least we should have the same x-icon. Also the x should already appear when typing, currently only appears when clicking someplace else.

Screenshot?
current comments:
<img width="383" alt="Bildschirmfoto 2022-03-10 um 11 42 17" src="https://user-images.githubusercontent.com/35491681/157645412-37809698-f0b4-4c32-89ce-72bfd264d937.png">

dashboard project list:
<img width="383" alt="Bildschirmfoto 2022-03-10 um 11 39 06" src="https://user-images.githubusercontent.com/35491681/157645369-88d29d67-19c2-4c93-8fe0-58a663411a3a.png">

**Comment by khamui** [comment]
@CarolingerSeilchenspringer there is an issue with the blue clearing button regarding some browsers (Firefox and IE). Those do not have them builtin.

The upper one is our custom icon. As I remember right in current stage we use both variants together. Maybe we should have a quick chat about it with @phillimorland ?

**Comment by phillimorland** [comment]
@khamui we don't use the async_comments on stage yet so not sure what you're referring?
@CarolingerSeilchenspringer which browser was the screenshot of 'dashboard project list' take in? this looks like default behaviour of chrome, it does not exist in other browsers and best we can do is hide it but as those form fields (project, idea ect. search filter) are not react based, as such I'm unsure if we can implement the close button we have in the comments

**Comment by khamui** [comment]
@phillimorland yes thats what i meant, the non async comment is using both

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland @khamui yes, that was chrome and I also now realize that dashboard is not react. If you say the upper one is our default, then let's stick with it. Can we make it look as on a+? it looks a bit nicer there and is a bit off (not centered) on mB.
<img width="482" alt="Bildschirmfoto 2022-03-10 um 14 23 38" src="https://user-images.githubusercontent.com/35491681/157670651-063b8fe4-5615-4e04-8696-0d4fb35e954c.png">
