### ISSUE TITLE
testing 5209: wrong time zone

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4256]
**URL:** https://meinberlin-dev.liqd.net/mapideas/2021-00629/
**user:** logged in
**expected behaviour:** correct time next to my comments
**behaviour:** time is 1 hour behind, both for created and deleted
**important screensize:**
**device & browser:** 
**Comment/Question:** the export has the correct time

Screenshot?
<img width="383" alt="Bildschirmfoto 2022-03-10 um 12 07 22" src="https://user-images.githubusercontent.com/35491681/157649711-16d34bb9-fdbc-4001-84bd-1f86446ae08e.png">

**Comment by fuzzylogic2000** [comment]
@khamui Right. It thought it would be in the right timezone with the django stuff in the comment serializer. Noooo, wait. We use the `time`, right? And without the date, the code has no way of knowing which timezone to use. Or maybe not. Will look into that tomorrow.
