### ISSUE TITLE
Icon for blueprint seems broken

### ISSUE THREAD

**Issue by damusp** [liqd/a4-meinberlin#427]
Our blueprint icons are not supposed to have filled areas, just outlines.
Here, door and chimney got filled.

<img width="429" alt="bildschirmfoto 2017-05-19 um 09 55 38" src="https://cloud.githubusercontent.com/assets/22769111/26238505/a63bcfdc-3c79-11e7-8351-49b3f32d9ff2.png">

**Comment by vellip** [comment]
Maybe try and make it several paths instead of just one big.

**Comment by kleingeist** [comment]
@damusp is the agenda-setting icon [1] also broken? or is the clip correctly filled?

[1] https://github.com/liqd/a4-meinberlin/blob/master/meinberlin/static/images/blueprints/agenda-setting.svg

**Comment by damusp** [comment]
oh, thanks for noticing! the clip is not supposed to be filled.

**Comment by xi** [comment]
I will fix it.
