### ISSUE TITLE
can move polygon on all maps in both projects and plans

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4281]
**URL:** eg for projects https://meinberlin-dev.liqd.net/dashboard/projects/moderiertes-projekt-testprojekt/point/ and for plans https://meinberlin-dev.liqd.net/dashboard/organisations/permanent-test-projects/plans/82/ and in userfrontend https://meinberlin-dev.liqd.net/projekte/carolin-findet-ihrberlin-2-2/
**user:** any (frontend) and registered (dashboard)
**expected behaviour:** cannot move polygone
**behaviour:** can move polygone
**important screensize:**
**device & browser:** tested on monterey chrome and firefox
**Comment/Question:** when this happened on a+ we tested on meinBerlin and as I remember it wasn't there or we fixed it. It worked afterwards.

Screenshot?

**Comment by fuzzylogic2000** [comment]
fixed
