### ISSUE TITLE
Deleted comments remain shown

### ISSUE THREAD

**Issue by 2e2a** [liqd/a4-meinberlin#435]
After a comment is deleted you see this:
![deleted_comment](https://cloud.githubusercontent.com/assets/16001917/26309075/f041b324-3efb-11e7-872b-b10d0d92d6ba.png)

e.g. https://meinberlin-dev.liqd.net/topicprio/topic1/

**Comment by xi** [comment]
This is intended behavior. We could maybe do something about the styling.

**Comment by 2e2a** [comment]
interesting

**Comment by 2e2a** [comment]
Will do the styling when redoing the comments.
