### ISSUE TITLE
make install - npm doesn't resolve

### ISSUE THREAD

**Issue by raynor84** [liqd/a4-meinberlin#4372]
Hi,

I'm getting following error, that does not resolve:

npm install --no-save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: a4-meinberlin@2.1.0
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   peer react@">=16.0.0" from @testing-library/react-native@9.0.0
npm ERR!   node_modules/@testing-library/react-native
npm ERR!     dev @testing-library/react-native@"9.0.0" from the root project
npm ERR!   peer react@"18.0.0" from react-native@0.69.1
npm ERR!   node_modules/react-native
npm ERR!     peer react-native@">=0.59" from @testing-library/react-native@9.0.0
npm ERR!     node_modules/@testing-library/react-native
npm ERR!       dev @testing-library/react-native@"9.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^18.2.0" from react-test-renderer@18.2.0
npm ERR! node_modules/react-test-renderer
npm ERR!   peer react-test-renderer@">=16.0.0" from @testing-library/react-native@9.0.0
npm ERR!   node_modules/@testing-library/react-native
npm ERR!     dev @testing-library/react-native@"9.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/stefan/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/stefan/.npm/_logs/2022-07-11T14_26_13_755Z-debug-0.log
make: *** [Makefile:51: install] Fehler 1

I tried some different versions... and took a previous version of your code from March 2022.

Kind Regards

Stefan

**Comment by goapunk** [comment]
Hi Stefan,
with nodejs version > 14.0.0 you need to use `npm install --legacy-peer-deps` instead of just `npm install`. As you are using the makefile, just run `npm install --legacy-peer-deps` before you run `make install``.

If that doesn't fix your issue let me know!

Cheers,
Julian

**Comment by raynor84** [comment]
that did it thx.
