### ISSUE TITLE
notification for starting/ending project is send for unpublished modules

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4383]
**URL:** https://meinberlin-dev.liqd.net/dashboard/modules/interaktive-veranstaltung-17/phases/
**user:** any
**expected behaviour:** no notification should be send for modules that are not shown in a published project
**behaviour:** notification sent for both starting and ending of phase
**important screensize:**
**device & browser:** 
**Comment/Question:** happened on prod and a user got an e-mail, I tested on dev

Screenshot?

**Comment by fuzzylogic2000** [comment]
fixed in release, will also be fixed in main as soon as a4 is updated
