### ISSUE TITLE
Rating Buttons 

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#4470]
**URL:** https://speakup.digital/projects/feedback-fur-speakup/
**expected behaviour:** *Expect to read how many people rated positive/negative*
**behaviour:** *Currently the whole button gets green/red*
**important screensize:** *both*
**device & browser:** *Safari Version 15.6.1 (17613.3.9.1.16)*

<img width="663" alt="Screenshot 2022-09-13 at 10 51 02" src="https://user-images.githubusercontent.com/59610786/189857130-b34eb0c9-40c0-4762-902b-6e4406795685.png">
<img width="653" alt="Screenshot 2022-09-13 at 10 52 46" src="https://user-images.githubusercontent.com/59610786/189857517-edfabef8-42e9-4f24-a231-91cb2c672597.png">

**Comment by fuzzylogic2000** [comment]
fixed!
