### ISSUE TITLE
#6422 [mB] improve pagination in all lists on platform

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#4485]
**URL:** https://meinberlin-dev.liqd.net/projekte/burgerhaushalt-3-phasen/?mode=list
**important screensize:** *Both*
**device & browser:** *Safari Version 15.6.1 (17613.3.9.1.16) + Chrome Version 104.0.5112.101*
**Comment/Question:**
01 - Currently when the user clicks on a new page, the list refreshes without having to reload the page, thanks for this, it is already much better than reloading the whole page, as the projects have a rather long introduction. My question is, Will it make sense to leave it that way when we have a long list of ideas or would it be possible to add an anchor link snippet from the beginning of the list?

02 – Don't we need a H2 - Contributions/Ideas List here?
<img width="307" alt="Screenshot 2022-09-20 at 09 52 41" src="https://user-images.githubusercontent.com/59610786/191201354-5dba156b-e0f4-4fdf-896e-3b956de63206.png">

03 – Sorry, I never checked this before cause its our CI, but I decided to double check and discovered that our Hover styling using Grey + Pink Text doesn't have enough contrast, it's not tragic, but changing it a bit to the darker pink (or leave all the backgrounds white) would pass AA 4.5;1 and 3:1, currently it passes only the AA 3:1. 
Example: 
<img width="547" alt="Screenshot 2022-09-20 at 09 50 56" src="https://user-images.githubusercontent.com/59610786/191203701-c3dc662c-da9c-40bf-8863-14ffa8de30a9.png">
<img width="146" alt="Screenshot 2022-09-20 at 09 50 47" src="https://user-images.githubusercontent.com/59610786/191203710-154b0fcb-9900-436a-8b77-04ee3a031e66.png">
<img width="192" alt="Screenshot 2022-09-20 at 10 10 54" src="https://user-images.githubusercontent.com/59610786/191203898-cda55079-2db6-4dbf-abed-feb0a99adb58.png">

Unfortunately, this would also affect the pagination: 
<img width="312" alt="Screenshot 2022-09-20 at 10 11 37" src="https://user-images.githubusercontent.com/59610786/191204024-8b76387d-0fbe-4a78-9927-3bbebfdd33bb.png">

As I said, it's not the most urgent thing since we used the logged in dropdown menu during this whole time but if it's possible to change the pink to a slightly darker one, our dark-pink colour is #CD0055. 

04 – It seems that there is a pixel off here
<img width="587" alt="Screenshot 2022-09-20 at 11 30 40" src="https://user-images.githubusercontent.com/59610786/191223264-1d575aff-51db-4959-88ce-fc6de476b294.png">

Thanks! 
**

**Comment by khamui** [comment]
@mcastro-lqd to the points you caught while reviewing/testing:

1) Not sure if I am following. Meaning after clicking on another page in pagination it would scroll to the beginning of the list? I think it would be possible, but probably an improvement (story) i guess.

2) yes, i think that is true. I can change it to h2. That fine @phillimorland ?

3) this will change the primary color generally right? so it will affect everything, not only text in front of grey background? @phillimorland @mcastro-lqd shall i change it?

4) could not replicate in Safari and chrome (maybe fixed in the meantime?)
