### ISSUE TITLE
#6421 [mB] notification for contact in proposal form

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#4486]
**important screensize:** *Both*
**device & browser:** *Safari Version 15.6.1 (17613.3.9.1.16)*
**Comment/Question:** As far as I understood, the new Proposal Contact Wording is not implemented. Is that right? Ignore if it's being updated but apparently this story was supposed to be finished

<img width="832" alt="Screenshot 2022-09-20 at 12 14 38" src="https://user-images.githubusercontent.com/59610786/191232102-30690ff2-5ae7-48c5-9355-952fe780196d.png">

**New Text in German**: _Für Rückfragen bzw. im Falle einer Umsetzung meines Vorschlags können Sie mich kontaktieren. Ich werde automatisch benachrichtigt, wenn es eine Statusänderung oder eine offizielle Rückmeldung zu meinem Vorschlag gibt._
**New Text in English**: _For questions or in case of implementation of my proposal you can contact me. I will receive automatic notifications for any status update or official statement to my proposal_

**Comment by fuzzylogic2000** [comment]
Right! I think the wording was changed after the story was done. Will change it!

**Comment by fuzzylogic2000** [comment]
fixed with https://github.com/liqd/a4-meinberlin/pull/4517
