### ISSUE TITLE
change budget limit to a reasonable number

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4502]
**URL:** https://meinberlin-dev.liqd.net/budgeting/create/module/burgerinnenhaushalt-3-phasen-5/
**user:** registered user
**expected behaviour:** the error message for the budget limit is reasonable
**behaviour:** the limit is 2147483647
**important screensize:**
**device & browser:** 
**Comment/Question:**  we can set it to 100 000 000. Is that an enhancement issue or should be a story?

Screenshot?
![Bildschirmfoto 2022-09-22 um 11 33 17](https://user-images.githubusercontent.com/35491681/191751674-7429763a-b7a0-418e-b221-693a480fdcdd.png)

**Comment by fuzzylogic2000** [comment]
That's easy, we can do that.
