### ISSUE TITLE
space in budget form field

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4504]
**URL:** https://meinberlin-dev.liqd.net/budgeting/2021-00665/update/
**user:** registered
**expected behaviour:** I cannot enter space in the budget field and if I can, the error warning helps me understand
**behaviour:** when having space before or after number, the warning from firefox says: please insert a number. As I have done that and may not realize the space, this may be confusing. 
**important screensize:**
**device & browser:**  firefox on mac
**Comment/Question:** Can we influence that? In chrome you cannot enter space and in safari the space is being ignored and deleted with saving.

**Comment by fuzzylogic2000** [comment]
As that's a number field from Django, we will have to write our own field to clean the spaces out. That would be a story. As this is not important (right?!), we should just close this issue. Please reopen if you disagree.
