### ISSUE TITLE
filter budgeting list: pluralisation of wirding for results

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#4522]
**URL:** 
**user:** 
**expected behaviour:** 
**behaviour:** For the freetext filter, when there was only one proposal found, it says "1 results found"
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by CarolingerSeilchenspringer** [comment]
can we have as wording "x Vorschläge/ proposals" when nothing has been entered in freetext filter and "1 Suchergebnis/ result" or "x Suchergebnisse/ results" when filter has been used?

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer Yes, we can do that, but I don't think that's a good idea. It gets too complicated if we have to check the pluralization as well as if the filters were used. Only checking the number and the pluralization is easier and less likely to break. 
Should we use singular "1 Vorschlag/ proposal" and plural "x Vorschläge/ proposals" then? Or do you prefer "Ein Vorschlag/ one proposal" for the singular?
