### ISSUE TITLE
budgeting filter buttons don't lose focus/hover after click

### ISSUE THREAD

**Issue by goapunk** [liqd/a4-meinberlin#4547]
**URL:** https://meinberlin-dev.liqd.net/projekte/burgerhaushalt-3-phasen-testprojekt/?mode=list
**user:** any
**expected behaviour:** button state turns to not hover/not focus, background turns white
**behaviour:** button state stays focused/hovering, background is grey
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by goapunk** [comment]
seems to only apply to the `Filter` button now, the others work

**Comment by fuzzylogic2000** [comment]
> @phillimorland The grey focus-ring is still there in this PR, but I find it harder to see than when the whoole button is grey. I think the problem in the issue is, that the ring is gone, but the (filter expand) button is still grey after it was used.

I think this might be an issue of expectation, it's still grey because after being clicked the focus is still on the button, if you tab through and press enter to open the filters, you must tab again to move the focus to the next item so the behaviour is correct for keyboard users but I guess not great for mouse users? not really sure what to do here?!

_Originally posted by @phillimorland in https://github.com/liqd/a4-meinberlin/issues/4605#issuecomment-1289083950_

**Comment by khamui** [comment]
hm, also not sure what is best. if we tab inside of the dropdown (e.g. selecting an option), the focus-ring appears blue. Maybe it makes sense to make the focus-ring always blue and use the grey background only for hover?

Or we leave it how it is, in doubt it is better to use the a11y friendly way?

**Comment by mcastro-lqd** [comment]
@khamui Yeah, lets do the focus blue and grey background for hover

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer @mcastro-lqd while checking this I realised we use 2 different filter hide buttons, one for comments and one on this list, as we should have the same for consistency, which do you guys prefer?
list button
![screenshot(39)](https://user-images.githubusercontent.com/5871230/201143410-d83f7374-3869-4990-9daf-aff1709aa60c.png)
comment button with open and close behavior: 
![screenshot(38)](https://user-images.githubusercontent.com/5871230/201143573-7b9089e8-e245-4d41-8de4-2c480788a4ed.png)
![screenshot(37)](https://user-images.githubusercontent.com/5871230/201143590-4f62e436-efce-4e9e-bdf9-70ffc2eee64c.png)

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland as we use the comment button also on project overview mobile version, I'd suggest we replace the list button by comment button

**Comment by mcastro-lqd** [comment]
True, I always might have got confused with GD, sorry. I'd also stick to what we already have

**Comment by phillimorland** [comment]
@mcastro-lqd @CarolingerSeilchenspringer sorry I have more questions here, I was trying to make filters more accessible and realised that they are all shown even when there are no ideas on the list, should they be there if that is the case?

**Comment by mcastro-lqd** [comment]
Hey @phillimorland thanks for point that out, If its possible to not show them in an empty state, its even better :)

**Comment by fuzzylogic2000** [comment]
It should be like that.
