### ISSUE TITLE
Budgeting: detail link "x More" on tiles looks off

### ISSUE THREAD

**Issue by khamui** [liqd/a4-meinberlin#4575]
**URL:** 
**user:** 
**expected behaviour:** link should be vertically centered as in design
**behaviour:** is aligned to the bottom
**important screensize:**
**device & browser:** 
**Comment/Question:** 
<img width="1049" alt="Bildschirmfoto 2022-10-18 um 14 28 01" src="https://user-images.githubusercontent.com/52801593/196443308-16c94050-3551-4fe9-b6e0-13d652d39d6b.png">

**Comment by fuzzylogic2000** [comment]
The "More" also needs to be marked as translatable.

**Comment by fuzzylogic2000** [comment]
another minor issue: between 364-400px there is a line break between "2" and "More".

_Originally posted by @goapunk in https://github.com/liqd/a4-meinberlin/pull/4572#discussion_r998424447_

**Comment by phillimorland** [comment]
@khamui I don't think we shouldn't use template literals inside the render as means the strings are not translated, also i'm not sure if its the clearest way to write it anyway specially when there is no need if we don't need it to be multi line, what do you think?

**Comment by khamui** [comment]
@phillimorland not sure if i follow the second part. Do you mean the wording `x More` is not clear? And the multi line should be avoided?

**Comment by phillimorland** [comment]
@khamui I mean we can just use normal concatenation if we don't need the string to be multiline right? like `{x} {translated.more}` there's no need for the the `$` or ticks?!
