### ISSUE TITLE
list views label filter

### ISSUE THREAD

**Issue by Rineee** [liqd/a4-meinberlin#4581]
**URL:** https://meinberlin-dev.liqd.net/projekte/burgerhaushalt-3-phasen-testprojekt/?mode=list
**user:** 
**expected behaviour:** the filters are arranged nicely
**behaviour:** when there are all filters in a list view (category, labels, archived, sorting) it gets too crowded and the sorting filter is off
**important screensize:**
**device & browser:** 
**Comment/Question:** Since this was not in the story, not sure if it is an issue? @CarolingerSeilchenspringer @mcastro-lqd I think we would need a design for that? 

Screenshot?
![image](https://user-images.githubusercontent.com/9589411/196706630-dbd82a26-5cba-4a72-bc39-f5905f93b048.png)

**Comment by fuzzylogic2000** [comment]
I think the only modules that can have a ll filters are the budgeting and the kiezkasse, right @CarolingerSeilchenspringer ? The other ideas cannot be archived?

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 @Rineee yes, archived is only for budgeting and Kiezkasse, but the issue will come back with the filter for the ampel, also a filter that all idea-modules will have. This actually means that we will have to do the filter re-design also for django list, right? This would be a story then. Will close the issue and write a story.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 @Rineee as we don't have the search function for the django list the design would be different. Before we do that we should think about react lists for brainstorming and idea collection, those are the relevant modules here. Let's take it to refinement.
