### ISSUE TITLE
#6487 Limitation of code generation doesn't work 

### ISSUE THREAD

**Issue by SandisStudi** [liqd/a4-meinberlin#4594]
**URL:** g.e. https://meinberlin-dev.liqd.net/dashboard/modules/burgerinnenhaushalt-3-phasen-10/download-codes/ or https://meinberlin-dev.liqd.net/dashboard/modules/burgerinnenhaushalt-3-phasen-12/download-codes/
**user:** admin
**expected behaviour:** As an admin I should not be able to generate more then 5 Mio Codes per one module 
**behaviour:** If I create a new participatory budgeting module (3 phases) and send more code generating requests shortly one after another(each one not bigger then 5 Mia Codes) that summed up are more then 5 Mio codes , the code generation limit doesn’t work till these requests are done and I get more then 5 Mio Codes
**important screensize:** ---
**device & browser:** Mac Firefox, Chrome, Edge
**Comment/Question:** ---

**Comment by CarolingerSeilchenspringer** [comment]
will close the issue as this is only when task has not been finished and it is only for admins
