### ISSUE TITLE
#6487 Screenreader doesnt spell properly

### ISSUE THREAD

**Issue by SandisStudi** [liqd/a4-meinberlin#4595]
**URL:** g.e. https://meinberlin-dev.liqd.net/dashboard/modules/burgerinnenhaushalt-3-phasen-10/download-codes/
**user:** admin
**expected behaviour:** The most used screenreaders (JAWS and NVDA) should tell me how many participatory codes I have already generated in participatory budgeting module (3 phases), and should spell the abbreviations right and read the numbers 
**behaviour:** * Neither NVDA nor JAWS as a screenreader tells me the number of already generated codes. Both Screenreadrs reads the term "code package no.1" as “Code Package NO” without a number
**important screensize:**----
**device & browser:** Mac and Firefox,Chrome,Edge
**Comment/Question:**

**Comment by fuzzylogic2000** [comment]
I would say in the mB case this is a translation issue as we will not have this problem in German. Can you please checek again after the translations are done?

**Comment by fuzzylogic2000** [comment]
The translaton should already be there (in ten minutes), so: could you check again @SandisStudi ? Thank you!

**Comment by jostertag** [comment]
The translation is there now, I just checked it. But the screenreader tells me now always "Code Paket Nr. 1 herunterladen", even when I'm on the link of the other code packages. So for example if I'm on the "Herunterladen-Link" for "Code Paket Nr. 5" the screenreader still tells me "Code Paket Nr. 1 herunterladen".
