### ISSUE TITLE
tested 6519: wording change dashboard

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4599]
**URL:** https://meinberlin-dev.liqd.net/dashboard/modules/burgerinnenhaushalt-3-phasen-5/labels/
**user:** initiator
**expected behaviour:** 
**behaviour:** the last sentence is wrong as long as react list is not released. 
**important screensize:**
**device & browser:** 
**Comment/Question:** temporarily take out last sentence from translation and mark for a later release that we have to take it back in.

Screenshot?
<img width="679" alt="Bildschirmfoto 2022-10-21 um 13 55 49" src="https://user-images.githubusercontent.com/35491681/197190188-80abc4dc-8d34-4ce6-a580-7656916eaec4.png">

**Comment by fuzzylogic2000** [comment]
The sentence is wrong anyway, as we added the label filter to all lists now. So, all lists can be filtered for it and we should just change the wording.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 then let's change the last sentence to: EN:  The list of all ideas can be filtered by labels. GER: Die Liste aller Ideen kann nach Merkmalen gefiltert werden.
