### ISSUE TITLE
testing 6520: support icon and three-dot-menue not aligned

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4600]
**URL:** https://meinberlin-dev.liqd.net/budgeting/2022-00864/
**user:** any
**expected behaviour:** support icon and three-dot-menue not aligned
**behaviour:** in rating phase they are aligned
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

<img width="679" alt="Bildschirmfoto 2022-10-21 um 14 09 22" src="https://user-images.githubusercontent.com/35491681/197192477-69d5b434-9c29-45d8-9764-f355385854e9.png">

**Comment by phillimorland** [comment]
this is a task
