### ISSUE TITLE
testing 6520: on map there is still the rating in support phase

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4601]
**URL:** https://meinberlin-dev.liqd.net/projekte/support-phase/?mode=map&ordering=dailyrandom
**user:** any
**expected behaviour:** I see support symbol
**behaviour:** I see rating symbol
**important screensize:**
**device & browser:** 
**Comment/Question:** Can we even change this as long as map is django?

<img width="308" alt="Bildschirmfoto 2022-10-21 um 14 12 53" src="https://user-images.githubusercontent.com/35491681/197193038-7fe2d3e7-550f-4286-ae1a-cad82d573039.png">

**Comment by fuzzylogic2000** [comment]
Yeah, sorry, it didn't make sense to remove it without adding the new info, so it's still there. But we are doing it! It will be tested again with the next story as that adds showing the support. :)
