### ISSUE TITLE
Bad UX on finished projects

### ISSUE THREAD

**Issue by xi** [liqd/a4-meinberlin#462]
In the project detail, we usually show the title and description of the active phase. When no phase is active, we show "Participation is not possible at the moment." as a title and no description.

This is a bit harsh and does not really explain, *why* participation is not possible.

Maybe we can change the wording and add a description. We should explain:

- Why is participation not possible
- What can I do instead?

**Comment by damusp** [comment]
It would be best if we could have different texts for the different occassions. 
Participation might not be possible when:
- the project is finished
- there is temporarily no active phase
- there is an offline event going on (?)

I am not happy with this design, but to get an idea, here's what it should basically feel like:
![finished_message](https://cloud.githubusercontent.com/assets/22769111/26723924/1eb9f4fc-4797-11e7-8690-696023492016.png)

**Comment by damusp** [comment]
this is now a user story

**Comment by xi** [comment]
This has been fixed in #631
