### ISSUE TITLE
[6519] Wording "More"-Link Proposal Tiles

### ISSUE THREAD

**Issue by jostertag** [liqd/a4-meinberlin#4624]
**URL:** https://meinberlin-dev.liqd.net/projekte/burgerhaushalt-3-phasen-testprojekt/?mode=list (for example)
**user:** all
**expected behaviour:** The wording for the "More"-Link in the proposal tiles should be in german.
**behaviour:** The wording is in english: "More".
**important screensize:** - 
**device & browser:** any
**Comment/Question:** I don't know if this is part of the story or if the wording is on purpose in english. 

Screenshot?

**Comment by fuzzylogic2000** [comment]
Same here: please translate yourself and let us know if it isn't available on weblate.
