### ISSUE TITLE
[6560] Wording issue "Status"-Filter

### ISSUE THREAD

**Issue by jostertag** [liqd/a4-meinberlin#4626]
**URL:** https://meinberlin-dev.liqd.net/projekte/burgerhaushalt-3-phasen-testprojekt/?mode=list
**user:** all
**expected behaviour:** the wording should be consistent with the agreed wording in the story.
**behaviour:** 
- [ ] the wording in german is "checked" instead of "geprüft"
- [ ] the wording in german is "nicht umgesetzt" instead of "wird nicht umgesetzt"

**important screensize:** -
**device & browser:** all
**Comment/Question:** 

Screenshot?
<img width="910" alt="Bildschirmfoto 2022-10-25 um 18 30 15" src="https://user-images.githubusercontent.com/113608720/197831237-1991737a-ae44-4808-bd4f-a2aaabf1c589.png">

**Comment by fuzzylogic2000** [comment]
Don't you do the translations? The strinds in webölate should be up to date, let us know if you can't find them.
