### ISSUE TITLE
#6460 dashboard: "show in project" button not updarted after poll save

### ISSUE THREAD

**Issue by Ronja-liqd** [liqd/a4-meinberlin#4628]
**URL:** 
**user:** initiator/admin
**expected behaviour:** Right afterI click on on "save" button after putting in questions for the first time to a poll project, I can click on the "show in project" button to add it
**behaviour:** "Show in project" button is only clickable after refreshing the page.
**important screensize:**
**device & browser:** any
**Comment/Question:** Same issue occurs when saving text for the first time in the text commenting modul.

Screenshot?

**Comment by fuzzylogic2000** [comment]
This is in the dashboard, right? 
You need to fill in the module info to be allowed to then add it to the project, but the page is not reloaded after the poll or text document changes, so the button is not updated and still disabled.

**Comment by Ronja-liqd** [comment]
I am honestly not quite sure if I understand your anwer correctely but I will add some maybe helpful screenshots.

The difference is that in stage, after I have filled in the questions for the poll project and clicked on save, the "show in project" button is clickable. But in dev it is only when I refresh the page after having saved the questions.

dev after putting in all information:
![Screenshot 2022-10-26 at 16-06-41 meinBerlin](https://user-images.githubusercontent.com/113356258/198049334-4b231669-fa2f-4ff5-9411-482f24021471.png)

stage after putting in all information:
![Screenshot 2022-10-26 at 16-08-21 meinBerlin](https://user-images.githubusercontent.com/113356258/198048952-8795c2a5-5f11-4c2a-b383-a107189de55c.png)

**Comment by phillimorland** [comment]
NOTE: also an issue for documents and if we introduce other react actions into dashboard will be an issue there also
