### ISSUE TITLE
IE11: beberlin logo is a blue rectangle

### ISSUE THREAD

**Issue by vellip** [liqd/a4-meinberlin#463]
The SVG document is missing the viewbox attribute. Same happens for tempelhof. See: https://stackoverflow.com/questions/27970520/svg-with-width-height-doesnt-scale-on-ie9-10-11

<img width="459" alt="screen shot 2017-05-29 at 09 47 22" src="https://cloud.githubusercontent.com/assets/16354712/26541075/806f52a0-4454-11e7-8fa7-26290ccad664.png">

**Comment by xi** [comment]
Fixed by 24b6d30
