### ISSUE TITLE
#6460 Affiliated comments are not shown in interactive event

### ISSUE THREAD

**Issue by Ronja-liqd** [liqd/a4-meinberlin#4630]
**URL:** https://meinberlin-dev.liqd.net/projekte/module/interaktive-veranstaltung/
**user:** any
**expected behaviour:** When in an interactive event project an affiliation is selected to filter the comments, the comments with that affiliation are displayed.
**behaviour:** No comments are displayed after selecting an affiliation.
**important screensize:**
**device & browser:** any
**Comment/Question:** The chosen affiliation is also not shown on the comment.

Screenshot?

no comments after selecting affiliation filter
![Screenshot 2022-10-26 at 13-55-46 Tests Ronitiator — meinBerlin](https://user-images.githubusercontent.com/113356258/198022692-856e5fd4-f1c0-4903-a47e-13f1223a3d7c.png)

comments missing affiliation:
![Screenshot 2022-10-26 at 13-55-09 Tests Ronitiator — meinBerlin](https://user-images.githubusercontent.com/113356258/198022683-3c5a0ff8-7f39-4338-92e9-81d906c0271e.png)

**Comment by Rineee** [comment]
Oh no, and also the whole box is broken..

**Comment by phillimorland** [comment]
@Rineee what box?
