### ISSUE TITLE
#6460 Up/Downvotes only shown after refreshing

### ISSUE THREAD

**Issue by Ronja-liqd** [liqd/a4-meinberlin#4631]
**URL:** https://meinberlin-dev.liqd.net/text/paragraphs/113/ ; https://meinberlin-dev.liqd.net/budgeting/2022-00885/
**user:** 
**expected behaviour:** When I click on the up/downvote button of an answer to a comment and hide them afterwards, my votings are still there when I dehide them again.
**behaviour:** The up/downvotes are only shown after the page is refeshed.
**important screensize:**
**device & browser:** any
**Comment/Question:**  green "Beitrag erstellt" banner also shortly shows up, after dehiding the answers

Screenshot?

before clicking "hide answers":
![Screenshot 2022-10-26 at 15-15-59 Titel 1 — meinBerlin](https://user-images.githubusercontent.com/113356258/198038373-2d79094e-f3b5-4b71-a3f2-0e60ec3f448f.png)

when looking at the answers again:
![Screenshot 2022-10-26 at 15-16-23 Titel 1 — meinBerlin](https://user-images.githubusercontent.com/113356258/198038390-b2c07a61-d745-42e6-9746-b5784628c10c.png)

"Beitrag erstellt" button after dehiding the anwers:
<img width="795" alt="Bildschirmfoto 2022-10-26 um 15 37 12" src="https://user-images.githubusercontent.com/113356258/198041032-6c77c2b3-10bc-48ed-afb1-b03b6c251120.png">

**Comment by CarolingerSeilchenspringer** [comment]
will close after taking to @Ronja-liqd again as this is the same on stage and can stay like that.
