### ISSUE TITLE
Space underneath footer

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-meinberlin#465]
If a page does not contain enough content, the footer does not stick to the bottom
![bildschirmfoto 2017-05-29 um 11 18 08](https://cloud.githubusercontent.com/assets/2905743/26544053/9f0fd89a-4460-11e7-8a5d-1719e6733596.png)

**Comment by damusp** [comment]
I am bothered by empty looking pages in the first place, but that's a different story. @xi, your solution is fine imo.
