### ISSUE TITLE
#6536 idea list: long labels for mobile not breaking

### ISSUE THREAD

**Issue by SandisStudi** [liqd/a4-meinberlin#4657]
**URL:** https://meinberlin-dev.liqd.net/projekte/module/brainstorming-mit-karte-7/?mode=list
**user:** all
**expected behaviour:** If i look at proposal list i want to see the "Merkmale" and "Kategorien" in the proposal tiles in a nice way without breaking the frame
**behaviour:** If the name of "Merkmale" or "Kategorien" gets too long, the tile of "Merkmale" or "Kategorie" breaks the frame of proposal tile 
**important screensize:** 
**device & browser:** only so far Samsung Galaxy S20
**Comment/Question:** 

Screenshot?
![grafik](https://user-images.githubusercontent.com/113611764/200363181-90daaa4a-ab93-46d2-9529-0cb2027b2cf8.png)

**Comment by fuzzylogic2000** [comment]
For the link, both proposals neither have labels nor categories?
And on Samsung Galaxy means, that they are cut off for all other devices? Can you also add a screenshot of one of these where it's not broken?

**Comment by SandisStudi** [comment]
Yeah someone had removed it/changed it back to short version
I tested it now with max. 40 charecters in "merkmale" and "label" and Samsung galaxy S 20 with chorme still has a little bit of frame break 

![bs_realdroid_Mobile_Samsung Galaxy S20-11 0-1440x3200(1)](https://user-images.githubusercontent.com/113611764/205058644-30668282-a993-4391-bf4b-4d5fc83d0faf.jpg)

**Comment by SandisStudi** [comment]
for samsung galaxy S 10 (chrome) and Iphone 13 (safari) there are no frame breaks

![bs_realdroid_Mobile_Samsung Galaxy S10-9 0-1440x2960](https://user-images.githubusercontent.com/113611764/205058871-3b013af2-7309-4cdc-80bb-4355fd29b5f9.jpg)
![bs_realios_Mobile_iPhone 13-15 0](https://user-images.githubusercontent.com/113611764/205058882-afa75bc3-c5df-4b48-9c9f-9a0d55409dd2.jpg)

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer @mcastro-lqd We do currently cut the labels off after 40 characters. That's still quite long. Can we shorten them to 30 chars?
