### ISSUE TITLE
#6536 Screenreader and numbers in "Merkmal" titel

### ISSUE THREAD

**Issue by SandisStudi** [liqd/a4-meinberlin#4658]
**URL:** https://meinberlin-dev.liqd.net/projekte/module/priorisierung-2/?ordering=name&labels=&category=
**user:** all
**expected behaviour:** If i use screenreader and there is a long number in the name of "Merkmal", i want that the screenreader reads it to me in a understandable way
**behaviour:** NWDA screenreader reads a long number in the titel of "Merkmale"/ "Merkmale" tile as hundreds and tens
**important screensize:**no
**device & browser:** Chrome, Edge, Firefox

**Comment by CarolingerSeilchenspringer** [comment]
as mentioned towards @phillimorland please check all the screen reader related issues and then let's talk about how to handle them. Maybe best to collect all and have a last test when everything is done and then do all at once?

**Comment by phillimorland** [comment]
NOTE: this is user generated content expected to be a string, we could add help text explaining this but that's it

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer What are we meant to do here? Should we add a helptext, so that people hopefully add text for Markmale instead of long numbers? Do we need to do that? Do real people not testing add numbers like that?

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 @SandisStudi @phillimorland yes, this is an edgecase that I think won't happen so I don't think we need to change either screenreader nor helptext.
