### ISSUE TITLE
#6536  Screenreader and "+"/"-" button in the map

### ISSUE THREAD

**Issue by SandisStudi** [liqd/a4-meinberlin#4660]
**URL:** https://meinberlin-dev.liqd.net/projekte/module/priorisierung-mit-karte/
**user:** all
**expected behaviour:** If i target the "+"/"-" button in the map with screenreader, i want to understand what is this button and what i can do with it
**behaviour:** JAWS and NVDA reads the "+"/"-" button in an incomprehnsible way
**important screensize:**non
**device & browser:** NVDA (Chrome, Edge, Firefox) JAWS (Chrome)

**Comment by phillimorland** [comment]
NOTE: check how wheel map deals with their map controls
