### ISSUE TITLE
Screenreader and proposal sites

### ISSUE THREAD

**Issue by SandisStudi** [liqd/a4-meinberlin#4661]
**URL:** https://meinberlin-dev.liqd.net/maptopicprio/2022-00911/
**user:** all
**expected behaviour:** If i take a look at the proposal site, i want that the screenreader reads me the name of the proposal in the titel and the tiles "Kategorie" and "Merkmale" in the subtitel
**behaviour:** JAWS and NVDA reads me either the name of the proposal in the titel nor the "Merkmale", "Kategorie" tiles in the suubtitel
**important screensize:** non 
**device & browser:** NVDA (Chrome, FIrefox, Edge), JAWS (Chrome)

**Comment by phillimorland** [comment]
see comment https://github.com/liqd/a4-meinberlin/issues/4659

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer please read the comment from the referenced issue and reopen if there is still a problem
