### ISSUE TITLE
in idea creator has no link to user profile

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-meinberlin#467]
I can't click on the creators username to access the userprofile, e.g. here: https://meinberlin-stage.liqd.net/budgeting/pflege-des-dorfteichs-bohnsdorf/

**Comment by xi** [comment]
Thanks for the feedback!

This is actually intentional. The user profile that was introduced in #458 mainly exist so that the links in comments do not lead to 404 pages. It is not yet ready to be a prominent feature yet.
