### ISSUE TITLE
link to profile breaks if space in username

### ISSUE THREAD

**Issue by vellip** [liqd/a4-meinberlin#468]

**Comment by xi** [comment]
Can you give an example? I found an example that works fine; https://meinberlin-stage.liqd.net/profile/Kerstin%20Josupeit/

**Comment by xi** [comment]
I could not find any space related issues, but I found a 500 error on a username with umlaut: https://meinberlin-stage.liqd.net/profile/B%C3%A4rlinerin/

**Comment by 2e2a** [comment]
The problem was the encoding of the `x-ajax-path` header.
