### ISSUE TITLE
#6704 E-Mail Notification for Status of Ideas

### ISSUE THREAD

**Issue by jostertag** [liqd/a4-meinberlin#4697]
**URL:** https://meinberlin-dev.liqd.net/projekte/module/ideensammlung-mit-karte-6/?mode=list
**user:** registered user
**expected behaviour:** In Moduls with Ideas, the user should get a notification when the status of his/her idea has been changed by the initiator or moderator.
**behaviour:** In Moduls with Ideas (except Participatory Budget), the user doesn't get a notification when the status of his/her idea has been changed.
**important screensize:** any
**device & browser:** any
**Comment/Question:** In the participatory budget, the user is getting an E-Mail notification with the respective text.

Screenshot?

**Comment by fuzzylogic2000** [comment]
@jostertag Are you sure? It works locally. Can you check that your idea crator has enabled Notifications? (In https://meinberlin-dev.liqd.net/account/profile/). 
And if that is the reason, the explanation is that the other email is sent to the contact that you give in the proposal form, no matter if you have enabled notifications or not as you agree to being contacted directly in the form. For ideas, the email of the creator of the idea is used and thus the notifications need to be enabled.
And if that's not the reason, I have no idea. Maybe you need to use different users for the idea creator and the moderator role?

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 @jostertag  I tested again for idea collection and it worked. So I guess @fuzzylogic2000 is right with her explanation and I will close the issue. If you still test differently @jostertag please reopen the issue.
