### ISSUE TITLE
#6704 Form of address E-Mail-Notification

### ISSUE THREAD

**Issue by jostertag** [liqd/a4-meinberlin#4698]
**URL:** https://meinberlin-dev.liqd.net/budgeting/2022-00936/
**user:** registered user
**expected behaviour:** The user should be adressed as in other E-Mail-Notifications (the current form of address is "Hallo 'username',"
**behaviour:** The form of adress in the current E-Mail-Notification is "Hallo ,". The username is missing and there is a space before the comma.
**important screensize:** -
**device & browser:** any
**Comment/Question:** This only applies to participatory budgeting, as users in the other modules have not yet received any e-mail notification when their status changes (see [issue #4697)](https://github.com/liqd/a4-meinberlin/issues/4697))

Screenshot?
<img width="700" alt="Bildschirmfoto 2022-11-17 um 15 53 01" src="https://user-images.githubusercontent.com/113608720/202479234-e96a5c98-a655-481d-9af8-47ffc6129f1d.png">

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer This is for the messages for the contact, so for the proposals from budgeting, where we get the email address from the form and not the creator. So, we don't have the username. Should we 
- use the username of the creator (which might be weird if the username is a Quartiesmanagement and the email sth. diffrenet, 
- use the email address
- use no username ("Hallo," or "Guten Tag,")
- use the username when the email from the creator is used and no username when another email was added (this might get a bit more complicated, though.)?

I think, I would prefer option 3 ("Guten Tag,").

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 Of course option 4 would be the nicest, but also due to the wording it may be easiest to do option 3, because: in other mailings, if we have the username we always write "hallo xxx", if we don't know it, we write "Guten Tag", so that would add even more complexity to it. So go for "Guten Tag" without username. Would that change be only in participatory budgeting or in all modules?

**Comment by fuzzylogic2000** [comment]
It would only change for participatory budgeting as we send the email to the contact there and do not have the username. For the other notifications on moderator feedback or statement, we send it to the creator and thus do have the username and will continue to use it.
