### ISSUE TITLE
test 6668: two arrows for moderation tasks accordion 

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4720]
**URL:** https://meinberlin-dev.liqd.net/budgeting/2022-00903/
**user:** moderator
**expected behaviour:** one way to open accorion
**behaviour:** two arrows (one extra to the very left) to open accordion
**important screensize:**
**device & browser:** safari on mac only
**Comment/Question:** 

Screenshot?
<img width="563" alt="Bildschirmfoto 2022-11-24 um 15 44 06" src="https://user-images.githubusercontent.com/35491681/203811238-10324a21-2547-4bb2-aa4a-6472d590767a.png">

**Comment by fuzzylogic2000** [comment]
@phillimorland If you have time today, it would be great if you could have a look! But if not, that's also fine, will be in the next release, then!

**Comment by phillimorland** [comment]
@fuzzylogic2000 I don't have my mac with me while looking after guinea pigs

**Comment by fuzzylogic2000** [comment]
> @fuzzylogic2000 I don't have my mac with me while looking after guinea pigs

:heart_eyes: :hamster:

**Comment by jostertag** [comment]
I found the same problem while testing it with an Iphone (IOS), but here on Safari and !**Chrome**!
