### ISSUE TITLE
#6610 [mB] pkg 4 (moderation): moderation tasks: filter Design

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#4721]
**URL:** https://meinberlin-dev.liqd.net/budgeting/2022-00772/
**user:** *moderators*
**important screensize:** *Both*
**device & browser:** *Safari Version 16.1 (18614.2.9.1.12) and Chrome Version 107.0.5304.110*
**Comment/Question:** 
*
01 – Is it possible to leave the Text sizes/style in a way that it makes sense hierarchically? Like, the Main Idea text being the 24pt one, then Offizielle Ruckmeldung + Moderation 20pt, Subtasks 18pt Bold, Tasks 16pt Regular? 

02 – Me and Caro talked and we agreed that without React + the possibility to click on the Radio button directly, it feels really strange, so I would rather leave it without when the subtask is not completed and maybe Grey? I know this was my fault, I should have done that before but somehow I thought it would communicate better that something was missing. Im sorry. 
<img width="722" alt="Screenshot 2022-11-24 at 18 17 53" src="https://user-images.githubusercontent.com/59610786/203841673-6153f535-5d4d-4e5d-bb88-f6f0e67a7e85.png">

03 – On Safari I see a dropdown Arrow Icon before Moderation but on Chrome it works fine.  
<img width="739" alt="Screenshot 2022-11-24 at 18 39 19" src="https://user-images.githubusercontent.com/59610786/203841741-e48da894-4dae-4106-bfde-3839363ae2b0.png">

04 – It also looks weird without empty state here, I thought all the projects would have Moderation Sub-tasks but some of them may not have. So maybe if we create something like that, it would be better to understand why this bar is displayed there. 
<img width="597" alt="Screenshot 2022-11-24 at 18 44 37" src="https://user-images.githubusercontent.com/59610786/203842503-6a7f8016-064d-48aa-9413-94fbfa8ac429.png">

Thanks
*

**Comment by fuzzylogic2000** [comment]
Yes, for 1 we need to find out if that's the usual styles coming from the headlines and maybe have to adapt the sizes there.
And 2, no problem, we can do that!
