### ISSUE TITLE
Idea Description Paragraph is off

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#4722]
**URL:** https://meinberlin-dev.liqd.net/budgeting/2022-00772/
**expected behaviour:** *Expect the text to break at the right column*
**behaviour:** *Even with space when text is too long, the paragraph cross the column*
**important screensize:** *Both*
**device & browser:** *Safari*

![IMG_9200](https://user-images.githubusercontent.com/59610786/203842825-b4ad4fd8-1bd8-4423-aaee-b5397f50ee33.PNG)
<img width="828" alt="Screenshot 2022-11-24 at 18 45 36" src="https://user-images.githubusercontent.com/59610786/203842833-121f4285-fd25-4aa7-bad9-fda9e097a5bb.png">

**Comment by fuzzylogic2000** [comment]
@mcastro-lqd Can you remember how you added the text? I tried to reproduce and updated your idea, but all paragraphs I added are breaking. Only when I copied your text, the text is also not breaking. :woman_shrugging:

**Comment by mcastro-lqd** [comment]
@fuzzylogic2000 I did that a while ago, but I think I just copied + pasted the formatted text a couple of times.

**Comment by phillimorland** [comment]
@mcastro-lqd @CarolingerSeilchenspringer the original link is gone so I tried to update this one https://meinberlin-dev.liqd.net/budgeting/2022-00956/ however even when copied and pasted text I cannot reproduce, can you guys? if not can we close?

**Comment by mcastro-lqd** [comment]
@phillimorland idk, maybe it happens when bold + italic (???) https://meinberlin-dev.liqd.net/budgeting/2023-00967/

**Comment by mcastro-lqd** [comment]
@phillimorland Try copying and pasting the link, Idk why it doesn't work when is redirected from GitHub
