### ISSUE TITLE
Same styling - Thumbs Up

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#4768]
**URL:** https://meinberlin-dev.liqd.net/budgeting/2022-00958/
**expected behaviour:** *Can we copy the same style from the former button? Hover + Stroke and also add a bit spacing between icon and number*
**important screensize:** *mobile + desktop*
**device & browser:** *Safari Version 16.1 (18614.2.9.1.12)*

Currently:
![Screenshot 2022-12-14 at 16 41 18](https://user-images.githubusercontent.com/59610786/207641100-e3b8e1d6-b57e-424a-b609-80be5db447a5.png)

Proposal: 
![Screenshot 2022-12-14 at 16 41 56](https://user-images.githubusercontent.com/59610786/207641174-b1383429-2ddc-4288-a048-c8e6296be599.png)

meinBerlin:
![Screenshot 2022-12-14 at 16 41 45](https://user-images.githubusercontent.com/59610786/207641203-8325c360-5071-4280-b973-4bf10afd6c4e.png)

**Comment by CarolingerSeilchenspringer** [comment]
please consider that we have the same button in interactive event looking like this:
![Bildschirmfoto 2022-12-15 um 10 42 12](https://user-images.githubusercontent.com/35491681/207826123-9860b924-941f-4713-836d-d4bf0ddfe374.png)
