### ISSUE TITLE
Login button on index page although logged in

### ISSUE THREAD

**Issue by mkind** [liqd/a4-meinberlin#477]
On the staging and the development server, the start page advertises *Berlin mitgestalten (...) Anmelden*. The *login* button is also advertised although I am logged in. As a consequence, clicking on the link gets me to the start page again. 

![2017-05-30-095542_1230x986_scrot](https://cloud.githubusercontent.com/assets/640747/26573717/122fb32c-451f-11e7-96c4-e31b6f8128bf.png)

**Comment by 2e2a** [comment]
The call to action block is configured in wagtail and the button just takes a link, which might be different from login.

We could start matching URLs at this place and hide the button if the URL is the login URL, but this seems quite an overhead for this issue.

Decided to close.
