### ISSUE TITLE
email notification on feedback to contribution: styling of listing is off

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4807]
**URL:** notification on new feedback to contribution (eg via this project: https://meinberlin-dev.liqd.net/budgeting/2022-00945/)
**user:** registered idea/proposal contributor
**expected behaviour:** 
**behaviour:** if list is entered to feedback the dots are left while the text is centered
**important screensize:**
**device & browser:** mac mail programme
**Comment/Question:**

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer link gives a 404 and i'm not sure I follow, this is what I see on this page, is that correct? 
https://meinberlin-dev.liqd.net/budgeting/2022-00946/
 
![screenshot](https://user-images.githubusercontent.com/5871230/211621302-7d4dd19a-b8e8-475a-87a6-c00c0e15b6ff.png)

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland I meant mail notifications
<img width="677" alt="Bildschirmfoto 2023-01-11 um 09 17 29" src="https://user-images.githubusercontent.com/35491681/211753623-4eaad687-2a38-46c5-959f-86c270dc039a.png">
