### ISSUE TITLE
[mB] pkg 2 (phases): change display of phases on project/ multimodule page

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#4809]
**URL:** https://meinberlin-dev.liqd.net/projekte/burgerinnenhaushalt-3-phasen/?mode=list
**important screensize:** *Mobile*
**device & browser:** *Safari Version 16.1 (18614.2.9.1.12)*
**Comment/Question:** *
Could you try to use the same color for finished/upcoming as on Zeplin? So we have a bit more distinction of what's active? 
![Screenshot 2023-01-04 at 17 12 23](https://user-images.githubusercontent.com/59610786/210599389-692597f9-17a0-4eed-bb04-cdd46a08a75f.png)

Would it be possible to leave the Activ on top? Cause then we have more space for the date.* 
![Screenshot 2023-01-04 at 16 06 42](https://user-images.githubusercontent.com/59610786/210585105-a84da24c-4cfb-41b4-ae68-dab4981eda12.png)

Also on Safari Mobile I got this thin grey line here, on Chrome it works normally 🤷‍♂️  
![IMG_0351](https://user-images.githubusercontent.com/59610786/210585461-04b423d3-6d41-4dca-93bb-9dc57d6442ca.jpg)

**Comment by phillimorland** [comment]
will also add that with long sentence it is moved to the next line: 
https://meinberlin-dev.liqd.net/projekte/budgeting-3/
