### ISSUE TITLE
#6799 [mB] pkg 3 (navigation): back-button jumps to filtered proposal list 

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#4810]
**URL:** https://meinberlin-dev.liqd.net/projekte/burgerinnenhaushalt-3-phasen/?mode=list&moderator_feedback=CONSIDERATION
**important screensize:** *Desktop*
**device & browser:** *Safari Version 16.1 (18614.2.9.1.12) and Chrome Version 108.0.5359.94 (Official Build) (x86_64)*
**Comment/Question:**wow, this go back thing was a life changing thing. I doesn't feel so lost when I come back to the list haha Thanks!

The bottom part of the dropdown seems a bit off.
![Screenshot 2023-01-04 at 16 44 23](https://user-images.githubusercontent.com/59610786/210596355-71f881c3-a48d-404c-b711-e5fea3e43dfa.png)

Im never fully happy with all these Dropdowns when we have too many of them, but I guess that's for now what we use. Would it make sense to reduce the spacing of the filters only a bit? So we can have a clearer division. 
![Screenshot 2023-01-04 at 16 50 23](https://user-images.githubusercontent.com/59610786/210596528-89ab752d-0365-4760-a2d7-1b96af6d1944.png)

This part of the Module seems also a bit off.
![Screenshot 2023-01-04 at 16 02 03](https://user-images.githubusercontent.com/59610786/210596762-89cad87f-9f0a-4dc7-8198-53cc732766bb.png)

**

**Comment by khamui** [comment]
@mcastro-lqd the first described issue and the third (spacings) seem to be fixed already.
