### ISSUE TITLE
Issues switching from map to list after clearing filters in map view

### ISSUE THREAD

**Issue by SandisStudi** [liqd/a4-meinberlin#4815]
**URL:** https://meinberlin-dev.liqd.net/projekte/burgerhaushalt-3-phasen-mit-support-testprojekt/?mode=list
**user:** initiator, reg. User
**expected behaviour:** I want to filter the proposals in map view for „Categories“ and „Merkmale“, then clear all filter in Map view and go back to list view to look at the proposals 
**behaviour:** after clearing all filters in map view and going back to list view, the list shows that there are no proposals and also don’t display the filters „Merkmale“ and „Kategorien“, sometimes even the new list disappears at all and shows only the old list (dev) 
**important screensize:** no
**device & browser:** mac firfox, chrome, safari
**Comment/Question:** 

Screenshot?
new list disappears 

![Bildschirmfoto 2023-01-05 um 11 49 39](https://user-images.githubusercontent.com/113611764/210786205-4d19695d-6443-4bef-a00c-e548a82bf571.png)

**Comment by Rineee** [comment]
Note: related to https://sentry.liqd.net/organizations/liqd/issues/2830/?project=2, happens when the category= or label= in url parameters
