### ISSUE TITLE
testing 6799: breadcrumb list is going back to map

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4816]
**URL:** https://meinberlin-dev.liqd.net/budgeting/2023-00960/
**user:** any
**expected behaviour:** when coming to detail view via map I want to be able to go back to map.
**behaviour:** I go back to map but breadcrumb says list.
**important screensize:**
**device & browser:** 
**Comment/Question:** The behavior is correct but our wording change does not match. Can we individually write "list" or "map" depending on where user is going/coming from? If not we could write "alle Vorschläge"

Screenshot?

**Comment by fuzzylogic2000** [comment]
We did say that this would happen as long as we don't change the default from map to list. And even after that change, if the map is chosen and the user goes back, it will still be wrong. We could check if we have the list or map there or could also display the project name. But I think, that would be a very small story, not an issue.
The wording change would be Ok to do as an issue. Please let us know which one it should be.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 thank for clarification, that reminds me to add "list as default" as a story. Would "know if back if going to list or map" be another story or can I make one story out of both?

**Comment by fuzzylogic2000** [comment]
As both go pretty well together, I would say putting it in one story is fine.
