### ISSUE TITLE
Project overview loading time

### ISSUE THREAD

**Issue by philli-m** [liqd/a4-meinberlin#4832]
Project overview loading is very slow, discussion was started in this PR: https://github.com/liqd/a4-meinberlin/pull/4448

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland is this taken care of? should it go into prod milestone?

**Comment by phillimorland** [comment]
linked https://github.com/liqd/a4-meinberlin/issues/1833

**Comment by CarolingerSeilchenspringer** [comment]
made a story out of this
