### ISSUE TITLE
#6669 email notification on feedback to contribution: status not shown + styling of "Rückmeldung" is off

### ISSUE THREAD

**Issue by jostertag** [liqd/a4-meinberlin#4850]
**URL:** notification on new feedback to contribution via this post https://meinberlin-dev.liqd.net/budgeting/2023-00976/
**user:** reg. user
**expected behaviour:** 
As user I want to see the status of my proposal in the E-Mail notification. As a user I want that everything is centred. 

**behaviour:** 
- [ ] as user I just see "" (see screenshot) and no status in the E-Mail notification. 
- [ ] The position of the word "Rückmeldung" looks odd, because it is on the left side and not centred. 

**important screensize:** - 
**device & browser:** mac , thunderbird mail
**Comment/Question:** maybe related to this closed issue https://github.com/liqd/a4-meinberlin/issues/4807 ?

<img width="1052" alt="Bildschirm­foto 2023-01-17 um 15 27 00" src="https://user-images.githubusercontent.com/113608720/212924594-4a16c4c3-5f4f-4ef1-9861-fd8b5f6599ba.png">

Screenshot?

**Comment by jostertag** [comment]
@CarolingerSeilchenspringer as you can see in the screenshot, the position of the word "Rückmeldung" looks also a bit odd, because it is on the left side and not centred. Should that be changed too?

**Comment by CarolingerSeilchenspringer** [comment]
@jostertag Yes, it should all be centered. If the status is empty then I believe it should not show the whole sentence, as I remember that is how it was before.

**Comment by jostertag** [comment]
@CarolingerSeilchenspringer in this case I changed the status to "wird geprüft". If I change the status is empty, then the wording is correct (as you can see in the screenshot) 
<img width="819" alt="Bildschirm­foto 2023-01-17 um 17 58 26" src="https://user-images.githubusercontent.com/113608720/212963090-40d02b29-7a1d-4b58-9e38-6ab9c690944a.png">

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer We cannot have everything centered and the bullet points not look odd at the same time. I think, the feedback itseld should be left aligned, but everything else centered? 
Should the title "Rückmeldung" above the feedback be centered or left aligned?
Actually @mcastro-lqd needs to answer that.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000  for the b-plan-statements we also decided to make the whole mail (starting with "Guten Tag") left aligned because it looked wired for longer texts. I'd suggest to do the same here unless @mcastro-lqd has another idea. <img width="734" alt="Bildschirmfoto 2023-01-23 um 10 13 51" src="https://user-images.githubusercontent.com/35491681/214003006-b45a77b7-e834-4df5-b7a3-7490c1d5e88b.png">

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer What is the status here? We cannot deploy it like that, right? For now I propose to change the failed fix for the bullets back. (https://github.com/liqd/a4-meinberlin/commit/a288829aa13a40d7ada72471e2170b4c8fd1feb3) Or do you have an idea how we can make the content of the feedback text left aligned @phillimorland ?

**Comment by phillimorland** [comment]
@fuzzylogic2000 if I remember the issue correctly I think we can add nested inline styles for lists to be left aligned but I would have to check, I'm also not totally clear on current state of this, did left align not work?

**Comment by fuzzylogic2000** [comment]
@phillimorland Looks like it only worked for the "Rückmeldung", which is the text from the email, but not the richtext we get from the model. I did not check, it looked so right,...

**Comment by mcastro-lqd** [comment]
@CarolingerSeilchenspringer I'd recommend Main title and Subhead Centered and content aligned to the left, no longer text should be centred.

**Comment by phillimorland** [comment]
@fuzzylogic2000 we might have a bit of an issue with the richtext here but i'll have a play and see what can be done. 
@CarolingerSeilchenspringer what is the ideal format for the emails if possible?

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland let's go with what @mcastro-lqd wrote then as this is also what we do for bplan statement (see screenshot above).

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer can you forward me the problematic emails, will look monday

**Comment by jostertag** [comment]
@phillimorland I forwarded the e-mails to you

**Comment by jostertag** [comment]
I still get e-mails with the wrong styling of wording. It is still all centered, except of the word "Rückmeldung" (see screenshot).

<img width="722" alt="Bildschirm­foto 2023-02-17 um 12 28 28" src="https://user-images.githubusercontent.com/113608720/219640495-b8c53fa5-ccc2-4319-9405-c3d9850b32df.png">

**Comment by jostertag** [comment]
Ok my bad! It was just on demo.

**Comment by jostertag** [comment]
before I close the issue, I wanted to know, whether the issue was fixed before demo was released or not? and whether it is possible that it looks off on stage/prod?

**Comment by Rineee** [comment]
@jostertag The commit that fixes this issue was merged after demo release, so if it is fine on dev, the issue can be closed. It will probably also be on stage/prod (depending on when it was introduced), but should then be fixed with next release.
