### ISSUE TITLE
"Status"-tile in list view: status is cut off due to limited number of characters

### ISSUE THREAD

**Issue by jostertag** [liqd/a4-meinberlin#4853]
**URL:** https://meinberlin-dev.liqd.net/projekte/burgerhaushalt-3-phasen-mit-support-testprojekt/?mode=list#proposal_903
**user:** any
**expected behaviour:** as a user I want to fully see in the list view the status "für nächste Phase qualifiziert" in the tiles within the proposals
**behaviour:** the status "für nächste Phase qualifiziert" is not fully visible. The wording of the status is cut off and "..." is placed at the end instead.
**important screensize:** 1424x1200
**device & browser:** mac on ff, chrome & safari
**Comment/Question:** 
@CarolingerSeilchenspringer said, that we could maybe set the number of characters (when a tag is cut off) 3 characters higher as it concerns a general rule with number of characters. Caro asked Marcelo, who said that 3 more characters should work as well on the mobile version.

<img width="1440" alt="Bildschirm­foto 2023-01-17 um 16 20 22" src="https://user-images.githubusercontent.com/113608720/212937864-41667514-1fb9-4bb1-aaf3-dd9265f3d3f6.png">

**Comment by khamui** [comment]
@jostertag not sure if got your comment right? currently it is limited at 25 chars. I don't get `when a tag is cut off`?
in case of the adding 3 more chars would end it this particular case in <kbd>für nächste Phase qualifiziere...</kbd>

**Comment by jostertag** [comment]
@khamui we want the tag/tile "für nächste Phase qualifiziert" to be fully visible. Is there a possibility to do that? And how would that affect the other tags/tiles?

With "when a tag is cut off" I mean that there is a rule for tiles/tags (you said 25 chars.), that defines when a sentence/word will be cut off and "..." will be added. 

I hope that it's now more understandable.

**Comment by khamui** [comment]
uff, sorry I wrote a bit of crap, my sentence is not even German. 

ah got it now! thanks for explanation. we would need to define a max length (so probably choosing the longest sentence of all languages) and make this the max chars. We could apply this rule only to the ampel labels, and leave the other labels (which are defined by intiators/users) limited to 25 chars? 

@jostertag do you think that would improve it a little bit?

**Comment by jostertag** [comment]
@khamui that sounds good! especially if you can apply this rule just for the ampel labels :) I believe that this would be the ideal solution.
