### ISSUE TITLE
translation 'you have x votes left' missing

### ISSUE THREAD

**Issue by Rineee** [liqd/a4-meinberlin#4867]
**URL:** 
**user:** 
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
![image](https://user-images.githubusercontent.com/9589411/214012776-982b3274-67e9-4fc1-a181-00be1ed1004c.png)

**Comment by Rineee** [comment]
@jostertag We added a dot at the end in the original string, so now it says "you have 1 vote left."/"you have %s votes left."
Could you translate that again? Before it was "Sie haben noch 1 Stimme."/"Sie haben noch %s Stimmen." Thank you!

**Comment by jostertag** [comment]
@Rineee in weblate the translation that I added is still there (also with the dot).
<img width="1062" alt="Bildschirm­foto 2023-01-24 um 10 56 11" src="https://user-images.githubusercontent.com/113608720/214262024-bbe6b819-3cf1-4ea1-adfd-0f9fb47b4d47.png">

**Comment by Rineee** [comment]
Ups, sorry, it seems we just didnt merge the translations yet.. sorry should have checked that before :grimacing: 

Fixed here https://github.com/liqd/a4-meinberlin/pull/4858
