### ISSUE TITLE
Not enough padding between (down-)votes and support icons

### ISSUE THREAD

**Issue by goapunk** [liqd/a4-meinberlin#4899]
**URL:** https://meinberlin-dev.liqd.net/projekte/budgeting-1/?mode=list#proposal_988
**user:** admin
**expected behaviour:** uniform space between icons
**behaviour:** not enough space between down votes and support icon
**important screensize:**
**device & browser:** firefox
**Comment/Question:** 

Screenshot?

![mb-budgeting-icons](https://user-images.githubusercontent.com/1710203/216310800-1d8e95fe-38a8-415f-a1b0-3c3003b55972.png)

**Comment by phillimorland** [comment]
linked https://github.com/liqd/a4-meinberlin/issues/4719
