### ISSUE TITLE
Export-Button Problem in Modul "Brainstorming (with map)" on Prod, Stage and Dev

### ISSUE THREAD

**Issue by jostertag** [liqd/a4-meinberlin#4904]
**URL:** https://meinberlin-dev.liqd.net/dashboard/projects/multimodul-test-merkmalkategorie/basic/
**user:** initiator, admin
**expected behaviour:** as I user I want to export all Ideas and Comments in all moduls which have Ideas/Proposals
**behaviour:** In the Modules "Brainstorming/Brainstorming with Map" I cannot see the Excel-Export-Button and therefore not export the ideas/comments in my project. 
**important screensize:** - 
**device & browser:** - 
**Comment/Question:** Every other modul with proposals/ideas has the excel-export-button. There's a workaround when recreating the right URL, I can get to the Excel-Export page. In this case: https://meinberlin-dev.liqd.net/dashboard/modules/brainstorming-mit-karte-7/export/mapidea/
<img width="311" alt="Bildschirm­foto 2023-02-03 um 10 50 25" src="https://user-images.githubusercontent.com/113608720/216568760-5075d601-eb68-44f1-9209-a3b547d994f9.png">

Screenshot?

**Comment by fuzzylogic2000** [comment]
How very weird. Good workaround you found, though!
I am agreeing with @Rineee : this should be in the prod release milestone. @CarolingerSeilchenspringer ?!

**Comment by CarolingerSeilchenspringer** [comment]
@Rineee @fuzzylogic2000 I added it to the prod release milestone.
