### ISSUE TITLE
#6963 Wrong Number in Wording of Helptext

### ISSUE THREAD

**Issue by jostertag** [liqd/a4-meinberlin#4907]
**URL:** https://meinberlin-dev.liqd.net/dashboard/modules/burgerinnenhaushalt-3-phasen-21/download-codes/
**user:** admin, initiator
**expected behaviour:** Each code-package should contain a max. of 1.000.000 codes. The wording of the helptext should have also the right number of 1.000.000 codes per package ~~as each package should contain a maximum of 1.000.000 codes per excel-file.~~
**behaviour:** the number in the wording of the helptext is "10.000.000" ~~and the packages can contain more than 1.000.000 codes. ~~
**important screensize:** -
**device & browser:** mac ff
**Comment/Question:** I tried it with generating two mill codes and the codes were put in only one code-package. I also couldn't download the package probably because it was too big.

Package size issue: https://github.com/liqd/a4-meinberlin/issues/4911

<img width="649" alt="Bildschirm­foto 2023-02-03 um 17 21 37" src="https://user-images.githubusercontent.com/113608720/216654132-0ce1f00d-6826-4651-a884-064ba5db80af.png">

Screenshot?

**Comment by CarolingerSeilchenspringer** [comment]
@jostertag so this is actually two issues, one for wrong wording and the second for setting the right maximum of codes per package? As I am not sure what the current setting is or should be let's wait for a dev-answer on this.

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer I have created another issue for amount of codes, should it also go in demo release?
