### ISSUE TITLE
#6963 Too many codes in 1 package

### ISSUE THREAD

**Issue by phillimorland** [liqd/a4-meinberlin#4911]
URL: https://meinberlin-dev.liqd.net/dashboard/modules/burgerinnenhaushalt-3-phasen-21/download-codes/
user: admin, initiator
expected behaviour: Each code-package should contain a max. of 1.000.000 codes. ~~The wording of the helptext should have also the right number of 1.000.000 codes per package as each package should contain a maximum of 1.000.000 codes per excel-file.~~
behaviour: ~~the number in the wording of the helptext is "10.000.000" and~~ the packages can contain more than 1.000.000 codes.
important screensize: -
device & browser: mac ff
Comment/Question: I tried it with generating two mill codes and the codes were put in only one code-package. I also couldn't download the package probably because it was too big.

Linked: https://github.com/liqd/a4-meinberlin/issues/4907

**Comment by phillimorland** [comment]
@Rineee @fuzzylogic2000 is this due to here:
https://github.com/liqd/a4-meinberlin/blob/71a3bfbac3e9a0a189c0054ee7ea0b90d61fb717/meinberlin/apps/votes/tasks.py#L10
if so it seems deleberate, is this just relic from our old token system or is there a reason?

**Comment by fuzzylogic2000** [comment]
@phillimorland Yes, seems to be from that number. It was changed from slicing the packages directly in the export view to where you found it now. https://github.com/liqd/a4-meinberlin/commit/eacd22c795353a6a5a0ac9773f74dba6ae533bc5
Hopefully it works again, when you remove one zero.
