### ISSUE TITLE
report modal after submitted (report) `x`-mark missing top spacing

### ISSUE THREAD

**Issue by khamui** [liqd/a4-meinberlin#4939]
**URL:** 
**user:** 
**expected behaviour:** report modal has even padding
**behaviour:** report modal after submitted (thanks page) misses top spacing (x-mark too close to the edge)
**important screensize:**
**device & browser:** 
**Comment/Question:** 
check for aplus!

<img width="1136" alt="Bildschirm­foto 2023-02-09 um 13 52 29" src="https://user-images.githubusercontent.com/52801593/217818496-b3bd67ce-b956-47bc-bb82-947a15b5b32f.png">

**Comment by khamui** [comment]
@CarolingerSeilchenspringer and @jostertag to keep the consistency of our recently unified modals, we would need a title for each single modal. Meaning also for the thank you modal. As this involves a "new" wording I wanted to check with you, what to do here best?

Bringing @lthueer into the loop as well as this affects A+ too.

Currently I just added something for you to check what could be a good title:

<img width="996" alt="Bildschirm­foto 2023-02-13 um 17 01 25" src="https://user-images.githubusercontent.com/52801593/218509954-68e93078-a51a-41a4-8b4f-29c07e980a02.png">

**Comment by CarolingerSeilchenspringer** [comment]
@khamui @lthueer I like that we will have consistent modals. For title for this modal I suggest "Meldung gesendet/ report sent" as the modal the user sees before has the title and CTA "Meldung senden/ Send Report". As this is the confirmation it makes most sense to me.
