### ISSUE TITLE
landing page storefront counts: project counts for whole Berlin and districts include different projects

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-meinberlin#4945]
**URL:** https://meinberlin-dev.liqd.net/ (landing page)
**user:** all
**expected behaviour:** The project count should include the same projects, so the projects that are shown for a district are a subset of the ones shown for whole Berlin
**behaviour:** 
Projects for whole Berlin (Projekte zu denen wir Ihre Meinung wissen möchten) we count all active (with active or future phases) projects that are public or semipublic.
```
    projects = Project.objects.all().filter(
        Q(access=Access.PUBLIC) | Q(access=Access.SEMIPUBLIC),
        is_draft=False,
        is_archived=False,
    )
    active_project_count = 0
    for project in projects:
        if project.active_phase or project.future_phases:
            active_project_count += 1
    return active_project_count
```
For a single district that can be added as a storefront item (Was passiert gerade in...), we also include the plans marked as running.
```
        projects = Project.objects.filter(
            Q(access=Access.PUBLIC) | Q(access=Access.SEMIPUBLIC),
            administrative_district=self.district,
            is_draft=False,
            is_archived=False,
        )
        plans = Plan.objects.filter(district=self.district, status=0)
        active_project_count = plans.count()
        for project in projects:
            if project.active_phase or project.future_phases:
                active_project_count += 1
        return active_project_count
```
**important screensize:**
**device & browser:** 
**Comment/Question:** Shouldn't both either include or not include the plans? (Uh and it does include all plans, not only the published ones, I will already fix that!)

![image](https://user-images.githubusercontent.com/8178179/218026557-daf74ca8-1b1a-4307-a041-199144870fff.png)

For the current storefron on prod, the numbers 77 (Berlin) vs. 75 (Treptow-Köpenick) are a bit weird, I think?

@CarolingerSeilchenspringer Should we act on tis and either show the plans for both or not at all? Otherwise just close this issue, please!

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 I added this as a story to my new epic redesign and will therefore close this issue. Thanks for pointing it out!
