### ISSUE TITLE
#6951 wording: space missing before link to "End Session"

### ISSUE THREAD

**Issue by jostertag** [liqd/a4-meinberlin#4946]
**URL:** https://meinberlin-dev.liqd.net/projekte/module/burgerinnenhaushalt-3-phasen-24/?
**user:** any (with token)
**expected behaviour:** there should be a space between "Are you finished" and "End Session"
**behaviour:** There is no space between "Are you finished" and "End Session"
**important screensize:** -
**device & browser:** mac ff
**Comment/Question:** I also updated the wording on weblate. Maybe when you fix the issue, can you also merge the fixed translation?

Screenshot?
<img width="858" alt="Bildschirm­foto 2023-02-10 um 10 36 47" src="https://user-images.githubusercontent.com/113608720/218089815-5821d8f8-da55-4fbe-8914-c7906b5edac6.png">

**Comment by Rineee** [comment]
fixed here https://github.com/liqd/a4-meinberlin/pull/4947
