### ISSUE TITLE
Wording: no formal adress regarding notice when comment is too long (missing String on Weblate)

### ISSUE THREAD

**Issue by jostertag** [liqd/a4-meinberlin#4973]
**URL:** https://meinberlin-demo.liqd.net/budgeting/2023-00049/
**user:** any
**expected behaviour:** as a user on mein Berlin I want to be adressed in a formal way (Sie) 
**behaviour:** When I write a comment which is too long, I get a notice with an informal adress that the textfield should not contain more than 4000 characters.
**important screensize:** - 
**device & browser:** - 
**Comment/Question:** there is no string on weblate yet, so I cannot translate it correctly

Screenshot?
<img width="725" alt="Bildschirmfoto 2023-02-13 um 10 27 18" src="https://user-images.githubusercontent.com/113608720/219613075-f384b1ad-4227-4ee8-b4fc-c166d9ba3fe4.png">

**Comment by fuzzylogic2000** [comment]
Can you please check on dev? We don't know if that was an old thing or if it's already fixed when you find stuff on demo.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 same on dev
