### ISSUE TITLE
rename "back" to list/map also in idea create form and idea edit form

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4981]
**URL:** https://meinberlin-dev.liqd.net/budgeting/2023-00960/ and https://meinberlin-dev.liqd.net/budgeting/2023-00960/update/
**user:** registered user
**expected behaviour:** breadcrumb navigation says "list/map" instead of "zurück" also in idea created and idea edit form. "zurück zum Vorschlag" is called "Vorschlag" (to be consistent).
**behaviour:** it says "zurück" and "zurück zum Vorschlag"
**important screensize:**
**device & browser:** 
**Comment/Question:** We changed this in story https://taiga.liqd.net/project/liqd-liquid-software/us/6958?milestone=340 but forgot about the two forms. Issue or story?

Screenshot?
<img width="638" alt="Bildschirmfoto 2023-02-22 um 13 27 44" src="https://user-images.githubusercontent.com/35491681/220621038-739ef9d2-d9c4-43cf-933e-c88a5ee49f11.png">
<img width="638" alt="Bildschirmfoto 2023-02-22 um 13 27 58" src="https://user-images.githubusercontent.com/35491681/220621045-8960d92e-fb9f-43de-b758-2eff212c2da7.png">

**Comment by fuzzylogic2000** [comment]
We cannot say if the "back" is list or map and will also not know the filters here. Also going back to the idea means that afterwards we have forgotten all filters.
So that means it is 2 wording changes. "zurück" will be "map/Karte" and "zurück zum Vorschlag" will be "proposal/Vorschlag". Are you OK with that or do we need to talk about it?

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 I guess it is ok if we forget the filters. So to clarify: "back" always leads to the map as default, so we write "map/Karte" and "Zurück zum Vorschlag" we just shorten to "Vorschlag". That sounds good to me.
