### ISSUE TITLE
feedback mail messed up

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4984]
**URL:** mail
**user:** user who got feedback on proposal 
**expected behaviour:** 
**behaviour:** design messed up
**important screensize:**
**device & browser:** Mac, Mail
**Comment/Question:** 

Screenshot?
<img width="1001" alt="Bildschirmfoto 2023-02-22 um 14 06 48" src="https://user-images.githubusercontent.com/35491681/220628302-1fca58a3-0121-4f2e-b50d-74cbbfe22ba3.png">

**Comment by philli-m** [comment]
@CarolingerSeilchenspringer is feedback mail only broken when feedback is text string with no white space or is it also broken when tested with real text/lorum ipsum?

**Comment by CarolingerSeilchenspringer** [comment]
@philli-m ups, I was too quick yesterday, I didn't see that the feedback contained long fake words. Looks good otherwise!
