### ISSUE TITLE
breadcumb navigation does not remember map/list after voting action

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4988]
**URL:** https://meinberlin-dev.liqd.net/budgeting/2023-00998/
**user:** user with code
**expected behaviour:** when I am active voting on proposal detail page this does not effect the breadcrumb navigation
**behaviour:** when I vote on the list, go to proposal detail page and unvote for the propsal, the breadcrumb jumps from list to map
**important screensize:**
**device & browser:** chrome, safari and edge (not on firefox)
**Comment/Question:** 

Screenshot?

**Comment by fuzzylogic2000** [comment]
Oh no, I am not sure if we can fix that. I think we have to reload the detail page to make the button work. And reloading removes the info about the back link. I guess this also happens when you vote on the proposal on the detail view? Or only for unvoting?

**Comment by fuzzylogic2000** [comment]
Yes, the medium solution would be to have the page in React.
I am not sure if there's no short term one. @philli-m Is there another way to update the button without reloading?

**Comment by khamui** [comment]
@fuzzylogic2000 @CarolingerSeilchenspringer 

there would be only hacky workarounds for a short-term fix. For instance we could save the mode (parsing the back-url) into localStorage and adding it back to the back-link url after reload. But as I said that is very hacky. Do you think we should do this?

**Comment by CarolingerSeilchenspringer** [comment]
@khamui sounds tempting but I'd rather soon change detail view to react. So I will close this issue and bring it into a story to do later.
