### ISSUE TITLE
issue from BO subdomain audit: Header: Content Security Policy ist gesetzt

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#5042]
issue from BO subdomain audit:

Handlung erforderlich: Empfehlung
Prügungskriterium: Header: Content Security Policy ist gesetzt
Erwartetes Ergebnis: Es existiert eine sinnvolle Einstellung des HTTP-Headers Content Security Policy.
Beobachtetes Ergebnis: Gesetzt ist:
upgrade-insecure-requests; default-src 'self' https://stats.liqd.net https://iframely-prod.liqd.net/; block-all-mixed-content; child-src blob: https://www.youtube-nocookie.com/ https://www.youtube.com/ https://player.vimeo.com/ https://stats.liqd.net/; script-src 'self' 'unsafe-eval' 'unsafe-inline' blob: https://stats.liqd.net https://iframely-prod.liqd.net/; connect-src 'self' https://bplan-prod.liqd.net https://meinberlin-captcha.liqd.net https://stats.liqd.net https://*.berlinonline.de; img-src 'self' data: blob: https://meinberlin-captcha.liqd.net https://meinberlin-media.liqd.net *.tile.openstreetmap.org https://*.berlinonline.de https://stats.liqd.net; style-src 'self' 'unsafe-inline'

Kommentar: Eine Wildcard-Regel zu berlinonline.de ist ggf. nicht notwendig. Generell sollte auf Wildcard verzichtet werden.

Bitte prüfen, ob die Angaben noch aktuell sind, Einbindungen einiger Domains wie tile.openstreemap.org konnten nicht beobachtet werden.

Die Einstellung "unsafe-inline" sollte gegen "nonce" oder "hash" ausgetauscht werden.

Relevanz: Kritisch

Ergebnis: teilweise erfüllt

**Comment by CarolingerSeilchenspringer** [comment]
@goapunk is this related to https://taiga.liqd.net/project/liqd-liquid-software/us/7273?no-milestone=1 and how do we proceed here?

**Comment by goapunk** [comment]
more or less, however the story is a bit more complicated and possibly concerns all our projects. This issue is a bit easier to solve so I wouldn't connect them.

**Comment by CarolingerSeilchenspringer** [comment]
@goapunk what is the status here? This story is still in milestone release June/July which already took place and I would like to close. Where would you put it? Next release milestone?

**Comment by goapunk** [comment]
@CarolingerSeilchenspringer  we can put it in the next milestone, yes

**Comment by goapunk** [comment]
fixed
