### ISSUE TITLE
List Filter should be visible before any ideas/proposals are created

### ISSUE THREAD

**Issue by jostertag** [liqd/a4-meinberlin#5043]
**URL:** https://meinberlin-stage.liqd.net/projekte/beteiligungshaushalt-2024/?mode=list
**user:** any
**expected behaviour:** in the Bürger*innenhaushalt (1, 2 & 3 Phasen), before there are proposals/ideas created by the users, I want to see the existing filter in the list view.
**behaviour:** Befor  there are any ideas/proposals created in the module, the whole filter (including categories, labels, archived, etc.) is not visible in the list view.
**important screensize:** -
**device & browser:** tested on mac (firefox, chrome & safari), on samsung galaxy s9 (chrome), windows (chrome)
**Comment/Question:** 
Somehow Caro saw earlier on Chrome the filter in the list view before there were any ideas/proposals created, but I also checked on chrome and couldn't see the filter in the list view

Screenshot?
![Bildschirm­foto 2023-03-23 um 18 07 49](https://user-images.githubusercontent.com/113608720/227281854-fda463c7-0dce-443d-a450-d45ac84bc9de.png)

![Bildschirm­foto 2023-03-23 um 18 09 55](https://user-images.githubusercontent.com/113608720/227282493-8eb07e86-eb67-408e-b92c-85d3b928818b.png)

**Comment by CarolingerSeilchenspringer** [comment]
questions for devs: is this a bug we just missed during testing or an enhancement? Don't know how it was before we changed to react but I think showing filter would give the empty list more structure
