### ISSUE TITLE
Styling issue with rating & comment icons on proposal overview (mobile version)

### ISSUE THREAD

**Issue by jostertag** [liqd/a4-meinberlin#5098]
**URL:** https://mein.berlin.de/projekte/module/ideensammlung-74/?page=1
**user:** any
**expected behaviour:** the icons of rating and comment should be in the right place of the proposal tile
**behaviour:** in the mobile version the icons of rating and commments are outside the proposal tile
**important screensize:** Iphone 10, Samsung Galaxy S9+
**device & browser:** Iphone 10, Samsung Galaxy S9+
**Comment/Question:** I couldn't test it on a tablet, but maybe its also there.

Screenshot?
![Gemeinsam Digital Berlin – Arena der Ideen — meinBerlin](https://github.com/liqd/a4-meinberlin/assets/113608720/3326b3d1-9b93-45e1-8f98-fd26ba419a90)

**Comment by goapunk** [comment]
@mcastro-lqd any suggestion what we should do here? move the ratings to the bottom? or move the title to a line below the ratings ? We could also hyphenate the long words but that might not work very reliable.
