### ISSUE TITLE
Login seems weird on Dev 

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#5116]
**URL:** https://meinberlin-dev.liqd.net/accounts/login/?next=/
**user:** *all*
**expected behaviour:** *Click and be able to read*
**important screensize:** *Desktop*
**device & browser:** *Safari Version 16.4 (18615.1.26.110.1)*
<img width="323" alt="Screenshot 2023-06-13 at 16 04 26" src="https://github.com/liqd/a4-meinberlin/assets/59610786/e24b318e-b696-455c-a862-cd7e707d6c05">

**Comment by philli-m** [comment]
This is the BS 5.3 update, I implemented a fix here https://github.com/liqd/a4-meinberlin/pull/5119 but after further investigation I found it could be a bigger issue so have downgraded for now and will see what happens with their next release
