### ISSUE TITLE
mB - voting count shown for admin 1 and 2 pb

### ISSUE THREAD

**Issue by Ronja-liqd** [liqd/a4-meinberlin#5141]
**URL:** https://meinberlin-dev.liqd.net/projekte/module/burgerinnenhaushalt-1-phase-11/?mode=list, https://meinberlin-dev.liqd.net/projekte/module/burgerinnenhaushalt-2-phasen-11/?mode=list
**user:** admin
**expected behaviour:** only the comment counter is shown in the list of the one pb and pb
**behaviour:** The vote counter also shown in the list in all phases
**important screensize:**
**device & browser:** all
**Comment/Question:** 
Not sure if this really is an issue since it is only with admins but wrote it since the votes aren't existing in these modules.

Screenshot
<img width="959" alt="Bildschirm­foto 2023-06-19 um 10 39 34" src="https://github.com/liqd/a4-meinberlin/assets/113356258/7017c60b-6821-4d65-9df8-ff73db6b68af">

**Comment by goapunk** [comment]
I think that's normal, we show everything for admins

**Comment by philli-m** [comment]
@Ronja-liqd @goapunk there was an architectural decisions some time ago that admins can always see everything so this is intentional so will close
