### ISSUE TITLE
improve heading structure

### ISSUE THREAD

**Issue by vellip** [liqd/a4-meinberlin#515]
Part of the BITV-Test: "1.3.1a HTML-Strukturelemente für Überschriften"
----
_Notice the difference between 'could' (optional) and 'has to'._

- [x] project list: title of a single project could be `<h2>`
- [x] project form: "Edit Project" has to be `<h1>`
- [ ] project contents: "Manage project content" has to be `<h1>`
- [ ] poll contents: every question could have a heading as improvement
- [x] project moderators: text of h1 could be more specific, saying it's about editing moderators

**Comment by xi** [comment]
>  project list: title of a single project could be <h2>

This is not so simple:

- On `/projects/`, there is no heading above them.
- On `/`, there are three levels above: Title, subtitle, and block title.

**Comment by vellip** [comment]
All those remarks **only** count for the dashboard, as user space isn't tested yet. So when I said project list, I meant `/dashboard/organisations/liqd/projects/`

**Comment by xi** [comment]
@vellip do you think #534 was sufficient? If not, what needs to be done?

**Comment by vellip** [comment]
This looks fine with dashboard II.
