### ISSUE TITLE
rename table header on moderators list

### ISSUE THREAD

**Issue by vellip** [liqd/a4-meinberlin#516]
Part of the BITV-Test: "1.3.1e Datentabellen richtig aufgebaut"
----

Rename the table column header "Delete" to "Remove moderator". Same for the icon `aria-label`.

**Comment by xi** [comment]
To clarify: The original string is "Remove" and the german translation is "Löschen". It should be made clear that this action will not delete the user account, but will remove it from the list of moderators.
