### ISSUE TITLE
#7421 Long category/label title seems to be not shown completely

### ISSUE THREAD

**Issue by jostertag** [liqd/a4-meinberlin#5170]
**URL:** https://meinberlin-dev.liqd.net/projekte/module/burgerinnenhaushalt-2-phasen-12/?mode=list
**user:** any
**expected behaviour:** as a user I should not get confused by a cut off category/label title. It should be readable at least until the ":" to see if the word ends.
**behaviour:** the category/label title looks like that it is cut off (even though the word is complete). The ":"-sign is cut off.
**important screensize:** any
**device & browser:** mac ff, safari & chrome
**Comment/Question:** Maybe we should change the limit to 20 characters (with spaces). I thought that with 25 characters (with spaces) it won't be cut off. But it will be cut off before the ":"-sign. With the limit to 20 characters (with spaces) we could also see the first default setting of the filter ("Alle"). In the screenshot you can see the difference between 25 and 20 characters.
What do you think @mcastro-lqd ?

Screenshot?
<img width="1111" alt="Bildschirm­foto 2023-07-04 um 16 43 08" src="https://github.com/liqd/a4-meinberlin/assets/113608720/89cf1570-ece7-4f8e-9c6a-c4b122588994">

**Comment by philli-m** [comment]
@jostertag those filters should actually stretch the whole width of the container there, I can fix that and see if we still have an issue the char count?

**Comment by jostertag** [comment]
@philli-m does this then also works for the map view? and additionally if the category/label has more than 20 characters (with spaces) it leads also to the problem that the default setting of the filter ("Alle") will be cut off --> "..."


<img width="1438" alt="Bildschirm­foto 2023-07-11 um 10 51 01" src="https://github.com/liqd/a4-meinberlin/assets/113608720/2f8c5bbd-58ae-44bb-a565-05dbeeba3f33">
