### ISSUE TITLE
improve validity of HTML

### ISSUE THREAD

**Issue by vellip** [liqd/a4-meinberlin#519]
Part of the BITV-Test: "4.1.1a Valides HTML"
----

- [x] duplicate ids occur on pages with the datepicker (maybe just with several phases?)
- [x] Date and time for datetimepicker need separate labels
- [x] don't use max_length on `type="hidden"` inputs (type of phase)
- [x] the separate e-mails for each moderator on the moderators page should not be a `label`
- [x] field to add moderators has a `type=None`
- [x] don't use `rows` attribute on `type="hidden"`

**Comment by xi** [comment]
> duplicate ids occur on pages with the datepicker (maybe just with several phases?)

fixed in https://github.com/liqd/a4-meinberlin/pull/613#issuecomment-314500515

**Comment by xi** [comment]
>  don't use max_length on type="hidden" inputs (type of phase)

Fixed upstream: https://code.djangoproject.com/ticket/27015
