### ISSUE TITLE
Counting Comments on map popup and list items (2 issues - similar problem  in a+)

### ISSUE THREAD

**Issue by jostertag** [liqd/a4-meinberlin#5220]
**URL:** https://meinberlin-dev.liqd.net/mapideas/2023-01031/ ; https://meinberlin-dev.liqd.net/projekte/testprojekt-newsletter/
**user:** any
**expected behaviour:** the counting of comments should be consistent
**behaviour:** 

1. The number of comments in the detail idea view is not the same anymore as the number in the idea overview (list & map). This is because the detail ide view now counts as well child comments while the idea overview doesn't. (see screenshot 1 vs. 2)

2. The counting in the detail view stops at 100 seperate comments. If there are child comments, it adds to counting of 100. The number is then also different to the idea overview. If I scroll down, then new comments are loaded and the counting number on top changes. This can be very confusing. (see screenshot 1, 2 & 3)

**important screensize:** any
**device & browser:** mac ff
**Comment/Question:** 

Screenshot?
**1. screenshot of idea overview (map)**
<img width="821" alt="Bildschirm­foto 2023-08-01 um 15 36 52" src="https://github.com/liqd/a4-meinberlin/assets/113608720/ac6d7dd2-9785-49ad-85d4-f380cda6401d">

**2. screenshot of idea detail view with child comments**
<img width="847" alt="Bildschirm­foto 2023-08-01 um 15 37 17" src="https://github.com/liqd/a4-meinberlin/assets/113608720/45951686-f9d2-4acb-8615-8b75182ac943">

**3. screenshot of idea detail view with child comments and scrolled down**
<img width="972" alt="Bildschirm­foto 2023-08-01 um 15 37 40" src="https://github.com/liqd/a4-meinberlin/assets/113608720/3e2c3d16-0578-4a87-8f47-285d61e04be3">

**Comment by goapunk** [comment]
this should be fixed already I think, but maybe good to double check

**Comment by philli-m** [comment]
map popups and list items only counting parent comments not child comments

**Comment by goapunk** [comment]
map popup and list items count correctly for me, so it's only the multi module tiles showing the wrong count
