### ISSUE TITLE
Questions not copied in duplicated projects

### ISSUE THREAD

**Issue by maxliqd** [liqd/a4-meinberlin#5225]
**URL:** 
mein.berlin.de
meinberlin-dev.liqd.net
Examples:
Original: https://meinberlin-dev.liqd.net/projekte/umfrage-original/
Duplicate: https://meinberlin-dev.liqd.net/projekte/umfrage-original-2/
**user:** initiator
**expected behaviour:** when I duplicate a project with a module poll, the questions are copied too
**behaviour:** questions are not copied, need to be added manually again
**important screensize:**
**device & browser:** 
**Comment/Question:** 
Not tested for other modules yet!

Screenshot?

**Comment by CarolingerSeilchenspringer** [comment]
will close as this would rather be a story.
