### ISSUE TITLE
(Story 7630) icon in Header too small

### ISSUE THREAD

**Issue by pascalkienast** [liqd/a4-meinberlin#5269]
**URL:** https://meinberlin-design-dev.liqd.net/
**user:** mobile devices
**expected behaviour:** I want to see the meinberlin-Logo also on small mobile devices
**behaviour:** the logo can get really small on some screens
**important screensize:** everything under 340px width is too small
**device & browser:** chrome, safari
**Comment/Question:** 
maybe its not important since a lot of new smartphone have really big displays
**Screenshot?**
![Screenshot 2023-10-17 at 12-35-24 iPhone 12 v14 1](https://github.com/liqd/a4-meinberlin/assets/6682526/72a615b6-a333-49d4-915d-741444a5d26a)

**Comment by CarolingerSeilchenspringer** [comment]
@pascalkienast the header still is not completely final as the anmelde button will go somewhere else and the logo has to be discussed. We will finalize the header later, so I will still close this for now.
