### ISSUE TITLE
(Story 7627) The arrow icon in the footer is not shown on some mobile devices

### ISSUE THREAD

**Issue by pascalkienast** [liqd/a4-meinberlin#5270]
**URL:** https://meinberlin-design-dev.liqd.net/
**user:** any
**expected behaviour:** I want to see an arrow, so i know i can expand the footer menu
**behaviour:** the arrow-icon is on some devices not shown or an other icon is shown
**important screensize:** mobile devices
**device & browser:** Strangely, in desktop browsers that are made to mobile size, it sometimes seems that the arrow icon is not displayed correctly. In Browserstack this has only happened in rather older Android devices. In the following browsers i can reproduce the error: Firefox 118 for MacOs and Edge and Firefox Mobile-Browser on Android. On Chome it just shows no Icon.
**Comment/Question:** 

Screenshot?
Error in showing the icons:
![Screenshot 2023-10-17 at 12-45-05 Samsung Galaxy S21 v11 0](https://github.com/liqd/a4-meinberlin/assets/6682526/21e0fb67-0f47-407f-bae0-b29e803edb34)
Correct Arrow-Icons:
![Screenshot 2023-10-17 at 12-48-11 iPhone 14 Pro v16 3](https://github.com/liqd/a4-meinberlin/assets/6682526/c217c55e-c30f-48cc-bf52-193aa181f751)

**Comment by philli-m** [comment]
I can't reproduce on real device, running Firefox mobile browser on my android and it looks and works fine. @hom3mad3 can you reproduce this? (also not urgent, just when you have time)

**Comment by pascalkienast** [comment]
@philli-m @CarolingerSeilchenspringer  I really have to say that this issue was kind of tricky right from the start... Because now I can no longer reproduce this issue in any browsers (not even in desktop browsers and browserstack, where this Font-Awesome icon was not displayed correctly before). So the issue can be closed.
