### ISSUE TITLE
#7681 [mB] Add BO breadcrumbs to mB and check functionality

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#5276]
**URL:** https://meinberlin-design-dev.liqd.net/projekte/burgerinnenhaushalt-2-phasen-support-testprojekt/
**Comment/Question:** *maybe we could always start with meinBerlin once you are in a page that is not the landing page like we have in Feedback Geben? Would it be possible?* 
<img width="487" alt="Screenshot 2023-10-24 at 09 37 39" src="https://github.com/liqd/a4-meinberlin/assets/59610786/c20b5d42-f279-4a46-8122-613d51c7ad9d">
<img width="396" alt="Screenshot 2023-10-24 at 09 37 29" src="https://github.com/liqd/a4-meinberlin/assets/59610786/7c674103-1f99-44bb-9004-5b403dff660d">

**Comment by philli-m** [comment]
fixed with https://github.com/liqd/a4-meinberlin/pull/5348
