### ISSUE TITLE
#7630 adapt content header to berlin CI

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#5277]
**URL:** https://meinberlin-design-dev.liqd.net
**Comment/Question:** *The logo in black is here* 
[mein-berlin-logo.svg.zip](https://github.com/liqd/a4-meinberlin/files/13112566/mein-berlin-logo.svg.zip)

**Comment by mcastro-lqd** [comment]
[mein-berlin-logo.svg.zip](https://github.com/liqd/a4-meinberlin/files/13112560/mein-berlin-logo.svg.zip)

**Comment by philli-m** [comment]
fixed with https://github.com/liqd/a4-meinberlin/pull/5348
