### ISSUE TITLE
Confirm registration email sends password reset

### ISSUE THREAD

**Issue by m4ra** [liqd/a4-meinberlin#5295]
**URL:*https://meinberlin-design-dev.liqd.net/accounts/confirm-email/* 
**user:*new* 
**expected behaviour:*receive an email confirmation email* 
**behaviour:*received a reset password email* 
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by philli-m** [comment]
linked https://github.com/liqd/a4-meinberlin/issues/5330

**Comment by m4ra** [comment]
was my mistake as i didn't read carefully the email sent bcz it is in german, notifying the the account exists, and thus suggesting to request a password reset.

**Comment by m4ra** [comment]
was my mistake as i didn't read carefully the email sent bcz it is in german, notifying the the account exists, and thus suggesting to request a password reset.
