### ISSUE TITLE
[#7681] Breadcrumbs in mB Redesign don't work as expected in text discussion module

### ISSUE THREAD

**Issue by sblindow** [liqd/a4-meinberlin#5304]
**URL:**
https://meinberlin-design-dev.liqd.net/projekte/module/text-diskutieren-6/

**user:** 
Commenting User.

**expected behaviour:**
When I go to comment on a piece of text in the text discussion module, I want to keep the correct page structure and be able to go back to the module layer.

**behaviour:** 
When I go to comment on paragraph, a seperate page is loaded (designatet with the name of the paragraph in the breadcrumbs) and I can leave a comment. However, the page that contains the whole text (Module Layer) is not saved in the Breadcrumbs. I can only go back to the project Layer.

**important screensize:**
not relevant as far as I know.

**device & browser:**
Mac OS; Firefox, Safari, Chrome

**Comment/Question:**

Screenshot?
Module Layer designated as "Text diskutieren" in the Breadcrumbs:
<img width="1820" alt="Module_Layer" src="https://github.com/liqd/a4-meinberlin/assets/144320958/eb6a8588-dfff-4943-916f-e2dc6296ce3c">

Paragraph Layer, missing the "Text diskutieren" in the Breadcrumbs and leading straight back to the project.
<img width="1824" alt="Paragraph_Layer" src="https://github.com/liqd/a4-meinberlin/assets/144320958/3f7f7157-5337-400b-ab8c-0b3085962d25">

**Comment by philli-m** [comment]
@sblindow just a little reminder, in future can you add the story number to the title just so we can see which issues are story related much easier

**Comment by philli-m** [comment]
@CarolingerSeilchenspringer do we still want to redo the documents anyway? if so maybe this fix can be added then as this could be a bit annoying and may not be needed?

**Comment by CarolingerSeilchenspringer** [comment]
@philli-m we will also re-do text commenting. I will leave this issue open and on hold and link it to the story.
