### ISSUE TITLE
[#7681] Breadcrumbs in mB Redesign: Breadcrumbs on Moderation Page show generic "Idea" or "Proposal" instead of the actual name

### ISSUE THREAD

**Issue by sblindow** [liqd/a4-meinberlin#5305]
**URL:** 
examples:
https://meinberlin-design-dev.liqd.net/ideas/2023-01052/moderate/
https://meinberlin-design-dev.liqd.net/budgeting/2023-01051/moderate/

**user:** 
moderators

**expected behaviour:** 
When I navigate from the Idea-/ Proposal-Page to the moderation view, I want to see the name of the Idea/ Proposal that I am currently moderating in the breadcrumbs. This works correctly on the Idea-/ Proposal-Page itself.

**behaviour:**
Instead of the name of the Idea/ Proposal, a generic "Idea" or "Proposal" string designates the structural layer of the Idea-/ Proposal-Page in the breadcrumbs. 

**important screensize:**
Not relevant as far as I know.

**device & browser:** 
Mac OS: Firefox, Safari, Chrome.

**Comment/Question:** 

Screenshot?

Breadcrumbs on the Proposal Page, showing the name of the proposal.
<img width="1895" alt="Breadcrumbs_Proposal_Layer" src="https://github.com/liqd/a4-meinberlin/assets/144320958/bdf85c81-958e-403a-848e-92b629ebd7b1">

Breadcrumbs on the Moderation page, showing a generic "Proposal":
<img width="1906" alt="Breadcrumbs_Moderation_Page" src="https://github.com/liqd/a4-meinberlin/assets/144320958/d7a71059-80a6-4f4f-b634-61ff9d43dd20">

**Comment by CarolingerSeilchenspringer** [comment]
@philli-m it will all be react so will close issue.
