### ISSUE TITLE
[#7681] Breadcrumbs in mB Redesign: Moderation Page of Kiezkasse Module is missing Breadcrumbs

### ISSUE THREAD

**Issue by sblindow** [liqd/a4-meinberlin#5306]
**URL:** 
https://meinberlin-design-dev.liqd.net/kiezkasse/2023-01079/moderate/

coming from:
https://meinberlin-design-dev.liqd.net/kiezkasse/2023-01079/

**user:** 
moderator

**expected behaviour:**
When on the moderation page, I want to easily navigate back in the page structure using breadcrumbs.

**behaviour:**
In the Kiezkassen Module the Breadcrumbs are not yet implemented on the Moderation Page.

**important screensize:**
Not relevant as far as I know.

**device & browser:** 
mac OS: safari, Firefox, Chrome

**Comment/Question:** 

Screenshot?

**Comment by philli-m** [comment]
awaiting answer from https://github.com/liqd/a4-meinberlin/issues/5305

**Comment by CarolingerSeilchenspringer** [comment]
@philli-m we will no longer have the moderation page so will close issue.
