### ISSUE TITLE
Profile page is empty

### ISSUE THREAD

**Issue by xi** [liqd/a4-meinberlin#533]
In #458 we added a user profile page. Back then, we already struggled to find content that can be put on that page. In #530 we got the feedback that the little information that we had put on the profile was still too much, so now we are left with nothing but the username.

A user profile page is not the highest priority when it comes to user demands. However, the comments from a4-core contain a link to a profile page, so not having it breaks those links.

**Comment by damusp** [comment]
the profile page is nice for building up an online community feeling. 

however, with only the username on it, the profile page is ridiculous. 
so, in my opinion, it would be best to get rid of it. 

But as @xi said:
> However, the comments from a4-core contain a link to a profile page, so not having it breaks those links.
how can we handle the broken links?
