### ISSUE TITLE
UI/UX Test – #7767 [mB] re-design tabs

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#5364]
**URL:** https://meinberlin-design-dev.liqd.net/
**important screensize:** *Both*
**device & browser:** *Chrome and Safari*
**Comment/Question:** *
The Tab links are actually grey, they turn black once clicked on, you can see on Zeplin the color code #454545.

On Safari I don’t see the Grey Line, you can find the example from BO here: 
https://www.berlin.de/suche/?q=Film&hq=

And on Chrome I get the tab aligned to the center when not logged in.
<img width="1088" alt="Screenshot 2023-12-07 at 16 14 18" src="https://github.com/liqd/a4-meinberlin/assets/59610786/37722791-dd0d-4e23-a264-4cd44ff16ede">

Imagem Desktop
<img width="1000" alt="Screenshot 2023-12-07 at 15 53 38" src="https://github.com/liqd/a4-meinberlin/assets/59610786/b722e6ff-a4a5-44a7-9421-3bdf1dfc163f">

Imagem Mobile
BO Asked us once to make the alignment here full width which I find a bit strange, but maybe if we increase the spacing between the items, we can have them more aligned to the bearbeiten button. I would also separate the Bearbeiten from the tab a bit more on Mobile.

![IMG_1392](https://github.com/liqd/a4-meinberlin/assets/59610786/103a3c67-c105-41d9-8213-80c5d896ccd9)

Thank you
*

**Comment by philli-m** [comment]
@mcastro-lqd do you have a link to where we can find the tab styling? I didn't know they existed so wrote our own styles
