### ISSUE TITLE
UI/UX Test - #7701 [mB] replace project hero with image with aside

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#5366]
**URL:** https://meinberlin-design-dev.liqd.net/
**important screensize:** *Both*
**device & browser:** *Chrome and Safari*
**Comment/Question:** *
Spacing here between Title and Subhead is a bit too much compared to the design. Can we lower a bit? And it’s also missing the Headerbild Urheber*in on the side that was on Zeplin when an Image is Added. 
<img width="1784" alt="Screenshot 2023-12-07 at 16 42 52" src="https://github.com/liqd/a4-meinberlin/assets/59610786/d20901eb-4c61-4a43-940d-3e6acc24f34a">

Is it possible to have the image cropped full width here instead of the black spaces on the sides? 
![IMG_1397](https://github.com/liqd/a4-meinberlin/assets/59610786/a6717214-059d-4ee3-9274-ac1fb4184e6a)

Cheers,

*

**Comment by philli-m** [comment]
@mcastro-lqd for the cropping issue I'm not sure as link isn't for a project but I think the screenshot you sent, the image does have black edges is it this ones? https://meinberlin-design-dev.liqd.net/projekte/test-modules/

**Comment by CarolingerSeilchenspringer** [comment]
@mcastro-lqd can you check above question?

**Comment by mcastro-lqd** [comment]
@philli-m @CarolingerSeilchenspringer Omg yes, forget about that then! Sorryyy
