### ISSUE TITLE
chapter and project view are identical

### ISSUE THREAD

**Issue by xi** [liqd/a4-meinberlin#537]
In commenting text projects, the project detail view is identical to the detail view of the first chapter, e.g.:

https://meinberlin-dev.liqd.net/projects/text-create/
https://meinberlin-dev.liqd.net/text/chapters/3/

It would be nice to only use one canonical URL for that.

**Comment by xi** [comment]
The same issue exists if we have more than one module on a project. It might even be more important there. Some more thoughts:

- [canonical URLs](https://tools.ietf.org/html/rfc6596) are used if there are several views for a single resource. But this is not the case here. We have two views on two different resources (project and module). But both views render an identical result.
- The hierarchy is project -> module -> item. In the navigation, we skip the module level. This way the platform seems less complicated at first glance. This works well in most cases, but gets really confusing in the few cases where it doesn't.
- There is real value in both URLs
  - The URL to a project always show you the *current* module.
  - The URL to a module always shows you the *same* module.

There does not seem to be a generic solution for this kind of problem.

**Comment by xi** [comment]
> There does not seem to be a generic solution for this kind of problem.

On second thought, this issue arises only when you try to bypass a level of navigation. So this is really a design issue.

**Comment by xi** [comment]
Our latest idea is to have a redirect on one of the views. E.g. redirecting from project to active module would be easy to implement, but redirecting from active module to project might actually be more useful because it would allow sharing the project page on social media.

**Comment by kleingeist** [comment]
i talked with @2e2a and we decided it be best to redirect from the first chapter to the project detail page

**Comment by kleingeist** [comment]
closed with #848
