### ISSUE TITLE
#7702 [mB] change design of React proposal list to BO card - missing pluralization of comment/ like counts 

### ISSUE THREAD

**Issue by sblindow** [liqd/a4-meinberlin#5370]
**URL:** 
[Example-url](https://meinberlin-design-dev.liqd.net/projekte/module/ideensammlung-mit-karte-5/?mode=list)

**user:** 
All

**expected behaviour:** 
The application should dynamically adjust the word to its singular or plural form based on the count

For example, "1 Kommentar", "2 Kommentare", "1 Like", "0 Likes", etc.
 
**behaviour:** 
The terms indicating the count (comments, likes, dislikes) are static and do not change according to the number, leading to grammatical inaccuracies.

**important screensize:**
Not relevant

**device & browser:** 
All devices/ browsers

**Screenshots:** 

<img width="1001" alt="Bildschirmfoto 2023-12-13 um 10 57 56" src="https://github.com/liqd/a4-meinberlin/assets/144320958/be210d59-398c-444b-930f-2f8877be691a">

<img width="1003" alt="Bildschirmfoto 2023-12-06 um 13 57 37" src="https://github.com/liqd/a4-meinberlin/assets/144320958/b8dad537-1982-4f43-bfdc-410765528d8a">

**Comment by philli-m** [comment]
NOTE: comment and vote strings should change according to the code however possible this is a translation issue, plural function should be added to the like and dislike
