### ISSUE TITLE
 #7767 [mB] re-design tabs - placement of the tabs

### ISSUE THREAD

**Issue by NaneKL** [liqd/a4-meinberlin#5379]
**URL:** 
https://meinberlin-design-dev.liqd.net/projekte/burgerhaushalt-3-phasen-mit-support-testprojekt/

**user:** 
all

**expected behaviour:** 
The tabs are on the left side of the page

**behaviour:** 
The tabs are in the middle/ more towards the left side. 
If you use a phone there is a high chance that the tabs are not all in a line, but one is belowe the others (see screenshots). If you click the tab that is below the others they will appera in a line once again.

**important screensize:**
**device & browser:** 
computer-all browsers
mobile phones-all browser, but the probability of the shift happening is higher if you use chrome.
tablets- Only on ipads is the placement right

**Comment/Question:** 

Screenshot?

![Bürgerhaushalt (3 Phasen)](https://github.com/liqd/a4-meinberlin/assets/147801301/24554eeb-3aed-4c11-9f51-d78468327e77)
![über das Projekt](https://github.com/liqd/a4-meinberlin/assets/147801301/b87536d0-7d79-4d64-8ce8-f442205b76c7)

**Comment by philli-m** [comment]
put onhold as linked to this issue https://github.com/liqd/a4-meinberlin/issues/5364 and will await their styles so we are not doubling up and creating conflicting css
