### ISSUE TITLE
#7760 [mB] change all idea/proposal lists to react - Missing 'Archived' Tag in archived Proposal-/ Idea list Items

### ISSUE THREAD

**Issue by sblindow** [liqd/a4-meinberlin#5382]
**URL:** 
[Example List](https://meinberlin-design-dev.liqd.net/projekte/module/burgerinnenhaushalt-3-phasen-12/?mode=list&is_archived=true)
[Zeplin Design Link](https://app.zeplin.io/project/5b051eef7aaa417d2227c55c/screen/654d06f0fdaee279a98519d6)

**user:**
All Users

**expected behaviour:**
According to the design template for the React list, archived proposals/ideas should display a grey "archived" tag. This is needed when archived proposals/ideas are displayed alongside non-archived ones. The last two proposals in the design link serve as a reference for how this should appear.

**behaviour:** 
Currently, the 'Archived' tag is missing in the React list.

**important screensize:**
screensize not relevant

**device & browser:** 
MacOs using Firefox

**Comment by philli-m** [comment]
@CarolingerSeilchenspringer I remember us talking about this but apparently did not note down what was decided. The original story was to implement new design in existing list but as the existing list items did not have any label/styling for archived I thought we decided to have an extra story as the code logic doesn't exist so it's a bit out of the scope of the existing story?

**Comment by CarolingerSeilchenspringer** [comment]
@sblindow @philli-m the archived styling still needs to get a go so this will be another story.
