### ISSUE TITLE
#7761 change search, sorting, filter and list/map switch components in budgeting app - setting filter without filter button possible

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#5390]
**URL:** https://meinberlin-design-dev.liqd.net/projekte/burgerhaushalt-3-phasen-mit-support-testprojekt/?mode=list
**user:** any
**expected behaviour:** I always have to press the button "filter" after setting the filter. 
**behaviour:** This is not true for "all". If I e.g. set a topic, I have to hit "filter" in order for it to work. When selecting "all" the list gets filtered without hitting the filter button.
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by vellip** [comment]
This has been fixed with the react-maps update.
