### ISSUE TITLE
#7274 Adding Links in new CK editor is not working

### ISSUE THREAD

**Issue by pascalkienast** [liqd/a4-meinberlin#5391]
**URL:** https://meinberlin-dev.liqd.net
**user:** any
**expected behaviour:** if i add a link in an ck editor textbox without the "https://" (e.g. only liqd.net etc) it should automatically add https:// so the link works with the html
**behaviour:** if i add a link in an n an ck editor textbox without the "https://" it adds automatically "/https:/", which causes the link to not work
**important screensize:** no
**device & browser:** any
**Comment/Question:** if i add an link with the "https://" or "http://" it works without problems. 

Screenshot?
![Screenshot 2024-01-09 at 11-41-22 Dashboard](https://github.com/liqd/a4-meinberlin/assets/6682526/c3d26735-f5c1-47ef-8503-a0676e6b7cd6)
![Screenshot 2024-01-09 at 11-41-47 Dashboard](https://github.com/liqd/a4-meinberlin/assets/6682526/43577110-7aa4-4699-b1b7-1c368548112a)

**Comment by goapunk** [comment]
upstream pr: https://github.com/hvlads/django-ckeditor-5/pull/182

**Comment by goapunk** [comment]
fixed in our fork
