### ISSUE TITLE
#7274 [mB] replace ck editor - Image or File Upload not working as initiator

### ISSUE THREAD

**Issue by pascalkienast** [liqd/a4-meinberlin#5393]
**URL:** https://meinberlin-dev.liqd.net
**user:** as initiator
**expected behaviour:**  if i upload an image (or File like pdf) in the new ck editor, the image should be should be inserted into the text box
**behaviour:** if i upload an image/File as initiator in the ck-editor text-box the error message "Couldn't upload file: (image name)" comes up as an alert box
**important screensize:** any
**device & browser:** any
**Comment/Question:** As an Admin the upload works fine

Screenshot?
![Bildschirmfoto 2024-01-09 um 13 39 42](https://github.com/liqd/a4-meinberlin/assets/6682526/014031d7-fc76-430e-b97d-d98392e2e7ec)

**Comment by goapunk** [comment]
will be fixed by https://github.com/liqd/django-ckeditor-5/pull/4
