### ISSUE TITLE
#7861 [mB] update search, sorting, filter and list/map switch to new BO components in all apps with list (based on budgeting list) - Inconsistent filter visibility for scheduled Modules in Projects

### ISSUE THREAD

**Issue by sblindow** [liqd/a4-meinberlin#5396]
**URL:**
[Scheduled Module in otherwise empty project](https://meinberlin-design-dev.liqd.net/projekte/testing-filter-on-react-lists-single-module/)
[Scheduled Module in project alongside other modules](https://meinberlin-design-dev.liqd.net/projekte/module/brainstorming-13/)

**user:**
All

**expected behaviour:**
For scheduled modules that are not yet open for participation, the filter should remain hidden since there is no user-generated content.

**behaviour:**
When a project has multiple modules that are viewed on separate pages, the filter for scheduled modules (not yet open) is correctly hidden.

However, in projects with only a single module viewed on the project overview page, the filter for such scheduled modules is visible.

**important screensize:**
Not relevant to this issue as far as I can tell.

**device & browser:**
Tested mainly on MacOs using Firefox.

**Comment by CarolingerSeilchenspringer** [comment]
we will take the filter + no results as default but @mcastro-lqd will check again the design.

**Comment by CarolingerSeilchenspringer** [comment]
@sblindow @vellip @MarleyMi needs concept and improvement, will close and make a story
