### ISSUE TITLE
#7861 [mB] update search, sorting, filter and list/map switch to new BO components in all apps with list (based on budgeting list) - View Switch visible in 'No Map' Module Variants

### ISSUE THREAD

**Issue by sblindow** [liqd/a4-meinberlin#5398]
**URL:**
Issue found in:
- [Brainstorming ohne Karte](https://meinberlin-design-dev.liqd.net/projekte/brainstorming-2/?mode=map)
- [Ideensammlung ohne Karte](https://meinberlin-design-dev.liqd.net/projekte/caros-text-zerreissen/?mode=map)
- [Priorisierung ohne Karte](https://meinberlin-design-dev.liqd.net/projekte/themenpriorisierung/?mode=map)

**user:**
All

**expected behaviour:**
In modules featuring a map, users can toggle between list-view and map-view, for spacial overview of user-generated Ideas.
The view switch option should be absent in non-map modules.

**behaviour:**
The view switch is visible in the „no map“ variants of three modules (listed in URL section). It is not functional but can be interfaced with.

**important screensize:**
Not relevant

**device & browser:**
MacOs using Firefox

**Comment by vellip** [comment]
This has been fixed along with the react-maps changes.
