### ISSUE TITLE
#7762 [mB] Fullwidth-Servicepanel with phase title etc. breaks at 1181px width

### ISSUE THREAD

**Issue by pascalkienast** [liqd/a4-meinberlin#5427]
**URL:** https://meinberlin-design-dev.liqd.net/
**user:** any
**expected behaviour:** i want to have the servicepanel with the phase title and description like in the designs and also like the berlin-styleguide
**behaviour:** on devices with an screensize smaller than 1182px width (so all mobile devices), the fullwidth service panel breaks and is only half displayed
**important screensize:** 1181px width
**device & browser:** any
**Comment/Question:** 

Screenshot?
![Bildschirmfoto 2024-01-30 um 10 23 21](https://github.com/liqd/a4-meinberlin/assets/6682526/80f23c54-60f9-426d-870c-bcb24122c3ff)

![Bildschirmfoto 2024-01-30 um 10 23 09](https://github.com/liqd/a4-meinberlin/assets/6682526/f65ad121-d179-4c76-89a4-a15ff1e54899)

On mobile devices:
![Screenshot 2024-01-30 at 10-01-45 Samsung Galaxy S22 v12 0](https://github.com/liqd/a4-meinberlin/assets/6682526/7bb18a90-4b29-4614-860c-29b8c226a9c4)
![Screenshot 2024-01-30 at 10-03-33 iPhone 12 v14 7](https://github.com/liqd/a4-meinberlin/assets/6682526/624b5d39-e34c-4e9c-8198-8c2c0e64f13e)

**Comment by goapunk** [comment]
fixed by #5442
