### ISSUE TITLE
Re-Style login/register form

### ISSUE THREAD

**Issue by kleingeist** [liqd/a4-meinberlin#548]
as noted by @damusp in #547 the login and register are in need of some re-styling

**Comment by damusp** [comment]
![login](https://user-images.githubusercontent.com/22769111/27286158-75a5ba2e-54ff-11e7-838a-b77b9f1e67c3.png)

hey @xi @kleingeist I've been moving things around a little. 
What do you think?

**Comment by xi** [comment]
Extending the `form-group` component so we can fit a link in there sounds overly complicated to me. That is also not a place where I would expect that functionality (most providers have it somewhere below the input fields.
