### ISSUE TITLE
Decouple projects/plans overview cache from user activity

### ISSUE THREAD

**Issue by m4ra** [liqd/a4-meinberlin#5510]
**URL:** https://meinberlin-dev.liqd.net/projekte/
**user:** *any user*
**expected behaviour:** *Project overview speed is fast, and not related to first page load in order to save the cache*
**behaviour:** *Cache is saved after the first user interaction with the page, so first time is slow, and last till the cache timeout, see redis cache in settings/production.py*
~**important screensize:** *mobile? desktop?*~
~**device & browser:** *e.g. Desktop, firefox 68.0.2 (64-Bit)*~
**Comment/Question:** Possible solutions:

- cache a serialized queryset using the StatusFilter for each status, 
- or call the api endpoint from the celery task
- or cache a serialized queryset and remove the not related statuses from json manually in the api list view, 
- or make a database view to store the queryset, aka a virtual table

If needed or helpful you can add a screenshot. Since issues are public, make sure to not display personal or secret data.

**Comment by CarolingerSeilchenspringer** [comment]
@m4ra has this been resolved with the second improvement story?

**Comment by m4ra** [comment]
Yes, I am closing it.
