### ISSUE TITLE
#7768 [mB] re-design registration and login forms : Tooltip Position Issue in Firefox on Form Submission

### ISSUE THREAD

**Issue by sblindow** [liqd/a4-meinberlin#5553]
**URL:**
https://meinberlin-design-dev.liqd.net/accounts/signup/

**user:** 
Front-end user trying to register.

**expected behaviour:** 
When a required field is left blank on the registration form and the user tries to submit, a tooltip should appear next to the relevant field, stating "Bitte füllen Sie dieses Feld aus" ("Please fill out this field"), and should stay anchored to the field even when the page is scrolled.

**behaviour:** 
In Firefox, the tooltip detaches from the input field upon scrolling and moves across the page. This behavior is inconsistent with other browsers (like Chrome, Edge, Safari) where the tooltip stays anchored.

**important screensize:**
Screensize not applicable.

**device & browser:** 
The issue is specific to Firefox.

**Screenshot**
Tooltip appears:
<img width="758" alt="Bildschirmfoto 2024-03-05 um 10 58 36" src="https://github.com/liqd/a4-meinberlin/assets/144320958/fe39f720-518a-486d-9c3d-a1be0756486f">

Then I moves across the page when scrolling:
<img width="943" alt="Bildschirmfoto 2024-03-05 um 10 58 42" src="https://github.com/liqd/a4-meinberlin/assets/144320958/9061b065-acbf-4fa3-8c48-088aa27fce41">

**Comment by sblindow** [comment]
Is this behavior due to our CSS/JavaScript influencing Firefox's rendering, or is it a bug with Firefox's version of tooltip implementation for form validation?

**Comment by vellip** [comment]
This bug has been filed for 10+ years with mozilla. https://bugzilla.mozilla.org/show_bug.cgi?id=643758 I will close this as it's not on our side.
