### ISSUE TITLE
#7768 [mB] re-design registration and login forms: Translations and wording

### ISSUE THREAD

**Issue by sblindow** [liqd/a4-meinberlin#5554]
**URL:**
[Registration Form](https://meinberlin-design-dev.liqd.net/accounts/signup/)
[Log-in Form](https://meinberlin-design-dev.liqd.net/accounts/login/?next=%2F)

**Comment/Question:**
###### Registration Form
- Consent to terms of use and privacy policy is in english on the german page
- "Already have an account?" in the footer needs to be translated to "Sie haben bereits ein Konto?"

###### Log-in Form
- "Don't have an account yet?" in the footer needs to be translated to "Sie haben noch kein Konto?"
- Insted of the form label "Anmeldung" for the login form field, it should be "Nutzername oder E-Mail*" according to the design template.

**Comment by sblindow** [comment]
Is this a dev issue or can this be done by PMs through Weblate?

**Comment by CarolingerSeilchenspringer** [comment]
in Registration form: change "Benutzername" to "Nutzername" in both title and helptext (we use this wording also in all our e-mail footers)
in log-in form: change "Anmeldung" to "Nutzername oder E-Mail"

**Comment by goapunk** [comment]
@sblindow @CarolingerSeilchenspringer you can find design-dev components in weblate now, so translation should be possible

**Comment by CarolingerSeilchenspringer** [comment]
@sblindow can you check again and if needed do the translation?

**Comment by sblindow** [comment]
@Julian All translations on design-dev are done. I will check once, after the changes are implemented, because the translation string for the terms of use and privacy consent has a lot of formatting. If everything worked correctly, we can close the Issue :)

**Comment by vellip** [comment]
@sblindow is there anything left to do here?

**Comment by CarolingerSeilchenspringer** [comment]
@sblindow will close this issue as before final release we will check weblate and test extensively so would see if translations are unexpectedly missing.
