### ISSUE TITLE
test 7768 [mB] re-design registration and login forms: take out placeholder

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#5555]
**URL:** https://meinberlin-design-dev.liqd.net/accounts/signup/?next=/
**user:** 
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** depending on answer from BO we should take placeholder out of the registration and login forms

Screenshot?

**Comment by CarolingerSeilchenspringer** [comment]
answer from BO: no placeholder needed if we have title. Overall agreement (also with a+) that we no longer use placeholder but titles (only) instead.

**Comment by vellip** [comment]
This has already been done with #5699
