### ISSUE TITLE
ckeditor5 character count needs styling or should be removed

### ISSUE THREAD

**Issue by goapunk** [liqd/a4-meinberlin#5564]
see screenshot

![Screenshot 2024-03-13 at 08-18-37 Idea 0 — Rückmeldung geben](https://github.com/liqd/a4-meinberlin/assets/1710203/dbda25fb-5e87-4f0e-b63a-f20c77f8d0de)

**Comment by CarolingerSeilchenspringer** [comment]
@mcastro-lqd can you give a styling?
