### ISSUE TITLE
Wording problem when more than one comment

### ISSUE THREAD

**Issue by pascalkienast** [liqd/a4-meinberlin#5571]
**URL:** https://meinberlin-design-dev.liqd.net
**user:** any
**expected behaviour:** correct wording
**behaviour:** see screenshot
**important screensize:** any
**device & browser:** any 
**Comment/Question:** if there is more than one comment, it must be called "comments" or "Kommentare" in german. The fact that a different string must then be displayed probably still needs to be implemented. Therefore, the problem here is probably not the translation.

Screenshot?
If singular, "Kommentar" is correct
![Screenshot 2024-03-17 at 22-59-37 Multimodul alle Module (Testprojekt) — meinBerlin](https://github.com/liqd/a4-meinberlin/assets/6682526/2d5460d0-f37d-40a9-b94a-2511d9dd9bc8)
If more than 1, it should be "Kommentare"
![Screenshot 2024-03-17 at 22-45-17 Multimodul alle Module (Testprojekt) — meinBerlin](https://github.com/liqd/a4-meinberlin/assets/6682526/1d6ea457-2861-4907-b9af-bd665696547c)

**Comment by goapunk** [comment]
I think this should be fixed once we rebase dev on main, but have to check

**Comment by CarolingerSeilchenspringer** [comment]
@goapunk so will put this onto hold and we'll see once we rebase.

**Comment by goapunk** [comment]
Once https://github.com/liqd/a4-meinberlin/pull/5584 was merged we need to add the translations in weblate and it should be fixed

**Comment by goapunk** [comment]
test link: https://meinberlin-design-dev.liqd.net/projekte/module/burgerinnenhaushalt-2-phasen/?mode=list

**Comment by goapunk** [comment]
done
