### ISSUE TITLE
#7768 [mB] re-design registration and login forms: Styling - Grid + Font space between lines

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#5575]
**URL:** https://meinberlin-design-dev.liqd.net/accounts/signup/?next=/
**behaviour:** *Describe the issue*
**device & browser:** *Chrome and Safari*
**Comment/Question:** *I think the grid is fine like that but I would just confirm with meinBerlin people if that's allowed according to the StyleGuide cause I thought every form should be full width, but maybe that's fine.

Another thing I saw was the Spacing between lines that is different than the style guide(24)
Currently its 19.2 
<img width="538" alt="Screenshot 2024-03-18 at 17 51 22" src="https://github.com/liqd/a4-meinberlin/assets/59610786/84a5b77f-cf47-461c-8198-853cfabdabf4">
<img width="1076" alt="Screenshot 2024-03-18 at 17 59 44" src="https://github.com/liqd/a4-meinberlin/assets/59610786/55bda170-20e4-4f08-9def-73c4817d9f14">

*

**Comment by vellip** [comment]
@mcastro-lqd Were you able to confirm whether or not the form width is fine as is?

**Comment by mcastro-lqd** [comment]
@vellip Yes, the Login forms are based on VHS. They should be like here, cause its from BerlinOnline: 

https://projects.invisionapp.com/share/2A13CASBY38N#/screens

https://projects.invisionapp.com/share/BT13AU2LCYS2#/screens

**Comment by CarolingerSeilchenspringer** [comment]
as discussed between @mcastro-lqd and @hom3mad3 we stick to the form width but please have a look at the spacing mentioned above.
