### ISSUE TITLE
#8012 [mB] re-design moderator feedback 

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#5588]
**URL:** https://meinberlin-design-dev.liqd.net/budgeting/2023-01020/moderate/
**behaviour:** *Main Buttons aren't styled according to styleguide*
**important screensize:** *Both*
**device & browser:** *Chrome and Safari*
**Comment/Question:** *I imagined that this is will be fixed in the future, just wanted to leave it registered here* 

<img width="1075" alt="Screenshot 2024-04-08 at 16 29 12" src="https://github.com/liqd/a4-meinberlin/assets/59610786/b083123c-bb2b-480e-8eab-cbced008e75f">

**Comment by goapunk** [comment]
This is fixed by now
