### ISSUE TITLE
Filter, List and Map View and Proposals-List are not shown at all in Webkit Browsers

### ISSUE THREAD

**Issue by pascalkienast** [liqd/a4-meinberlin#5591]
**URL:** for example: https://meinberlin-design-dev.liqd.net/projekte/burgerhaushalt-3-phasen-mit-support-testprojekt/?mode=map
**user:** any
**expected behaviour:** it should show the list of proposals and the filters and an list/map view (like in the designs on zeplin) 
**behaviour:** On Safari (macOS and iOS) and therefore in WebKit, it is just not shown at all
**important screensize:** any screensize
**device & browser:** tested in browserstack and on macOS - as soon as safari is used, it is not shown
**Comment/Question:** 
URL on Safari:
<img width="1104" alt="Bildschirmfoto 2024-04-09 um 17 21 28" src="https://github.com/liqd/a4-meinberlin/assets/6682526/9b08efa8-4605-4463-a6fc-a791df7754a6">

Same Site on Firefox:
![Screenshot 2024-04-10 at 09-25-34 Bürgerhaushalt (3 Phasen) — meinBerlin](https://github.com/liqd/a4-meinberlin/assets/6682526/faebdae6-209e-4e70-9182-5fcee87fbdda)

**Comment by goapunk** [comment]
I think it's due to the broken tabs but will have to take a closer look

**Comment by karlcow** [comment]
in STP 192

![Screenshot 2024-04-12 at 14 13 21](https://github.com/liqd/a4-meinberlin/assets/505230/ae804c50-c61b-4bd6-846f-3db9569823e7)

**Comment by goapunk** [comment]
> in STP 192
> 

@karlcow thanks :)

**Comment by vellip** [comment]
@pascalkienast @goapunk this has been fixed then, right? Will close, feel free to open up again & specify any missing steps if not.
