### ISSUE TITLE
streamline breakpoints & replace hardcoded values

### ISSUE THREAD

**Issue by hom3mad3** [liqd/a4-meinberlin#5592]
## Issue Description:
Our scss code still uses old breakpoint values, and we're unsure if they'll match the new design for user-facing views. Plus, some parts of the new code is being declared using fixed numbers instead of flexible variables. We need to decide whether to keep using the old values or add new ones for the redesign, while ensuring everything still works for the dashboard.

**Expected Behavior:** 
Figure out if we need new breakpoint values for the redesign, while also replacing fixed numbers with flexible variables throughout the code to make things easier to manage and compatible with both old and new designs.

**Tasks:**
1. Ensure breakpoints adapt smoothly to redesign for both dashboard and user-facing views.
2. Replace hardcoded values with variables for code flexibility.
3. Check for differing breakpoints between dashboard and user-facing views, considering separate sets if needed.

**Comment by CarolingerSeilchenspringer** [comment]
@hom3mad3 has this been resolved via the breakpoint story?
