### ISSUE TITLE
Navigation icon for open answer in survey module too large

### ISSUE THREAD

**Issue by pascalkienast** [liqd/a4-meinberlin#5616]
**URL:** e.g. https://meinberlin-stage.liqd.net/projekte/module/umfrage-78/ (on dev and stage - so, maybe also on prod)
**user:** any
**expected behaviour:** see screenshot from zeplin
**behaviour:** the buttons for navigations are bigger than in the zeplin design
**important screensize:** any (also mobile)
**device & browser:** any
**Comment/Question:** i think this issue is really minor, since it currently looks also ok. 
And it seems to be no A4-Issue, since on A+ the Nav-Icon is smaller.

Here is the nav-icon on a+: ![Screenshot 2024-05-08 at 12-43-27 adhocracy _permanent test projects](https://github.com/liqd/a4-meinberlin/assets/6682526/0e77b120-60a7-45d6-b568-66936080bfdb)

Screenshot?
This is currently how it looks:
![Screenshot 2024-05-08 at 12-47-02 Big multimodule test project — meinBerlin](https://github.com/liqd/a4-meinberlin/assets/6682526/c472c156-5cc8-428c-a40b-230ff8e3ae03)

This is the design on zeplin
![Screenshot 2024-05-08 at 12-46-47 Zeplin - Projects](https://github.com/liqd/a4-meinberlin/assets/6682526/a5dfa59a-c466-44fc-a785-b161ed06d1f8)

**Comment by CarolingerSeilchenspringer** [comment]
@hom3mad3 is this something you can fix while working on the poll module re-design? It is the old design bug a feature used quite often so I think worth fixing before launch of re-design.
