### ISSUE TITLE
Big images are not shown in Chrome

### ISSUE THREAD

**Issue by pascalkienast** [liqd/a4-meinberlin#5617]
**URL:** https://mein.berlin.de/projekte/isek-fur-das-fordergebiet-badstraepankstrae/?initialSlide=1
**user:** any
**expected behaviour:** the images should load
**behaviour:** the images are not loading and the site is broken
**important screensize:** any
**device & browser:** On Chrome Browsers
**Comment/Question:** the console in chrome gives an 404 for https://mein.berlin.de/api/follows/... (see screenshot)
And the images that are embedded are extremly big (around 29000x18000 pixel and 10mb filesize)

Screenshot?
The console in chrome:
<img width="1377" alt="Bildschirmfoto 2024-05-13 um 11 24 49" src="https://github.com/liqd/a4-meinberlin/assets/6682526/fb889d41-48e3-4a6d-ad8a-ab8af1b0454b">

How the site looks on chrome:
![Screenshot_Chrome](https://github.com/liqd/a4-meinberlin/assets/6682526/65e00dea-d9dc-4db2-b79e-affa07b5fcbe)

How the site looks in other browsers (firefox)
![Screenshot_Firefox](https://github.com/liqd/a4-meinberlin/assets/6682526/0e8e64c0-a715-4ca2-9694-b04bc5eac060)

**Comment by CarolingerSeilchenspringer** [comment]
please set the max size to 5MB

**Comment by CarolingerSeilchenspringer** [comment]
will be a story.
