### ISSUE TITLE
cannot edit my own subcomment

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#5657]
**URL:** https://meinberlin-stage.liqd.net/mapideas/2024-02606/
**user:** registered user, also true for admin and moderation
**expected behaviour:** I can edit my idea via "bearbeiten"
**behaviour:** the comment changes to "Nur eingeladene Nutzer*innen können sich aktiv beteiligen." Clicking on edit again makes the comment appear again.
**important screensize:**
**device & browser:** 
**Comment/Question:** only on stage, not on prod and dev!

original comment
<img width="554" alt="Bildschirmfoto 2024-07-01 um 20 31 07" src="https://github.com/liqd/a4-meinberlin/assets/35491681/ea8ce253-0726-4561-8957-986075f6f57d">

comment after trying to edit
<img width="549" alt="Bildschirmfoto 2024-07-01 um 20 31 39" src="https://github.com/liqd/a4-meinberlin/assets/35491681/30668113-b6da-44ab-8a2d-e95c20ed49c4">

**Comment by goapunk** [comment]
only applies to child comments, very likely also exists on prod

**Comment by CarolingerSeilchenspringer** [comment]
@goapunk you are right, that's why I couldn't reproduce.

**Comment by goapunk** [comment]
@CarolingerSeilchenspringer this should be fixed (but not released) by now (https://github.com/liqd/adhocracy4/pull/1642)

**Comment by vellip** [comment]
tested locally, can confirm
