### ISSUE TITLE
#8231 [mB] optimize image upload

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#5680]
**URL:** https://meinberlin-dev.liqd.net/dashboard/projects/project-0999/information/
**user:** *initiator*
**behaviour:** *In the story Caro mentioned* 

> Add an file-size restriction of 5mb to CKEditor Image-Uploads (Here the error-message should be shown like the message when no alt-text is given to the image, but with the message “Das Bild darf höchstens 5 MB groß sein.”) - For mB wording (from weblate): “Image should be at most {max_size} MB” // “Das Bild darf höchstens {max_size} MB groß sein.”

However this is not happening cause I uploaded a 6mb pic and it worked out fine without error message

<img width="625" alt="Screenshot 2024-08-01 at 11 51 00" src="https://github.com/user-attachments/assets/868108c4-650d-4929-a070-09b8abd89163">

**Comment by pascalkienast** [comment]
@mcastro-lqd thanks for the issue. i also noticed the same (and just wanted to write an issue as well)
No matter how large the image (i also tryed an 6mb and even a 30mb image), everything worked and there was no error message.

**Comment by goapunk** [comment]
@mcastro-lqd @pascalkienast sorry, somehow the code didn't make it on the dev server as intended. It should work now, could you check again?

**Comment by pascalkienast** [comment]
@goapunk yes, now it seems to work. I would check it briefly in other browsers etc., but basically this issue can actually be closed now, as the problem is no longer so fundamental that it is not working at all
<img width="1080" alt="Bildschirmfoto 2024-08-05 um 09 40 42" src="https://github.com/user-attachments/assets/f6a4ddb8-9ae2-4922-bd2c-5b9ed284ddcf">

**Comment by pascalkienast** [comment]
I have now tested this as initiator, admin, as well as under chrome, firefox, safari and via browserstack on mobile devices. It worked everywhere, so this issue can definitively be closed
