### ISSUE TITLE
#8163 [mB] improve performance for /projekte – Projects with a future participation phase appear in the 'running' filter 

### ISSUE THREAD

**Issue by sblindow** [liqd/a4-meinberlin#5682]
**URL:** 
https://meinberlin-dev.liqd.net/projekte/
scroll down to 'Beteiligungshaushalt Berlin 2023' for example

**user:** 
any

**expected behaviour:** 
Projects that have a participation planned, but are not active yet, should not appear in the list, when the 'running' filter is set.

**behaviour:** 
Currently these projects do appear in the list and slip through the filter.

Screenshot?
![Bildschirmfoto 2024-08-15 um 10 43 54](https://github.com/user-attachments/assets/4b6367ea-3604-435e-9b32-16fc4d5acc0a)

**Comment by goapunk** [comment]
I think this is actually intentional (and it always has been like this), the `running` filter shows all projects which you can participate now or in the future. Let's wait for @CarolingerSeilchenspringer to confirm and close this if so
