### ISSUE TITLE
#8163 [mB] improve performance for /projekte – loadtimes exceed 5 seconds by ~20 seconds on refresh every 5 minutes

### ISSUE THREAD

**Issue by sblindow** [liqd/a4-meinberlin#5683]
**URL:**
https://meinberlin-dev.liqd.net/projekte/

**user:** 
any

**expected behaviour:** 
/projekte should fully load in less than 5 seconds for any user at any time. 

**behaviour:** 
/projekte takes significantly longer to load every 5 minutes for the first user requesting the page. (between 20 and 30 seconds)

**Comment by goapunk** [comment]
should be fixed now via admin repo
