### ISSUE TITLE
#7864 [mB] redesign comments and replies (Report/Share)

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#5694]
**URL:** https://meinberlin-design-testing-dev.liqd.net/ideas/2024-01098/
**important screensize:** *Mobile*
**device & browser:** *Safari Version 17.5 (19618.2.12.11.6) / Chrome Version 126.0.6478.127 (Official Build) (arm64)*
**Comment/Question:** 

<img width="426" alt="Screenshot 2024-09-03 at 09 00 26" src="https://github.com/user-attachments/assets/2649db76-f412-4ad1-a299-f390e75d279a">

Regarding this area here, I agree that it looks an error. I was thinking, if its not super difficult/time consuming to change that now, would it be possible to just leave the Like/Dislike/Comment on Mobile and add the Report and Share under the ellipsis-V? 

Also for Mobile, we could maybe leave a little bit less spacing between them cause on iPhone it looks like this and it would make more sense to have them more aligned with the grey line:
![IMG_2453](https://github.com/user-attachments/assets/4271be22-f15c-43f6-b4e8-31436db0453c)

**Comment by CarolingerSeilchenspringer** [comment]
@vellip as discussed with @mcastro-lqd and @MarleyMi we can think of three options to solve this: 1) take out the words like/dislike as the icons should be self-explanatory,  2) hide share and report behind three dots (if @TeaJayyy agrees we could do this in A4) or 3) move wording below icons as done e.g. by linkedIn
<img width="448" alt="Bildschirmfoto 2024-10-07 um 16 43 39" src="https://github.com/user-attachments/assets/e44da612-a829-4dec-927c-f5b58c629fb6"> Can you say/ check which one of those solutions would work best for you?

**Comment by vellip** [comment]
@CarolingerSeilchenspringer I'd say 1) and 3) are the easiest done as I have no say about whether you want to move those buttons globally in a4.

**Comment by CarolingerSeilchenspringer** [comment]
@vellip please go for 3) then and lets see how that works.

**Comment by vellip** [comment]
@CarolingerSeilchenspringer fixed in #5724
