### ISSUE TITLE
#7864 [mB] redesign comments and replies (list/ map view of ideas is missing in Safari(macOS) and on IOS(all browsers))

### ISSUE THREAD

**Issue by sblindow** [liqd/a4-meinberlin#5697]
**URL:** 
https://meinberlin-design-dev.liqd.net/projekte/module/brainstorming-mit-karte-12/

**user:** 
any

**expected behaviour:** 
In all map based modules (brainstorming with map, idea challenge with map, participatory budgeting, prioritization with map) the Module page should load with the list/ map view of ideas 

**behaviour:** 
On the following set-ups:
- macOS: Safari
- IOS: all Browsers (tested Safari, Chrome and Firefox)

the list/ map view of ideas/ proposals doesn't load in the above mentioned modules.

**device & browser:** 
- macOS: Safari
- IOS: all Browsers (tested Safari, Chrome and Firefox)

**macOS - Firefox**
---
![macOS-Firefox](https://github.com/user-attachments/assets/91be0d3a-a218-400b-a4f5-afab280c7456)
---
**macOS - Safari**
---
![macOS-Safari](https://github.com/user-attachments/assets/cf21884a-336b-42cb-8e52-aafc82c311ea)
---
**Single Module (prioritization with map) - left: firefox, right: safari**
---
![firefox-left_safari-right](https://github.com/user-attachments/assets/e57577a4-b5e6-49da-8b2e-b37e986d76ff)
---

**Comment by goapunk** [comment]
fixed
