### ISSUE TITLE
Comment section width is currently resizable

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#5716]
**URL:** https://meinberlin-design-testing-dev.liqd.net/ideas/2024-01098/
**user:** *all*
**expected behaviour:** *That only the height is expandable by the user, the width should be resized by the screen responsiveness.*
**behaviour:** *Currently the whole comment section is resizable.*
**important screensize:** *Desktop*
**device & browser:** *Safari Version 17.6 (19618.3.11.11.5)*

<img width="1009" alt="Screenshot 2024-10-08 at 15 00 34" src="https://github.com/user-attachments/assets/91baf557-0177-41cc-8c0b-ea3eb53d1b35">
<img width="1323" alt="Screenshot 2024-10-08 at 15 00 00" src="https://github.com/user-attachments/assets/ffe78f3e-6cc3-49b0-b56d-0b9ec728b195">

**Comment by CarolingerSeilchenspringer** [comment]
@hom3mad3 @vellip @jonasDarley3000 can someone take over this issue? then we can close the issue story from sprint 21-24.

**Comment by hom3mad3** [comment]
@hom3mad3 can do!

**Comment by goapunk** [comment]
fixed
