### ISSUE TITLE
#8433 fix: improve text-based emails (remove html) - some mails still have html tags in the plaintext part

### ISSUE THREAD

**Issue by sblindow** [liqd/a4-meinberlin#5725]
## expected behaviour:
As a user I want to have the option to read all mein.berlin mails in clean plaintext.

## behaviour: 
After the Improvement, some mails still have html tags in them:

### 'office worker notification' and 'submitter confirmation'

https://github.com/liqd/a4-meinberlin/blob/219819b1f40b062ae2cd553bad26da6bf700de74/meinberlin/apps/bplan/templates/meinberlin_bplan/emails/office_worker_notification.de.email 
https://github.com/liqd/a4-meinberlin/blob/219819b1f40b062ae2cd553bad26da6bf700de74/meinberlin/apps/bplan/templates/meinberlin_bplan/emails/submitter_confirmation.de.email

The user statement that is inserted at the bottom of these two emails is encapsulated by an html paragraph tag.

 **screenshots:**
---
![new-statement](https://github.com/user-attachments/assets/dde370b0-c651-4396-8906-c71d904f8a39)
---
![your-statement](https://github.com/user-attachments/assets/1c577f37-9166-4844-bd3d-2ff0517bb76f)
---

### 'notify creator on moderator feedback'

https://github.com/liqd/a4-meinberlin/blob/219819b1f40b062ae2cd553bad26da6bf700de74/meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_creator_on_moderator_feedback.de.email 
https://github.com/liqd/a4-meinberlin/blob/219819b1f40b062ae2cd553bad26da6bf700de74/meinberlin/apps/notifications/templates/meinberlin_notifications/emails/notify_creator_on_moderator_feedback.en.email  

In this mail the greeting is encapsulated by html tags. Another Issue you can see in the plaintext is the 'Rückmeldung:' string. This is not visible in the html version of the mail (see screenshot).

**screenshot**
---
![moderator-feedback](https://github.com/user-attachments/assets/b85b31df-127d-40d9-b368-ad8bea82b4da)
---
![moderator-feedback_html](https://github.com/user-attachments/assets/827e32ad-1af7-4379-b25b-755e517f15d1)
---

### Newsletter, Initiator Mail and Platform Mail

Links to the code were not in the US so these might have been overlooked. These can be sent by Initiators in the Organization Dashboard.

**screenshots**
---
![newsletter](https://github.com/user-attachments/assets/c138ef77-6cd6-4187-bd20-bb1c22446001)
---
![initiator-mail](https://github.com/user-attachments/assets/c49ce852-51d0-4e71-b27f-d34f777aa4ec)

**Comment by vellip** [comment]
also a sentry error:

UnicodeEncodeError: 'utf-8' codec can't encode characters in position 191-192: surrogates not allowed
(16 additional frame(s) were not displayed)
...
  File "meinberlin/apps/newsletters/emails.py", line 25, in dispatch
    return super().dispatch(object, *args, **kwargs)

**Comment by CarolingerSeilchenspringer** [comment]
@vellip @hom3mad3 who can handle this issue? the respective story is already closed (as we decided on the new issue process afterwards).

**Comment by hom3mad3** [comment]
@CarolingerSeilchenspringer @vellip wonder if this could be handled with the new email template story? @MarleyMi is already aware

**Comment by CarolingerSeilchenspringer** [comment]
good idea @hom3mad3 ! @MarleyMi I added a link to this issue to the story.

**Comment by vellip** [comment]
fixed with #5766 
It's impossible to fix newsletter emails or any emails that contain CKEditor 5 content because that just simply is rich text. In those cases html will still be delivered. We did fix a ton of those emails now and it's definitely already better than what it was before.
