### ISSUE TITLE
#8447 #8469 #8470 #8448 [mB] project overview 

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#5764]
**URL:** https://meinberlin-design-dev.liqd.net/projekte/
**user:** *all*
**important screensize:** *Both*
**device & browser:** *Safari Version 18.1.1 (20619.2.8.11.12) & Chrome Version 131.0.6778.86 (Official Build) (arm64)*
**Comment/Question:** *Is it fine if I add here as a list?

01 – Can we keep the Form padding here the same? Otherwise they move a bit depending on the viewing mode and it create more chaos. If they stay the same, the switch would be smoother like this prototype here: https://www.figma.com/proto/vzwVPLittUtVRDfb8QBPR6/meinBerlin?node-id=854-21431&t=ma2DE9VIqe4CGe5f-1 
You can even keep the same grey width for both because Kiezradar will also have more stuff going on so I think it's fine to have this one as a big thing. 

![Frame](https://github.com/user-attachments/assets/634306c7-d8b6-4c2f-a869-75096fa90647)

02 – The empty state is missing. _(Ignore if its planned differently)_

03 – Is is possible to make the padding here a bit bigger? So it doesn't touch the Close X button when more pills are added? 
Also, when Selected, the Pin Icon should switch to Green if possible. 
<img width="477" alt="Screenshot 2024-11-26 at 17 04 19" src="https://github.com/user-attachments/assets/baf84324-b27c-4ac0-a884-aec09aff6c43">

04 – Would it possible to enable users to use scrolling to zoom in and out in the map? 

05 – Is there a way to show the actual Filters in the Pill? _(e.g. Instead of Districts show Kreuzberg)_
<img width="260" alt="Screenshot 2024-11-26 at 17 06 59" src="https://github.com/user-attachments/assets/0e7b61fd-128e-47d5-9b92-0209b27a9610">

06 – The Img Copywriter is currently size 8pt, in the StyleGuide is 11pt 
<img width="870" alt="Screenshot 2024-11-26 at 17 18 05" src="https://github.com/user-attachments/assets/d78b9993-0364-4b63-a0ef-fdb02d44fb7d">
<img width="340" alt="Screenshot 2024-11-26 at 17 20 57" src="https://github.com/user-attachments/assets/6e19b73f-68c3-4b44-9018-f06d3274c1c6">

07 – Could we have the spacing here fixed like all the same?
![Spacing](https://github.com/user-attachments/assets/24df090c-f1de-411e-b9ee-2dbb7197119e)

08 – I had the feeling that on Mobile the tiles could have a bit more spacing here in order to give a bit of space to breathe between them. 
![spacing tiles mobile](https://github.com/user-attachments/assets/94f1efbe-a2dd-4f0b-bd89-662672972ed1)

09 – I have no idea why, but this button on Safari is bold + grey on Mobile:
![IMG_5267](https://github.com/user-attachments/assets/b1c98fb6-e13c-442b-a5e4-e0c69436d760)

10 – Is this styling coming from somewhere on the StyleGuide?
![IMG_5269](https://github.com/user-attachments/assets/bfbb59bf-ad3a-4d75-a1d3-8eeb0738fc6f)

11 – I guess on Mobile the Map Tile wasn't implemented yet, so if that's the case, ignore my comment, just putting here because I have to: 
![IMG_5272](https://github.com/user-attachments/assets/16aeb4ca-a1e8-4310-b57c-1de1ad027fd4)

*

**Comment by CarolingerSeilchenspringer** [comment]
@vellip can you have a look on the design issues regarding map and filter?
