### ISSUE TITLE
#8481 [mB] re-design button in registration process

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#5765]
**URL:** https://meinberlin-design-dev.liqd.net/accounts/password/reset/
**user:** *all*
**important screensize:** *Mobile*
**device & browser:** *Safari Version 18.1.1 (20619.2.8.11.12) & Chrome*
**Comment/Question:** *Main Default Buttons on Mobile are Bold, they are Regular* 

![IMG_5276](https://github.com/user-attachments/assets/a2edeb5d-9467-408e-93db-4b4c6fbeff58)

**Comment by CarolingerSeilchenspringer** [comment]
@vellip can you have a look?
