### ISSUE TITLE
#8546 [mB] interactive event: statistics (Sev) - Issue with filters when switching between Questions and Statistics view

### ISSUE THREAD

**Issue by sblindow** [liqd/a4-meinberlin#5773]
**user:** 
all

**expected behaviour:** 
Wether the filters are removed when switching to the statistics view or kept, the displayed list should be consistent with the indicated fitler selections.

**behaviour:** 
Going to the statistics and then back to the questions removes the filter selection form the drop-down but doesn't reset the list (any user & any filter).

**Comment by CarolingerSeilchenspringer** [comment]
if easy remember the filter. If this is more difficult then remove filter and adapt list accordingly.

**Comment by sevfurneaux** [comment]
@CarolingerSeilchenspringer This is now resolved and merged in the [[#8546] Pass initial filter state to filters](https://github.com/liqd/a4-meinberlin/pull/5869).
