### ISSUE TITLE
#8546 [mB] interactive event: statistics (Sev) - 'bookmarked' pill appears on questions in the 'answered questions' list

### ISSUE THREAD

**Issue by sblindow** [liqd/a4-meinberlin#5774]
**URL:** 
example project: https://meinberlin-design-dev.liqd.net/projekte/module/interaktive-veranstaltung-4/

**user:** 
all

**expected behaviour:** 
The bookmarked attribute is meant to indicated which questions have been chosen for discussion by the moderators, but have not been answered yet. Accordingly this attribute only makes sense on the questions list. If a question has been answered, it does not matter anymore, wether it has been bookmarked before.

**behaviour:** 
the 'bookmarked' pill appears on questions in the 'answered questions' list

**Screenshot:**
---
![Bildschirmfoto 2024-11-27 um 16 25 56](https://github.com/user-attachments/assets/70c98766-7dac-49de-ace7-5cb0ca1a13bb)
---

**Comment by sevfurneaux** [comment]
Closing this issue, as it is merged in a PR.
