### ISSUE TITLE
Uploaded image permissions

### ISSUE THREAD

**Issue by 2e2a** [liqd/a4-meinberlin#581]
The ckeditor sometimes(?) sets the file permissions of uploaded files to 600 (`-rw-------`) resulting in 403 errors, as the serving nginx cannot read them.

**Comment by kleingeist** [comment]
not sure how to handle this, as we can't reproduce it :/

**Comment by 2e2a** [comment]
> not sure how to handle this, as we can't reproduce it :/
I'll close this issue. It was rather for documentation in case it occurs again, which did not happen since.
