### ISSUE TITLE
#8470 mB Project Overview: Tile in Map - Tile appears behind the map when zooming out quickly.

### ISSUE THREAD

**Issue by sblindow** [liqd/a4-meinberlin#5816]
**URL:** 
https://meinberlin-design-dev.liqd.net/projekte/

**user:** 
any

**expected behaviour:** 
Using the + and - buttons on the map to zoom in and out feels intuitive and smooth.

**behaviour:** 
When using the buttons to zoom out quickly, an enlarged version of the last selected tile is visible in the spaces of the map that take a little longer to load. This results in a slightly disorienting and buggy feeling user experience.

**device & browser:** 
occured on all devices, mobile included

**Comment by CarolingerSeilchenspringer** [comment]
at least in chrome on mac when zooming the whole map jumps to a different place including the zoom buttons. I have to scroll to zoom again.
