### ISSUE TITLE
#8470 mB Project Overview: Tile in Map - Tiles are missing the Project Teaser Text (Desktop)

### ISSUE THREAD

**Issue by sblindow** [liqd/a4-meinberlin#5817]
**URL:** 
https://meinberlin-design-dev.liqd.net/projekte/
**user:** 
any

**expected behaviour:** 
The project tiles should contain the Teaser text of the project (kurzbeschreibung)

**behaviour:** 
The Teaser Text is not visible on the tiles.

**Comment by CarolingerSeilchenspringer** [comment]
decided to now show the text for now.
