### ISSUE TITLE
#8470 mB Project Overview: Tile in Map - Tile is broken on mobile

### ISSUE THREAD

**Issue by sblindow** [liqd/a4-meinberlin#5818]
**URL:** 
https://meinberlin-design-dev.liqd.net/projekte/

**user:** 
any

**expected behaviour:** 
Tiles on mobile should exclude the teaser text but contain image, category, title, progressbar and (semi-)private icon.

**behaviour:** 
currently the tile appear to be broken. Only the projects image is visible.

**device & browser:** 
All mobile platforms

**Comment**
Also Mentioned in: https://github.com/liqd/a4-meinberlin/issues/5764

**Comment by CarolingerSeilchenspringer** [comment]
probably connected to https://github.com/liqd/a4-meinberlin/issues/5821

**Comment by vellip** [comment]
will be fixed by #5776
