### ISSUE TITLE
#8470 mB Project Overview: Tile in Map - Project Status is not reflected pin color

### ISSUE THREAD

**Issue by sblindow** [liqd/a4-meinberlin#5819]
**URL:**
https://meinberlin-design-dev.liqd.net/projekte/

**user:** 
any

**expected behaviour:** 
Active Projects should be discernable by their green pin, while the pin for inactive projects should be dark blue.

**behaviour:** 
Currently all pins are dark blue.

**Comment by vellip** [comment]
will be fixed by #5776
