### ISSUE TITLE
#8448 [mB] Project overview: Filter and Search - Filtering for anything in "kind of participation" crashes the project overview

### ISSUE THREAD

**Issue by sblindow** [liqd/a4-meinberlin#5820]
**URL:** 
https://meinberlin-design-dev.liqd.net/projekte/

**user:** 
any

**expected behaviour:** 
The filter should work.

**behaviour:** 
When filtering for any combination of selections in the "kind of participation" filter, the project overview crashes and just shows a blank section.

**device & browser:** 
Any system and browser

**Comment by vellip** [comment]
will be fixed by #5776
