### ISSUE TITLE
#8470 mB Project Overview: Tile in Map - tiles are not clickable on mobile

### ISSUE THREAD

**Issue by sblindow** [liqd/a4-meinberlin#5821]
**URL:** 
https://meinberlin-design-dev.liqd.net/projekte/

**user:** 
any

**expected behaviour:** 
Tapping the tiles anywhere on their area except the small x in the top right corner should lead to the corresponding project.

**behaviour:** 
Cannot tap tiles on mobile.

**device & browser:** 
All mobile platforms

**Comment by CarolingerSeilchenspringer** [comment]
probably connected to https://github.com/liqd/a4-meinberlin/issues/5818
