### ISSUE TITLE
#8448 [mB] Project overview: Filter and Search - organization search bar is selectable through the filter menus

### ISSUE THREAD

**Issue by sblindow** [liqd/a4-meinberlin#5822]
**URL:** 
https://meinberlin-design-dev.liqd.net/projekte/

**user:** 
any

**expected behaviour:** 
filter menus should block the mouse icon from selecting the organization search bar when they are layered on top of it.

**behaviour:** 
trying to select a filter option that is layered directly over the organization search bar, selects the text field of the search bar instead.

**device & browser:** 
All Platforms, desktop and mobile

**Comment by vellip** [comment]
Has recently been fixed
