### ISSUE TITLE
#8466 #8467 #8547 #8546 Interactive Event

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#5841]
**URL:** https://meinberlin-design-dev.liqd.net/projekte/module/interactive-event/
**important screensize:** *Both*
**device & browser:** *Safari Version 18.1.1 (20619.2.8.11.12) + Chrome Version 131.0.6778.86 (Official Build) (arm64)*
**Comment/Question:** *Will add a couple points here related to the stories cause they are mostly styling.* 

01 – I know that the design was confusing cause I should have documented better this behaviour, but if it was not understandable by looking at it, it probably won't work at all. I still find weird to use green as a **Hide** button, therefore I tried black for some of them, but I guess its better if we could just to use them all the same, you can find them in the Figma file in the component page.  
<img width="206" alt="Screenshot 2024-12-03 at 18 41 17" src="https://github.com/user-attachments/assets/6e500ad0-648b-4751-acca-4aa8fcae7bb9">
<img width="222" alt="Screenshot 2024-12-03 at 18 48 36" src="https://github.com/user-attachments/assets/e4bf6b7b-86c7-4bcc-9aa4-33c4ab0c1f5a">

02 – The statistics aren't working yet probably? If it was not implemented yet, ignore this comment.
<img width="1013" alt="Screenshot 2024-12-03 at 18 30 29" src="https://github.com/user-attachments/assets/a4e03235-5ed9-476f-8701-0ccec205caa7">

03 – Normally this Button has a bit more padding between the icon and the wording, could you fix that please?
<img width="121" alt="Screenshot 2024-12-03 at 18 30 47" src="https://github.com/user-attachments/assets/dc679863-5833-4732-bb24-7b15737636b6">

04 – Is it possible to align this in a better way? I know it might be hard, but it looks super unbalanced.
<img width="876" alt="Screenshot 2024-12-03 at 18 55 06" src="https://github.com/user-attachments/assets/b414a70b-53c5-43d0-aed8-caab0946ebd5">

05 – Also the distribution of the elements here are divided equally but It should be Frage + Pill on top and Like at the bottom 
<img width="743" alt="Screenshot 2024-12-03 at 18 59 37" src="https://github.com/user-attachments/assets/2e273706-8f94-48e4-9b92-f33afb864e15">

06 – Same here with the intro text. 
<img width="832" alt="Screenshot 2024-12-03 at 19 02 22" src="https://github.com/user-attachments/assets/bb925390-5d8f-4009-8a5c-7dd9d61a9317">

07 – Can we use this video size from the Styleguide? It takes way less space and it can expand only when clicked on it.
<img width="1033" alt="Screenshot 2024-12-03 at 19 04 52" src="https://github.com/user-attachments/assets/c50c5534-5c55-43d1-beae-52e0a195eacc">
https://styleguide.berlin.de/patterns/09-vertical_marketing-page-modul-video/09-vertical_marketing-page-modul-video.html

08 – Is there a possibility to create one option called ALL that cancels all the other selected ones? It's difficult to go back to all if we have to deselect all. Trying to figure out a better solution for that, specially on Mobile is a bit annoying. 
![IMG_5521](https://github.com/user-attachments/assets/54a444b6-d068-4e3c-9d35-a47f3127c0e5)

**Comment by CarolingerSeilchenspringer** [comment]
No 6 can be ignored as we decided to take this navigation out all together, there will be a separate story for it.

**Comment by sevfurneaux** [comment]
@CarolingerSeilchenspringer These are all fixed in the following PR https://github.com/liqd/a4-meinberlin/pull/5858, awaiting review and deployment.

One note on point 08:

> 08 – Is there a possibility to create one option called ALL that cancels all the other selected ones? It's difficult to go back to all if we have to deselect all. Trying to figure out a better solution for that, specially on Mobile is a bit annoying.

The filters use a `<MultiSelect />` component which is used across the whole site, so if we added "All" as an option, we'd need to change it in this complex component. I'd suggest we add that as a separate ticket if we want to make this change.

**Comment by CarolingerSeilchenspringer** [comment]
@sevfurneaux thanks, will close this issue then and prepare a story.

**Comment by sevfurneaux** [comment]
@CarolingerSeilchenspringer great, thanks 🙏
