### ISSUE TITLE
#8527 [mB] re-design mailings (Philipp)

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-meinberlin#5850]
**device & browser:** *Thunderbird + Mailbox Webmail*

I've already talked to @vellip but Im leaving it here as well for sprint organisation.

Mails aren't loading as they are supposed to and I have no option to select that I want to display remote content. 

<img width="1052" alt="Screenshot 2024-12-04 at 16 15 15" src="https://github.com/user-attachments/assets/1ecb14f0-5fff-45f9-941f-0300d4fb3915">
<img width="974" alt="Screenshot 2024-12-04 at 16 15 47" src="https://github.com/user-attachments/assets/4371be30-4176-4451-92dd-5009010d982d">

**Comment by vellip** [comment]
Superseded by https://github.com/liqd/a4-meinberlin/issues/5878
