### ISSUE TITLE
#8571 [mB] project overview: icons for privat & semi public projects (Sev)

### ISSUE THREAD

**Issue by Anastasiia3040** [liqd/a4-meinberlin#5853]
**URL:** https://speakup.digital/projects/feedback-fur-speakup/
**user:** *moderator/ initiator/ participants/ visitors (non-logged-in)/ admin/ cms-editors/ developers*
**important screensize:** *Both*
**device & browser:** *Chrome Version 131.0.6778.109 (Official Build) (arm64) **
**Comment/Question:** 

￼I’m not sure if that makes sense,  however the progress bar doesn’t work properly. If it wasn't implemented yet, ignore this. 

<img width="529" alt="Screenshot 2024-12-04 at 17 14 34" src="https://github.com/user-attachments/assets/c2d9c17a-b6b0-4a37-8f9b-6ba10aaa8d02">

In mobile version the picture doesn't alligned. And it goes beyond the white frame. Is it possible to fix this issue?

![Screenshot 2024-12-04 at 11 57 18](https://github.com/user-attachments/assets/7f2987bb-6415-46c6-9db6-2ac4d6ac63c5)

**Comment by vellip** [comment]
second part is covered by me.

the first part seems to be right to me. Not sure if you meant that the bars differ in their length but it says 27 days in both, but its actually correct that way, because one starts in november and one starts in december.

let me know if you disagree @Anastasiia3040

**Comment by CarolingerSeilchenspringer** [comment]
@Anastasiia3040 @vellip I agree this is a bit confusion but correct as the relation dark/light green depends on the overall length of participation phase. So as @vellip said 27 days out of 2 month is different than out of 6 month. It has been like this before and we are not 100% happy with it but will leave it for now.
