### ISSUE TITLE
#8450 [mB] update and release meinBerlin - Rating buttons have been impacted by A4 changes

### ISSUE THREAD

**Issue by sblindow** [liqd/a4-meinberlin#5876]
**behaviour**
Rating buttons on ideas, proposals and comments have a changed design.

**device & browser:**
All devices
 
**Screenshots**

---

Rating buttons look like this now on stage:

<img width="670" alt="Bildschirmfoto 2024-12-10 um 14 08 21" src="https://github.com/user-attachments/assets/273d1807-eeae-4baf-9def-0fc6ac0c31bc">

---

This is what they should look like:

<img width="175" alt="Bildschirmfoto 2024-12-10 um 14 05 10" src="https://github.com/user-attachments/assets/eceb162d-c7fc-4185-9b1b-893e4065252e">

**Comment by goapunk** [comment]
ups :/ @vellip @hom3mad3 where the rating / like changes a breaking change in a4?

**Comment by vellip** [comment]
@goapunk oh. I wasn't aware this was going to be pushed to prod. regarding a+ afaik @CarolingerSeilchenspringer said, they want the same style for a+. My fault, sorry. I assumed that there is the `.aural` class in all liqd projects. Projects would then need this css `.aural {height:1px;overflow:hidden;position:absolute;top:-1000px;width:1px;margin:0 !important;padding:0 !important}`

**Comment by vellip** [comment]
otherwise I can go back and remove the aural class and try to do it with aria attributes instead.

**Comment by goapunk** [comment]
I guess it's not just the aural but also the icon, right? I think we might have arrived at a point where we need to branch out a4 into current prod and redesign prod (until the redesign is done). 

Apart from that I think `.aural` comes from the BO styleguide, in a4 we use `a4-sr-only` and either do
```
.a4-sr-only {
@extend .visually-hidden;
```
in a+ and mb prod
or 
```
.a4-sr-only {
@extend .aural;
}
```
for the redesign. So in any case we probably want to replace `aural` with `a4-sr-only`

**Comment by CarolingerSeilchenspringer** [comment]
@goapunk @vellip I was considering to just take the new rating design to prod already but just realized that that would not effect the new rating item on all idea tiles. This is probably also true for a+ and needs to be considered by @t-j-q ?

**Comment by CarolingerSeilchenspringer** [comment]
as discussed today: we will change the icon from ^ to "thumbs up" in A4. That should be both for the rating of ideas/comments/replies, but also on the tiles. This is how it will stay for a+, for mB there will be a new solution coming with the re-design as we already have on design-dev.

**Comment by vellip** [comment]
fixed with https://github.com/liqd/a4-meinberlin/pull/5883
