### ISSUE TITLE
Uneven top/bottom margin in item list if only the title is show

### ISSUE THREAD

**Issue by kleingeist** [liqd/a4-meinberlin#590]
If only the title of an item is shown in the item list and neither categories, author, date and additional labels the top and bottom margins are uneven.
![prio-list-space](https://user-images.githubusercontent.com/167407/27688762-19680002-5cdc-11e7-9b20-0cc127e72626.png)

**Comment by phillimorland** [comment]
@MagdaN @fuzzylogic2000 is currently possible to not have at least an author and creation date? if not, i propose we close this issue
