### ISSUE TITLE
Get genders straight (in de translation)

### ISSUE THREAD

**Issue by kleingeist** [liqd/a4-meinberlin#610]
Currently we are using the asterisk `*` on some of the translated texts. For example in
* "E-Mail Adresse der Sachbearbeiter*in"
* "Die Beschreibung verdeutlicht Nutzer*innen was das Ziel des Projekts ist und "
* ...

But are missing it on some other places:
* "Nutzer können Vorschläge mit Budgetangabe machen und erhalten durch "
* "Jeder Nutzer darf pro Frage nur eine Stimme abgeben."
* ... 

I think we should use the asterisk everywhere

**Comment by xi** [comment]
Since meinBerlin is operated by the administration of Berlin, the guidelines ["Geschlechtergerechte Sprache in der Berliner Verwaltung"](https://www.berlin.de/sen/frauen/_assets/flyer_geschlechtergerechte_sprache.pdf) might be interesting.

**Comment by vellip** [comment]
We will use "-innen und er".

**Comment by xi** [comment]
There are quite some problematic constructs:

- compound nouns ("Nutzerkonto")
- articles ("Der Nutzer", similar: "Jeder Nutzer")
- large difference in size between german and english for short strings ("user" -> "Nutzerin oder Nutzer")

I tried to address these in 10f2abf2

**Comment by fuzzylogic2000** [comment]
These are the rules, that we try to follow: 

-   use male form with compound nouns and articles ("Nutzerkonto", "Der Nutzer")
-   use * for short strings ("Nutzer*in")
-   use two genders for long sentences ("Nutzerinnen und Nutzer können …")

@CarolingerSeilchenspringer @hmkay @phillimorland @MagdaN Should we close this issue for now or keep it open as a reminder?

**Comment by hmkay** [comment]
hmm...probably @CarolingerSeilchenspringer should have the last word here, but I´d say close it for now...
