### ISSUE TITLE
Tempelhof: wrong link redirection in archive

### ISSUE THREAD

**Issue by rukala** [liqd/a4-meinberlin#615]
When I navigate to the archive on tempelhofer-feld and click on "ideas" I get a (probably 404) error. My guess is that the URL is wrong: https://tempelhofer-feld.berlin.de/i/tempelhofer-feld/category/ missing the "archive"

**Comment by xi** [comment]
This was an issue with the server setup. Fixed now.

**Comment by treba123** [comment]
Fixed, was my fault :)
There's actually some weird redirects on the site (https://tempelhofer-feld-archiv.liqd.net/static/themen.html points to https://tempelhofer-feld.berlin.de/i/tempelhofer-feld/category/ which again points to https://tempelhofer-feld-archiv.liqd.net/i/tempelhofer-feld/category/ which again has to remove the trailing "/" so it becomes https://tempelhofer-feld-archiv.liqd.net/i/tempelhofer-feld/category).

That actually also breaks the archive tool, as it does not follow hops to tempelhofer-feld.berlin.de.

Anyway, should work again now but I'll have to clean that up anyway
