### ISSUE TITLE
tile layout broken in edge

### ISSUE THREAD

**Issue by xi** [liqd/a4-meinberlin#621]
This seems to be a bug in the grid implementation of edge. Note that edge implements an old version of the spec. I hope that this will fix itself when the implement the new spec in edge 16.

https://caniuse.com/#search=grid

@Navigator28 could you please provide a screenshot?

**Comment by Navigator28** [comment]
![Uploading edge tiles.PNG…]()

**Comment by Navigator28** [comment]
![edge tiles offical](https://user-images.githubusercontent.com/29987899/28579423-f7196c58-715c-11e7-97b1-00be0dd11e09.PNG)
Tiles on the website

**Comment by xi** [comment]
autoprefixer stopped adding `-ms-grid` properties at some point: https://twitter.com/autoprefixer/status/849744717570899968

So this should be fixed with the next server update.
