### ISSUE TITLE
Research use of role="presentation" on forms

### ISSUE THREAD

**Issue by vellip** [liqd/a4-meinberlin#653]
In some cases we set a form's role to "presentation" (https://github.com/liqd/a4-meinberlin/pull/651/commits/f0382e74581c0730eba65ae8a72cfe5b03196ed9#diff-51ffa9d1947b77b1e35c781f79682cf1R3). I am not sure if this is a desirable pattern. We should research/ask clever people about this.

**Comment by xi** [comment]
I asked on the WAI IG mailing list and there seemed to be some confusion about this. However, the rough consensus seems to be that form elements only get the implicit form role if they have an accessible name.

> Div with  `<DIV  role=”form”>` only (no aria labeling) = WAS considered a region/landmark in FF, Chrome and IE with JAWS and NVDA
HTML `<form>` only (no aria labeling) =  WAS NOT  considered a region/landmark in FF, Chrome and IE with JAWS and NVDA
HTML `<form role=”form”>` only (no aria labeling) = WAS ALSO  considered a region/landmark in FF, Chrome and IE with JAWS and NVDA
HTML `<form role=”form” aria-label=”my form region”>` = WAS ALSO considered a region/landmark in FF, Chrome and IE with JAWS and NVDA
