### ISSUE TITLE
No 404 on invalid offline event URL

### ISSUE THREAD

**Issue by vellip** [liqd/a4-meinberlin#668]
Navigating to http://localhost:8000/offlineevents/sdgosdjgsdjgsd/ (while 'sdgosdjgsdjgsd' doesn't exist), will cause a 500 "meinberlin-stage.liqd.net is currently unable to handle this request."

**Comment by 2e2a** [comment]
seems to be fixed: https://meinberlin-stage.liqd.net/offlineevents/asdsad/
