### ISSUE TITLE
Switch between map and list view is not intuitive

### ISSUE THREAD

**Issue by 2e2a** [liqd/a4-meinberlin#750]
@hmkay did not see that there is a list view in the map projects

**Comment by damusp** [comment]
Hmm…
I too get the feeling that this needs to be much more obvious. 

Making the button stand out more (most likely with color, maybe with size and positioning?) would help a bit. If we want to get further with it, we would need to make some layout changes…

**Comment by kleingeist** [comment]
there is a new concept to merge the list and map view in PR #937
