### ISSUE TITLE
React success message disappears only after reload

### ISSUE THREAD

**Issue by 2e2a** [liqd/a4-meinberlin#754]
When a document or poll is saved the shown success message does not disappear on further react actions (e.g. adding a paragraph). It stays until a page reload.

This might be confusing for the user.

**Comment by vellip** [comment]
This should be working as intended, the user can close it manually or when something's entered into a field.

**Comment by 2e2a** [comment]
> This should be working as intended, the user can close it manually or when something's entered into a field.

This does not apply to the ck editor. So editing something there does not close the success message. Not sure if this is worth fixing, though.
