### ISSUE TITLE
Dashboard: Access to project not clear

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-meinberlin#823]
The tick next to "Access to project" is not clear in its intention. Who has access if I tick it?

**Comment by hmkay** [comment]
Suggestions:
>Das Projekt ist öffentlich. Entfernen Sie den Haken, wenn nur eingeladene Nutzer*innen teilnehmen sollen. 
>The project is public. Remove the tick if only invited users are intended to participate.

**Comment by kleingeist** [comment]
fixed with liqd/adhocracy4#190
