### ISSUE TITLE
timeline includes only title, not type

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-meinberlin#828]
Modules and offline-events are only displayed as titles. It is not always clear which one is a module and which one is an offline-event.

**Comment by damusp** [comment]
Yeah, sometimes it's made clear with the title, but not always. 

Questions: 
1) in what ways is this harmful? 
2) how can we make it more clear, without getting the timeline too overloaded? 
- we might display this piece of information always inside the timeline
- we might display it only on hover (not mobile-friendly 🙄)
- we might display it below together will all the descriptions and titles and stuff
