### ISSUE TITLE
Excel export immediately starts download

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-meinberlin#831]
Clicking on "Excel export" causes immediate download without telling me nor giving me the choice to decide. Also: short description is missing.

**Comment by xi** [comment]
I get what you mean. Could you please answer the following questions so we can find a better solution:

- What did you expect?
- Why did you expect that?
- What do other pages do in your experience?

**Comment by hmkay** [comment]
1) I expected to get on another page with more information about this item.
2) Because all other headings first lead to a page where I then can do things. The other pages do not cause a direct action.
3) In my experience, other pages tell me what will happen and give me an extra button on which I have to click consciously before I download something.

**Comment by damusp** [comment]
Would you say this could be fixed by changing the naming on the label?

e.g. "Download Excel File"?

**Comment by kleingeist** [comment]
Technically it would be possible to add a intermediate page. We already store a simple description to the export function (e.g. "Documents with comments")
And it could be possible to have multiple different exports per module (maybe different evaluations of polls). Although currently there is at most one.
