### ISSUE TITLE
Following button not translated on productive

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-meinberlin#832]
The text in the dropdown of the following button is still in English while the rest of the site is in German. This is on productive and can be seen here: https://mein.berlin.de/projects/vorbereitende-untersuchungen-ehemaliger-guterbahnh/?mode=list

It was tested on Safari 10.1 in German.

<img width="424" alt="bildschirmfoto 2017-09-25 um 16 45 29" src="https://user-images.githubusercontent.com/15341015/30814671-236a319a-a211-11e7-963c-33d0e66314b5.png">

**Comment by xi** [comment]
Somehow `make makemessages` does not extract these string. Probably there is an issue with `meinberlin/apps/contrib/management/commands/makemessages.py`.
