### ISSUE TITLE
Prevent double scrollbar when using modals

### ISSUE THREAD

**Issue by kleingeist** [liqd/a4-meinberlin#843]
Bootstrap assumes the body is set to be scrollable with `overflow-y: auto;` and adapts this property when using modals.
But we are using `overflow-y: auto;` on the  `<html>` element.

**Comment by xi** [comment]
It seems like webkit browsers scroll the body element by default, while other scroll the body element by default.

I looked through the bootstrap code and could not find a place where they force one way or the other.

I do not have a good answer right now, but I think calling this a bug is a bit dramatic.

**Comment by kleingeist** [comment]
![Drama Queen](https://media.giphy.com/media/5WXqTFTgO9a7e/giphy.gif)

i am not sure about the consequences if we change it. can we force scrolling on the body on every browser or is this something that will probably break because it's kind of built in?
