### ISSUE TITLE
Address results need two clicks

### ISSUE THREAD

**Issue by xi** [liqd/a4-meinberlin#846]
Address search was added in #806. When testing in Firefox 52.3.0, I noticed that results often need two clicks to be selected. It seems like no click event is fired.

We should test this in a more recent version of firefox. Maybe it is just a browser bug.

**Comment by kleingeist** [comment]
Firefox 56.0:
Reproduce:
- load page
- set focus to input search field
- type address
- press enter
- click on the proposal
=> no result, second click required

It may be noted that it works when:
- load page
- set focus to input search field
- type address
- click the search icon button
- click on the proposal
=> map pin is updated
