### ISSUE TITLE
"Progress-circle" is mis-shaped

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-meinberlin#857]
![screenshot issue](https://user-images.githubusercontent.com/30862422/31081220-735d4654-a78b-11e7-99a5-0018de0d5c49.jpeg)

The circle showing the progress of the created project is mis-shaped (see attach.)

**Comment by xi** [comment]
Whi browser did you use (which version)?

**Comment by hmkay** [comment]
Safari Version 11.0 (12604.1.38.1.7)

**Comment by xi** [comment]
Cannot reproduce on Safary 10.1 on browserstack.

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland I saw it on Safari 12.0 on MacOS 10.13.6 (and I think on Internet Explorer during a Schulung but I don't have it on my mac :-)
![image](https://user-images.githubusercontent.com/35491681/47500605-86d0e880-d863-11e8-9135-62376ae06c4e.png)

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer has this been encountered again since Feb?

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland yes, I just checked again, it is still there, Safari 12.1.1. on my mac, but only if you zoom in or out.

**Comment by CarolingerSeilchenspringer** [comment]
will be gone with new dashboard
