### ISSUE TITLE
Moderatorfeedback form broken

### ISSUE THREAD

**Issue by 2e2a** [liqd/a4-meinberlin#865]
Moderatorform stopped working.

We should consider refactoring it and getting rid of multiforms instead of fixing them.

**Comment by kleingeist** [comment]
actually this is a problem between the django debug toolbar and multiforms. 
if you disable the debug toolbar the form view renders fine. 

see for example: https://DEVSERVER.liqd.net/budgeting/guter-vorschlag/moderate/
