### ISSUE TITLE
Make private project setting more clear

### ISSUE THREAD

**Issue by kleingeist** [liqd/a4-meinberlin#868]
Currently the checkbox is kind of hidden and it is not instantly clear what is meant by "Access to Project". The setting should be more obvious and it's consequences more clear.

Opin has another way of showing the setting which we could/should adopt

**Comment by xi** [comment]
Related: https://github.com/liqd/adhocracy4/pull/190

**Comment by xi** [comment]
See https://github.com/liqd/a4-opin/pull/874 for the solution used in opin.
