### ISSUE TITLE
Share buttons overlap info text on landingpage

### ISSUE THREAD

**Issue by 2e2a** [liqd/a4-meinberlin#88]
On dev:

![screenshot from 2017-03-07 09-13-12](https://cloud.githubusercontent.com/assets/16001917/23647500/646f9aee-0316-11e7-9571-a9dfb252c88b.png)

**Comment by xi** [comment]
I already noticed the issue when working on the footer and tried to fix it in dfd8d72a0d084c55d798c395238c108119a2b7dd, but only for tile wrappers.

At one point I thought that there was a clearfix on `l-wrapper`, but it actually is not. @vellip do you think we should add it, or would that be to invasive?
