### ISSUE TITLE
The time is not shown if project has not started yet

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-meinberlin#905]
There is only the date shown if a project has not started yet. The best should be to show the time also, so people visiting a project’s page which should start some time on the same day are better informed and do not suspect an error.

![bildschirmfoto 2017-10-17 um 11 45 24](https://user-images.githubusercontent.com/15341015/31658286-e6794a06-b330-11e7-9802-1978da193666.png)

This was tested on meinberlin-stage

**Comment by xi** [comment]
I think showing both date and time all the time is overly verbose. Best would be to show time if date is today. The grammar is not trivial though.

**Comment by rittermo** [comment]
This is essential information, so being verbose (adding five more characters, 00:00, doesn’t make this verbose, btw) is not the biggest concern here.
