### ISSUE TITLE
Activate cache busting

### ISSUE THREAD

**Issue by xi** [liqd/a4-meinberlin#948]
Django has built-in cachebusting via [ManifestStaticFilesStorage](https://docs.djangoproject.com/en/1.11/ref/contrib/staticfiles/#manifeststaticfilesstorage). AFAIK we already use `collectstatic` in production, so it would be a simple matter of adding the following line to production.py:

```
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
```

However, I got the following error:

```
ValueError: The file 'a4images/imageUploader.js' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x7f5f3d33c780>.
```
I got it to work by running `collectstatic` first with the default storage and than again with this one. But I don't think this is how it was intended to be used.

**Comment by fuzzylogic2000** [comment]
This works, right?

**Comment by fuzzylogic2000** [comment]
Hmm, or not that well with running collectstatic twice?! We should also do it like that: https://github.com/liqd/a4-opin/pull/1008/files
