### ISSUE TITLE
Validate that phases within a module do not overlap

### ISSUE THREAD

**Issue by xi** [liqd/a4-meinberlin#950]
This causes various bugs

**Comment by kleingeist** [comment]
not sure if this is a bug anymore for meinBerlin as there are no longer any blueprints with more then one phase: thus new projects created from the dashboard cannot have overlapping phases.

it is still possible to add phases from the django admin, but it would be very difficult to add such checks there. and i think it is okay to rely on the site admin not creating faulty projects.

i think we may close this issue or at least label it as enhancement or refactor
