### ISSUE TITLE
Detailed participation end date

### ISSUE THREAD

**Issue by 2e2a** [liqd/a4-meinberlin#959]
In the timeline and in notification emails the detailed time when the project phase ends needs to be shown.

**Comment by xi** [comment]
Is "detailed" the same as "date and time"? In that case, also see #905.

**Comment by 2e2a** [comment]
| Is "detailed" the same as "date and time"? In that case, also see #905.

Yes. We need to show the time, as we got a complaint of a user who was not able to participate in a project thinking it would go to 24:00.
