### ISSUE TITLE
Random test fails

### ISSUE THREAD

**Issue by xi** [liqd/a4-meinberlin#976]
Sometimes tests fail for no reason. [Example](https://travis-ci.org/liqd/a4-meinberlin/builds/298099889).

The error typically looks like this:

```
django.db.utils.IntegrityError: UNIQUE constraint failed: meinberlin_users_user.username
```

It seems like some mock is generating non-unique data.

**Comment by kleingeist** [comment]
the problem may still occur with emails which are also required to be unique
see for example: https://travis-ci.org/liqd/a4-meinberlin/builds/302522571?utm_source=email&utm_medium=notification
